### ISSUE TITLE
BVN Live "list index out of range" ERROR

### ISSUE THREAD

**Issue by bruggieinoz** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1019]
BVN Live TV is no longer functioning :-(
Select Live TV, International, BVN. This throws Error:
Information: The selection triggered an unexpected error, would you like to share your error log so that we can try to resolve this issue? Selecting Yes, results in error "sorry, sharing your error log failed: Unable to retrieve the paste URL.
Momentarily, in top right, this error is displayed: Index Error, List Index out of range

I have tried this with 0.2.36, 0.2.37 and 0.2.39-beta15

From KODI.LOG:
2022-12-17 00:25:43.610 T:2645807936   ERROR: [Catch-up-TV-&-More.support] list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                redirect = parent_ins(route, arg_params, self.callback_params)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                results = super(Resolver, self).__call__(route, args, kwargs)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                return route.function(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/wo/bvn.py", line 162, in get_live_url
                                                resp.text)[0]
                                            IndexError: list index out of range

Other LIVE channels work OK

**Comment by bruggieinoz** [comment]
I think I figured it out, well at least to get it going again.
It looks like some changes were made at the bvn.tv/bvnlive URL and that it now references a different media player.
If I update the below section in BVN.py, all seems to function again:

# STREAM :
# OLD
# URL_STREAM = 'https://start-player.npo.nl/video/%s/streams?profile=dash-widevine&quality=npo&tokenId=%s&streamType=broadcast&mobile=0&ios=0&isChromecast=0'
# NEW
URL_STREAM = 'https://npoplayer-test.s3.eu-central-1.amazonaws.com/video/%s/streams?profile=dash-widevine&quality=npo&tokenId=%s&streamType=broadcast&mobile=0&ios=0&isChromecast=0'

**Comment by bruggieinoz** [comment]
Excellent, thank you. That seems to function fine now
