### ISSUE TITLE
[rtbf] replay issues

### ISSUE THREAD

**Issue by nirolfa** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1028]
strange issue with 

exposure.api.redbee.live (v2/customer/RTBF/businessunit/Auvio/)
and 
login.rtbf.be  (/accounts.login?loginID)

connection error : failed to establish connection 0xd04e8838
connection error : failed to establish connection 0xd5e75980
=============
after 10 retries or waiting 2 min and retry it works
but have to do this everytime before watching a new replay

started to happen around 26/12/2022

**Comment by nirolfa** [comment]
peut être lié au https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1022
je vais re-tester avec dernier build

**Comment by nirolfa** [comment]
dernier build ne corrige pas le problème

**Comment by darodi** [comment]
@nirolfa 

toujours en cours de correction ici

https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1017

**Comment by nirolfa** [comment]
je sais pas si ça peut aider ...

https://c9851ec-az-westeurope.fsly.cdn.ebsd.ericsson.net/rtbf/auvio/assets/2980731_6BA97Bb/materials/EUIBPwftDI_6BA97Bb/vod-idx-2.ism/.mpd

https://rbm-rtbf.live.ott.irdeto.com/licenseServer/widevine/v1/rbm-rtbf/license?contentId=2980731_6BA97Bb&keyId=956d408e-4c95-4d70-a787-8e182ed371b3&ls_session=

**Comment by joaopa00** [comment]
Est-ce que la requête est prête à mettre poussée? Elle a toujours le statut "DRAFT"

**Comment by darodi** [comment]
@joaopa00 

Je viens de push la bonne version.
Testé sous rpi osmc et windows.
On peut merger.

**Comment by darodi** [comment]
@joaopa00 

peut être férmé

**Comment by darodi** [comment]
@nirolfa 

Toujours le même problème?
Si oui, comment le reproduire? Quelle vidéo?

**Comment by nirolfa** [comment]
fixed, merci ;)

**Comment by nirolfa** [comment]
retour du bug

meme problème qu'avant :(
pourtant ça marchait hier et avant hier  ....
pas possible de s'inspirer de https://github.com/yt-dlp/yt-dlp ?

**Comment by nirolfa** [comment]
retour du bug

meme problème qu'avant :(
pourtant ça marchait hier et avant hier ....
pas possible de s'inspirer de https://github.com/yt-dlp/yt-dlp ?

**Comment by darodi** [comment]
@nirolfa 

normalement, yt-dlp ne permet plus de télécharger quoi que ce soit de auvio depuis les DRM.

**Comment by darodi** [comment]
@nirolfa 

Quel retour de bug?
Le live et le replay marchent sans problème pour moi.
Ouvrir une nouvelle issue avec la procédure pour reproduire le cas.
Merci

**Comment by nirolfa** [comment]
@darodi 
sorry, j'ai refait qq tests donc

kodi 19.4 + windows = ok
=========================================
kodi 19.4 + libreelec/raspbery : 
  * replay semble ok 
    (mais parfois il me semble que j'ai un httpsconnectionpool error  sur /v2/customer/RTBF/businessunit                /auvio/auth/gigyaLogin)
    * live tv nok
     HttpConnectionPool
url api/partner/generic/live/planningcurrent?v=8channel=laune&target_site=meidaz&partner_l
         => NewConnectionError urllib3.connection.HTTPConnection
     line 174 in urlib3/connection.py

c'est assez bizzare, je comprend pas
j 'essaie d envoyer les logs full ce soir

**Comment by darodi** [comment]
@nirolfa 

Live depuis le menu `TV` de kodi ou depuis le menu `Live TV` de CUTVM?

**Comment by nirolfa** [comment]
j'ai essayé les 2 et même erreur dans les 2 cas
(par contre sous win  ca marche meme depuis le menu tv de kodi  !!)

**Comment by nirolfa** [comment]
022-12-31 20:11:30.993 T:1528     INFO <general>: Python interpreter stopped
2022-12-31 20:11:32.630 T:1530    ERROR <general>: [Catch-up-TV-&-More.support] 403 Client Error: Forbidden for url: https://exposure.api.redbee.live/v2/customer/RTBF/businessunit/Auvio/entitlement/live_436119_6BA97Bb/play
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py", line 697, in get_live_url
                                                       return get_video_redbee(plugin, external_id, is_drm)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py", line 475, in get_video_redbee
                                                       video_format, forced_drm = get_redbee_format(plugin, video_id, redbee_jwt['sessionToken'], is_drm)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py", line 794, in get_redbee_format
                                                       formats = urlquick.get(url, headers=headers, max_age=-1).json()['formats']
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 493, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 487, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 442, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 415, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 960, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://exposure.api.redbee.live/v2/customer/RTBF/businessunit/Auvio/entitlement/live_436119_6BA97Bb/play
2022-12-31 20:11:32.633 T:1530    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 290, in error_handler
                                                       code = exception.code
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--

2022-12-31 20:11:32.958 T:1530     INFO <general>: Python interpreter stopped

**Comment by nirolfa** [comment]
Je sais pas si ca peut aider

https://exposure.api.redbee.live/v2/customer/RTBF/businessunit/Auvio/entitlement/live_437673_6BA97Bb/play?ifa=f286b2eb-165d-46fa-8cc7-f85cc9316ab8&deviceType=desktop&width=1920&height=577&pageUrl=https%3A%2F%2Fauvio.rtbf.be%2Flive%2Fexcalibur-lepee-magique-437673&domain=auvio.rtbf.be&mute=false&autoplay=true&supportedFormats=dash%2Chls%2Cmss%2Cmp3&supportedDrms=widevine


Json rsponse for formats

--
0 | Object { format: "DASH", mediaLocator: "https://C9851Ec-rbm-hilv.fsly.cdn.ebsd.ericsson.net/L25/6c240c64/0ca9256d.isml/.mpd?t=2023-01-14T15%3A53%3A00.000", liveDelay: 10000, … }
format | "DASH"
drm | Object { "com.widevine.alpha": {…} }
com.widevine.alpha | Object { certificateUrl: "https://rbm-rtbf.live.ott.irdeto.com/licenseServer/widevine/v1/rbm-rtbf/certificate", licenseServerUrl: "https://rbm-rtbf.live.ott.irdeto.com/licenseServer/widevine/v1/rbm-rtbf/license?contentId=0ca9256d&keyId=ddab6ebd-9ae9-433e-b85a-************&ls_session=eyJ0eXAiOiJKV1QiLCJraWQiOiIwOGIzODQwZS0wYThhLTQyYTItODNhNC03ZGM0Mzc0ZDJmYmEiLCJhbGciOiJIUzI1NiJ9.eyJhaWQiOiJyYm0tcnRiZiIsInN1YiI6IjlkMmJmNmI2ODA4YTQ4OTliMGZhOTQ5YjcwZDE3NDczXzZCQTk3QmIiLCJpYXQiOjE2NzM3MTY5ODIsImV4cCI6MTY3MzcyMDU4MiwianRpIjoicE1abzlKd08wa2M4OFJyOFNjOU1vcWVMOUwxc1B3ZzVXS0lxUHVQbjVYVT0iLCJlbnQiOlt7ImVwaWQiOiJkZWZhdWx0IiwiYmlkIjoiYmVsZ2lhbl82QkE5N0JiIn1dLCJpc2UiOnRydWV9.pMNfltsro_rFnkD7VJ4S_q_CryfBFPEvW9iigqp3o1c" }
certificateUrl | "https://rbm-rtbf.live.ott.irdeto.com/licenseServer/widevine/v1/rbm-rtbf/certificate"
licenseServerUrl | "https://rbm-rtbf.live.ott.irdeto.com/licenseServer/widevine/v1/rbm-rtbf/license?contentId=0ca9256d&keyId=ddab6ebd-9ae9-433e-b85a-********&ls_session=eyJ0eXAiOiJKV1QiLCJraWQiOiIwOGIzODQwZS0wYThhLTQyYTItODNhNC03ZGM0Mzc0ZDJmYmEiLCJhbGciOiJIUzI1NiJ9.eyJhaWQiOiJyYm0tcnRiZiIsInN1YiI6IjlkMmJmNmI2ODA4YTQ4OTliMGZhOTQ5YjcwZDE3NDczXzZCQTk3QmIiLCJpYXQiOjE2NzM3MTY5ODIsImV4cCI6MTY3MzcyMDU4MiwianRpIjoicE1abzlKd08wa2M4OFJyOFNjOU1vcWVMOUwxc1B3ZzVXS0lxUHVQbjVYVT0iLCJlbnQiOlt7ImVwaWQiOiJkZWZhdWx0IiwiYmlkIjoiYmVsZ2lhbl82QkE5N0JiIn1dLCJpc2UiOnRydWV9.pMNfltsro_rFnkD7VJ4S_q_CryfBFPEvW9iigqp3o1c"
mediaLocator | "https://C9851Ec-rbm-hilv.fsly.cdn.ebsd.ericsson.net/L25/6c240c64/0ca9256d.isml/.mpd?t=2023-01-14T15%3A53%3A00.000"
live

**Comment by darodi** [comment]
@nirolfa 

Le lien du live était-il toujours live au moment de l'essai?
Dans la section live, il y a plusieurs liens quand une émission est suivie d'une autre sur la même chaîne.

Ici, il y a une erreur 403.
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1028#issuecomment-1382862235
Y-a-t’il eu une erreur sur /auvio/auth/gigyaLogin avant? 
Le log ne donne pas tout le processus.

**Comment by nirolfa** [comment]
je vais regarder pour retester cette semaine et envoyer logs full.
Entre temps, nouveaux problèmes avec les replay maintenant ....   
J'enverrai les 2 logs vendredi.

ps:  yt-dlp  marche (combiné à mp4decoder)
