### ISSUE TITLE
RTBF live error

### ISSUE THREAD

**Issue by wilfarte** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1051]
Environnement:
nvidia shield
kodi 19.4
Catchup 0.2.39-beta17

Erreur d'accès à RTBF direct via le plugin.
Le premier accès fonctionne toujours bien mais si je quitte le stream pour ensuite y revenir par la suite j'ai un message HTTP ERROR 403 forbidden URL

[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/10409355/kodi.log)

**Comment by nirolfa** [comment]
en lien avec #1028

**Comment by darodi** [comment]
@wilfarte 

Live depuis le menu TV de kodi ou depuis le menu Live TV de CUTVM?

**Comment by wilfarte** [comment]
Depuis le menu live TV de CUTVM

**Comment by joaopa00** [comment]
Peux-tu tester cette version?
[version de test](https://docs.google.com/uc?export=download&id=1B1lZgZcLsh3KQJqtg7EsPtdsILpCCX4V)

**Comment by wilfarte** [comment]
Sous Nvidia shield, dois je me contenter de copier le contenu du dossier Ressources du fichier zip fourni?

**Comment by wilfarte** [comment]
Sous Windows, Kodi 19.5, j'ai installé la version fournie et j'obtiens de temps à autre la même erreur ( copie du fichier de ressources).
Je joins le fichier de log
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/10436171/kodi.log)

**Comment by joaopa00** [comment]
Est-ce que le mode dialogue dialogue est activé?
Si oui, peux-tu tester en le désactivant?

**Comment by wilfarte** [comment]
Le mode pour la qualité vidéo est sur DEFAULT

**Comment by joaopa00** [comment]
Une nouvelle version de test...

[version de test](https://docs.google.com/uc?export=download&id=1wYRpwUJ5dG6PA2AoKxpAVTWrayXstn4K)

**Comment by darodi** [comment]
@joaopa00 

une modification de code? moyen de voir dans une PR draft?

**Comment by joaopa00** [comment]
J'ai juste rajouté l'user-agent dan les en-têtes des requêtes.

**Comment by darodi** [comment]
Je ne pense pas que c'est ça.
D'après les tickets, ça fonctionne, puis après un certain temps ça ne marche plus. 
Je penche pour un token avec une durée de vie limitée qui est renvoyé toujours identique tant que le délai du token n'est pas dépassé et un refresh à faire après le délai. 
Voir fonctionnement de oauth2 : access_token et refresh_token.
Malheureusement, je n'ai pas réussi à reproduire leur cas.

**Comment by darodi** [comment]
Il faudrait que je vérifie à nouveau le flux, pour voir si on avait bien une durée de vie en même temps que l'access_token. De mémoire, je pense que oui.

**Comment by wilfarte** [comment]
Juste une question... L'accès aux chaînes de la RTBF peut se faire via le menu avec deux entrées différentes:
- RTBF AUVIO et ensuite La UNE ou TIPIK
- Ne pas entrer dans le sous menu RTBF AUVIO et directement avoir accès à LA UNE
Il me semble avoir moins de problèmes lorsque je passe par le menu RTBF AUVIO. Les problèmes sont différents et ne sont plus nécessairement liés à un timeout du token éventuel.
Je vous ferai parvenir les logs des entrées dans le menu AUVIO

La question sera de savoir comment intégrer le contenu de ce sous menu dans l'IPMANAGER

**Comment by darodi** [comment]
> Il me semble avoir moins de problèmes lorsque je passe par le menu RTBF AUVIO. Les problèmes sont différents et ne sont plus nécessairement liés à un timeout du token éventuel.

C'est à dire?

**Comment by wilfarte** [comment]
> > Il me semble avoir moins de problèmes lorsque je passe par le menu RTBF AUVIO. Les problèmes sont différents et ne sont plus nécessairement liés à un timeout du token éventuel.
> 
> C'est à dire?

Si je rencontre des problèmes de connexion en ayant cliqué sur le lien dans la racine du menu pour les chaînes belges... ex: LA UNE et que je vais ensuite sur le sous men AUVIO - LA UNE cela semble fonctionner plus facilement. Peut-être une coïncidence ?

**Comment by wilfarte** [comment]
Suite à différents essais sous Windows, votre plugin fonctionne bien. Je n'ai plus d'erreur quelque soit le programme de la RTBF regardé en direct. J'ai cru voir dans un autre post un commentaire allant dans ce sens sous Windows.
Par contre, sous Nvidia Shield, les problèmes persistent avec une différence sur l'erreur.
Pour les programmes décrits en accessibilité ouverte, pas de problème. Pour les programmes avec accessibilité en belgique, voici une partie des logs liés à l'erreur. La beta18 et la dernière version que vous avez envoyé ont le même symptôme.
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/10472424/kodi.log)
Les problèmes sont identiques en Kodi19.5 et Kodi20

**Comment by darodi** [comment]
quelle est la version de widevine installée?
je ne la vois pas dans les logs

**Comment by wilfarte** [comment]
J'ai cru comprendre que sous android tv, Widevine est installé sous android et donc ne l'est pas sous kodi.
Pour inputstream helper 0.5.10+matrix.1 (kodi addon repository)

**Comment by darodi** [comment]
même problème sur mon téléphone sous Android

**Comment by nirolfa** [comment]
La questions que je me pose, c'est pourquoi ca déconne avec rtbf et c'est ok avec rtl ???
Et c'est pas juste le live qui va plus avec rtbf, les replay aussi ça marche plus :( 
InputStream Helper 0.5.10+matrix
windwine 4.10.2449.0 (14816.131.0)

**Comment by darodi** [comment]
@nirolfa 
pas la même chaîne, pas le même site, pas la même plateforme, pas la même gestion de licences DRM.
Problème sous android uniquement avec la dernière beta.
Je n'ai pas encore eu l'occasion de regarder pourquoi.

**Comment by nirolfa** [comment]
>>> Si je rencontre des problèmes de connexion en ayant cliqué sur le lien dans la racine du menu pour les chaînes belges... ex: LA UNE et que je vais ensuite sur le sous men AUVIO - LA UNE cela semble fonctionner plus facilement. Peut-être une coïncidence ?

oui je confirme qu il y a un truc du style, 
 maintenant parfois attendre 1min avant reclicker ca marche, d autres fois il faut reclicker 20 fois

**Comment by nirolfa** [comment]
@darodi 
bon je vais peut être me remettre à la programmation
quelques conseils par où commencer pour premier plugin, qq bons tutos ?
des tips pour le debugging facile ?

**Comment by darodi** [comment]
@nirolfa 

- pycharm comme IDE? 
   - https://www.jetbrains.com/fr-fr/pycharm/download/download-thanks.html?platform=windows&code=PCC
- catchuptvandmore-test pour tester le plugin et les routes et faire du debug
  - https://github.com/Catch-up-TV-and-More/catchuptvandmore-test
- la documentation de codequick qu'on utilise pour CUTVM
  - https://scriptmodulecodequick.readthedocs.io/en/stable/index.html
  - plus les exemples https://scriptmodulecodequick.readthedocs.io/en/stable/examples.html

**Comment by Hir0-84** [comment]
Hi I do not know if the problem is related. I have the last version of the add-on installed from the beta channel of the repo. When I try to stream live tv content (ex. La une) from iptv.simple client I get the following error message:

error<general> GetDirectory - Error getting /data/user/0/org.xbmc.kodi/cache/apk/assets/addons/inputstream.adaptive/
error<general> AddOnLog: inputsteam.adaptive: WV_DRM: Exception setting Service Certificate
error<general> AddOnLog: inputsteam.adaptive: OpenDRMSystem failed
error<general> CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/.../1@pvr.iptvsimple_1235520811.pvr]

I am running KODI 20.0 on Android 9.
InputStream Helper is at version 0..510+matrix.1
InputStream Adaptive us at version 20.3.4

Widevine CDM is built into Android

**Comment by joaopa00** [comment]
The latest version means nothing. PLease explicit the exact version of catchuptvandmore you are using.

**Comment by Hir0-84** [comment]
Sorry! I am using v. 0.2.39-beta20

**Comment by Hir0-84** [comment]
If it can help here is the traceback of the error:

`2023-03-05 12:29:51.193 T:5939    error <general>: [Catch-up-TV-&-More.support] 403 Client Error: Forbidden for url: https://exposure.api.redbee.live/v2/customer/RTBF/businessunit/Auvio/entitlement/live_444628_6BA97Bb/play
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py", line 697, in get_live_url
                                                       return get_video_redbee(plugin, external_id, is_drm)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py", line 475, in get_video_redbee
                                                       video_format, forced_drm = get_redbee_format(plugin, video_id, redbee_jwt['sessionToken'], is_drm)
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py", line 794, in get_redbee_format
                                                       formats = urlquick.get(url, headers=headers, max_age=-1).json()['formats']
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/urlquick.py", line 493, in get
                                                       return request('get', url, params=params, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/urlquick.py", line 487, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/urlquick.py", line 442, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/urlquick.py", line 415, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 960, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://exposure.api.redbee.live/v2/customer/RTBF/businessunit/Auvio/entitlement/live_444628_6BA97Bb/play
2023-03-05 12:29:51.232 T:5939    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 290, in error_handler
                                                       code = exception.code
                                                              ^^^^^^^^^^^^^^
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--`

**Comment by joaopa00** [comment]
Do you have a belgium IP? Did you fulfill your credentials in settings?

**Comment by Hir0-84** [comment]
Yes I have a belgian IP. The credentials for AUVIO are set.

**Comment by joaopa00** [comment]
Can you give a try with  [test version](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/archive/refs/heads/dev.zip)

**Comment by Hir0-84** [comment]
Hi thank you I will give a try over the weekend as soon as I get back control on the TV

**Comment by Hir0-84** [comment]
Before installing the new version LaUne was working, but not LaTrois. During the last days LaUne sometime worked while LaTrois has never worked for me on AndroidTV.
I have installed the new version and both LaUne and LaTrois are not working (see new log)

file:///home/hir0/LaUne.log

The same version (dev) on the linux machine is able to open both LaUne and LaTrois without problems

**Comment by Hir0-84** [comment]
[LaUne.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/10926559/LaUne.txt)

**Comment by dur3x** [comment]
@Hir0-84 I currently have the exact same problem on my side on Android 9.0 Kodi 20 catchup v0.2.39beta21

> 2023-03-11 15:37:52.096 T:10868    info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
2023-03-11 15:37:52.097 T:10868   error <general>: GetDirectory - Error getting /data/user/0/org.xbmc.kodi/cache/apk/assets/addons/inputstream.adaptive/
2023-03-11 15:37:52.413 T:10868    info <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file (Periods: 1, Streams in first period: 3, Type: VOD)
2023-03-11 15:37:52.685 T:10868   error <general>: AddOnLog: inputstream.adaptive: WV_DRM: Exception setting Service Certificate
2023-03-11 15:37:52.691 T:10868   error <general>: AddOnLog: inputstream.adaptive: OpenDRMSystem failed
2023-03-11 15:37:52.695 T:10868   error <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf/get_video_url/?_pickle_=800495d5000000000000007d94288c075f7469746c655f948c2f44656d61696e206e6f75732061707061727469656e7420533036202d20313136202d20457069736f64652031333737948c076974656d5f6964948c05617576696f948c09766964656f5f75726c948c4c68747470733a2f2f7777772e727462662e62652f7461726d61632f706c61792f64657461696c5f64656d61696e2d6e6f75732d61707061727469656e742d7330363f69643d33303036393633948c08766964656f5f6964944af3e12d008c0669735f64726d94888c0969735f7265646265659488752e]

I'm well running it in belgium and with credentials set (it works on their website)

**Comment by joaopa00** [comment]
I am not in Belgium and I do not have a Belgian vpn. So I can not test by myself. Can you give a try to this version?
[test version](https://docs.google.com/uc?export=download&id=17JMRb6_0zo89bkpMiPuZQhAE-rAZvQ_Q)

**Comment by wilfarte** [comment]
"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py", line 488, in get_video_redbee
                                                       resp_cert = urlquick.get(certificate_url, headers=GENERIC_HEADERS, max_age=-1).text
                                                                                ^^^^^^^^^^^^^^^
                                                   NameError: name 'certificate_url' is not defined

**Comment by dur3x** [comment]
> I am not in Belgium and I do not have a Belgian vpn. So I can not test by myself. Can you give a try to this version? [test version](https://docs.google.com/uc?export=download&id=17JMRb6_0zo89bkpMiPuZQhAE-rAZvQ_Q)

I tested it (from dev branch) and it works for non-DRM content but for DRM content it crashes like that:

> 2023-04-22 14:31:56.155 T:24533    info <general>: Creating InputStream
2023-04-22 14:31:56.179 T:24533 warning <general>: AddOnLog: inputstream.adaptive: Set headers to the manifest by using "inputstream.adaptive.stream_headers" property is a deprecated behaviour that will be removed in future.
                                                   To set headers to the manifest, use "inputstream.adaptive.manifest_headers" property.
2023-04-22 14:31:56.186 T:24533    info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
2023-04-22 14:31:56.187 T:24533   error <general>: GetDirectory - Error getting /data/user/0/org.xbmc.kodi/cache/apk/assets/addons/inputstream.adaptive/
2023-04-22 14:31:56.431 T:24533    info <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file (Periods: 1, Streams in first period: 7, Type: live)
2023-04-22 14:31:56.501 T:24533   error <general>: AddOnLog: inputstream.adaptive: WV_DRM: Exception setting Service Certificate
2023-04-22 14:31:56.510 T:24533   error <general>: AddOnLog: inputstream.adaptive: OpenDRMSystem failed
2023-04-22 14:31:56.516 T:24533   error <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf/get_live_url/?_pickle_=80049511010000000000007d94288c075f7469746c655f948c4f4c612054726f6973202d204c65676f20467269656e6473203a2043696e712066696c6c657320656e206d697373696f6e202d2044657320616d692d652d7320c3a02071756174726520706174746573948c076974656d5f6964948c05617576696f948c086c6976655f75726c948c4668747470733a2f2f727462662d6c6976652e666c2e667265656361737465722e6e65742f6c6976652f727462662f67656f2f64726d2f6c6174726f69735f6165732e6d337538948c0669735f64726d94888c076c6976655f6964944a94eb06008c0969735f72656462656594888c0b65787465726e616c5f6964948c136c6976655f3435333532345f3642413937426294752e]

If that can help you, I can check to give you a belgium vpn access

**Comment by darodi** [comment]
> même problème sur mon téléphone sous Android
_Originally posted by @darodi in https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1051#issuecomment-1399310367_

@wilfarte @nirolfa @dur3x 
Je n'ai plus de soucis sous android avec mon téléphone maintenant.
Cette issue existe-t-elle toujours pour vous?

I don't have the problem on Android with my phone anymore.
Is this issue still open for you?

**Comment by wilfarte** [comment]
> > même problème sur mon téléphone sous Android
> > _Originally posted by @darodi in [#1051 (comment)](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1051#issuecomment-1399310367)_
> 
> @wilfarte @nirolfa @dur3x Je n'ai plus de soucis sous android avec mon téléphone maintenant. Cette issue existe-t-elle toujours pour vous?
> 
> I don't have the problem on Android with my phone anymore. Is this issue still open for you?

Bonjour à tous

Sous nvidia shield le problème persiste. Pour les contenus non-DRM ok mais pour le DRM, l problème est toujours présent.
J'ai actuellement la version 0.2.39-beta37
Merci pour le travail effectué par ceux qui font évoluer le produit. C'est un petit problème à côté de toutes les améliorations et correctifs apportés sur ce produit.

**Comment by stemy2** [comment]
Même problème ici.
0.2.39-beta39
kodi 20.2 linux

**Comment by stemy2** [comment]
Update: toutes les chaînes fonctionnent, sauf La Trois, qui continue d'afficher cette même erreur

**Comment by stemy2** [comment]
Après quelques tests, tantôt toutes les chaînes fonctionnent, tantôt certaines retournent une erreur 403, et ce sans que je ne change quoi que ce soit à la configuration.

**Comment by PowaBanga** [comment]
I have exactly the same problem on my archlinuxarm, kodi 20.5

**Comment by stemy2** [comment]
à l'heure où j'écris ce message, le problème est toujours d'actualité. J'en viens à me demander si les devs ont la possibilité de le résoudre.

**Comment by stemy2** [comment]
Un contournement trouvé dans un autre ticket: https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1400#issuecomment-3050321266

Il suffit de copier-coller le contenu dans un fichier xml et l'utiliser comme source pour la liste de chaînes. Et ça marche plutôt bien.
