### ISSUE TITLE
Http error France2/france3/france4/france5

### ISSUE THREAD

**Issue by Mttpz** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1056]
les chaines France2/france3/france4/france5 ne fonctionne plus, il y a un probleme d'http error qui s'affiche

**Comment by joaopa00** [comment]
S'il y a des items

**Comment by matwillshak** [comment]
Même problème chez moi. Version 0.2.39 bêta 17 sur fire tv 4K Max.

**Comment by raydenxxx** [comment]
Même problème ici avec la dernière beta

Voici le log de l'erreur:
`2023-01-15 19:56:33.713 T:13268   ERROR <general>: [Catch-up-TV-&-More.support] 403 Client Error: Forbidden for url: https://simulcast-p.ftven.fr/ZXhwPTE2NzM4MzA1OTB+YWNsPSUyZip+aG1hYz0yYjlhMjczNjg1N2Y2NTJlNGEzMzllYjRiMGYzMTY4ZTZmN2Q0NzQxNGUwNDhjYjk4YmJiYmRlMzM5MmEwOGZh/simulcast/France_2/hls_fr2/index.m3u8?hdnea=exp=1673809590~acl=%2F*~hmac=ce8bca60016091e0c076ae99014c0a5f169e56083131490728e3e9703d8edfae
                                                   Traceback (most recent call last):
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\fr\francetv.py", line 414, in get_live_url
                                                       return resolver_proxy.get_francetv_live_stream(plugin, broadcast_id)
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\resolver_proxy.py", line 535, in get_francetv_live_stream
                                                       return get_stream_with_quality(plugin, video_url, license_url=URL_LICENSE_FRANCETV)
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\resolver_proxy.py", line 203, in get_stream_with_quality
                                                       url, bitrate = M3u8(video_url, headers).get_url_and_bitrate_for_quality()
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\streams\m3u8.py", line 209, in get_url_and_bitrate_for_quality
                                                       self.media_streams = M3u8.get_media_streams(self.url, self.headers, self.append_query_string,
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\streams\m3u8.py", line 137, in get_media_streams
                                                       for s, b, r in M3u8.get_streams(url, headers=headers, append_query_string=append_query_string, map_audio=False,
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\streams\m3u8.py", line 66, in get_streams
                                                       resp = urlquick.get(url, headers=headers, max_age=-1, verify=verify)
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 493, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 487, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 442, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 415, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 960, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://simulcast-p.ftven.fr/ZXhwPTE2NzM4MzA1OTB+YWNsPSUyZip+aG1hYz0yYjlhMjczNjg1N2Y2NTJlNGEzMzllYjRiMGYzMTY4ZTZmN2Q0NzQxNGUwNDhjYjk4YmJiYmRlMzM5MmEwOGZh/simulcast/France_2/hls_fr2/index.m3u8?hdnea=exp=1673809590~acl=%2F*~hmac=ce8bca60016091e0c076ae99014c0a5f169e56083131490728e3e9703d8edfae
2023-01-15 19:56:33.714 T:13268   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py", line 23, in <module>
                                                       main()
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\main.py", line 290, in error_handler
                                                       code = exception.code
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--
                                                   
2023-01-15 19:56:33.764 T:13268    INFO <general>: Python interpreter stopped`

Versions :
Kodi: 19.5.0 Windows 64 bit
Catch-up: 0.2.39~beta17

[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/10420970/kodi.log)
![1 erreur francetv](https://user-images.githubusercontent.com/122745590/212561601-eea35092-8bc8-4a78-b1f0-36ee703fa822.jpg)

**Comment by toto6976** [comment]
Aucun problème avec dietpi v8 amd64 sur raspberry avec Kodi 19.4.
Merci pour le super travail

**Comment by raydenxxx** [comment]
> Aucun problème avec dietpi v8 amd64 sur raspberry avec Kodi 19.4.
> Merci pour le super travail
> Les soucis semblent être très spécifiques à certaines distributions...

Ce souci est spécifique à la version 0.2.39 bêta 17 de catch up, pas de rapport avec la version de kodi

**Comment by joaopa00** [comment]
Au final, c'est réglé avec la béta 18 ou il y a encore des problèmes?

**Comment by raydenxxx** [comment]
> Au final, c'est réglé avec la béta 18 ou il y a encore des problèmes?

Je ne l’ai pas encore installé… si tu le fais n’hésite pas à faire un retour 👍

**Comment by raydenxxx** [comment]
> Au final, c'est réglé avec la béta 18 ou il y a encore des problèmes?

Je vois pas de bêta 18, tu es sur qu’elle est dispo?

**Comment by MiloDino88** [comment]
J'avais la même erreur sous avec Kodi 19.4 sur une firestick.

Je viens d'installer la béta 18, problème résolu ! merci @joaopa00

**Comment by raydenxxx** [comment]
Tout remarche aussi chez moi (France tv et m6) avec la beta 18.

merci la team

**Comment by glenan** [comment]
> les chaines France2/france3/france4/france5 ne fonctionne plus, il y a un probleme d'http error qui s'affiche

Hier, retour du même problème

**Comment by DeedeeGuffies** [comment]
Pareil
