### ISSUE TITLE
Chaines BFM TV HS sur Linux avec Kodi 20

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1061]
Kodi 20 + Linux Mint 20.3 

2023-01-16 18:58:37.126 T:39381   error <general>: GetItemsForPlayList: Unable to get playlist items for plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay/get_live_url/?_pickle_=8004955b000000000000007d94288c075f7469746c655f948c2542464d2052c3a967696f6e73202842464d204d41525345494c4c452050524f56454e434529948c08786d6c74765f6964944e8c076974656d5f6964948c0b42464d5f726567696f6e7394752e
2023-01-16 18:58:39.824 T:39489 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-01-16 18:58:39.824 T:39489 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-01-16 18:58:39.848 T:39381    info <general>: VideoPlayer::OpenFile: plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay/get_live_url/?_pickle_=8004955b000000000000007d94288c075f7469746c655f948c2542464d2052c3a967696f6e73202842464d204d41525345494c4c452050524f56454e434529948c08786d6c74765f6964944e8c076974656d5f6964948c0b42464d5f726567696f6e7394752e
2023-01-16 18:58:39.849 T:39494    info <general>: Creating InputStream
2023-01-16 18:58:39.881 T:39494    info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 990x558, max allowed: 990x558, Adjust refresh rate: 0
2023-01-16 18:58:39.984 T:39494    info <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file (Periods: 1, Streams in first period: 3, Type: live)
2023-01-16 18:58:40.283 T:39494   error <general>: AddOnLog: inputstream.adaptive: Download failed with error 400: https://sbg1-cdn-edge-live00.pfd.sfr.net/ncdn-live-pal1.pfd.sfr.net/sid=080c4fltp62aha7kfjig/sdash/LIVE$BFM_MARSEILLEPROV/index.mpd/Manifest/S!d2ENZGFzaF9keW5fd2lkZRICVP7...8BFgSf/QualityLevels(2000000)/Fragments(video=Init)
2023-01-16 18:58:40.283 T:39494   error <general>: AddOnLog: inputstream.adaptive: No MOOV in stream!
2023-01-16 18:58:40.301 T:39494   error <general>: CVideoPlayer::OpenInputStream - error opening [plugin://p

Edit:
Fonctionne sous windows et Kodi 20

**Comment by joaopa00** [comment]
Du coup, il serait intéressant d'avoir un log complet sous Windows (mode déboggage activé avec les flux curl et video activés) te le même sous linux pour voir les différences pour els requêtes sous windows et linux

**Comment by enigma131** [comment]
Ok, je fais cela demain

**Comment by joaopa00** [comment]
Le mode de déboguage CURL n'est pas activé dans les logs que tu as joints. On ne voit pas les en-têtes des requêtes. Comme tels qu'attachés, les logs sont inutiles.

**Comment by enigma131** [comment]
OK, comment on fait ?

**Comment by joaopa00** [comment]
Est-ce que les autres régions BFM fonctionnent sous Windows?
Et au fait, quel windows utilises-tu?

**Comment by enigma131** [comment]
BFM azur fonctionne partout. 
Pour Windows: W10 famille à jour.
Et cela fonctionne chez toi et si oui sous quel OS ?

**Comment by joaopa00** [comment]
Aucun des BFM fonctionne chez moi. C'est pour ça que je suis surpris que ça focntionne chez toi.
Je teste sous Linux, Android et Windows 11

**Comment by joaopa00** [comment]
Peux tu testersous Windows  toutes les chaines de BFM (BFMTV RCM Découverte, RMC story et toutes les regionales) en passant par le menu (pas de chaines en favori)

Et lister celles qui fonctionnent et celles qui ne fonctionnent pas...

**Comment by enigma131** [comment]
Je viens de tester sous Android tout marche aussi beta 17. Ok je retourne sous windows

**Comment by enigma131** [comment]
Sous W10 + Kodi 20 + beta 17 + en passant par le menu, elles marchent toutes CAD bfm tv, les 2 RMC ainsi que BFM provence
Sous Android, kodi 19.3 et même résultat.
Je pense que tu as un problème de compte , ils sont enregistrés ou tu ne m'as pas répondu.

**Comment by joaopa00** [comment]
Sous linux:
~/.kodi/userdata/addon_data/plugin.video.catchuptvandmore/settings.xml

**Comment by enigma131** [comment]
Mes mots de passes sont identiques windows / Linux
Je ne sais pas s'il y a cause à effet, cela s'est produit quand j'ai upgradé Kodi en V20. Bfm Marseille je lécoute tous les jours.

**Comment by joaopa00** [comment]
Un bon moyen serait de remttre la verion 19 de Kodi et voir si ça remarche.

**Comment by enigma131** [comment]
Je viens d'essayer sur une seconde machine sous Linux et kodi 19.3, marche pas. (la roue tourne indéfiniment)
Chez toi cela remarche sous Linux ?

**Comment by enigma131** [comment]
Donc conclusion provisoire : Widevine ne se met pas à jour sur Kodi 20 !

**Comment by enigma131** [comment]
Je viens de voir un truc bizarre sous Nexus. Avec windows cela fonctionne mais la résolution est réduite à 1024 pix.
La page plugin affiche 0.2.39 beta 17 et quand je clique sur mise à jour il affiche 0.2.38 matrix 1??? Lequel est utilisé ?

**Comment by enigma131** [comment]
En plus le plugin ne se met plus à jour sur Nexus.

**Comment by enigma131** [comment]
Oui c'est lié à Nexus mais comment le régler ou diagnostiquer, je suis prêt à contribuer mais je ne sais pas quoi est impliqué. Widewine c'est via inputstreamhelper non ?
J'ai 2 PVRs qui merdent aussi sous Nexux mais OK sous Windows.

**Comment by joaopa00** [comment]
Ben je n'en sais pas plus que toi. Il doit y avoir une différence dans les requêtes qui font qu'elles sont ou non acceptées par le serveur de BFM.

**Comment by enigma131** [comment]
Crois - tu qu'i vont me renseigner sur le github inputsteamhelper en leur parlant de catchup tv and more ?

**Comment by joaopa00** [comment]
Android Nexus 20: pas de problème

**Comment by enigma131** [comment]
Via la beta ou non ?

**Comment by joaopa00** [comment]
Oui, la béta 18

**Comment by enigma131** [comment]
Le mien ne me propose pas de maj, tu l'as installé manuellement ?

**Comment by joaopa00** [comment]
Non, c'était disponible sur Kodi.

**Comment by enigma131** [comment]
Reçu, oui marche sur Android + nexus, c'est dingue ça

**Comment by enigma131** [comment]
Flatpak (pour Linux) est mis à jour Nexux aussi, mais avec ce dernier le plugin ne se met même pas à jour en version beta... aucune version Linux ne marche pour l'instant avec ces chaines.
https://flathub.org/apps/details/tv.kodi.Kodi

**Comment by enigma131** [comment]
Pourquoi la version beta ne se charge plus sous Nexus (Windows + Linux (deb et Flatpak)) ?

**Comment by enigma131** [comment]
J'ai peut être trouvé une piste. En voulant mettre à jour inputstream helper, je reçois une erreur, une piste ?

2023-01-25 17:25:59.530 T:383764   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'FileNotFoundError'>
                                                   Error Contents: [Errno 2] No such file or directory: '/home/toto/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/4.10.2557.0-linux-x64.zip'
                                                   Traceback (most recent call last):
                                                     File "/home/toto/.kodi/addons/script.module.inputstreamhelper/default.py", line 8, in <module>
                                                       run(sys.argv)
                                                     File "/home/toto/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 14, in run
                                                       widevine_install()
                                                     File "/home/toto/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 44, in widevine_install
                                                       Helper('mpd', drm='widevine').install_widevine()
                                                     File "/home/toto/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 34, in clean_before_after
                                                       result = func(self, *args, **kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 214, in install_widevine
                                                       if not widevine_eula():
                                                     File "/home/toto/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 47, in widevine_eula
                                                       with ZipFile(compat_path(store('download_path'))) as archive:
                                                     File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
                                                       self.fp = io.open(file, filemode)
                                                   FileNotFoundError: [Errno 2] No such file or directory: '/home/toto/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/4.10.2557.0-linux-x64.zip'
                                                   -->End of Python script error report<--
                                                   
2023-01-25 17:26:01.069 T:383766 warning <general>: [script.module.inputstreamhelper] Recursively create directory '/home/toto/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/'.

**Comment by enigma131** [comment]
J'vance ...comme je peux.
Il y a un sujet ici :
https://www.reddit.com/r/kodi/comments/xha2b6/where_is_inputstream_adaptive_for_kodi_20/
qui donne le lien : https://github.com/xbmc/inputstream.adaptive/releases

qui donne la version 20.3.2-Nexus

or : apt policy kodi-inputstream-adaptive
kodi-inputstream-adaptive:
  Installé : 6:20.3.1-2~focal
  Candidat : 6:20.3.1-2~focal
 Table de version :
 *** 6:20.3.1-2~focal 500
        500 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
La dernière version n'est donc pas complée chez Ubuntu

**Comment by enigma131** [comment]
I've just tested a Flatpak Nexus version. It's working, and :
ls -la /var/lib/flatpak/app/tv.kodi.Kodi/x86_64/stable/9d8ed8de7f40016c5ea03bc70a386dc7a893e315729fdc13361c53b78c864ba1/files/lib/kodi/addons/inputstream.adaptive
total 4376
drwxr-xr-x  2 root root    4096  1 janv.  1970 .
drwxr-xr-x 85 root root    4096  1 janv.  1970 ..
lrwxrwxrwx  1 root root      28  3 févr. 19:03 inputstream.adaptive.so -> inputstream.adaptive.so.20.0
lrwxrwxrwx  1 root root      30  3 févr. 19:03 inputstream.adaptive.so.20.0 -> inputstream.adaptive.so.20.3.2
-rwxr-xr-x  2 root root 2934856 21 janv. 14:55 inputstream.adaptive.so.20.3.2

Conclusion : version 20.3. is need

**Comment by joaopa00** [comment]
Merci pour le retour. Ce n'est donc pas un problème de Catchuptvandmore. Je ferme.

**Comment by enigma131** [comment]
Windows inputstream.adaptive.dll version is also version 20.3.2 and is working

**Comment by enigma131** [comment]
Fonctionne après mise à jour de inputstream.adaptive en version 20.3.2 .

**Comment by joaopa00** [comment]
Sous ubuntu kinetic, c'est toujours la version 20.3.1 qui est disponible. Reste juste à attendre que le repo de Kodi soit mis à jour....

**Comment by enigma131** [comment]
Installe le PPA, cela devrait fonctionner : https://launchpad.net/%7Eteam-xbmc/+archive/ubuntu/ppa/+index?batch=75&memo=750&start=750
 kodi-inputstream-adaptive 	6:20.3.2-1~kinetic 	Wolfgang Schupp (12 hours ago)

**Comment by khalistoo** [comment]
@enigma131  comment tu mets a jours inpustream.adaptive sur Nexus - Android ? Moi c'est toutes les chaînes qui saccadent ou qui ne montrent que l'image  alors que sur Nexus (flatpack) Ubuntu tout fonctionne (avec la beta 18, et juste des bugs de pubs avec france tv) 

Si je me plante d'endroit, n’hésitez pas a me rediriger vers le bon thread ;)

**Comment by enigma131** [comment]
Tu as quelle version d'installé et quelle version d'Android ? Chez moi ça a été automatique avec le package Nexus installé depuis le Google Store.

**Comment by enigma131** [comment]
@khalistoo : Et la version de inputstream.adaptive que tu as sous Nexus ?

**Comment by khalistoo** [comment]
@enigma131  je viens de uninstall Kodi sur android, je suis en train de remettre la 19.5 sorry... 
Je te tiens au jus si ca remarche au replante. 

Sur Nexus Ubuntu (flatpack), le build que j ai de kodi est un 20.0.0, et input stream je suis sur la 0.5.10+matrix.1 j'immagine que c'est deja pas trop loin de la latest, et il me semble que sur Adroid j'etais pareil.

**Comment by enigma131** [comment]
@khalistoo : non 0.5.1 c'est le helper

**Comment by khalistoo** [comment]
@enigma131  c'est bien ce qu'il me semblait, merci beaucoup. 

Du coup, je viens de faire une fresh install sur Android avec: 
Kodi 19.5, 
La beta 19 de catchup, (la 17 passait correctement mais problems avec les chaine du groupe TF1, et la 18 plantait)
La 19.0.7 d' InputStreamAdaptive (qui doit etre la latest j'immagine vu que ca vient du repo officiel)... 

Ca lag de temps en temps sur les chaines tf1 (j imagine entre les "chapitres"). 

J ai pas vu de lag énormes sur France TV mais en meme temps j ai pas passé bcp de temps (mais plus que 3 minutes). 

Sur le groupe M6 ca freeze au bout de 2:15 - 2:30 en moyenne

Pas teste les BFM (pas de compte mais je peux les faire si besoin)

**Comment by enigma131** [comment]
Tu es sous quelle résolution écran ? Pilote carte graphique pour l'accélération matérielle ?

**Comment by joaopa00** [comment]
Mise  a jour de Inpustream adaptive sous Ubuntu Kinetic pour le repo officiel de Kodi. Comme prévu, cela a résolu le problème de BFMVTV et ses soeurs.
