### ISSUE TITLE
Replay RMC HS

### ISSUE THREAD

**Issue by mmtest1** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1079]
Bonjour,
Le replay de rmc ne fonctionne plus chez moi depuis plusieurs jours par contre le direct sans problème, le message affiché :  bad operand type for unary +: 'str'
mon install : RPI4 + Libreelec 10.0.4 + Kodi 19.5
widewine à jour
catchup tv and more en beta 18
un extrait du log : 

2023-01-27 17:09:42.083 T:1472     INFO <general>: initializing python engine.
2023-01-27 17:09:43.414 T:1472     INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2023-01-27 17:09:48.007 T:1472     INFO <general>: initializing python engine.
2023-01-27 17:09:49.131 T:1472     INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2023-01-27 17:09:56.450 T:1472     INFO <general>: initializing python engine.
2023-01-27 17:09:57.217 T:1472     INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2023-01-27 17:09:59.419 T:1472     INFO <general>: initializing python engine.
2023-01-27 17:10:00.147 T:1472    ERROR <general>: [Catch-up-TV-&-More.support] bad operand type for unary +: 'str'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay.py", line 282, in video
                                                       'User-Agent': + web_utils.get_random_ua(),
                                                   TypeError: bad operand type for unary +: 'str'
2023-01-27 17:10:00.147 T:1472     INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2023-01-27 17:10:08.129 T:1472     INFO <general>: Python interpreter interrupted by user
2023-01-27 17:10:08.129 T:1054     INFO <general>: Skipped 6 duplicate messages..
2023-01-27 17:10:08.129 T:1054    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay/video/?_pickle_=8004957d000000000000007d94288c075f7469746c655f948c2153324537202d20466f72c3aa742074726f706963616c6520647520477579616e61948c065f617267735f948c3a7765622f76322f636f6e74656e742f50726f647563743a3a4e4555465f4e554d32335f4e32333835323138323434343532372f6f7074696f6e739468028694752e]
2023-01-27 17:10:11.517 T:1565     INFO <general>: initializing python engine.
2023-01-27 17:10:12.978 T:1565     INFO <general>: CPythonInvoker(14, /storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2023-01-27 17:10:18.840 T:1565     INFO <general>: initializing python engine.
2023-01-27 17:10:19.612 T:1565    ERROR <general>: [Catch-up-TV-&-More.support] bad operand type for unary +: 'str'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay.py", line 282, in video
                                                       'User-Agent': + web_utils.get_random_ua(),
                                                   TypeError: bad operand type for unary +: 'str'
2023-01-27 17:10:19.619 T:1565     INFO <general>: CPythonInvoker(14, /storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2023-01-27 17:10:22.801 T:1565     INFO <general>: Python interpreter interrupted by user
2023-01-27 17:10:22.802 T:1054     INFO <general>: Skipped 1 duplicate messages..
2023-01-27 17:10:22.802 T:1054    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay/video/?_pickle_=80049572000000000000007d94288c075f7469746c655f948c1653354533202d20416c657274652074656d70c3aa7465948c065f617267735f948c3a7765622f76322f636f6e74656e742f50726f647563743a3a4e4555465f4e554d32335f4e32333933333937383731343532372f6f7074696f6e739468028694752e]
2023-01-27 17:10:22.802 T:1054     INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2023-01-27 17:10:25.695 T:1392    ERROR <general>: DoWork - Direct texture file loading failed for resource://resource.images.catchuptvandmore/channels/fr/rmcbfmplay_fanart.jpg
2023-01-27 17:10:25.698 T:1095    ERROR <general>: DoWork - Direct texture file loading failed for resource://resource.images.catchuptvandmore/channels/fr/rmcbfmplay.png
2023-01-27 17:10:26.250 T:1605     INFO <general>: initializing python engine.
2023-01-27 17:10:27.196 T:1605     INFO <general>: CPythonInvoker(15, /storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully

si besoin de plus d'info ou de test je suis disponible
merci pour le travail accompli

**Comment by joaopa00** [comment]
C'est déjà fixé dans GIT. Il faut utiliser soit le GIT ou attendre que la béta sorte ou que la version stable sorte.

**Comment by mmtest1** [comment]
Merci beaucoup, bonne soirée
