### ISSUE TITLE
404 Client Error sur les chaines France.tv la1ere

### ISSUE THREAD

**Issue by nicos974** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1088]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
Une erreur 404 Client Error se produit systématiquement sur les chaines la1ere de France.tv.
Se produit sur tout périphérique (Mac, Windows, boitier TV multimédia)
Le programme s'affiche correctement, seul le live est en erreur.

### Screenshots
[Screenshot](https://github.com/nicos974/Pictures/blob/caefa4327e90fa9d37b134a427b210909957f3d9/Screenshot.png)

### Your environment
 - [ ] Android
 - [ ] OSX
 - [ ] Windows

 - Operating system version/name: MacOS Ventura 13.1
 - Kodi version: Kodi 19.3
 - Catch-up TV & More version: 0.2.39

### Additional context
Add any other context about the problem here:

### Debug log
2023-02-06 09:52:53.991 T:5755     INFO <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/la_1ere/get_live_url/?item_id=la_1ere&language=R%C3%A9union
2023-02-06 09:52:54.043 T:6864     INFO <general>: initializing python engine.
2023-02-06 09:52:58.853 T:6864    ERROR <general>: [Catch-up-TV-&-More.support] 404 Client Error: Not Found for url: https://la1ere.francetvinfo.fr/webservices/mobile/live.json
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/la_1ere.py", line 147, in get_live_url
                                                       resp = urlquick.get(URL_LIVES_JSON,
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/urlquick.py", line 493, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/urlquick.py", line 487, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/urlquick.py", line 442, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/urlquick.py", line 415, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/models.py", line 960, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://la1ere.francetvinfo.fr/webservices/mobile/live.json
2023-02-06 09:52:58.867 T:6864    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 290, in error_handler
                                                       code = exception.code
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--
                                                   
2023-02-06 09:52:59.212 T:6864     INFO <general>: Python interpreter stopped

**Comment by joaopa00** [comment]
J'ai testé. Pas de problème pour moi avec la béta 19. Essaie avec elle.

**Comment by S3LL1G28** [comment]
Même chose pour mytf1 replay même avec la beta.

**Comment by joaopa00** [comment]
C'est quoi le rapport avec les chaines de La première????

**Comment by S3LL1G28** [comment]
Mes excuses je vais creer une autre issue

**Comment by joaopa00** [comment]
Pas de nouvelles  du rapporteur. Si le problème persiste, n'hésitez pas à réouvrir.
