### ISSUE TITLE
Live Équipe 21 ne fonctionne plus

### ISSUE THREAD

**Issue by GregAce** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1117]
Android TV + kodi 20  + 0.2.39 beta 20

2023-03-07 08:32:43.100 T:6831     info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/lequipe/get_live_url/?item_id=lequipe
2023-03-07 08:32:43.655 T:7969    error <general>: [Catch-up-TV-&-More.support] list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/lequipe.py", line 111, in get_live_url
                                                       live_id = re.compile(r'video-id\=\"(.*?)\"', re.DOTALL).findall(resp.text)[0]
                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
                                                   IndexError: list index out of range
2023-03-07 08:32:43.677 T:7969    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'kodi_six.xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 337, in error_handler
                                                       log_uploader = importlib.import_module('resources.lib.log_uploader')
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
                                                       return _bootstrap._gcd_import(name[level:], package, level)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 940, in exec_module
                                                     File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/log_uploader.py", line 22, in <module>
                                                       LOGPATH = xbmc.translatePath('special://logpath')
                                                                 ^^^^^^^^^^^^^^^^^^
                                                   AttributeError: module 'kodi_six.xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--

**Comment by joaopa00** [comment]
Je confirme le problème (une petite note au passage, attacher les logs au lieu de les copier-coller)

**Comment by joaopa00** [comment]
Devrait  être resolu dans GIT.
