### ISSUE TITLE
Latest Version on latest Kodi Version 20

### ISSUE THREAD

**Issue by kalligrafin** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1120]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:
 I Have an netherland IP Adress, can not start any netherland channel. Error is always: list indices  must be integers or slices 

### To Reproduce
Steps to reproduce the behaviour:
1.start kodi
2.start catchup
3.choose Netherland
4.

### Expected behaviour
A clear and concise description of what you expected to happen:Starting channel

### Actual behaviour
Tell us what happens instead:error 

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - x[ ] Android Firetv
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:20
 - Catch-up TV & More version:0.2.3 matrix.1
 - Installation method:Addon Kodi on Firetv

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by enigma131** [comment]
Hi, have you try latest beta release ? (0.2.39 beta 20)

**Comment by kalligrafin** [comment]
Hi , there is no beta version for catch on kodi ( Firetv) latest is .38Thx Am 10.03.2023 um 20:15 schrieb enigma131 ***@***.***>:﻿
Hi, have you try latest beta release ? (0.2.39 beta 20)

**Comment by kalligrafin** [comment]
Sorry tomatoes on my eyes. I reinstalled Kodi nexus version 20, installed catch 039 latest beta , same problem on my firetv. Error netherland channel indies Mississippi integers and slices . Can you help me ?

**Comment by joaopa00** [comment]
You need to attach a log with ffmpeg,  curl video and channel enabled

**Comment by kalligrafin** [comment]
I am sorry, I am new to this, I do not know what you mean. Thx for helping

**Comment by Id2ndR** [comment]
Trying to install the latest beta on Kodi 20 Nexus give me this error in the log:

    error <general>: Requested path https://mirrors.kodi.tv/addons/matrix/script.module.codequick/script.module.codequick-1.0.2+matrix.1.zip not found in known repository directories

**Comment by joaopa00** [comment]
Here is the wiki to install the latest beta [wiki](https://catch-up-tv-and-more.github.io/installation/)

**Comment by darodi** [comment]
↪ Root menu (1) ➡ Live TV (1) ➡ Netherlands (10) ➡ NPO 1 (1)

resp_token = urlquick.get(URL_TOKEN_API, headers=headers, max_age=-1)
with URL_TOKEN_API =  https://www.npostart.nl/api/token
returns no response 
and     api_token = json_parser_token['token'] gives the error


```
2023-07-12 19:57:23.272 T:12296   error <general>: [Catch-up-TV-&-More.support] list indices must be integers or slices, not str
   Traceback (most recent call last):
	 File "C:\Users\rodi_\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
	   redirect = parent_ins(route, arg_params, self.callback_params)
	 File "C:\Users\rodi_\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 67, in __call__
	   results = super(Resolver, self).__call__(route, args, kwargs)
	 File "C:\Users\rodi_\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\script.py", line 169, in __call__
	   return route.function(self, *args, **kwargs)
	 File "C:\Users\rodi_\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\nl\npo.py", line 361, in get_live_url
	   api_token = json_parser_token['token']
   TypeError: list indices must be integers or slices, not str

```

**Comment by darodi** [comment]
It is geo locked for me, I can't help more. sorry

>Vanwege uitzendrechten is het niet mogelijk om deze uitzending buiten Nederland te bekijken.
>
>We verwijzen je graag door naar de livestream van BVN. BVN toont een uitgebreide selectie van de tv-programma's van NPO.
>
>Start hier de BVN livestream.
