### ISSUE TITLE
France 24 et Euronews Hs

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1126]
Sans doute flux cassés.

**Comment by joaopa00** [comment]
Problème de Kodi, pas de Catchuptvandmre. Youtube a changé son API. C'est fixé dans le github de YTDL, mais  Kodi n'embarque pas encore cette nouvelle version.

**Comment by dirkf** [comment]
Est-ce que votre Kodi(s) accède(nt) à France 24 et à Euronews par YouTube?

Sinon, le changement d'API par YouTube et ce problème associé de YouTube-DL ne sont pas liés.

**Comment by joaopa00** [comment]
Oui, Catchuptvandmore utilise youtube-dl pour lire les flux de France 24 et Euronews
023-03-23 14:14:34.536 T:10543   debug <general>: ------ Window Deinit (DialogNotification.xml) ------
2023-03-23 14:14:35.569 T:10609   debug <general>: [Catch-up-TV-&-More] [youtube] NiRIbKwAejk: Downloading m3u8 information
                                                   
2023-03-23 14:14:36.142 T:10609   debug <general>: [Catch-up-TV-&-More] [youtube] NiRIbKwAejk: Downloading MPD manifest
                                                   
2023-03-23 14:14:37.766 T:10609   debug <general>: [Catch-up-TV-&-More] ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
                                                   
2023-03-23 14:14:37.767 T:10609   error <general>: [Catch-up-TV-&-More.support] Youtube-DL: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
                                                   Traceback (most recent call last):
                                                     File "/home/joaopa00/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/joaopa00/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/home/joaopa00/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/home/joaopa00/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/wo/euronews.py", line 42, in get_live_url
                                                       return resolver_proxy.get_stream_youtube(plugin, json_parser['videoId'], False)
                                                     File "/home/joaopa00/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py", line 351, in get_stream_youtube
                                                       return get_stream_default(plugin, url_youtube, download_mode)
                                                     File "/home/joaopa00/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py", line 253, in get_stream_default
                                                       return plugin.extract_source(video_url, quality)
                                                     File "/home/joaopa00/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 180, in extract_source
                                                       raise RuntimeError(stored_errors[0])
                                                   RuntimeError: Youtube-DL: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ltai0001** [comment]
Est ce qu' on peut réparer manuellement le version youtube-dl dans l'attente que Team Kodi mette a jour?
Si c'est possible peut tu expliquer comment faire?
Merci beaucoup...

**Comment by enigma131** [comment]
Pour réparer il faut que tu précise peut être pour quelle cible ?
Sous Linux il faut pendre le source et le compiler. (Pas fait de mon coté, j'utilise le navigateur internet pour les visualiser)

**Comment by dirkf** [comment]
Comme a dit [@joaopa00](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1126#issuecomment-1475431408), je crois que le problème existe à https://github.com/Catch-up-TV-and-More/script.module.youtube.dl/tree/dev/lib/youtube_dl. Il faut remplacer les fichiers de youtube-dl par ceux de https://github.com/ytdl-org/youtube-dl/tree/master/youtube_dl, c'est-à-dire les fichiers courants qui sont beaucoup meilleurs que ceux de '2021.03.03', version très ancienne. Ça comprend le PR https://github.com/ytdl-org/youtube-dl/pull/31675 qui corrige le problème "[YouTube] Unable to extract uploader id".

**Comment by joaopa00** [comment]
PR envoyé à xbmc/repo-script pour mettre à jour le dépot avec la version git de youtube-dl. Lorsque la PR sera mergée, pour ceux qui sont sur un sytème à base de linux, si vous avez installé youtube-dl, il faudra le désinstaller puisque Kodi utilse en priorité la version système de youtube-dl au lieu de la version embarquée.

**Comment by joaopa00** [comment]
Malgrè plusieurs relances de ma part sur le github de repo/script, pas de nouvelles de ma PR malheureusement :(

**Comment by joaopa00** [comment]
Bonne nouvelle. Youtube-DL est enfin mergé dans xbmc/repo-script (pour le moment suelement pour les versions de Kodi >18). Euronews refonctionne pour ces versions.
Problème d'adresse pour France24. Je regarde ça.


Je vais aussi bentôt faire une PR pour Youtube-DL pour Kodi 18.

**Comment by joaopa00** [comment]
Ca devrait être résolu dans GIT.
