### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by gpmas** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1132]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
I can't see any channels for M6 group (gulli...), it's ok for TF1, France TV...

### To Reproduce
Steps to reproduce the behaviour:
1. Go in Catch Up TV & More
2. TV en direct / France
3. Chose M6

### Your environment
 - [ ] Android TV : Xiaomi Box 3

 - Operating system version/name:
 - Kodi version: 20.1
 - Catch-up TV & More version: 0.2.38+matrix.1
 - Installation method: https://catch-up-tv-and-more.github.io/fr/installation/ (from dépôt)

### Additional context
I have delete kodi and clear all datas before installation

### Debug log
`2023-04-02 22:50:13.136 T:12391 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-04-02 22:50:13.138 T:12391 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-04-02 22:50:13.139 T:12391 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-04-02 22:50:13.140 T:12391 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-04-02 22:50:13.141 T:12391 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-04-02 22:50:13.142 T:12391 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-04-02 22:50:13.143 T:12391 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-04-02 22:50:13.144 T:12391 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-04-02 22:50:13.144 T:12391 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-04-02 22:50:13.145 T:12391 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-04-02 22:50:13.146 T:12391 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-04-02 22:50:13.147 T:12391 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-04-02 22:50:13.148 T:12391 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-04-02 22:50:13.149 T:12391 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-04-02 22:50:13.149 T:12391 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-04-02 22:50:13.150 T:12391 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-04-02 22:50:13.151 T:12391 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-04-02 22:50:13.152 T:12391 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-04-02 22:50:13.153 T:12391 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-04-02 22:50:13.154 T:12391 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-04-02 22:50:13.154 T:12391 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-04-02 22:50:13.155 T:12391 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-04-02 22:50:13.156 T:12391 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2023-04-02 22:50:13.157 T:12391 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-04-02 22:50:22.977 T:11863    info <general>: PVR Manager: Starting cleanup of cached images.
2023-04-02 22:50:24.040 T:11863    info <general>: PVR Manager: Cleaned up 0 cached images.
2023-04-02 22:50:28.442 T:12391   error <general>: [Catch-up-TV-&-More.support] list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/6play.py", line 572, in get_live_url
                                                       api_key = re.compile(r'\"[eu1.gigya.com](http://eu1.gigya.com/)\"\,key\:\"(.*?)\"').findall(
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   IndexError: list index out of range
2023-04-02 22:50:28.502 T:12391   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'kodi_six.xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 337, in error_handler
                                                       log_uploader = importlib.import_module('resources.lib.log_uploader')
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
                                                       return _bootstrap._gcd_import(name[level:], package, level)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 940, in exec_module
                                                     File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/log_uploader.py", line 22, in <module>
                                                       LOGPATH = xbmc.translatePath('special://logpath')
                                                                 ^^^^^^^^^^^^^^^^^^
                                                   AttributeError: module 'kodi_six.xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
                                                   
2023-04-02 22:50:28.910 T:11823   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/6play/get_live_url/?_pickle_=80049551000000000000007d94288c075f7469746c655f948c0e4d3620e28094204361706974616c948c08786d6c74765f6964948c14433131382e6170692e74656c6572616d612e6672948c076974656d5f6964948c026d3694752e]
2023-04-02 22:50:36.595 T:12461   error <general>: [Catch-up-TV-&-More.support] list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/6play.py", line 572, in get_live_url
                                                       api_key = re.compile(r'\"[eu1.gigya.com](http://eu1.gigya.com/)\"\,key\:\"(.*?)\"').findall(
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   IndexError: list index out of range
2023-04-02 22:50:36.659 T:12461   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'kodi_six.xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 337, in error_handler
                                                       log_uploader = importlib.import_module('resources.lib.log_uploader')
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
                                                       return _bootstrap._gcd_import(name[level:], package, level)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 940, in exec_module
                                                     File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/log_uploader.py", line 22, in <module>
                                                       LOGPATH = xbmc.translatePath('special://logpath')
                                                                 ^^^^^^^^^^^^^^^^^^
                                                   AttributeError: module 'kodi_six.xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
                                                   
2023-04-02 22:50:36.986 T:11823   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/6play/get_live_url/?_pickle_=80049551000000000000007d94288c075f7469746c655f948c0e4d3620e28094204361706974616c948c08786d6c74765f6964948c14433131382e6170692e74656c6572616d612e6672948c076974656d5f6964948c026d3694752e]
2023-04-02 22:50:52.451 T:11823    info <general>: Loading skin file: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.kodi.loguploader/resources/skins/default/1080i/script-loguploader-view.xml, load type: LOAD_ON_GUI_INIT
2023-04-02 22:53:05.610 T:11836    info <general>: CActiveAESink::OpenSink - initialize sink
2023-04-02 22:53:05.611 T:11836    info <general>: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2023-04-02 22:53:05.612 T:11836    info <general>: Minimum size we need for stream: 15104 Bytes`

**Comment by joaopa00** [comment]
Already fixed in beta
