### ISSUE TITLE
FR C8 replay - list index out of range

### ISSUE THREAD

**Issue by darodi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1133]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
C8 replay gives `list index out of range`

### To Reproduce
Steps to reproduce the behaviour:
1. 2  📁   Catch-up TV 
2. 2  📁   France   
3. 3  📁   myCANAL   
4. 2  📁   C8

### Expected behaviour
c8 program list

### Actual behaviour
list index out of range

### Your environment
 - [x] Android
 - [x] Linux
 - [x] Raspberry-Pi
 - [x] Windows

 - Catch-up TV & More version: last
 - Installation method: github clone

### Additional context
Add any other context about the problem here:

API changed?

`re.compile(r'window.__data=(.*?); window.app_config').findall(resp.text)`

returns nothing

### Debug log
```
 error <general>: [Catch-up-TV-&-More.support] list index out of range
   Traceback (most recent call last):
	 File "C:\Users\rodi_\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
	   redirect = parent_ins(route, arg_params, self.callback_params)
	 File "C:\Users\rodi_\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\route.py", line 196, in __call__
	   session_data = self._process_results(results)
	 File "C:\Users\rodi_\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\route.py", line 210, in _process_results
	   listitems = validate_listitems(results)
	 File "C:\Users\rodi_\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\route.py", line 39, in validate_listitems
	   raw_listitems = list(raw_listitems)
	 File "C:\Users\rodi_\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\fr\mycanal.py", line 130, in list_categories
	   json_replay = re.compile(
   IndexError: list index out of range
```

**Comment by joaopa00** [comment]
Mycanal étant géobloqué, je ne peux tester. Quelqu'un d'autre devra essayer de résoudre le problème.

**Comment by darodi** [comment]
je vais essayer de trouver le temps, mais l'API et le contenu des pages semble avoir complètement changé

**Comment by joaopa00** [comment]
Bonjour

la solution est toujours la même: envoyer des patches qui résout le problème.
Comme je n'ai pas accès à mycanal, je ne peux pas jeter un oeil au problème. Et suivant Darodi résoudre le problème n'a pas l'air s'être trivial.

**Comment by identik5** [comment]
D'accord, et vous savez ou je peux avoir le patch mycanal du coup :) ? 
Merci beaucoup pour votre réponse en tout cas :)
