### ISSUE TITLE
UKTV Play not working

### ISSUE THREAD

**Issue by aaaaaaaargh** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1137]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
Errormessage when trying to watch UKTV Play 

### To Reproduce
Steps to reproduce the behaviour:
    1. Select Catch Up
    2. Select United Kingdom
    3. Select UKTV Play
    4. Try to play any Video

### Expected behaviour
Video should play

### Actual behaviour
Errormessage "Type Error" "decoding str is not supported" is displayed

### Your environment
Operating system version/name: Linux (LibreELEC 10.0.4)
Kodi version: 19.5
Catch-up TV & More version: Latest BETA (0.2.39~beta23)
Installation method: From Catch Up TV Beta Repo

### Debug log
```
2023-04-10 11:05:18.491 T:1610     INFO <general>: initializing python engine.
2023-04-10 11:05:18.739 T:1610  WARNING <CAddonSettings[inputstream.adaptive]>: failed to load value "" for setting DECRYPTERPATH
2023-04-10 11:05:18.739 T:1610  WARNING <CAddonSettings[inputstream.adaptive]>: failed to load value "" for setting MAXBANDWIDTH
2023-04-10 11:05:18.744 T:1610  WARNING <CAddonSettings[inputstream.adaptive]>: failed to load value "" for setting DECRYPTERPATH
2023-04-10 11:05:18.744 T:1610  WARNING <CAddonSettings[inputstream.adaptive]>: failed to load value "" for setting MAXBANDWIDTH
2023-04-10 11:05:18.750 T:1610  WARNING <CAddonSettings[inputstream.adaptive]>: failed to load value "" for setting DECRYPTERPATH
2023-04-10 11:05:18.750 T:1610  WARNING <CAddonSettings[inputstream.adaptive]>: failed to load value "" for setting MAXBANDWIDTH
2023-04-10 11:05:18.755 T:1610  WARNING <CAddonSettings[inputstream.adaptive]>: failed to load value "" for setting DECRYPTERPATH
2023-04-10 11:05:18.755 T:1610  WARNING <CAddonSettings[inputstream.adaptive]>: failed to load value "" for setting MAXBANDWIDTH
2023-04-10 11:05:18.760 T:1610  WARNING <CAddonSettings[inputstream.adaptive]>: failed to load value "" for setting DECRYPTERPATH
2023-04-10 11:05:18.760 T:1610  WARNING <CAddonSettings[inputstream.adaptive]>: failed to load value "" for setting MAXBANDWIDTH
2023-04-10 11:05:18.791 T:1610  WARNING <CAddonSettings[inputstream.adaptive]>: failed to load value "" for setting DECRYPTERPATH
2023-04-10 11:05:18.792 T:1610  WARNING <CAddonSettings[inputstream.adaptive]>: failed to load value "" for setting MAXBANDWIDTH
2023-04-10 11:05:18.794 T:1610  WARNING <CAddonSettings[inputstream.adaptive]>: failed to load value "" for setting DECRYPTERPATH
2023-04-10 11:05:18.794 T:1610  WARNING <CAddonSettings[inputstream.adaptive]>: failed to load value "" for setting MAXBANDWIDTH
2023-04-10 11:05:18.826 T:1610  WARNING <general>: [script.module.inputstreamhelper] Widevine update check was made on 2023-04-06 11:23
2023-04-10 11:05:19.709 T:1610    ERROR <general>: [Catch-up-TV-&-More.support] decoding str is not supported
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 871, in text
                                                       content = str(self.content, encoding, errors='replace')
                                                   TypeError: decoding str is not supported

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/uk/uktvplay.py", line 262, in get_video_url
                                                       (get_brightcove_policy_key(data_account, data_player))
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/uk/uktvplay.py", line 231, in get_brightcove_policy_key
                                                       return re.compile('policyKey:"(.+?)"').findall(file_js.text)[0]
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 879, in text
                                                       content = str(self.content, errors='replace')
                                                   TypeError: decoding str is not supported
2023-04-10 11:05:19.729 T:1610  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
```

**Comment by aaaaaaaargh** [comment]
Additional info: This used to work with Kodi Matrix / LibreElec9

**Comment by joaopa00** [comment]
Tested with the video Annika S1E1: no problem. You have to attach the full log with debug enabled and specially the channels curl video and ffmpeg enabled

**Comment by aaaaaaaargh** [comment]
The problem seems to be caused by leftovers when upgrading from LE9/Kodi18 to LE10/Kodi19
Everything works fine with a fresh installation of Libreelec10/Kodi19 and LE11/Kodi20. 
So I'd better do a fresh install to avoid more problems, thanks!
