### ISSUE TITLE
Cannot play RMC Decouverte

### ISSUE THREAD

**Issue by SecT0uch** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1143]
### Describe the bug
I'm unable to play RMC Decouverte, while having no issue with RMC Story.

### To Reproduce
Steps to reproduce the behaviour:
1. Try playing RMC Decouverte

### Expected behaviour
Channel should play

### Actual behaviour
Log:
```
2023-04-29 19:39:11.026 T:3660     info <general>: CActiveAESink::OpenSink - initialize sink
2023-04-29 19:39:11.026 T:3660     info <general>: CAESinkALSA::Initialize - Attempting to open device "@"
2023-04-29 19:39:11.032 T:3660     info <general>: CAESinkALSA::Initialize - Opened device "sysdefault"
2023-04-29 19:39:11.032 T:3660     info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2023-04-29 19:39:11.032 T:3660     info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE4
2023-04-29 19:39:11.630 T:3161    error <general>: [Catch-up-TV-&-More.support] 452 Client Error: Unavailable For You for url: https://ncdn-live-pctv.pfd.sfr.net/sdash/LIVE$RMC_DECOUVERTE/index.mpd/Manifest?start=LIVE&end=END&device=dash_dyn_wide
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay.py", line 370, in get_live_url
                                                       response = urlquick.get(stream["url"])
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 493, in get
                                                       return request('get', url, params=params, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 487, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 442, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 415, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 960, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 452 Client Error: Unavailable For You for url: https://ncdn-live-pctv.pfd.sfr.net/sdash/LIVE$RMC_DECOUVERTE/index.mpd/Manifest?start=LIVE&end=END&device=dash_dyn_wide
2023-04-29 19:39:11.633 T:3161    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 290, in error_handler
                                                       code = exception.code
                                                              ^^^^^^^^^^^^^^
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--
                                                   
2023-04-29 19:39:11.776 T:3602    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay/get_live_url/?_pickle_=8004957b000000000000007d94288c075f7469746c655f948c2a524d432044c3a9636f75766572746520e2809420576865656c6572204465616c657273204672616e6365948c08786d6c74765f6964948c1543313430302e6170692e74656c6572616d612e6672948c076974656d5f6964948c0f524d432044c3a9636f75766572746594752e]
2023-04-29 19:39:11.776 T:3602     info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
```

### Your environment
 - [ X] Linux

 - Operating system version/name: CoreELEC 20.1-Nexus
 - Kodi version: Kodi Nexus v20.0 final
 - Catch-up TV & More version: Last beta
 - Installation method: Beta repository

**Comment by enigma131** [comment]
Error here too. RMC story is OK. Kodi 20.1 Linux , Catchup latest beta.

**Comment by joaopa00** [comment]
Résolu dans Git. Dommage, je venais de sortir une nouvelle béta!
