### ISSUE TITLE
UK Catch-up TV Program Errors

### ISSUE THREAD

**Issue by snoopymail** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1151]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:

When trying to playback catch-up tv programs from Channel 4, all streams produce errors. Only Channel 4 catch-up tv programs are affected and all others (Blaze, STV, UKTV Play, My 5), seem to be working fine.

### To Reproduce
Steps to reproduce the behaviour:
1. Open Catch-up TV & More.
2. Open Catch-up TV.
3. Open United Kinkdom.
4. Open Channel 4.
5. Open any Category (eg. Comedy).
6. Open any Programme  (eg. The Inbetweeners).
7. Open any Series  (eg. Series 1).
8. Open any Episode  (eg. Episode 1 (First Day)).

### Expected behaviour
A clear and concise description of what you expected to happen:

Episode playback to start.

### Actual behaviour
Tell us what happens instead:

This selection triggered an unexpected error...

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Other

 - Operating system version/name: Windows 10 Pro 22H2
 - Kodi version: 18.9.0
 - Catch-up TV & More version: Catch-up TV & More version: 0.2.39 beta26 & 0.2.39 beta07
 - Installation method: Catch-up TV & More's Beta repository & Catch-up TV & More's Release repository

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

2023-05-16 13:01:27.316 T:54820   ERROR: [Catch-up-TV-&-More.support] str() takes at most 1 argument (2 given)
                                            Traceback (most recent call last):
                                              File "C:\Users\habib\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
                                                redirect = parent_ins(route, arg_params, self.callback_params)
                                              File "C:\Users\habib\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 67, in __call__
                                                results = super(Resolver, self).__call__(route, args, kwargs)
                                              File "C:\Users\habib\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\script.py", line 169, in __call__
                                                return route.function(self, *args, **kwargs)
                                              File "C:\Users\habib\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\uk\channel4.py", line 161, in get_video
                                                cipher = AES.new(bytes('n9cLieYkqwzNCqvi', 'UTF-8'), AES.MODE_CBC, bytes('odzcU3WdUiXLucVd', 'UTF-8'))
                                            TypeError: str() takes at most 1 argument (2 given)
2023-05-16 13:01:33.644 T:65332   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/uk/channel4/get_video/?_pickle_=80027d7101285507617373657449647102580700000032393138363437710355075f7469746c655f71045815000000457069736f64652031202846697273742044617929550b70726f6772616d6d6549647105580900000034343030322d3030317106752e]

**Comment by joaopa00** [comment]
I tried Frasier series 1 Episode 1. No problèm for me? Do  you have a UK IP address?

**Comment by snoopymail** [comment]
joaopa00 has confirmed that errors occur with Kodi v18.9 which is incompatible :(
