### ISSUE TITLE
Echec lecture replay vidéo - Keyerror "Location"

### ISSUE THREAD

**Issue by Sylvain77390** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1204]
Bonsoir,
Tout d'abord merci pour votre implication dans cet addon très pratique et sans concurrence pour centraliser les rediffusions des vidéos de la TV Française. Cela fait maintenant plusieurs années que j'utilise catch up Tv et j'avais toujours jusque-là réussi à me défaire des quelques aléas que j'avais pu rencontrer, mais cela fait maintenant quelques mois que je me bats avec cela et je ne trouve pas la solution.

### Description du bug
L'addon se charge bien mais si je lance une vidéo j'ai l'erreur "Keyerror "Location" " et la vidéo ne se lance pas.

Pensant que cela venait d'une distribution Mythbuntu trop ancienne (Xenial 16.04.7 LTS) ou bien de KODI 18, j'ai migré vers Ubuntu 18.04.6 LTS (Bionic Beaver) et KODI 19 mais cela ne change rien du tout.

### Environment
 - [x] Linux  
 
 - Operating system version/name: Ubuntu 18.04.6 LTS (Bionic Beaver)
 - Kodi version: 19 
 - Catch-up TV & More version: 0.2.38+matrix.1
 - Installation method: via dépôt

### Debug log
Un extrait des logs : 
2023-08-14 21:40:55.978 T:2899     INFO <general>: initializing python engine.
2023-08-14 21:40:59.917 T:2899     INFO <general>: CPythonInvoker(16, /home/kodi/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2023-08-14 21:41:00.971 T:2899     INFO <general>: initializing python engine.
2023-08-14 21:41:01.588 T:2899    ERROR <general>: [Catch-up-TV-&-More.support] 'location'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/home/kodi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/francetv.py", line 405, in get_video_url
                                                       return resolver_proxy.get_francetv_video_stream(plugin, broadcast_id, download_mode)
                                                     File "/home/kodi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py", line 460, in get_francetv_video_stream
                                                       location_url = resp3.headers['location']
                                                     File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/structures.py", line 52, in __getitem__
                                                       return self._store[key.lower()][1]
                                                   KeyError: 'location'
2023-08-14 21:41:01.606 T:2899  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2023-08-14 21:41:09.454 T:2899     INFO <general>: CPythonInvoker(16, /home/kodi/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2023-08-14 21:41:10.700 T:2899     INFO <general>: Python interpreter interrupted by user
2023-08-14 21:41:10.700 T:1442    ERROR <general>: Skipped 9 duplicate messages..
2023-08-14 21:41:10.700 T:1442    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/francetv/get_video_url/?_pickle_=80049591000000000000007d94288c075f7469746c655f948c49432064616e73206c27616972202d204461726d616e696e2c204c65204d616972652c205068696c69707065203a204c27617072c3a8732d4d6163726f6e206120636f6d6d656e63c3a9948c0c62726f6164636173745f6964948c2430313530303430612d656339642d343865632d396564642d39343933306234363465363794752e]
2023-08-14 21:41:11.987 T:2925     INFO <general>: initializing python engine.
2023-08-14 21:41:12.975 T:2925     INFO <general>: CPythonInvoker(17, /home/kodi/.kodi/addons/script.skinshortcuts/resources/lib/entry_point.py): script successfully run
2023-08-14 21:41:13.068 T:2925     INFO <general>: Python interpreter stopped
2023-08-14 21:41:28.310 T:2929     INFO <general>: initializing python engine.
2023-08-14 21:41:37.695 T:1442     INFO <general>: Loading skin file: DialogTextViewer.xml, load type: KEEP_IN_MEMORY
2023-08-14 21:41:37.820 T:2929     INFO <general>: CPythonInvoker(18, /home/kodi/.kodi/addons/script.logviewer/default.py): script successfully run
2023-08-14 21:41:38.201 T:2929     INFO <general>: Python interpreter stopped
2023-08-14 21:41:51.119 T:1442     INFO <general>: Activate of window '10705' refused because there are active modal dialogs
2023-08-14 21:42:02.949 T:2933     INFO <general>: initializing python engine.
2023-08-14 21:42:03.954 T:2933     INFO <general>: CPythonInvoker(19, /home/kodi/.kodi/addons/script.skinshortcuts/resources/lib/entry_point.py): script successfully run
2023-08-14 21:42:04.056 T:2933     INFO <general>: Python interpreter stopped
2023-08-14 21:42:08.262 T:2945     INFO <general>: initializing python engine.
2023-08-14 21:42:09.233 T:2945     INFO <general>: CPythonInvoker(20, /home/kodi/.kodi/addons/script.skinshortcuts/resources/lib/entry_point.py): script successfully run
2023-08-14 21:42:09.329 T:2945     INFO <general>: Python interpreter stopped

En vous remerciant par avance pour votre aide.
Sylvain 77390

**Comment by joaopa00** [comment]
Tester la version béta: [installer la version beta](https://catch-up-tv-and-more.github.io/installation/)

**Comment by darodi** [comment]
@Sylvain77390 

Il y a une erreur dans le code pour le groupe M6 qui cause un "Keyerror".
J'ai envoyé une correction qui sera disponible dans la prochaine version beta.

**Comment by Sylvain77390** [comment]
Bonjour Darodi,
et merci pour l'info ; j'espère que cela résoudra mon souci car pour ma part absoluement rien ne fonctionne...

Cordialement,
Sylvain 77390

**Comment by joaopa00** [comment]
Oui cela devrait être résolu dans la prochaine béta.
