### ISSUE TITLE
BVN Live no longer functions

### ISSUE THREAD

**Issue by bruggieinoz** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1215]
Reported this issue in ERROR #1019 and this was fixed, but same issue again now.
Tried latest/Beta and other versions.

Select Live TV/International/BVN
"IndexError" list index out of range appears.

From kodi.log:

2023-08-26 21:25:28.037 T:6332    ERROR <general>: [Catch-up-TV-&-More.support] list index out of range
                                                   Traceback (most recent call last):
                                                     File "C:\Users\fbrugman\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "C:\Users\fbrugman\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "C:\Users\fbrugman\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "C:\Users\fbrugman\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\wo\bvn.py", line 162, in get_live_url
                                                       token_id = re.compile(r'start\-player\.npo\.nl\/embed\/(.*?)\"').findall(
                                                   IndexError: list index out of range

Tried this with KODI on PC and PI

Hope someone can help, thanks

**Comment by darodi** [comment]
@bruggieinoz 

fixed
will be available when #1216 is released in next beta

**Comment by bruggieinoz** [comment]
@darodi thank you so much
