### ISSUE TITLE
Cnews replay in error

### ISSUE THREAD

**Issue by gilles0606** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1243]
hello,

cnews replay generate error.

2023-11-11 20:39:09.392 T:2177    error <general>: [Catch-up-TV-&-More.support] 403 Client Error: Forbidden for url: https://www.cnews.fr/les-replays
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                       session_data = self._process_results(results)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                       listitems = validate_listitems(results)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                       raw_listitems = list(raw_listitems)
                                                                       ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/cnews.py", line 83, in list_emissions
                                                       resp = urlquick.get(URL_REPLAY_CNEWS, max_age=-1)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 492, in get
                                                       return request('get', url, params=params, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 486, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 441, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 414, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.cnews.fr/les-replays
2023-11-11 20:39:09.397 T:2177    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 290, in error_handler
                                                       code = exception.code
                                                              ^^^^^^^^^^^^^^
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--
                                                   

thanks...

**Comment by joaopa00** [comment]
Merci pour le report de bug. Devrait être fixé dans GIT.

**Comment by gilles0606** [comment]
merci je confirme que cela refonctionne...
1000 Merci à toi...
