### ISSUE TITLE
RMC PLAY KO

### ISSUE THREAD

**Issue by osmoze06** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1286]
Bonjour à tous,

RMCPLAY semble hors service, test effectué sur Android + PC.

`2024-02-29 21:21:13.624 T:20056   error <general>: [Catch-up-TV-&-More.support] 'title'
                                                   Traceback (most recent call last):
                                                     File "C:\Kodi_Install\KODI_HK3\portable_data\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "C:\Kodi_Install\KODI_HK3\portable_data\addons\script.module.codequick\lib\codequick\route.py", line 196, in __call__
                                                       session_data = self._process_results(results)
                                                     File "C:\Kodi_Install\KODI_HK3\portable_data\addons\script.module.codequick\lib\codequick\route.py", line 210, in _process_results
                                                       listitems = validate_listitems(results)
                                                     File "C:\Kodi_Install\KODI_HK3\portable_data\addons\script.module.codequick\lib\codequick\route.py", line 39, in validate_listitems
                                                       raw_listitems = list(raw_listitems)
                                                     File "C:\Kodi_Install\KODI_HK3\portable_data\addons\plugin.video.catchuptvandmore\resources\lib\channels\fr\rmcbfmplay.py", line 107, in rmcbfmplay_root
                                                       item.label = spot["title"]
                                                   KeyError: 'title'
2024-02-29 21:21:13.652 T:20056   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'kodi_six.xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "C:\Kodi_Install\KODI_HK3\portable_data\addons\plugin.video.catchuptvandmore\addon.py", line 23, in <module>
                                                       main()
                                                     File "C:\Kodi_Install\KODI_HK3\portable_data\addons\plugin.video.catchuptvandmore\addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "C:\Kodi_Install\KODI_HK3\portable_data\addons\plugin.video.catchuptvandmore\resources\lib\main.py", line 337, in error_handler
                                                       log_uploader = importlib.import_module('resources.lib.log_uploader')
                                                     File "C:\Kodi_Install\KODI_HK3\system\python\Lib\importlib\__init__.py", line 127, in import_module
                                                       return _bootstrap._gcd_import(name[level:], package, level)
                                                     File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 778, in exec_module
                                                     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
                                                     File "C:\Kodi_Install\KODI_HK3\portable_data\addons\plugin.video.catchuptvandmore\resources\lib\log_uploader.py", line 22, in <module>
                                                       LOGPATH = xbmc.translatePath('special://logpath')
                                                   AttributeError: module 'kodi_six.xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
                                                   
2024-02-29 21:21:13.797 T:17692   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay/rmcbfmplay_root/?_pickle_=80049541000000000000007d94288c075f7469746c655f948c0c524d432042464d20506c6179948c08786d6c74765f6964944e8c076974656d5f6964948c0a726d6362666d706c617994752e
2024-02-29 21:21:13.798 T:19080   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay/rmcbfmplay_root/?_pickle_=80049541000000000000007d94288c075f7469746c655f948c0c524d432042464d20506c6179948c08786d6c74765f6964944e8c076974656d5f6964948c0a726d6362666d706c617994752e) failed`

**Comment by IceFreak66** [comment]
I have been struggling for a while on that one.
Turns out, in the json response of the main menu call of the RMC replay, some items in the spots list don't have a title.

Adding an existence check for the title property fixes the issue.

In rmcbfmplay.py, add : if "title" in spot: between lines 105 and 106

**Comment by geoffde** [comment]
It work perfectly. 

Thank you.

**Comment by osmoze06** [comment]
Bonjour à tous,

Test à nouveau ce soir, c'est directement l'accès à la rubrique RMC Replay qui ne fonctionne plus.

Ce n'est plus lors de l'accès aux épisodes des différentes émissions.

C'est carrément l'accès complet.

Merci pour votre aide.![IMG_20240301_205603.jpg](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/33359510/01138878-4d42-4cd9-9339-892a3be52d83)

**Comment by ghost** [comment]
Same issue on firetv stick  cannot access to json file for this modification

_Turns out, in the json response of the main menu call of the RMC replay, some items in the spots list don't have a title.

Adding an existence check for the title property fixes the issue.

In rmcbfmplay.py, add : if "title" in spot: between lines 105 and 106_

**Comment by willow3411** [comment]
bonjour, 
cela ne fonctionne pas chez moi sous libreelec RPI4 .
Que faut t'il ecrire exactement ?
merci

**Comment by yapa69** [comment]
> bonjour, cela ne fonctionne pas chez moi sous libreelec RPI4 . Que faut t'il ecrire exactement ? merci

Salut,

faut juste faire attention à l'indentation en python à la ligne en dessous
```
item = Listitem()
if "title" in spot:
    item.label = spot["title"]
item.set_callback(menu, "web/v1/spot/%s/content" % spot["id"])
```
c'est un épisode de VIntage Mecaninc S8E24 qui fou la grouille, il apparait ensuite en titre UNKNOWN
J'ai fait une PR https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1294

**Comment by joaopa00** [comment]
Rustine dans GIT. Je ferme. Merci pour le travail effectué.
