### ISSUE TITLE
Cnews Replay H.S.

### ISSUE THREAD

**Issue by gilles0606** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1351]
J'ai bien la dernière version

### Describe the bug
Le replay de cnews ne marche plus

### To Reproduce
juste essayer le replay de cnews

### Expected behaviour
J'ai mis les logs à la fin du message

### Your environment
 - [* ] Raspberry-Pi libreelec latest
 
### Debug log
2024-05-18 07:16:19.578 T:1922    error <general>: [Catch-up-TV-&-More.support] 403 Client Error: Forbidden for url: https://www.cnews.fr/les-replays
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                       session_data = self._process_results(results)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                       listitems = validate_listitems(results)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                       raw_listitems = list(raw_listitems)
                                                                       ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/cnews.py", line 85, in list_emissions
                                                       resp = urlquick.get(URL_REPLAY_CNEWS, headers=GENERIC_HEADERS, max_age=-1)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 492, in get
                                                       return request('get', url, params=params, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 486, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 441, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 414, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.cnews.fr/les-replays
2024-05-18 07:16:19.580 T:1922    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 297, in error_handler
                                                       code = exception.code
                                                              ^^^^^^^^^^^^^^
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--

merci

**Comment by joaopa00** [comment]
Devrait être fixé dans Git

**Comment by gilles0606** [comment]
Je confirme que cela refonctionne.
GRAND MERCI
