### ISSUE TITLE
RTL-TVI ne fonctionne pas

### ISSUE THREAD

**Issue by wilfarte** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1362]
Version 0.2.40  beta 08
Kodi version 21.0

Nvidia shield

Lorsque je sélectionne une chaine pour regarder en direct, j'ai un écran d'erreur avec le mot "video"
Je vous envoie les logs
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/15421087/kodi.log)

**Comment by joaopa00** [comment]
Est-ce que ça se passe pour toutes les chaînes ou seulement rtlplaybe?

**Comment by wilfarte** [comment]
Je viens d'essayer TF1 France 2 et France 3 live et c'est ok
RTL-TVI Plug RTL et ClubRTL donnent l'erreur

**Comment by joaopa00** [comment]
Ce sont certainement des problèmes différents pour chaque chaînes alors. Un seul problème par ticket.
Focalisons nous sur RTL-TVI dans ce ticket. Pour les autres chaînes ouvbres autant de tickets que de problèmes.

Attache un log complet (avec déboggage activé avec les canaux de déboggage curl video et audio activés)
Merci d'avance

**Comment by wilfarte** [comment]
Pouvez vous me dire où je peux activer ces modes de déboggage pour avoir un log complet?
Je pense avoir trouvé et j'espère que ce sera complet
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/15446961/kodi.log)

**Comment by jacqueminf** [comment]
Bonjour,

J'ai le même problème sous raspberry
kodi 20.2.0
Catch-up TV&More version : 0.2.39

Merci pour votre aide.


Voici les logs:
***************
2024-06-16 21:21:31.830 T:3083    error <general>: [Catch-up-TV-&-More.support] 404 Client Error: Not Found for url: https://e.m6web.fr/info?customer=rtlbe
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtlplaybe.py", line 701, in get_live_url
                                                       device_id = get_device_id()
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtlplaybe.py", line 756, in get_device_id
                                                       json_parser = urlquick.get(DEVICE_ID_URL, headers=headers, max_age=-1).json()
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 492, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 486, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 441, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 414, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://e.m6web.fr/info?customer=rtlbe
2024-06-16 21:21:31.834 T:3083    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 290, in error_handler
                                                       code = exception.code
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--
                                                   
2024-06-16 21:21:32.102 T:501     error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/be/rtlplaybe/get_live_url/?_pickle_=80049563000000000000007d94288c075f7469746c655f948c1b52544c2d54564920e280942043616d70696e672050617261646973948c08786d6c74765f6964948c14433136382e6170692e74656c6572616d612e6672948c076974656d5f6964948c0772746c5f74766994752e]

**Comment by darodi** [comment]
@jacqueminf 

utiliser la dernière version beta
https://e.m6web.fr/info?customer=rtlbe n'est plus appelé dans le code depuis avril.

**Comment by darodi** [comment]
## TODO

### live
- `URL_LIVE_JSON` ne fonctionne plus.
- Modifier la méthode `get_video_assets(plugin, token, item_id)`
   - Les urls sont `https://www.rtlplay.be/rtlplay/direct/[tvi, club, plug, contact, bel]`
   - Parser `window.App.playerData` et `window.dataLayer`

### replay
- Gérer le nouveau login SSO
- Pouvoir récupérer les films, séries non présents via l'ancienne API

**Comment by nirolfa** [comment]
duplicate de https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1434
