### ISSUE TITLE
TF1 : message d'erreur et chaîne France Television (France2, 3, 4 et 5) qui se bloquent

### ISSUE THREAD

**Issue by crocketear** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1373]
Configuration : 
- libreelec 12.0 sur raspberry 4
- CUTV&M 0.2.39

Description : 
Malgré une désinstallation/ réinstallation de l'addon, je ne peux plus avoir  les chaînes de France télévision  (France 2, 3, 4 et 5) qui fonctionnent 10 secondes puis l'image se bloque et le son buzze en continue.
Pour TF1,  impossible de lancer la chaine (il ne se passe rien et on revient au menu des chaines), soit j'ai un message d'erreur en français d'un fichier manquant.
Je précise que le replay de ces chaînes marche parfaitement, par contre.
Qu'est-ce que je dois faire ?
Merci d'avance,

**Comment by dszczyt** [comment]
Pas de pb pour moi avec tf1, ça devait être un problème côté provider.
Pour les chaînes FranceTV, j'ai soumis un patch ici #1374

**Comment by enigma131** [comment]
J'ai erreur 403 aussi pour TF1 . LCI,TMC, TFX fonctionnent.
2024-06-16 18:47:07.612 T:2437623   error <general>: CCurlFile::Open - <https://live-tf1-das-secure.cdn-0.diff.tf1.fr/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaXAiOiIxMDkuMjkuMTYxLjI5IiwiY21jZCI6IiIsImV4cCI6MTcxODU3MDgyNywiZ2lkIjoiYThmNWY1MGRkYzI1NDQ1ZTkyZmE0ZjU3MTJhN2NlZTIiLCJpYXQiOjE3MTg1NTY0MjcsImlzcyI6ImRlbGl2ZXJ5IiwibWF4YiI6MCwic3RlbSI6Ii9vdXQvdjEvYzI5MzEzYWYyYzI2NGUwMTk2MWY1MDY5MTg5MGIwZWIiLCJzdWIiOiJhOGY1ZjUwZGRjMjU0NDVlOTJmYTRmNTcxMmE3Y2VlMiJ9.xrkXlWDHW1F9b0b8LAb-c6KSmVedeReJuKpIOy56BnU/out/v1/c29313af2c264e01961f50691890b0eb/index.mpd> Failed with code 403:
                                                   
2024-06-16 18:47:07.612 T:2437623   error <general>: AddOnLog: inputstream.adaptive: CURLOpen returned an error, download failed: https://live-tf1-das-secure.cdn-0.diff.tf1.fr/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaXAiOiIxMDkuMjkuMTYxLjI5IiwiY21jZCI6IiIsImV4cCI6MTcxODU3MDgyNywiZ2lkIjoiYThmNWY1MGRkYzI1NDQ1ZTkyZmE0ZjU3MTJhN2NlZTIiLCJpYXQiOjE3MTg1NTY0MjcsImlzcyI6ImRlbGl2ZXJ5IiwibWF4YiI6MCwic3RlbSI6Ii9vdXQvdjEvYzI5MzEzYWYyYzI2NGUwMTk2MWY1MDY5MTg5MGIwZWIiLCJzdWIiOiJhOGY1ZjUwZGRjMjU0NDVlOTJmYTRmNTcxMmE3Y2VlMiJ9.xrkXlWDHW1F9b0b8LAb-c6KSmVedeReJuKpIOy56BnU/out/v1/c29313af2c264e01961f50691890b0eb/index.mpd
2024-06-16 18:47:07.612 T:2437623   error <general>: AddOnLog: inputstream.adaptive: Could not open / parse manifest (https://live-tf1-das-secure.cdn-0.diff.tf1.fr/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaXAiOiIxMDkuMjkuMTYxLjI5IiwiY21jZCI6IiIsImV4cCI6MTcxODU3MDgyNywiZ2lkIjoiYThmNWY1MGRkYzI1NDQ1ZTkyZmE0ZjU3MTJhN2NlZTIiLCJpYXQiOjE3MTg1NTY0MjcsImlzcyI6ImRlbGl2ZXJ5IiwibWF4YiI6MCwic3RlbSI6Ii9vdXQvdjEvYzI5MzEzYWYyYzI2NGUwMTk2MWY1MDY5MTg5MGIwZWIiLCJzdWIiOiJhOGY1ZjUwZGRjMjU0NDVlOTJmYTRmNTcxMmE3Y2VlMiJ9.xrkXlWDHW1F9b0b8LAb-c6KSmVedeReJuKpIOy56BnU/out/v1/c29313af2c264e01961f50691890b0eb/index.mpd)
2024-06-16 18:47:07.612 T:2437623   error <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/tf1plus/get_live_url/?_pickle_=80049558000000000000007d94288c075f7469746c655f948c1454463120e28094205365707420c3a02068756974948c08786d6c74765f6964948c14433139322e6170692e74656c6572616d612e6672948c076974656d5f6964948c0374663194752e]

**Comment by yyogui** [comment]
Same issue here: 

- Raspi 3
- Libreelec 12.0
- CupTV&M: 02.40~Beta10 
- inputstream.adaptive: 21.4.10

When I try to download the index.mpd file directly from cmdline it's work fine: 

`curl -v  https://live-tf1-das-secure.cdn-3.diff.tf1.fr/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaXAiOiI4My4yMDUuMTk5LjQiLCJjbWNkIjoiIiwiZXhwIjoxNzE5OTUxODI1LCJnaWQiOiIzMzgwMmJlNTM5NmU0NjAwYmNhM2U3
ODQzNWJiYjIxYyIsImlhdCI6MTcxOTkzNzQyNSwiaXNzIjoiZGVsaXZlcnkiLCJtYXhiIjowLCJzdGVtIjoiL291dC92MS9jMjkzMTNhZjJjMjY0ZTAxOTYxZjUwNjkxODkwYjBlYiIsInN1YiI6IjMzODAyYmU1Mzk2ZTQ2MDBiY2EzZTc4NDM1YmJiMjFjIn0.0b8vWXACASahcp
m1Rxo4_AuFlbPnwaWk6fMQHwnBtIc/out/v1/c29313af2c264e01961f50691890b0eb/index.mpd -o index.mpd
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host live-tf1-das-secure.cdn-3.diff.tf1.fr:443 was resolved.

* Connected to live-tf1-das-secure.cdn-3.diff.tf1.fr (92.122.166.117) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
(...)
> GET /eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaXAiOiI4My4yMDUuMTk5LjQiLCJjbWNkIjoiIiwiZXhwIjoxNzE5OTUxODI1LCJnaWQiOiIzMzgwMmJlNTM5NmU0NjAwYmNhM2U3ODQzNWJiYjIxYyIsImlhdCI6MTcxOTkzNzQyNSwiaXNzIjoiZGVsaXZlcnkiLCJtYXhiIjowLCJzdGVtIjoiL291dC92MS9jMjkzMTNhZjJjMjY0ZTAxOTYxZjUwNjkxODkwYjBlYiIsInN1YiI6IjMzODAyYmU1Mzk2ZTQ2MDBiY2EzZTc4NDM1YmJiMjFjIn0.0b8vWXACASahcpm1Rxo4_AuFlbPnwaWk6fMQHwnBtIc/out/v1/c29313af2c264e01961f50691890b0eb/index.mpd HTTP/1.1
> Host: live-tf1-das-secure.cdn-3.diff.tf1.fr
> User-Agent: curl/8.6.0
> Accept: */*
> 
(...)
< HTTP/1.1 200 OK
< Server: nginx/1.22.1
< X-MediaPackage-Manifest-Last-Sequence: 9037441
< X-MediaPackage-Manifest-Last-Updated: 1719943028557
< X-MediaPackage-Request-Id: Root=1-66843f75-024401ee7a5e0161503f2475
< X-Amz-Cf-Pop: CDG50-P2
< X-Amz-Cf-Id: 0Jn0qNsHVWt_N6kAUX9h2z-8Mu9uThy-3ewab0Sk2B_5ACIUoik5SQ==
< Expires: Tue, 02 Jul 2024 17:57:09 GMT
< Pragma: no-cache
< Date: Tue, 02 Jul 2024 17:57:09 GMT
< Content-Length: 15842
< Connection: keep-alive
< Akamai-Mon-Iucid-Del: 1439211
< Content-Type: application/dash+xml
< Cache-Control: no-cache
< Access-Control-Max-Age: 86400
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: Server,range,hdntl,hdnts,Akamai-Mon-Iucid-Ing,Akamai-Mon-Iucid-Del,Akamai-Request-BC
< Access-Control-Allow-Headers: authorization,origin,range,hdntl,hdnts,CMCD-Request,CMCD-Object,CMCD-Status,CMCD-Session
< Access-Control-Allow-Methods: GET,OPTIONS
< Access-Control-Allow-Origin: *
< 
{ [15842 bytes data]
100 15842  100 15842    0     0   137k      0 --:--:-- --:--:-- --:--:--  139k
* Connection #0 to host live-tf1-das-secure.cdn-3.diff.tf1.fr left intact

LibreELEC:~ # head index.mpd 
<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" id="201" type="dynamic" publishTime="2024-07-02T17:57:09+00:00" minimumUpdatePeriod="PT4S" availabilityStartTime="2023-02-17T13:29:59.312000+00:00" minBufferTime="PT10S" suggestedPresentationDelay="PT10.000S" timeShiftBufferDepth="PT27.500S" profiles="urn:mpeg:dash:profile:isoff-live:2011">`

May be issue needs to be open on inputstream.adaptive repo ? 

**### Kodi Error log:** 

`2024-07-02 18:23:46.209 T:7600    debug <general>: ADDON: Dll Initializing - InputStream Adaptive
2024-07-02 18:23:46.210 T:7600    debug <general>: SECTION:LoadDLL(/storage/.kodi/addons/inputstream.adaptive/inputstream.adaptive.so.21.4.10)
2024-07-02 18:23:46.210 T:7600    debug <general>: Loading: /storage/.kodi/addons/inputstream.adaptive/inputstream.adaptive.so.21.4.10
2024-07-02 18:23:46.210 T:7600    debug <general>: AddOnLog: inputstream.adaptive: Open()
2024-07-02 18:23:46.210 T:7600    debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.license_key" value: [redacted]
2024-07-02 18:23:46.210 T:7600    debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.license_type" value: com.widevine.alpha
2024-07-02 18:23:46.210 T:7600    debug <general>: AddOnLog: inputstream.adaptive: Property found 

"inputstream.adaptive.manifest_headers" value: Content-Type=&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+WOW64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F125.0.0.0+Safari%2F537.36+Vivaldi%2F6.7.3329.35&Authorization=Bearer+eyJhbGciOiJIUzI1NiIsImtpZCI6InNoYTI1NmVURjFfMSIsInR5cCI6IkpXVCJ9.eyJhaWQiOiJ0ZjEiLCJleHAiOjE3MTk5Mzc1NDUsImlhdCI6MTcxOTkzNzQyNSwiaXNzIjoiZXRmMS1kZWxpdmVyeSIsImp0aSI6ImQxYmRkMjFmLThlMjctNGM5MC1iY2ZkLTUwZjIyZTgxMGNmZiIsInN1YiI6ImdpZ3lhLTMzODAyYmU1Mzk2ZTQ2MDBiY2EzZTc4NDM1YmJiMjFjIn0.1cd3NrEtC9ZleCsI-2LjuGwYrp3DM7BKbdO6QyLzBig

2024-07-02 18:23:46.211 T:7600    debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.stream_headers" value: Content-Type=&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+WOW64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F125.0.0.0+Safari%2F537.36+Vivaldi%2F6.7.3329.35&Authorization=Bearer+eyJhbGciOiJIUzI1NiIsImtpZCI6InNoYTI1NmVURjFfMSIsInR5cCI6IkpXVCJ9.eyJhaWQiOiJ0ZjEiLCJleHAiOjE3MTk5Mzc1NDUsImlhdCI6MTcxOTkzNzQyNSwiaXNzIjoiZXRmMS1kZWxpdmVyeSIsImp0aSI6ImQxYmRkMjFmLThlMjctNGM5MC1iY2ZkLTUwZjIyZTgxMGNmZiIsInN1YiI6ImdpZ3lhLTMzODAyYmU1Mzk2ZTQ2MDBiY2EzZTc4NDM1YmJiMjFjIn0.1cd3NrEtC9ZleCsI-2LjuGwYrp3DM7BKbdO6QyLzBig

2024-07-02 18:23:46.211 T:7600    debug <general>: AddOnLog: inputstream.adaptive: Property found "inputstream.adaptive.stream_selection_type" value: ask-quality
2024-07-02 18:23:46.211 T:7600    debug <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Type: Ask quality
2024-07-02 18:23:46.215 T:7600     info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
2024-07-02 18:23:46.215 T:7600    debug <general>: AddOnLog: inputstream.adaptive: Supported URN: urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED

2024-07-02 18:23:46.215 T:7600    debug <general>: CurlFile::Open - <https://live-tf1-das-secure.cdn-3.diff.tf1.fr/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaXAiOiI4My4yMDUuMTk5LjQiLCJjbWNkIjoiIiwiZXhwIjoxNzE5OTUxODI1LCJnaWQiOiIzMzgwMmJlNTM5NmU0NjAwYmNhM2U3ODQzNWJiYjIxYyIsImlhdCI6MTcxOTkzNzQyNSwiaXNzIjoiZGVsaXZlcnkiLCJtYXhiIjowLCJzdGVtIjoiL291dC92MS9jMjkzMTNhZjJjMjY0ZTAxOTYxZjUwNjkxODkwYjBlYiIsInN1YiI6IjMzODAyYmU1Mzk2ZTQ2MDBiY2EzZTc4NDM1YmJiMjFjIn0.0b8vWXACASahcpm1Rxo4_AuFlbPnwaWk6fMQHwnBtIc/out/v1/c29313af2c264e01961f50691890b0eb/index.mpd>

2024-07-02 18:23:46.216 T:7600    debug <general>: easy_acquire - Created session to https://live-tf1-das-secure.cdn-3.diff.tf1.fr
2024-07-02 18:23:46.218 T:7601    debug <general>: Loading settings for pvr://channels/tv/Toutes%20les%20cha%c3%aenes@-1/1@pvr.iptvsimple_2121968547.pvr

2024-07-02 18:23:46.330 T:7600    error <general>: AddOnLog: inputstream.adaptive: Download failed, HTTP error 400: https://live-tf1-das-secure.cdn-3.diff.tf1.fr/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaXAiOiI4My4yMDUuMTk5LjQiLCJjbWNkIjoiIiwiZXhwIjoxNzE5OTUxODI1LCJnaWQiOiIzMzgwMmJlNTM5NmU0NjAwYmNhM2U3ODQzNWJiYjIxYyIsImlhdCI6MTcxOTkzNzQyNSwiaXNzIjoiZGVsaXZlcnkiLCJtYXhiIjowLCJzdGVtIjoiL291dC92MS9jMjkzMTNhZjJjMjY0ZTAxOTYxZjUwNjkxODkwYjBlYiIsInN1YiI6IjMzODAyYmU1Mzk2ZTQ2MDBiY2EzZTc4NDM1YmJiMjFjIn0.0b8vWXACASahcpm1Rxo4_AuFlbPnwaWk6fMQHwnBtIc/out/v1/c29313af2c264e01961f50691890b0eb/index.mpd`

**Comment by caywin25** [comment]
Hello
Je confirme aussi avoir l'erreur 400 sur tf1 mais ça semble aléatoire (sur libreelec)
Hier soir je l'avais (pendant l'euro...) et ce matin je ne l'avais pas.

**Comment by bibitocarlos** [comment]
Sous archlinux, impossible de regarder tf1, aussi bien le replay que le live.

**Comment by caywin25** [comment]
@bibitocarlos tu as quoi dans tes logs comme erreur ? 
c'est l'erreur 400 aussi ?

**Comment by bibitocarlos** [comment]
Pour le live : 
`2024-07-26 08:32:47.135 T:1608452    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/mytf1/get_live_url/?item_id=tf1
2024-07-26 08:32:47.259 T:1608768   error <general>: [Catch-up-TV-&-More.support] 'unable to import route module: resources.lib.channels.fr.mytf1'
                                                   Traceback (most recent call last):
                                                     File "/home/bibi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 248, in get_route
                                                       importlib.import_module(module_path)
                                                     File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
                                                       return _bootstrap._gcd_import(name[level:], package, level)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
                                                   ModuleNotFoundError: No module named 'resources.lib.channels.fr.mytf1'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/bibi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 300, in run_callback
                                                       route = self.get_route(self.selector)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/bibi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 250, in get_route
                                                       raise RouteMissing("unable to import route module: %s" % module_path)
                                                   codequick.support.RouteMissing: 'unable to import route module:resources.lib.channels.fr.mytf1'
`

**Comment by bibitocarlos** [comment]
J'ai trouvé mon problème, en fait tous les raccourcis TF1 dans Kodi ne marchent plus (favoris, PVR), si je vais directement dans Catchup, cela marche, il faut donc que je les recréent.
Merci à tous.

**Comment by joaopa00** [comment]
ON va partir du principe que le problème est reglé pour tout le monde avec la dernière beta(0.39.13) et Kodi Omega

Si le problème persiste, n'hésitez pas à réouvri ce fil.
