### ISSUE TITLE
SFR TV erreur 406

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1385]
### Your environment
 - [x ] Linux
 - [x ] Windows
 - [ ] Other no tested

 - Operating system version/name:
 - Kodi version: 20.2 Linux, 21 windows
 - Catch-up TV & More version: latest beta

Http via navigateur OK

### Debug log
2024-07-02 08:02:33.432 T:2736    error <general>: [Catch-up-TV-&-More.support] 406 Client Error: Not Acceptable for url: https://www.sfr.fr/cas/login?domain=mire-sfr&service=https%3A%2F%2Fwww.sfr.fr%2Fcas%2Foidc%2FcallbackAuthorize
                                                   Traceback (most recent call last):
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/providers/sfrtv.py", line 953, in get_live_stream
                                                       token = get_token(plugin)
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/providers/sfrtv.py", line 154, in get_token
                                                       session.post(
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 471, in post
                                                       return super(Session, self).post(url, data, json, **kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 637, in post
                                                       return self.request("POST", url, data=data, json=json, **kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 441, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 414, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/home/toto/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 406 Client Error: Not Acceptable for url: https://www.sfr.fr/cas/login?domain=mire-sfr&service=https%3A%2F%2Fwww.sfr.fr%2Fcas%2Foidc%2FcallbackAuthorize
2024-07-02 08:02:33.433 T:2736    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 297, in error_handler
                                                       code = exception.code
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--

**Comment by enigma131** [comment]
Des nouvelles ?

**Comment by geoffde** [comment]
J'ai le même problème mais visiblement pas de solutions pour le moment...

**Comment by enigma131** [comment]
Il n'y a peut être personne de dispo pour coder ... et puis c'est les vacances. La solution doit exister puisque cela fonctionne via le navigateur internet.

**Comment by enigma131** [comment]
Personne pour corriger l'erreur 406 ?

**Comment by sebmourlhou** [comment]
Hello,

Ils ont ajouté une sécurité au niveau du formulaire de connexion, à priori un token CSRF.

Autrement dit, c'est mal barré pour que ça refonctionne un jour avec le plugin, malheureusement...

**Comment by enigma131** [comment]
Merci pour la réponse. Pourtant cela fonctionne via le navigateur internet...

**Comment by sebmourlhou** [comment]
Oui bien-sûr, c'est justement ça le problème, ils veulent t'obliger à passer par leur site internet

**Comment by enigma131** [comment]
Il n'y as pas moyen de coder ce qui est utilisé par le navigateur ?

**Comment by GregAce** [comment]
Bonjour,
je suis aussi intéressé par la correction du problème :)

**Comment by enigma131** [comment]
Boujour, quelqu'un pour coder le correctif ?
J'ai un compte, je peux contribuer pour les tests...

**Comment by enigma131** [comment]
Toujours pas de solution ici ?

**Comment by calvin4242** [comment]
Bonjour, même soucis. Es ce que quelqu'un aurait des connaissances à ce sujet a partager pour nous aiguiller afin de  développer un correctif ?

**Comment by enigma131** [comment]
Je suis intéressé aussi pour une solution. Je peux bien sûr participer aux tests.

**Comment by enigma131** [comment]
Presque 2 ans que cette issue est ouverte. C'est mort, plus de solution ? Si oui je ferme.

**Comment by enigma131** [comment]
Merci pour ce retour, j'ai bien sûr un compte avec lequel j'arrive à regarder via le navigateur, et ce même compte est toujours renseigné dans Catchup tv and more. Cela fonctionnait il y a plus d'un an. Je suis sous Kodi 21.2, cela veut - til dire qu'il faut kodi 22 pour ces chaînes (je doute) ?

**Comment by enigma131** [comment]
Merci pour ces infos en +. J'ai installé kodi 22 sur windows. Tout fonctionne sauf SFR. errreur 406 comme avec Kodi 21. Tu as quel DNS ? J'utilise cloudflare. Une autre piste?

**Comment by enigma131** [comment]
Je remets l'erreur : 
2025-07-11 08:40:04.692 T:1317891   error <general>: [Catch-up-TV-&-More.support] 406 Client Error: Not Acceptable for url: https://www.sfr.fr/cas/login?domain=mire-sfr&service=https%3A%2F%2Fwww.sfr.fr%2Fcas%2Foidc%2FcallbackAuthorize
                                                   Traceback (most recent call last):
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                       session_data = self._process_results(results)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                       listitems = validate_listitems(results)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                       raw_listitems = list(raw_listitems)
                                                                       ^^^^^^^^^^^^^^^^^^^
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/providers/sfrtv.py", line 900, in list_lives
                                                       token = get_token(plugin)
                                                               ^^^^^^^^^^^^^^^^^
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/providers/sfrtv.py", line 154, in get_token
                                                       session.post(
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 471, in post
                                                       return super(Session, self).post(url, data, json, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/toto/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 637, in post
                                                       return self.request("POST", url, data=data, json=json, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 441, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/urlquick.py", line 414, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/home/toto/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 406 Client Error: Not Acceptable for url: https://www.sfr.fr/cas/login?domain=mire-sfr&service=https%3A%2F%2Fwww.sfr.fr%2Fcas%2Foidc%2FcallbackAuthorize
2025-07-11 08:40:04.695 T:1317891   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 297, in error_handler
                                                       code = exception.code
                                                              ^^^^^^^^^^^^^^
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--
                                                   
2025-07-11 08:40:04.830 T:1317896   error <general>: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/providers/sfrtv/list_lives/?_pickle_=8004951d000000000000007d948c075f7469746c655f948c0c545620656e2064697265637494732e
2025-07-11 08:40:04.843 T:1317848   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/resources/lib/providers/sfrtv/list_lives/?_pickle_=8004951d000000000000007d948c075f7469746c655f948c0c545620656e2064697265637494732e) failed

**Comment by Moulbi** [comment]
Diagnostic complet de l'erreur 406 sur le login CAS SFR TV
Ce diagnostic a été réalisé avec l'aide de Claude Code (l'outil en ligne de commande d'Anthropic) comme assistant technique, en menant des tests en direct contre les serveurs SFR : d'abord depuis une IP de datacenter, puis depuis une vraie ligne résidentielle SFR pour écarter tout biais lié à l'origine de la requête. Je partage le résultat ici pour éviter à d'autres de repartir de zéro, et pour donner aux mainteneurs des pistes concrètes si quelqu'un veut reprendre le sujet.
1. La cause du 406 est confirmée : anti-bot et captcha, pas un problème de headers
Le POST vers https://www.sfr.fr/cas/login?domain=mire-sfr&service=... est bloqué par SFR eux-mêmes, pas par un souci côté addon :
La page de login CAS intègre désormais un widget MTCaptcha (<div class="mtcaptcha"></div> présent dans le HTML du formulaire loginForm).
Les cookies posés sur cette page (TS01aa9b1d, TS01e4daa0, TS42abe983027, OClmoOot, etc.) correspondent à la convention de nommage de F5 BIG-IP Advanced WAF / Application Security Manager, une protection anti credential-stuffing/brute-force qui cible spécifiquement les formulaires de login.
Preuve que c'est ciblé sur le login, et pas un blocage général du domaine : un POST vers https://www.sfr.fr/ (page d'accueil) avec la même session passe en 200 OK, alors que seul le POST vers /cas/login renvoie 406.
Testé avec un jeu complet de headers navigateur modernes (Sec-Fetch-*, Sec-CH-UA*, Upgrade-Insecure-Requests, User-Agent Chrome à jour) : aucun effet, toujours 406. Ce n'est donc pas un problème de fingerprint HTTP superficiel.
Testé identique depuis une IP de datacenter et depuis une ligne résidentielle SFR (donc a priori de confiance) : même résultat.
Conclusion : c'est une protection anti-automatisation volontaire côté SFR sur ce endpoint précis, cohérente avec le fait que ce CAS protège l'accès à tout le compte client SFR (facturation, ligne mobile...), pas seulement la TV. TF1+/6play, eux, utilisent Gigya, une API dédiée à l'identité "média", sans cette protection.
2. Piste explorée : réutilisation de session (cookie SSO)
Le protocole CAS étant du SSO, l'hypothèse était qu'une session déjà authentifiée dans un vrai navigateur (donc le captcha déjà résolu par un humain) puisse être réutilisée pour obtenir un nouveau token sans repasser par le POST bloqué.
Résultat partiel, intéressant mais pas suffisant :
En injectant les cookies de session (CASTGC, JSESSIONID, etc.) d'un navigateur réellement connecté, le formulaire de login n'est plus jamais affiché et le 406/captcha est bien évité. La session est reconnue par CAS.
Mais l'étape suivante, la récupération du token OIDC final, échoue systématiquement avec une erreur serveur générique CAS ("An error has occurred. Please consult with your administrator."), que ce soit via l'appel explicite token=true&gateway=true ou en lisant le fragment #access_token=... d'une redirection OIDC implicit flow classique.
L'URL de redirection de l'appel authorize simple pointe encore vers /cas/login?...&oidcsqs=... sans afficher de formulaire. C'est cohérent avec une page-relais qui termine l'authentification via JavaScript côté client (redirection ou appel réseau déclenché par du JS), quelque chose qu'un client HTTP pur comme requests/urlquick ne peut pas exécuter.
Vérifié dans l'APK Android officiel RED TV : le module de login (com.altice.android.services.authent.ui.login) est entièrement natif (écrans Kotlin/Compose), sans aucune WebView. L'application officielle contourne donc entièrement ce problème en utilisant une API JSON dédiée, détaillée ci-dessous.
3. L'API mobile native (CasWebService)
En décompilant l'APK officiel RED TV (v4.4.0, com.sfr.android.redtv), on trouve une interface Retrofit com.altice.android.services.authent.ws.cas.CasWebService avec ces endpoints :
Code
C'est donc une vraie API JSON, distincte du portail web CAS, qui ne semble pas exiger la résolution du captcha MTCaptcha. Mais chaque appel à createToken/createTokenV4 exige, en plus du login et du mot de passe, trois headers : Authorization, secret et fingerprint, visibles dans les annotations @Header de l'interface Retrofit décompilée. Le nommage indique qu'il ne s'agit pas d'une simple clé publique de routage (comme un apiKey Gigya côté TF1+/6play), mais d'un mécanisme d'attestation d'application : une signature liée au binaire signé de l'app, destinée à prouver au serveur SFR que l'appel provient réellement de l'application officielle.
Reproduire cette signature nécessiterait d'extraire le secret embarqué dans l'APK et de reproduire l'algorithme de calcul du fingerprint. Ce n'est pas quelque chose qu'on a tenté d'aller plus loin dessus dans ce travail. Je le mentionne surtout pour que la communauté sache que cette porte existe et pourquoi elle reste fermée en l'état, plutôt que de repartir de zéro sur cette piste sans le savoir.
4. Bugs corrigés au passage (indépendants du problème principal)
En creusant, deux bugs réels et non liés au captcha ont été trouvés et corrigés :
log_uploader.py : crash AttributeError: module 'kodi_six.xbmc' has no attribute 'translatePath' sur Kodi 21 (Omega). xbmc.translatePath a été remplacé par xbmcvfs.translatePath (déjà utilisé ailleurs dans le même fichier), qui n'existe plus/pas sur cette version. Ce bug empêchait même d'afficher la popup de partage de log après une erreur.
sfrtv.py / extract_token_from_authorize_response : le payload du JWT retourné par SFR est encodé en base64url (RFC 7519, avec -/_), mais le code utilisait base64.b64decode standard, qui ignore silencieusement les caractères hors alphabet standard au lieu de lever une erreur. Ça décale la longueur et casse le calcul du padding (binascii.Error: Incorrect padding). Corrigé avec base64.urlsafe_b64decode. Ce bug était resté invisible jusqu'ici car l'exécution n'atteignait jamais ce point, bloquée plus tôt par le 406.
5. Code de référence
Tout ce travail (headers modernisés, option de cookie de session importé, correctifs JWT et log_uploader) est disponible sur cette branche pour qui veut creuser plus loin ou repartir de cette base : https://github.com/Moulbi/plugin.video.catchuptvandmore/tree/claude/sfr-stream-repair-g80v5q
En résumé, le blocage principal (406 sur le POST de login) est un choix de sécurité assumé par SFR (captcha et WAF F5), pas un bug corrigible côté client. La réutilisation de session SSO permet de l'éviter, mais bute ensuite sur une étape qui semble nécessiter l'exécution de JavaScript, chose qu'un addon Kodi ne peut pas faire sans embarquer un navigateur complet. Une solution jugée disproportionnée pour ce cas d'usage.

**Comment by geoffde** [comment]
Bonjour Moulbi,

Merci pour tout ce travail d’investigation.

Si je comprends bien, l’accès à SFR TV ne pourra jamais être rétabli. Dans ce cas, ne serait-il pas opportun de supprimer la partie « Fournisseur d’accès Internet » des menus du plug-in ?

Il y a peut-être aussi un sujet à creuser du côté de RMC BFM Play, qui a complètement changé d’adresse et dont les anciens comptes ne fonctionnent plus.

Encore merci pour le travail.
