### ISSUE TITLE
'>' not supported between instances of 'LooseVersion' and 'Version'

### ISSUE THREAD

**Issue by ludovic-79** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1409]
Bonjour,

Depuis la dernières mise à jour de mes 2 pc sous linuxmint et lubuntu, impossible de lire les chaine tv et replay.
J'utilise le flatpack de kodi.
Tous fonctionnais correctement avant les mise à jour des flatpack.

le log :
 error <general>: [Catch-up-TV-&-More.support] '>' not supported between instances of 'LooseVersion' and 'Version'
                                                   Traceback (most recent call last):
                                                     File "/home/ludo/.var/app/tv.kodi.Kodi/data/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/ludo/.var/app/tv.kodi.Kodi/data/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/ludo/.var/app/tv.kodi.Kodi/data/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/ludo/.var/app/tv.kodi.Kodi/data/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/francetv.py", line 414, in get_live_url
                                                       return resolver_proxy.get_francetv_live_stream(plugin, broadcast_id)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/ludo/.var/app/tv.kodi.Kodi/data/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py", line 577, in get_francetv_live_stream
                                                       return get_stream_with_quality(plugin, video_url, license_url=URL_LICENSE_FRANCETV)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/ludo/.var/app/tv.kodi.Kodi/data/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py", line 230, in get_stream_with_quality
                                                       if not is_helper.check_inputstream():
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/ludo/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 420, in check_inputstream
                                                       if self.drm == 'widevine' and not self._supports_widevine():
                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/ludo/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 163, in _supports_widevine
                                                       if parse_version(config.WIDEVINE_MINIMUM_KODI_VERSION[system_os()]) > parse_version(kodi_version()):
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: '>' not supported between instances of 'LooseVersion' and 'Version'
2024-09-25 11:25:01.963 T:85      debug <CAddonSettings[0@plugin.video.catchuptvandmore]>: trying to load setting definitions from old format...

[kodi.log](https://github.com/user-attachments/files/17129077/kodi.log)

**Comment by flatgreen** [comment]
I have the same error.
According to the log, this comes from "inputstreamhelper".
We can fix the problem by updating this file, see:
https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/570
Version 0.7 fixes the problem for me

**Comment by ludovic-79** [comment]
Thanks Flatgreen !
That fixes the problem for me too.
