### ISSUE TITLE
M6 Player not working

### ISSUE THREAD

**Issue by khalistoo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1420]
Since this morning M6/6Ter fails playing 

404 Client Error: Not Found for url: https://6play-users.6play.fr/v2/platforms/chromecast/services/6play/users/146470591c7d4195816faa417d8ad55c/videos/dashcenc_M6/upfront-token

Version 0.2.40-beta13

### Debug log
https://paste.kodi.tv/alehumawiw

**Comment by gerardop91** [comment]
Hi,

I have exactly the same bug, M6/W9/6Ter fail with the same message @khalistoo

**Comment by jeff2900** [comment]
Hello,
I do a fix for 6play and tv5monde. 
You can try it here:
https://www.mediafire.com/file/e26xrvknxzrfev0/plugin.video.catchuptvandmore-dev-0.2.40%257Ebeta13-fix-6play-v1.zip/file

If it's ok i will push a PR as soon.

**Comment by gerardop91** [comment]
@jeff2900 Good job, I install your fix and all are right now, Replay and Direct can be used.

Thanks for it

**Comment by caywin25** [comment]
Hello @jeff2900 

What is your change please?
Could you show us your PR?

Thanks

**Comment by emnbdx** [comment]
@jeff2900 Your fix work but only for 15 minutes.

Now I get http error 498

**Comment by quatreplusquatre** [comment]
Same problem as @khalistoo, error 404 when i start an replay program with 6play

**Comment by Masaju31** [comment]
Hello,
I have the same problem on a fire stick

**Comment by gerardop91** [comment]
For me it's right after fix, direct and replay ... i'm in France, any http error 498 after 15 minutes, the fix solve my problem. Tested now to be sure

**Comment by jeff2900** [comment]
I hope this new version fix HTTP Error 498:
https://www.mediafire.com/file/142svpkk9hxz5eh/plugin.video.catchuptvandmore-dev-0.2.40%257Ebeta13-fix-6play-v2.zip/file

**Comment by khalistoo** [comment]
Thanks @jeff2900 

I am testing the fix right now on Linux and it seems to hold fine.

 (oui j ai fait le ticket en anglais par habitude, désolé je peux continuer en Français :) ) .

**Comment by Masaju31** [comment]
@jeff2900 is it possible to install it on the fire stick?

**Comment by MacCord** [comment]
Can I have a little tutorial to install the fix. Before my wife kill me. Help, please

**Comment by khalistoo** [comment]
@MacCord  download the zip file from @jeff2900 link in the same machine you have your kodi installed then follow exactly these steps:

How to install from a ZIP file
https://kodi.wiki/view/Add-on_manager#How_to_install_from_a_ZIP_file

**Comment by Realys-31** [comment]
Hey ! Thanks @jeff2900 !

I also tested version V2. There are no more 404 or 498 errors, it works but without an image ...  ?!?
Whatever the channels of the M6 group (w9, 6ter, M6...) I have sound, no latency, but no image.

I'll have a look at the logs.
Thanks for everything.

----

J'ai aussi testé la version V2. Il n'y a plus d'erreur 404, ni 498, cela fonctionne mais sans image ...  ?!?
Qu'elles que soient les chaines du group M6 (w9, 6ter, M6...) j'ai le son, pas de latence, mais aucune image.

Je vais regarder les logs.
Merci pour tout.

**Comment by khalistoo** [comment]
@Realys-31  c'est quoi ta config ? 
J'ai teste sur Linux et sur Android (MiBox) et tout est OK.

**Comment by Realys-31** [comment]
LibreElec (Official) - 12.0.0 - Generic-legacy.x86_64
Lenovo G505 - AMD E1 - 8G SSD 120G

**Comment by Elegans59** [comment]
Bonjour, pour moi ça refonctionne...merci pour votre rapidité,vous faites des heureuses lol

**Comment by MacCord** [comment]
Bon, Kodi trouve pas le fichier zip, que je le laisse sur clé USB ou que je le colle dans la section download de ma Nokia streaming box... Les sources inconnues sont bien activées. Je pige pas où j'ai raté un truc

**Comment by Realys-31** [comment]
La machine:
LibreElec (Official) - 12.0.0 - Generic-legacy.x86_64
Lenovo G505 - AMD E1 - 8G SSD 120G
Les Add-ons:
Catchup-tv - PlutoTV - Arté +7 - Samsung TV Plus

J'utilise IPTV Merge, IPTV Manager pour afficher tout cela dans la section TV de kodi

Ce bug ne se produit que pour les channels 6play (M6 - W9 - 6ter). 

Voici ce que je peux trouver dans kodi.log :

...
2024-11-05 14:01:04.754 T:259826 warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2024-11-05 14:01:04.821 T:259826 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-11-05 14:01:04.957 T:1335     info <general>: VideoPlayer::OpenFile: plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/6play/get_live_url/?_pickle_=8004956f000000000000007d94288c075f7469746c655f948c293674657220e28094204c6120706574697465206d6169736f6e2064616e73206c612070726169726965948c08786d6c74765f6964948c1543313430332e6170692e74656c6572616d612e6672948c076974656d5f6964948c043674657294752e
2024-11-05 14:01:04.971 T:259828    info <general>: Creating InputStream
2024-11-05 14:01:04.983 T:259828    info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0
2024-11-05 14:01:05.426 T:259828 warning <general>: AddOnLog: inputstream.adaptive: ParseManifest: The <UTCTiming> tag element is not supported so playback problems may occur.
2024-11-05 14:01:05.427 T:259828    info <general>: AddOnLog: inputstream.adaptive: Manifest successfully parsed (Periods: 1, Streams in first period: 5, Type: live)
2024-11-05 14:01:06.020 T:259828   error <general>: AddOnLog: inputstream.adaptive: License server returned failure (HTTP error 406)
2024-11-05 14:01:07.447 T:259828    info <general>: Skipped 4 duplicate messages..
2024-11-05 14:01:07.447 T:259828    info <general>: Creating Demuxer
2024-11-05 14:01:07.448 T:259828    info <general>: Opening stream: 1001 source: 256
2024-11-05 14:01:07.641 T:259830 warning <general>: AddOnLog: inputstream.adaptive: ParseManifest: The <UTCTiming> tag element is not supported so playback problems may occur.
2024-11-05 14:01:07.821 T:259828    info <general>: Creating video codec with codec id: 27
2024-11-05 14:01:07.821 T:259828    info <general>: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2024-11-05 14:01:07.824 T:259828    info <general>: Creating video thread
2024-11-05 14:01:07.824 T:259833    info <general>: running thread: video_thread
2024-11-05 14:01:07.825 T:259828    info <general>: Opening stream: 1002 source: 256
2024-11-05 14:01:08.104 T:259828    info <general>: Finding audio codec for: 86018
2024-11-05 14:01:08.107 T:259828    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2024-11-05 14:01:08.107 T:259828    info <general>: OpenStream: Allowing max Out-Of-Sync Value of 10 ms
2024-11-05 14:01:08.107 T:259828    info <general>: Creating audio thread
2024-11-05 14:01:08.108 T:259835    info <general>: running thread: CVideoPlayerAudio::Process()
2024-11-05 14:01:08.108 T:259828    info <general>: Opening stream: 1005 source: 256
2024-11-05 14:01:08.438 T:259828    info <general>: CDVDSubtitlesLibass: Using libass version 1701000
2024-11-05 14:01:08.438 T:259828    info <general>: CDVDSubtitlesLibass: Creating ASS library structure
2024-11-05 14:01:08.438 T:259828    info <general>: CDVDSubtitlesLibass: Initializing ASS Renderer
2024-11-05 14:01:08.440 T:259828    info <general>: CDVDSubtitlesLibass: Initializing ASS library font settings
2024-11-05 14:01:08.514 T:259828    info <general>: CDVDSubtitlesLibass: Creating new ASS track
2024-11-05 14:01:08.591 T:259828   error <general>: AddOnLog: inputstream.adaptive: Decrypt Sample returns failure!
2024-11-05 14:01:08.910 T:259835    info <general>: Skipped 50 duplicate messages..
2024-11-05 14:01:08.910 T:259835    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2024-11-05 14:01:08.910 T:259835    info <general>: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
2024-11-05 14:01:08.915 T:1354     info <general>: CActiveAESink::OpenSink - initialize sink
2024-11-05 14:01:09.124 T:1354     info <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=HDMI,DEV=0"
2024-11-05 14:01:09.139 T:1354     info <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=HDMI,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x02"
2024-11-05 14:01:09.139 T:1354     info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2024-11-05 14:01:09.139 T:1354     info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S32NE
2024-11-05 14:01:09.942 T:259830 warning <general>: AddOnLog: inputstream.adaptive: ParseManifest: The <UTCTiming> tag element is not supported so playback problems may occur.
2024-11-05 14:01:21.012 T:259830    info <general>: Skipped 4 duplicate messages..
2024-11-05 14:01:21.012 T:259830 warning <general>: AddOnLog: inputstream.adaptive: ParseManifest: The <UTCTiming> tag element is not supported so playback problems may occur.
2024-11-05 14:01:23.727 T:1368     info <general>: Skipped 1 duplicate messages..
2024-11-05 14:01:23.727 T:1368     info <general>: plugin.audio.spotify:main_service:run: Main loop continuing. Loop counter: 1060.
2024-11-05 14:01:25.673 T:259830 warning <general>: AddOnLog: inputstream.adaptive: ParseManifest: The <UTCTiming> tag element is not supported so playback problems may occur.
2024-11-05 14:01:36.739 T:259830    info <general>: Skipped 4 duplicate messages..
...

Merciii pour votre soutient.

**Comment by khalistoo** [comment]
@MacCord  mais tu arrives a voir le dossier Downloads ou la clef usb depuis kodi ou pas du tout ?

**Comment by Elegans59** [comment]
> Bon, Kodi trouve pas le fichier zip, que je le laisse sur clé USB ou que je le colle dans la section download de ma Nokia streaming box... Les sources inconnues sont bien activées. Je pige pas où j'ai raté un truc

Bjr, as tu été dans les paramètres de ta box application kodi et autorisation fichier et contenus multimédia sur tjr autoriser?

**Comment by MacCord** [comment]
> @MacCord mais tu arrives a voir le dossier Downloads ou la clef usb depuis kodi ou pas du tout ?

Je vois la clé, le dossier download mais pas le fichier quand j'ouvre le dossier ou la clé. Et je ne peux pas selectionner le dossier ou la clé entieremnet

**Comment by MacCord** [comment]
> > Bon, Kodi trouve pas le fichier zip, que je le laisse sur clé USB ou que je le colle dans la section download de ma Nokia streaming box... Les sources inconnues sont bien activées. Je pige pas où j'ai raté un truc
> 
> Bjr, as tu été dans les paramètres de ta box application kodi et autorisation fichier et contenus multimédia sur tjr autoriser?

YES ! Merci. Les parametres etaient sur autoriser et pas sur toujours autoriser.

J'ai accès au fichier zip maintenant
Et 6 play fonctionne de nouveau !

**Comment by Elegans59** [comment]
> La machine: LibreElec (Official) - 12.0.0 - Generic-legacy.x86_64 Lenovo G505 - AMD E1 - 8G SSD 120G Les Add-ons: Catchup-tv - PlutoTV - Arté +7 - Samsung TV Plus
> 
> J'utilise IPTV Merge, IPTV Manager pour afficher tout cela dans la section TV de kodi
> 
> Ce bug ne se produit que pour les channels 6play (M6 - W9 - 6ter).
> 
> Voici ce que je peux trouver dans kodi.log :
> 
> ... 2024-11-05 14:01:04.754 T:259826 warning : ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream(). 2024-11-05 14:01:04.821 T:259826 warning : Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo. 2024-11-05 14:01:04.957 T:1335 info : VideoPlayer::OpenFile: plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/6play/get_live_url/?_pickle_=8004956f000000000000007d94288c075f7469746c655f948c293674657220e28094204c6120706574697465206d6169736f6e2064616e73206c612070726169726965948c08786d6c74765f6964948c1543313430332e6170692e74656c6572616d612e6672948c076974656d5f6964948c043674657294752e 2024-11-05 14:01:04.971 T:259828 info : Creating InputStream 2024-11-05 14:01:04.983 T:259828 info : AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 0 2024-11-05 14:01:05.426 T:259828 warning : AddOnLog: inputstream.adaptive: ParseManifest: The tag element is not supported so playback problems may occur. 2024-11-05 14:01:05.427 T:259828 info : AddOnLog: inputstream.adaptive: Manifest successfully parsed (Periods: 1, Streams in first period: 5, Type: live) 2024-11-05 14:01:06.020 T:259828 error : AddOnLog: inputstream.adaptive: License server returned failure (HTTP error 406) 2024-11-05 14:01:07.447 T:259828 info : Skipped 4 duplicate messages.. 2024-11-05 14:01:07.447 T:259828 info : Creating Demuxer 2024-11-05 14:01:07.448 T:259828 info : Opening stream: 1001 source: 256 2024-11-05 14:01:07.641 T:259830 warning : AddOnLog: inputstream.adaptive: ParseManifest: The tag element is not supported so playback problems may occur. 2024-11-05 14:01:07.821 T:259828 info : Creating video codec with codec id: 27 2024-11-05 14:01:07.821 T:259828 info : CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 2024-11-05 14:01:07.824 T:259828 info : Creating video thread 2024-11-05 14:01:07.824 T:259833 info : running thread: video_thread 2024-11-05 14:01:07.825 T:259828 info : Opening stream: 1002 source: 256 2024-11-05 14:01:08.104 T:259828 info : Finding audio codec for: 86018 2024-11-05 14:01:08.107 T:259828 info : CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac 2024-11-05 14:01:08.107 T:259828 info : OpenStream: Allowing max Out-Of-Sync Value of 10 ms 2024-11-05 14:01:08.107 T:259828 info : Creating audio thread 2024-11-05 14:01:08.108 T:259835 info : running thread: CVideoPlayerAudio::Process() 2024-11-05 14:01:08.108 T:259828 info : Opening stream: 1005 source: 256 2024-11-05 14:01:08.438 T:259828 info : CDVDSubtitlesLibass: Using libass version 1701000 2024-11-05 14:01:08.438 T:259828 info : CDVDSubtitlesLibass: Creating ASS library structure 2024-11-05 14:01:08.438 T:259828 info : CDVDSubtitlesLibass: Initializing ASS Renderer 2024-11-05 14:01:08.440 T:259828 info : CDVDSubtitlesLibass: Initializing ASS library font settings 2024-11-05 14:01:08.514 T:259828 info : CDVDSubtitlesLibass: Creating new ASS track 2024-11-05 14:01:08.591 T:259828 error : AddOnLog: inputstream.adaptive: Decrypt Sample returns failure! 2024-11-05 14:01:08.910 T:259835 info : Skipped 50 duplicate messages.. 2024-11-05 14:01:08.910 T:259835 info : CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac 2024-11-05 14:01:08.910 T:259835 info : Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through) 2024-11-05 14:01:08.915 T:1354 info : CActiveAESink::OpenSink - initialize sink 2024-11-05 14:01:09.124 T:1354 info : CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=HDMI,DEV=0" 2024-11-05 14:01:09.139 T:1354 info : CAESinkALSA::Initialize - Opened device "hdmi:CARD=HDMI,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x02" 2024-11-05 14:01:09.139 T:1354 info : CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats 2024-11-05 14:01:09.139 T:1354 info : CAESinkALSA::InitializeHW - Using data format AE_FMT_S32NE 2024-11-05 14:01:09.942 T:259830 warning : AddOnLog: inputstream.adaptive: ParseManifest: The tag element is not supported so playback problems may occur. 2024-11-05 14:01:21.012 T:259830 info : Skipped 4 duplicate messages.. 2024-11-05 14:01:21.012 T:259830 warning : AddOnLog: inputstream.adaptive: ParseManifest: The tag element is not supported so playback problems may occur. 2024-11-05 14:01:23.727 T:1368 info : Skipped 1 duplicate messages.. 2024-11-05 14:01:23.727 T:1368 info : plugin.audio.spotify:main_service:run: Main loop continuing. Loop counter: 1060. 2024-11-05 14:01:25.673 T:259830 warning : AddOnLog: inputstream.adaptive: ParseManifest: The tag element is not supported so playback problems may occur. 2024-11-05 14:01:36.739 T:259830 info : Skipped 4 duplicate messages.. ...
> 
> Merciii pour votre soutient.

Bsr, avez vous reessayer de l'installer une deuxième fois?

**Comment by Realys-31** [comment]
@Elegans59 , oui j'ai reessayé. Et je m'apperçois d'un nouveau pb sur le groupe TF maintenant ...

2024-11-05 15:37:11.861 T:3938    error <general>: [Catch-up-TV-&-More.support] 'unable to import route module: resources.lib.channels.fr.mytf1'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 248, in get_route
                                                       importlib.import_module(module_path)
                                                     File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
                                                     File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
                                                   ModuleNotFoundError: No module named 'resources.lib.channels.fr.mytf1'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 300, in run_callback
                                                       route = self.get_route(self.selector)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 250, in get_route
                                                       raise RouteMissing("unable to import route module: %s" % module_path)
                                                   codequick.support.RouteMissing: 'unable to import route module: resources.lib.channels.fr.mytf1'
2024-11-05 15:37:16.471 T:3938    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'kodi_six.xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 345, in error_handler
                                                       log_uploader.ask_to_share_log()
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/log_uploader.py", line 122, in ask_to_share_log
                                                       imagefile = os.path.join(xbmc.translatePath(PROFILE), '%s.png' % str(data.split('/')[-1]))
                                                                                ^^^^^^^^^^^^^^^^^^
                                                   AttributeError: module 'kodi_six.xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--

**Comment by Realys-31** [comment]
Effectivement, dans le dossier lib/channels/fr il n'y a pas la ressource mytf1.py

je l'ai collé depuis l'ancienne versio, et la c'est bon, j'ai retpouvé les chaines MyTF1.

C'est quand même hyper chelou ce truc là ...

**Comment by gerardop91** [comment]
J'ai également installé la version 2 (car la version 1 a fini par ne pas fonctionner) et tout est OK maintenant tant le direct que le replay

**Comment by Realys-31** [comment]
Bo me revoilà avec le Pb original pour le groupe 6Play.

https://pastebin.com/EwnJTmZL

Merci de votre soutien !

**Comment by Realys-31** [comment]
Bon, je viens d'upgrader LibreELEC en version 12.0.1. J'ai lu que imputstream.adaptive a été upgradé dans cette version.
Mais nada... je reste en mode radio sur le groupe 6play. J'ai le son mais pas l'image et les erreur imputstream dans les logs.

S'il vous plait, ceux qui sont sous linux et pour qui 6play fontionne, vous utilisez quelle version de inputstream.adaptive , merci.

**Comment by caywin25** [comment]
@jeff2900 a fait une PR
Ça marche impecc merci beaucoup

**Comment by Realys-31** [comment]
Ca y est !
Donc pour ceux qui sont sous LibreELEC 12.0 - Generic-legacy.x86_64(Linux x86 64-bit) - Kodi 21.1-Omega   :
- Upgrade LibreELEC OS 12.0.1
- Upgrade de InputStream 21.5.5.1
- Upgrade de InputSream FFmpge Direct 21.3.5.2
Puis, à  l'aide de l'addons  InputStream Helper (Slyguy Wraper) : (Re)install Widevine CDM

Redémarrer Kodi.

Et voilà, le groupe 6Play refonctionne avec le son et l'image et le différé ... ouf !

**Comment by yapa69** [comment]
> Ca y est ! Donc pour ceux qui sont sous LibreELEC 12.0 - Generic-legacy.x86_64(Linux x86 64-bit) - Kodi 21.1-Omega :
> 
>     * Upgrade LibreELEC OS 12.0.1
> 
>     * Upgrade de InputStream 21.5.5.1
> 
>     * Upgrade de InputSream FFmpge Direct 21.3.5.2
>       Puis, à  l'aide de l'addons  InputStream Helper (Slyguy Wraper) : (Re)install Widevine CDM
> 
> 
> Redémarrer Kodi.
> 
> Et voilà, le groupe 6Play refonctionne avec le son et l'image et le différé ... ouf !

j'avais eu les meme galeres que toi suite à l'upgrade sous rpi4 mais là j'ai juste mis le patch v2..Avouez qu'on fait tous ça pour l'amour est dans le pré pour mesdames :).

**Comment by quatreplusquatre** [comment]
Et pour ceux qui sont avec

Rasp4
Libreelec 11.0.6 (pas d'autres mises a jour de proposées)

Catchup 0.2.40 beta13

Il va y avoir bientôt une mise a jour?

Merci

**Comment by yapa69** [comment]
> Et pour ceux qui sont avec
> 
> Rasp4 Libreelec 11.0.6 (pas d'autres mises a jour de proposées)
> 
> Catchup 0.2.40 beta13
> 
> Il va y avoir bientôt une mise a jour?
> 
> Merci

Normalement les plugin sont compatibles entre la version 11 et 12. J'ai l'impression que les PR sont validées tous les 15 jours environ. Tu peux suivre l'avancée de la PR ici https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1421
Il faut forcer la mise à jour de 11 vers 12, ca ne sera jamais fait automatiquement via leur systeme de mise à jour
"Manual update in LibreELEC settings will not list LibreELEC 12.0 releases on switched devices as there are no matching arm images (only aarch64). You can [manually update](https://wiki.libreelec.tv/support/update) by placing a LibreELEC 12 release file (.tar or .img.gz) in /storage/.update and rebooting."

**Comment by quatreplusquatre** [comment]
Super merci @yapa69 pour les infos et @jeff2900 pour le fix, ca refonctionne.

**Comment by joaopa00** [comment]
Ca devrait être fixé dans la dernière béta. Merci à Jeff pour le boulot.
