### ISSUE TITLE
FRANCE 3 REGIONS - ALL REGIONS KO - FRANCETV

### ISSUE THREAD

**Issue by timalmoon** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1424]
### Describe the bug
A clear and concise description of what the bug is:

No more access to France 3 Regions (FR3 Region)

Affect ALL REGIONS

error <general>: [Catch-up-TV-&-More.support] 'NoneType' object has no attribute 'get'

### To Reproduce
Steps to reproduce the behaviour:
1. Tests with last versions : 0.2.40-beta14 and 0.2.39-matrix
2. Launch France 3 Regions in CatchupTV app (France)
3. Launch any Region or Dep
4. view logs

### Expected behaviour
A clear and concise description of what you expected to happen:

Maybe an update of "plugin.video.catchuptvandmore/resources/lib/channels/fr/france3regions.py" ?

### Actual behaviour
Tell us what happens instead:

FRANCE 3 REGIONS KO - ALL REGIONS

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 21.1
 - Catch-up TV & More version: 0.2.40-beta14 and 0.2.39-matrix
 - Installation method: repository

### Additional context
Add any other context about the problem here:

Since some days ...

Tests with with a french IP

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

Logs : 

2024-11-08 11:44:38.624 T:9900    error <general>: [Catch-up-TV-&-More.support] 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
redirect = parent_ins(route, arg_params, self.callback_params)
File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
results = super(Resolver, self).__call__(route, args, kwargs)
File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
return route.function(self, *args, **kwargs)
File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/france3regions.py", line 187, in get_live_url
video_id = root.find('.//div[@class="magneto"]').get('data-id')
AttributeError: 'NoneType' object has no attribute 'get'

2024-11-08 11:44:47.928 T:506     error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/france3regions/get_live_url/?_pickle_=XXXXXXXXXXXXXXXXXXX]

pickel number change in this log

**Comment by joaopa00** [comment]
Je confirme qu'il y a un problème

**Comment by joaopa00** [comment]
Devrait être fixé dans GIT.
