### ISSUE TITLE
RTL Play : Can't view different seasons of a show

### ISSUE THREAD

**Issue by lb544** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1434]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:

### To Reproduce
Steps to reproduce the behaviour:
1. Go to Catchup  / Belgium / RTL Play / RTL TVI / Divertissement 
2. Choose a show like "La meilleure friterie" 
3. 
4.

### Expected behaviour
A clear and concise description of what you expected to happen:
Select Season 1 / 2 ... more like on rtlplay.be
https://www.rtlplay.be/rtlplay/la-meilleure-friterie~2b9a38ac-91d3-4015-a7df-4eea4a41dbc7

### Actual behaviour
Tell us what happens instead:
There's only episodes from S01 / 2023

### Screenshots
If applicable, add screenshots to help explain your problem:

![Screenshot_20241125_214514_Vivaldi](https://github.com/user-attachments/assets/a7d2d8d6-7b55-43ca-8a25-8ca31ad29ffc)

![Screenshot_20241125_214910_RVNC Viewer](https://github.com/user-attachments/assets/fc48c241-f1de-40c4-be74-0e309f302649)

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [X] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 21.1
 - Catch-up TV & More version: 0.2.40 beta 16
 - Installation method: Repo

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Je viens de voir que pour lister les programmes, il n'y a pas besin d'adresse IP belge. Je vais jeter un coup d'oeil t voir ce que je peux faire.

Si Darodi ouvait passer par ici.....

**Comment by darodi** [comment]
L'ancienne API ne montre en effet que les anciennes vidéos.
Le nouveau site utilise une autre technique de login sso.
et une nouvelle technique de recherche. Il y a du boulot.
je serais également curieux de voir le fonctionnement de l'app android

**Comment by nirolfa** [comment]
Ca l'air utiliser meme api que pour chaine ici  https://github.com/add-ons/plugin.video.vtm.go/blob/master/resources/lib/vtmgo/vtmgo.py
A la place de "lfvp-api.dpgmedia.net/VTM_GO"
c'est https://lfvp-mobile-api.dpgmedia.net/rtl_play/

**Comment by nirolfa** [comment]
https://github.com/add-ons/plugin.video.vtm.go/wiki/API

**Comment by karlo2105** [comment]
DPG Media is owner of VTM as of RTL Belgium. Previously, RTL channels shared same backbone as M6 because they belonged to RTL group.

**Comment by lb544** [comment]
Des news à ce sujet ? 
Merci

**Comment by dmu7004** [comment]
Bonsoir,

J'ai le même problème, que ce soit avec la dernière version stable ou beta :(. Je ne vois que les anciennes émissions.

Une solution en cours ?

Merci :)

**Comment by jeff2900** [comment]
Bonjour,
J'ai essayé de corriger le script rtlplay.py pour avoir les replays.
Le site est bloqué en France par la géolocalisation et je n'ai pas d’adresse IP en Belgique, c'est pourquoi je n'ai testé que quelques liens.
Voici le lien de l'addon avec le correctif https://www.mediafire.com/file/3r0zidzjvoyxgkj/plugin.video.catchuptvandmore-0.2.41%257Ebeta08-fix-rtlplaybe.zip/file

Si les résultats sont concluants je ferai un PR plus tard.

**Comment by lb544** [comment]
Merci @jeff2900, le listing fonctionne de nouveau (Ex sur La Meilleure Friterie j'ai bien les 2 saisons)
Mais la lecture est impossible, j'ai un index out of range : 
```
2025-05-25 13:43:10.448 T:20328   error <general>: [Catch-up-TV-&-More.support] list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtlplaybe.py", line 349, in get_video_url
                                                       manifest, license_url, lic_token = get_final_video_url(plugin, item_id, video_url)
                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtlplaybe.py", line 364, in get_final_video_url
                                                       login_token = get_login_token(plugin)
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtlplaybe.py", line 329, in get_login_token
                                                       x_dpp_profile = re.match(r"^([a-f\d]{8}(-[a-f\d]{4}){3}-[a-f\d]{12})", login_cookie[1]['lfvp_auth.profile'], re.IGNORECASE).group(1)
                                                                                                                              ~~~~~~~~~~~~^^^
                                                   IndexError: list index out of range

```

Merci

**Comment by jeff2900** [comment]
Bonjour,
Merci pour le test. Je ne comprends pas pourquoi le script ne trouve pas la variable 'lfvp_auth.profile' chez vous.
J'ai modifié le script pour contourner cette erreur.
Pouvez-vous tester la nouvelle version  ?
https://www.mediafire.com/file/4vl6qpcqo4nkmhx/plugin.video.catchuptvandmore-0.2.41%257Ebeta09-fix-rtlplaybe.zip/file

**Comment by lb544** [comment]
@jeff2900  Le lien de téléchargement est en privé :(
Merci
