### ISSUE TITLE
RTBF - LIVE - Not working

### ISSUE THREAD

**Issue by nirolfa** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1437]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
RTBF - LIVE - Not working

### To Reproduce
Steps to reproduce the behaviour:
1. RTBF Live : La une not working, La trois not working, 
only  Tipik is working (strange one is working and not the other 2)

### Expected behaviour
LIve feed working

### Actual behaviour
Error 403 exposure.api.redbee.live/v2/

### Your environment

 - [ X] Raspberry-Pi

 - Operating system version/name:
﻿2024-12-01 13:08:35.223 T:1083     INFO <general>: -----------------------------------------------------------------------
2024-12-01 13:08:35.223 T:1083     INFO <general>: Starting Kodi (19.5 (19.5.0) Git:19.5-Matrix). Platform: Linux ARM 32-
2024-12-01 13:08:35.223 T:1083     INFO <general>: Using Release Kodi x32
Running on BCM2835 with LibreELEC (official): 10.0.4

 - Catch-up TV & More version: latest from dev 

### Additional context
Add any other context about the problem here:

### Debug log
2024-12-01 13:33:40.934 T:2460    ERROR <general>: [Catch-up-TV-&-More.support] 403 Client Error: Forbidden for url: https://exposure.api.redbee.live/v2/customer/RTBF/businessunit/Auvio/entitlement/live_566610_6BA97Bb/play
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py", line 787, in get_live_url
                                                       return get_video_redbee(plugin, external_id, is_drm)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py", line 548, in get_video_redbee
                                                       video_format, forced_drm = get_redbee_format(plugin, video_id, session_token, is_drm)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py", line 878, in get_redbee_format
                                                       formats = urlquick.get(url, headers=headers, max_age=-1).json()['formats']
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 492, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 486, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 441, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 414, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://exposure.api.redbee.live/v2/customer/RTBF/businessunit/Auvio/entitlement/live_566610_6BA97Bb/play
2024-12-01 13:33:40.938 T:2460    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 297, in error_handler
                                                       code = exception.code
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--

**Comment by nirolfa** [comment]
seems only temporary bug ? 
working back yesterday, strange

**Comment by stemy2** [comment]
The bug is temporary but recurring.
