### ISSUE TITLE
Cnews Replay HS ?

### ISSUE THREAD

**Issue by gilles0606** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1443]
Bonsoir,

Cnews Replay ne marche plus...

Voici ce que j'ai dans les logs...

Grand merci...

2024-12-13 19:09:46.109 T:1238  warning <general>: [py.warnings] /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.cnews.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
                                                     warnings.warn(
                                                   
2024-12-13 19:09:46.167 T:1238    error <general>: [Catch-up-TV-&-More.support] 'NoneType' object has no attribute 'text'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                       session_data = self._process_results(results)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                       listitems = validate_listitems(results)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                       raw_listitems = list(raw_listitems)
                                                                       ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/cnews.py", line 90, in list_emissions
                                                       item.label = video_datas.find(".//div[@class='field field-type-text']").text
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   AttributeError: 'NoneType' object has no attribute 'text'
2024-12-13 19:09:49.908 T:1237    error <general>: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/cnews/list_emissions/?_pickle_=80049598000000000000007d94288c075f7469746c655f948c0e4e6f7320c3a96d697373696f6e73948c076974656d5f6964948c05636e657773948c0c63617465676f72795f75726c948c4968747470733a2f2f7777772e636e6577732e66722f736572766963652f646d5f6c6f61646d6f72652f646d5f656d697373696f6e5f696e6465785f656d697373696f6e732f25732f30948c0470616765948c013094752e
2024-12-13 19:09:49.920 T:1004    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/cnews/list_emissions/?_pickle_=80049598000000000000007d94288c075f7469746c655f948c0e4e6f7320c3a96d697373696f6e73948c076974656d5f6964948c05636e657773948c0c63617465676f72795f75726c948c4968747470733a2f2f7777772e636e6577732e66722f736572766963652f646d5f6c6f61646d6f72652f646d5f656d697373696f6e5f696e6465785f656d697373696f6e732f25732f30948c0470616765948c013094752e) failed
2024-12-13 19:09:50.217 T:1241  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-12-13 19:09:58.782 T:1249     info <general>: Skipped 62 duplicate messages..
2024-12-13 19:09:58.782 T:1249    error <general>: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/
2024-12-13 19:09:58.802 T:1004    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/) failed
2024-12-13 19:09:59.134 T:1252  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-12-13 19:09:59.181 T:1251     info <general>: Skipped 4 duplicate messages..
2024-12-13 19:09:59.181 T:1251    error <general>: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/
2024-12-13 19:09:59.202 T:1004    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/) failed
2024-12-13 19:09:59.279 T:1253    error <general>: Unable to find plugin 
2024-12-13 19:09:59.279 T:1253    error <general>: GetDirectory - Error getting plugin://
2024-12-13 19:09:59.281 T:1004    error <general>: CGUIMediaWindow::GetDirectory(plugin://) failed
2024-12-13 19:10:02.699 T:1004     info <general>: Loading skin file: Settings.xml, load type: KEEP_IN_MEMORY
2024-12-13 19:10:06.000 T:1061     info <general>: SETTINGS: run # Received openConfigurationWindow
2024-12-13 19:10:06.010 T:1004     info <general>: Loading skin file: /usr/share/kodi/addons/service.libreelec.settings/resources/skins/Default/1080i/service-LibreELEC-Settings-mainWindow.xml, load type: LOAD_ON_GUI_INIT
2024-12-13 19:10:06.030 T:1004    error <general>: Control 1000 in window 13001 has been asked to focus, but it can't
2024-12-13 19:10:06.030 T:1061     info <general>: SETTINGS: run # Waiting
2024-12-13 19:10:11.032 T:1004     info <general>: Loading skin file: SettingsSystemInfo.xml, load type: KEEP_IN_MEMORY
2024-12-13 19:10:59.341 T:1004     info <general>: Samba is idle. Closing the remaining connections

**Comment by joaopa00** [comment]
Devrait être fixé dans GIT.

**Comment by gilles0606** [comment]
Hello,

oui je confirme que cela remarche...
GRAND MERCI à toi...
