### ISSUE TITLE
FranceTvsport live page doesnt open anymore (Seems to work again)

### ISSUE THREAD

**Issue by ginofalaci** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#183]
Its not working anymore since yesterday, giving an Keyerror: u'image' and the page doesnt show up.

`2019-05-29 11:40:00.292 T:123145460469760   FATAL: [Catch-up-TV-&-More.support] u'image'
                                            Traceback (most recent call last):
                                              File "/Users/jean/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/support.py", line 295, in run_callback
                                                redirect = parent_ins._process_results(results)
                                              File "/Users/jean/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/route.py", line 95, in _process_results
                                                raw_listitems = validate_listitems(raw_listitems)
                                              File "/Users/jean/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/route.py", line 34, in validate_listitems
                                                raw_listitems = list(raw_listitems)
                                              File "/Users/jean/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/francetvsport.py", line 157, in list_lives
                                                live_image = live_datas["image"]["large_16_9"]
                                            KeyError: u'image'
2019-05-29 11:40:00.292 T:123145460469760 WARNING: ###### debug ######
2019-05-29 11:40:00.292 T:123145460469760 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/main/multi_live_bridge/'
2019-05-29 11:40:00.292 T:123145460469760 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{u'item_id': u'francetvsport', u'item_dict': {u'info': {'title': u'France TV Sport (francetv)'}, u'art': {u'fanart': u'https://github.com/Catch-up-TV-and-More/images/raw/master/channels/fr/francetvsport_fanart.jpg', u'thumb': u'https://github.com/Catch-up-TV-and-More/images/raw/master/channels/fr/francetvsport.png'}, u'stream': {}, u'label': u'France TV Sport (francetv)', u'params': <class 'codequick.listing.Params'>({u'item_module': u'resources.lib.channels.fr.francetvsport', '_title_': u'France TV Sport (francetv)', u'is_playable': True, u'is_folder': False, u'item_id': u'francetvsport', u'item_dict': {...}}), u'context': {}, u'properties': <class 'codequick.listing.Property'>({}), u'subtitles': []}, u'item_module': u'resources.lib.channels.fr.francetvsport', u'is_playable': True, u'is_folder': False}'
2019-05-29 11:40:00.292 T:123145460469760 WARNING: [urlquick] Requesting resource: https://api-sport-events.webservices.francetelevisions.fr/directs
2019-05-29 11:40:00.292 T:123145460469760 WARNING: [urlquick] Request headers: {u'Host': u'api-sport-events.webservices.francetelevisions.fr', u'Accept-language': u'en-gb,en-us,en', u'Connection': u'keep-alive', u'Accept': u'*/*', u'Accept-Encoding': u'gzip, deflate'}
2019-05-29 11:40:00.292 T:123145460469760 WARNING: [urlquick] Attempting to decode with default encoding: 'utf8'
2019-05-29 11:40:00.292 T:123145460469760 WARNING: ###### debug ######`

**Comment by wwark** [comment]
Hi,

Thank you !

With this fix https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/fbecb68261b8ae5ba06519cf7feab1502d0c1509, the issue will not be present anymore 

The fix will be available in the next beta available around 23h00 (CET)
I close this ticket.

Wwark
