### ISSUE TITLE
Le replay Arte ne fonctionne plus

### ISSUE THREAD

**Issue by alexismorillo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#201]
Contenu des logs : 
```
2019-07-30 21:49:45.182 T:1558172400  NOTICE: [Catch-up-TV-&-More] [cq_utils.import_needed_module] Import module resources.lib.channels.wo.arte on the fly
2019-07-30 21:49:49.053 T:1558172400  NOTICE: Previous line repeats 1 times.
2019-07-30 21:49:49.053 T:1558172400   FATAL: [Catch-up-TV-&-More.support] u'description'
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 295, in run_callback
                                                redirect = parent_ins._process_results(results)
                                              File "/home/pi/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 95, in _process_results
                                                raw_listitems = validate_listitems(raw_listitems)
                                              File "/home/pi/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 34, in validate_listitems
                                                raw_listitems = list(raw_listitems)
                                              File "/home/pi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/wo/arte.py", line 353, in list_videos_sub_category
                                                video_plot = video_datas["description"]
                                            KeyError: u'description'
2019-07-30 21:49:49.053 T:1558172400 WARNING: ###### debug ######
2019-07-30 21:49:49.053 T:1558172400 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/wo/arte/list_videos_sub_category/'
2019-07-30 21:49:49.053 T:1558172400 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{'item_id': u'arte', u'is_playable': False, u'is_folder': True, 'sub_category_url': u'https://www.arte.tv/fr/videos/series-et-fictions/series/'}'
2019-07-30 21:49:49.053 T:1558172400 WARNING: [urlquick] Requesting resource: https://www.arte.tv/fr/videos/series-et-fictions/series/
2019-07-30 21:49:49.053 T:1558172400 WARNING: [urlquick] Request headers: {u'Host': u'www.arte.tv', u'Accept-language': u'en-gb,en-us,en', u'Connection': u'keep-alive', u'Accept': u'*/*', u'Accept-Encoding': u'gzip, deflate'}
2019-07-30 21:49:49.053 T:1558172400 WARNING: [urlquick] Cache is fresh, returning cached response
2019-07-30 21:49:49.053 T:1558172400 WARNING: ###### debug ######
```

**Comment by wwark** [comment]
Bonjour,
Merci pour l'alerte. Il y a de modifications sur la partie Arte.
J'ai déjà fait un premier fix sur la version 0.2.10~beta2.
Il reste encore quelques petits ajustements à faire.

Merci,
marc.

**Comment by wwark** [comment]
Dernières corrections apportées sur 0.2.11~beta02.
On a maintenant les descriptions, et quelques corrections.
Je ferme ce ticket.
