### ISSUE TITLE
Catch-up TV ne fonctionne plus

### ISSUE THREAD

**Issue by wawa79** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#207]
Bonjour,
Le plugin ne se lance plus et génère un message d'erreur dans Kodi :

```
2019-08-04 12:13:56.665 T:4260   FATAL: [Catch-up-TV-&-More.support] root() got an unexpected keyword argument 'item_skeleton'
                                            Traceback (most recent call last):
                                              File "C:\Users\Mediaportal\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 292, in run_callback
                                                results = route.function(parent_ins, **self.callback_params)
                                            TypeError: root() got an unexpected keyword argument 'item_skeleton'
2019-08-04 12:13:56.665 T:4260 WARNING: ###### debug ######
2019-08-04 12:13:56.665 T:4260 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: 'root'
2019-08-04 12:13:56.665 T:4260 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{u'item_skeleton': u"[('tf1', 'replay_entry'), ('france2', 'replay_entry'), ('france3', 'replay_entry'), ('canalplus', 'replay_entry'), ('france5', 'replay_entry'), ('m6', 'replay_entry'), ('c8', 'replay_entry'), ('w9', 'replay_entry'), ('tmc', 'replay_entry'), ('tfx', 'replay_entry'), ('nrj12', 'replay_entry'), ('france4', 'replay_entry'), ('bfmtv', 'replay_entry'), ('cnews', 'replay_entry'), ('cstar', 'replay_entry'), ('gulli', 'replay_entry'), ('franceo', 'replay_entry'), ('tf1-series-films', 'replay_entry'), ('lequipe', 'replay_entry'), ('6ter', 'replay_entry'), ('numero23', 'replay_entry'), ('cherie25', 'replay_entry'), ('la_1ere', 'replay_entry'), ('bfmbusiness', 'replay_entry'), ('rmc', 'replay_entry'), ('01net', 'replay_entry'), ('tfou', 'replay_entry'), ('xtra', 'replay_entry'), ('lci', 'replay_entry'), ('lcp', 'replay_entry'), ('rmcdecouverte', 'replay_entry'), ('stories', 'replay_entry'), ('bruce', 'replay_entry'), ('crazy_kitchen', 'replay_entry'), ('home', 'replay_entry'), ('styles', 'replay_entry'), ('comedy', 'replay_entry'), ('publicsenat', 'replay_entry'), ('histoire', 'replay_entry'), ('tvbreizh', 'replay_entry'), ('ushuaiatv', 'replay_entry'), ('studio-4', 'replay_entry'), ('irl', 'replay_entry'), ('seasons', 'replay_entry'), ('comedie', 'replay_entry'), ('les-chaines-planete', 'replay_entry'), ('golfplus', 'replay_entry'), ('cineplus', 'replay_entry'), ('infosportplus', 'replay_entry'), ('gameone', 'replay_entry'), ('francetveducation', 'replay_entry'), ('gong', 'replay_entry'), ('francetvsport', 'replay_entry')]", u'action': u'generic_menu', u'item_path': u"['root', 'channels', 'fr']", u'module_path': u'None', u'item_id': u'fr', u'module_name': u'None', u'window_title': u'France'}'
2019-08-04 12:13:56.665 T:4260 WARNING: ###### debug ######
2019-08-04 12:17:20.818 T:11860   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/?item_skeleton=%5B%28%27tf1%27%2C+%27replay_entry%27%29%2C+%28%27france2%27%2C+%27replay_entry%27%29%2C+%28%27france3%27%2C+%27replay_entry%27%29%2C+%28%27canalplus%27%2C+%27replay_entry%27%29%2C+%28%27france5%27%2C+%27replay_entry%27%29%2C+%28%27m6%27%2C+%27replay_entry%27%29%2C+%28%27c8%27%2C+%27replay_entry%27%29%2C+%28%27w9%27%2C+%27replay_entry%27%29%2C+%28%27tmc%27%2C+%27replay_entry%27%29%2C+%28%27tfx%27%2C+%27replay_entry%27%29%2C+%28%27nrj12%27%2C+%27replay_entry%27%29%2C+%28%27france4%27%2C+%27replay_entry%27%29%2C+%28%27bfmtv%27%2C+%27replay_entry%27%29%2C+%28%27cnews%27%2C+%27replay_entry%27%29%2C+%28%27cstar%27%2C+%27replay_entry%27%29%2C+%28%27gulli%27%2C+%27replay_entry%27%29%2C+%28%27franceo%27%2C+%27replay_entry%27%29%2C+%28%27tf1-series-films%27%2C+%27replay_entry%27%29%2C+%28%27lequipe%27%2C+%27replay_entry%27%29%2C+%28%276ter%27%2C+%27replay_entry%27%29%2C+%28%27numero23%27%2C+%27replay_entry%27%29%2C+%28%27cherie25%27%2C+%27replay_entry%27%29%2C+%28%27la_1ere%27%2C+%27replay_entry%27%29%2C+%28%27bfmbusiness%27%2C+%27replay_entry%27%29%2C+%28%27rmc%27%2C+%27replay_entry%27%29%2C+%28%2701net%27%2C+%27replay_entry%27%29%2C+%28%27tfou%27%2C+%27replay_entry%27%29%2C+%28%27xtra%27%2C+%27replay_entry%27%29%2C+%28%27lci%27%2C+%27replay_entry%27%29%2C+%28%27lcp%27%2C+%27replay_entry%27%29%2C+%28%27rmcdecouverte%27%2C+%27replay_entry%27%29%2C+%28%27stories%27%2C+%27replay_entry%27%29%2C+%28%27bruce%27%2C+%27replay_entry%27%29%2C+%28%27crazy_kitchen%27%2C+%27replay_entry%27%29%2C+%28%27home%27%2C+%27replay_entry%27%29%2C+%28%27styles%27%2C+%27replay_entry%27%29%2C+%28%27comedy%27%2C+%27replay_entry%27%29%2C+%28%27publicsenat%27%2C+%27replay_entry%27%29%2C+%28%27histoire%27%2C+%27replay_entry%27%29%2C+%28%27tvbreizh%27%2C+%27replay_entry%27%29%2C+%28%27ushuaiatv%27%2C+%27replay_entry%27%29%2C+%28%27studio-4%27%2C+%27replay_entry%27%29%2C+%28%27irl%27%2C+%27replay_entry%27%29%2C+%28%27seasons%27%2C+%27replay_entry%27%29%2C+%28%27comedie%27%2C+%27replay_entry%27%29%2C+%28%27les-chaines-planete%27%2C+%27replay_entry%27%29%2C+%28%27golfplus%27%2C+%27replay_entry%27%29%2C+%28%27cineplus%27%2C+%27replay_entry%27%29%2C+%28%27infosportplus%27%2C+%27replay_entry%27%29%2C+%28%27gameone%27%2C+%27replay_entry%27%29%2C+%28%27francetveducation%27%2C+%27replay_entry%27%29%2C+%28%27gong%27%2C+%27replay_entry%27%29%2C+%28%27francetvsport%27%2C+%27replay_entry%27%29%5D&item_id=fr&item_path=%5B%27root%27%2C+%27channels%27%2C+%27fr%27%5D&module_name=None&action=generic_menu&module_path=None&window_title=France
2019-08-04 12:17:20.828 T:10832   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/?item_skeleton=%5B%28%27tf1%27%2C+%27replay_entry%27%29%2C+%28%27france2%27%2C+%27replay_entry%27%29%2C+%28%27france3%27%2C+%27replay_entry%27%29%2C+%28%27canalplus%27%2C+%27replay_entry%27%29%2C+%28%27france5%27%2C+%27replay_entry%27%29%2C+%28%27m6%27%2C+%27replay_entry%27%29%2C+%28%27c8%27%2C+%27replay_entry%27%29%2C+%28%27w9%27%2C+%27replay_entry%27%29%2C+%28%27tmc%27%2C+%27replay_entry%27%29%2C+%28%27tfx%27%2C+%27replay_entry%27%29%2C+%28%27nrj12%27%2C+%27replay_entry%27%29%2C+%28%27france4%27%2C+%27replay_entry%27%29%2C+%28%27bfmtv%27%2C+%27replay_entry%27%29%2C+%28%27cnews%27%2C+%27replay_entry%27%29%2C+%28%27cstar%27%2C+%27replay_entry%27%29%2C+%28%27gulli%27%2C+%27replay_entry%27%29%2C+%28%27franceo%27%2C+%27replay_entry%27%29%2C+%28%27tf1-series-films%27%2C+%27replay_entry%27%29%2C+%28%27lequipe%27%2C+%27replay_entry%27%29%2C+%28%276ter%27%2C+%27replay_entry%27%29%2C+%28%27numero23%27%2C+%27replay_entry%27%29%2C+%28%27cherie25%27%2C+%27replay_entry%27%29%2C+%28%27la_1ere%27%2C+%27replay_entry%27%29%2C+%28%27bfmbusiness%27%2C+%27replay_entry%27%29%2C+%28%27rmc%27%2C+%27replay_entry%27%29%2C+%28%2701net%27%2C+%27replay_entry%27%29%2C+%28%27tfou%27%2C+%27replay_entry%27%29%2C+%28%27xtra%27%2C+%27replay_entry%27%29%2C+%28%27lci%27%2C+%27replay_entry%27%29%2C+%28%27lcp%27%2C+%27replay_entry%27%29%2C+%28%27rmcdecouverte%27%2C+%27replay_entry%27%29%2C+%28%27stories%27%2C+%27replay_entry%27%29%2C+%28%27bruce%27%2C+%27replay_entry%27%29%2C+%28%27crazy_kitchen%27%2C+%27replay_entry%27%29%2C+%28%27home%27%2C+%27replay_entry%27%29%2C+%28%27styles%27%2C+%27replay_entry%27%29%2C+%28%27comedy%27%2C+%27replay_entry%27%29%2C+%28%27publicsenat%27%2C+%27replay_entry%27%29%2C+%28%27histoire%27%2C+%27replay_entry%27%29%2C+%28%27tvbreizh%27%2C+%27replay_entry%27%29%2C+%28%27ushuaiatv%27%2C+%27replay_entry%27%29%2C+%28%27studio-4%27%2C+%27replay_entry%27%29%2C+%28%27irl%27%2C+%27replay_entry%27%29%2C+%28%27seasons%27%2C+%27replay_entry%27%29%2C+%28%27comedie%27%2C+%27replay_entry%27%29%2C+%28%27les-chaines-planete%27%2C+%27replay_entry%27%29%2C+%28%27golfplus%27%2C+%27replay_entry%27%29%2C+%28%27cineplus%27%2C+%27replay_entry%27%29%2C+%28%27infosportplus%27%2C+%27replay_entry%27%29%2C+%28%27gameone%27%2C+%27replay_entry%27%29%2C+%28%27francetveducation%27%2C+%27replay_entry%27%29%2C+%28%27gong%27%2C+%27replay_entry%27%29%2C+%28%27francetvsport%27%2C+%27replay_entry%27%29%5D&item_id=fr&item_path=%5B%27root%27%2C+%27channels%27%2C+%27fr%27%5D&module_name=None&action=generic_menu&module_path=None&window_title=France) failed
2019-08-04 12:17:20.848 T:7348   ERROR: XFILE::CDirectory::GetDirectory - Error getting library://video_flat/extrafanart/
2019-08-04 12:17:31.405 T:3628   ERROR: PVR::CPVRGUIDirectory::GetChannelsDirectory: Unable to obtain members of channel group 'Toutes les chaînes/extrafanart'
2019-08-04 12:17:31.405 T:3628   ERROR: XFILE::CDirectory::GetDirectory - Error getting pvr://channels/tv/Toutes les chaînes/extrafanart/
2019-08-04 12:17:43.008 T:10540   ERROR: XFILE::CDirectory::GetDirectory - Error getting addons://extrafanart/
2019-08-04 12:19:20.253 T:10832   ERROR: Previous line repeats 1 times.
2019-08-04 12:19:20.253 T:10832   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2019-08-04 12:19:21.080 T:8120   FATAL: [Catch-up-TV-&-More.support] '/main/generic_menu/extrafanart/'
                                            Traceback (most recent call last):
                                              File "C:\Users\Mediaportal\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 286, in run_callback
                                                route = self.get_route()
                                              File "C:\Users\Mediaportal\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 234, in get_route
                                                return self.registered_routes[path if path else self.selector]
                                            KeyError: '/main/generic_menu/extrafanart/'
2019-08-04 12:19:21.080 T:8120 WARNING: ###### debug ######
2019-08-04 12:19:21.080 T:8120 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/main/generic_menu/extrafanart/'
2019-08-04 12:19:21.080 T:8120 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{}'
2019-08-04 12:19:21.080 T:8120 WARNING: ###### debug ######
```

**Comment by wwark** [comment]
Bonjour @wawa79,

Pouvez-vous me confirmer que vous n'utilisez pas le skin par défaut de Kodi?
Est-ce que le problème est visible sur le skin par défaut de Kodi ?

Merci,
Wwark

**Comment by wawa79** [comment]
Bonjour,

Effectivement, pas de problème en repassant sous Estuary (j'utilise Andromeda). Ce qui est étrange, c'est que je suis sous Andromeda depuis plusieurs mois et que l'erreur n'est apparue qu'il y a quelques jours.

Cordialement,
Yann

**Comment by wwark** [comment]
Merci pour cette confirmation.
Ce ticket semble lié à ce ticket (https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/203)
Une question, est-ce que vous aviez installé le plugin depius le dépot officiel de Kodi ?

**Comment by wawa79** [comment]
Je vous avoue ne pas être certain. Il me semble être passé par la repository donnée dans la doc d'installation. Par contre, j'ai fait une désinstallation / réinstallation du plugin via le dépôt officiel.

**Comment by SylvainCecchetto** [comment]
Bonsoir,
Je viens d'installer ce skin sous Kodi 18/macOS et je n'ai pas de problème lors de l'utilisation du plugin :-/
Peut être est-ce un bon plan de tester une désinstallation complète du plugin et reinstallation en suivant ce tutoriel https://catch-up-tv-and-more.github.io/fr/installation/ ;-)
On pourra peut être voir par la suite si le problème persiste.

**Comment by victore447** [comment]
Bonjour, 
Teste de la derniere Version de catch-up via GitHub ce matin et tout fonctionne. 
Même les widgets avec le skin éminence pour la personnalisation de l'habillage de kodi  (pas le temps pour testé avec les autres skins). 

J'ai télécharger ici https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore puis installer le zip (mise à jour automatique). 

Pour la personnalisation de l'habillage du skin éminence pour kodi j'ai tout refait (ça marche).

**Comment by wawa79** [comment]
Bonjour,

Effectivement : une désinstallation / réinstallation a rendu le plugin a nouveau fonctionnel. Un peu pénible mais cela fonctionne...

**Comment by wwark** [comment]
Bonjour,
Est-ce qu'il y a encore des erreurs sur les widgets ?

**Comment by SylvainCecchetto** [comment]
Je ferme cette issue pour inactivité.
Re-ouvrir si nécessaire ;-)
