### ISSUE TITLE
Replay BFM TV accès impossible

### ISSUE THREAD

**Issue by nmaster2042** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#241]
Avec le plugin en version 2.14 beta2, impossible d'accéder au replay de BFM TV

Attention, ce bug se produit sur box Amlogic équipée de CoreElec 9.2.0 stable, pas sur PC KODI 18 sous ubuntu 19.04.

Ci-join log kodi de la box.

[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/3855499/kodi.log)

**Comment by wwark** [comment]
Hello,

Il faudrait ouvrir un ticket chez CoreElec
Et leur fournir cette trace d'erreur

2019-11-17 12:00:26.583 T:3887801152   DEBUG: [Catch-up-TV-&-More.support] Callback parameters: '{u'item_id': u'bfmtv', u'item_dict': {u'info': {'title': u'BFM TV'}, u'art': {u'fanart': u'https://github.com/Catch-up-TV-and-More/images/raw/master/channels/fr/bfmtv_fanart.jpg', u'thumb': u'https://github.com/Catch-up-TV-and-More/images/raw/master/channels/fr/bfmtv.png'}, u'stream': {}, u'label': u'BFM TV', u'params': <class 'codequick.listing.Params'>({u'item_module': u'resources.lib.channels.fr.bfmtv', '_title_': u'BFM TV', u'is_playable': False, u'is_folder': True, u'item_id': u'bfmtv', u'item_dict': {...}}), u'context': {}, u'properties': {}, u'subtitles': []}, u'item_module': u'resources.lib.channels.fr.bfmtv', u'is_playable': False, u'is_folder': True}'
2019-11-17 12:00:26.591 T:3887801152   FATAL: [Catch-up-TV-&-More.support] No module named lib2to3.pgen2.parse
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 292, in run_callback
                                                results = route.function(parent_ins, **self.callback_params)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 332, in replay_bridge
                                                item_module = importlib.import_module(kwargs.get('item_module'))
                                              File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/bfmtv.py", line 30, in <module>
                                                from past.utils import old_div
                                              File "/storage/.kodi/addons/script.module.future/libs/past/__init__.py", line 88, in <module>
                                                from past.translation import install_hooks as autotranslate
                                              File "/storage/.kodi/addons/script.module.future/libs/past/translation/__init__.py", line 41, in <module>
                                                from lib2to3.pgen2.parse import ParseError
                                            ImportError: No module named lib2to3.pgen2.parse
2019-11-17 12:00:26.591 T:3887801152 WARNING: ###### debug ######

Merci,
Wwark

**Comment by wwark** [comment]
@SylvainCecchetto  la lib script.module.future semble posé problème sur certain environnement.

**Comment by SylvainCecchetto** [comment]
Hi all,
It seems that this issue was already repot [here](https://github.com/cytech/weather.wundergroundpws/issues/3) and [here](https://github.com/foreverguest/repository.foreverguest/issues/13).

The workaround is describe [here](https://forum.kodi.tv/showthread.php?tid=200640&pid=2842804#pid2842804).

So, to sum up the issue:
* LibreELEC and CoreElec do not include the python lib2to3 module
* Download manually the lib2to3 module [here](http://rgho.st/87ZdFptr6)
* Extract this file in `/storage/.kodi/addons/script.module.future/libs/` path
* This issue should be solved

To conclude, wwark is right, it's not an issue related to our addon, it's an issue of your OS ;-)

(Je viens de réaliser que cette issue est en français, si besoin je peux traduire ma réponse)

**Comment by wwark** [comment]
Hello @sylvaincecchetto, on a beaucoup de personnes sur librelec ou corelec on n'a pas d'autres solutions le temps qu'il se mette à jour ?

**Comment by SylvainCecchetto** [comment]
Hello @wwark, tu as raison ... Je vais regarder ça ;-)

**Comment by SylvainCecchetto** [comment]
Je n'ai pas d'installation LibreElec sous la main pour tester :-/ mais logiquement le commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/d23ff0c48a3bbf9607bc9909448a21acdc42656e devrait résoudre le problème sans avoir à utiliser le workaround donné [ici](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/241#issuecomment-555093401)

**Comment by nmaster2042** [comment]
Merci, je comprends, cella vient de CoreElec à la base.
N'ayant pas accès à ma box (déplacement), je testerai dès que possible.
Merci pour votre aide

**Comment by SylvainCecchetto** [comment]
Ça marche, merci beaucoup !

**Comment by SylvainCecchetto** [comment]
Bonjour à tous,
J'ai pu tester LibreElec sur un machine virtuelle :
* En effet, la version `0.2.14~beta02` donne une erreur lorsque l'on rentre dans le Replay de BFM TV
* La branche `dev` avec le commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/d23ff0c48a3bbf9607bc9909448a21acdc42656e fonctionne bien !

Je laisse ouvert pour le moment, on pourra fermer l'issue après confirmation que la version `0.2.14~beta03` fonctionne bien sur LibreElec ou CoreElec ;-)

**Comment by wwark** [comment]
Closed issue - 0.2.14 release.
