### ISSUE TITLE
Download issue pour RTBF / Retrailler la partie Replay

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#246]
### Describe the bug
A clear and concise description of what the bug is:
Erreur pour download video sur RTBF à cause de l'encodage

### To Reproduce
1. Test download cette vidéo "RTBF Auvio - CQFD (Ce Qui Fait D\xe9bat) - Faut-il r\xe9instaurer des ann\xe9es d'\xe9tudes claires ?
2.
3.
4.

### Expected behavior
A clear and concise description of what you expected to happen:
Ne pas avoir d'erreur lors du téléchargement.

### Actuel behavior
Tell us what happens instead:
Donwload KO

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 17
 - Catch-up TV & More version: non connue
 - Installation method: non connue

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

```
00:08:56.842 T:140675021006592 WARNING: ###### debug ######
00:08:56.842 T:140675021006592   ERROR: /home/xavier/.kodi/addons/plugin.video.catchuptvandmore/addon.py:514: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
                                              elif 'No items found' not in exception:
00:09:03.787 T:140675603814144  NOTICE: [Catch-up-TV-&-More] [cq_utils.import_needed_module] Import module resources.lib.channels.be.rtbf on the fly
00:09:14.200 T:140675603814144  NOTICE: script.module.youtube.dl: youtube_dl core version: 2019.09.12.1
00:09:18.478 T:140675603814144  NOTICE: ++++==== script.module.addon.signals: sourceID keyword is DEPRECATED - use source_id ====++++
00:09:22.606 T:140675603814144  NOTICE: Previous line repeats 1 times.
00:09:22.606 T:140675603814144   FATAL: [Catch-up-TV-&-More.support] 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/xavier/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 292, in run_callback
                                                results = route.function(parent_ins, **self.callback_params)
                                              File "/home/xavier/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py", line 385, in get_video_url
                                                return download.download_video(stream_url, video_label)
                                              File "/home/xavier/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/download.py", line 52, in download_video
                                                vid, bg=Script.setting.get_boolean('dl_background'), path=path)
                                              File "/home/xavier/.kodi/addons/script.module.youtube.dl/lib/YDStreamExtractor.py", line 395, in handleDownload
                                                return _handleDownload(info, path, duration=duration, bg=False)
                                              File "/home/xavier/.kodi/addons/script.module.youtube.dl/lib/YDStreamExtractor.py", line 340, in _handleDownload
                                                if not StreamUtils.moveFile(filePath, path, filename=info.get('filename')):
                                              File "/home/xavier/.kodi/addons/script.module.youtube.dl/lib/YDStreamUtils.py", line 195, in moveFile
                                                destFilePath = os.path.join(dest_path, fname)
                                              File "/usr/lib/python2.7/posixpath.py", line 71, in join
                                                path +=  b
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
00:09:22.606 T:140675603814144 WARNING: ###### debug ######
00:09:22.606 T:140675603814144 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/be/rtbf/get_video_url/'
00:09:22.606 T:140675603814144 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{'video_id': u'2567068', u'is_playable': True, 'download_mode': True, u'is_folder': False, 'item_id': u'auvio', 'video_label': u"RTBF Auvio - CQFD (Ce Qui Fait D\xe9bat) - Faut-il r\xe9instaurer des ann\xe9es d'\xe9tudes claires ?"}'
00:09:22.606 T:140675603814144 WARNING: [urlquick] Requesting resource: https://www.rtbf.be/auvio/embed/media?id=2567068&autoplay=1
00:09:22.606 T:140675603814144 WARNING: [urlquick] Request headers: {u'Host': u'www.rtbf.be', u'Accept-language': u'en-gb,en-us,en', u'Connection': u'keep-alive', u'Accept': u'*/*', u'Accept-Encoding': u'gzip, deflate'}
00:09:22.606 T:140675603814144 WARNING: ###### debug ######
00:09:22.607 T:140675603814144   ERROR: /home/xavier/.kodi/addons/plugin.video.catchuptvandmore/addon.py:514: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
                                              elif 'No items found' not in exception:
```

**Comment by SylvainCecchetto** [comment]
C'est quelle catégorie cette émission stp wwark ?

**Comment by wwark** [comment]
Je n'ai pas encore regarder mais il y a plusieurs erreurs sur la partie replay
Il faut retravailler le replay RTBF

**Comment by SylvainCecchetto** [comment]
Dans mon test de ce matin, la section `Tous les programmes` de RTBF Audio retourne aucun item en effet :-/

**Comment by wwark** [comment]
Fixé partie Replay :+1: 
Reste à regarder le download !

**Comment by wwark** [comment]
Test ok de mon côté pour télécharger Emission > CQFD > (Ce Qui Fait D\xe9bat) - Faut-il r\xe9instaurer des ann\xe9es d'\xe9tudes claires ?

Surement un problème d'encodage sur kodi 17. 
J'ai demandé à cette personne de tester sur Kodi 18.

**Comment by wwark** [comment]
Bon sans son ... youtube-dl doit pas gérer le son dans le m3u8.

**Comment by SylvainCecchetto** [comment]
Ah pardon je croyais que c'était un problème que tu avais rencontré ;-)

**Comment by Gaet81** [comment]
cool, merci pour la rapidité d'adaptation.
J'ai une question, y a une raison pour laquelle vous parsez le site plutot que d'utiliser les API?
Si il faut je veux bien retravailler ce fichier pour utiliser les API plutôt que praser le site

**Comment by wwark** [comment]
hello @Gaet81,
Quand j'avais regardé à l'époque il y avait pas tout les contenus sur l'API comme sur le site web.
Il faut que je check ce point.

**Comment by wwark** [comment]
Ces points ne sont plus d'actualité je pense.
A rouvrir si besoin.
