### ISSUE TITLE
[Guide TV] 'NoneType' is not callable

### ISSUE THREAD

**Issue by SylvainCecchetto** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#248]
### Describe the bug
A clear and concise description of what the bug is:

### To Reproduce
1. Open Live TV FR
2.
3.
4.

### Expected behavior
A clear and concise description of what you expected to happen:

### Actuel behavior
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:
 - Catch-up TV & More version:
 - Installation method:

### Additional context
Add any other context about the problem here:

Si tu actives le mode Guide TV / Tu arrêtes le live TV.
Tu as cette erreur. et on doit fermer kodi pour ne plus avoir l'erreur.

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

```
2019-11-21 07:10:24.709 T:140337771177728 FATAL: [Catch-up-TV-&-More.support] attribute of type 'NoneType' is not callable
Traceback (most recent call last):
File "/home/wark/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 295, in runcallback
redirect = parent_ins._process_results(results)
File "/home/wark/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 95, in _process_results
raw_listitems = validate_listitems(raw_listitems)
File "/home/wark/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 34, in validate_listitems
raw_listitems = list(raw_listitems)
File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 226, in tv_guide_menu
tv_guide = xmltv.grab_tv_guide(menu_id, menu)
File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/xmltv.py", line 442, in grab_tv_guide
programmes = read_current_programmes(open(xmltv_fp, 'r'))
File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/xmltv.py", line 315, in read_current_programmes
start_ts = date_str_to_timestamp(start_s)
File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/xmltv.py", line 281, in date_str_to_timestamp
d = datetime.datetime.strptime(s, date_format_notz)
TypeError: attribute of type 'NoneType' is not callable
2019-11-21 07:10:24.709 T:140337771177728 WARNING: ###### debug ######
2019-11-21 07:10:24.709 T:140337771177728 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/main/tv_guide_menu/'
2019-11-21 07:10:24.709 T:140337771177728 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{u'item_id': u'fr_live', u'item_dict': {u'info': {'title': u'France'}, u'art': {u'thumb': u'https://github.com/Catch-up-TV-and-More/images/raw/master/channels/fr.png'}, u'stream': {}, u'label': u'France', u'params': <class 'codequick.listing.Params'>({u'item_id': u'fr_live', '_title': u'France', u'is_folder': True, u'is_playable': False, u'item_dict': {...}}), u'context': {}, u'properties': {}, u'subtitles': []}, u'is_playable': False, u'is_folder': True}'
2019-11-21 07:10:24.709 T:140337771177728 WARNING: [Catch-up-TV-&-More] xmltv file of fr_live was already download in the last 24 hours
```

**Comment by SylvainCecchetto** [comment]
Jai l'impression que tu as eu cette erreur avec un programme ayant le champ `start` du XMLTV vide.
En tout cas je n'arrive pas à reproduire :-/
Peux tu me faire parvenir tes les fichiers XMTLV de ton dossier userdata si cela se reproduit stp ;-)

**Comment by wwark** [comment]
Hello,

Avec la nouvelle version.
2019-11-23 10:01:06.563 T:140243417265920   DEBUG: [Catch-up-TV-&-More] xmltv url of fr_live: https://github.com/Catch-up-TV-and-More/xmltv/raw/master/tv_guide_fr_20191123.xml
2019-11-23 10:01:06.563 T:140243417265920   DEBUG: [Catch-up-TV-&-More] xmltv filename of fr_live: tv_guide_fr_20191123.xml
2019-11-23 10:01:07.665 T:140243417265920   DEBUG: [Catch-up-TV-&-More] xmltv module failed with error: attribute of type 'NoneType' is not callable

**Comment by SylvainCecchetto** [comment]
Arf je n'arrive pas à reproduire ce bug xD
Avec quelle chaine ? (je ne pense que ça change grand chose mais bon ...).

Aussi, peux tu commenter le try/catch stp pour avoir plus d'infos ? Merci à toi !

**Comment by wwark** [comment]
C'est sur le format de date

2019-11-23 10:18:38.727 T:139899188033280   DEBUG: [Catch-up-TV-&-More] xmltv filename of fr_live: tv_guide_fr_20191123.xml
2019-11-23 10:18:39.172 T:139899188033280   FATAL: [Catch-up-TV-&-More.support] attribute of type 'NoneType' is not callable
                                            Traceback (most recent call last):
                                              File "/home/wark/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 295, in run_callback
                                                redirect = parent_ins._process_results(results)
                                              File "/home/wark/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 95, in _process_results
                                                raw_listitems = validate_listitems(raw_listitems)
                                              File "/home/wark/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 34, in validate_listitems
                                                raw_listitems = list(raw_listitems)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 229, in tv_guide_menu
                                                tv_guide = xmltv.grab_tv_guide(menu_id, menu)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/xmltv.py", line 400, in grab_tv_guide
                                                programmes = read_current_programmes(open(xmltv_fp, 'r'))
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/xmltv.py", line 291, in read_current_programmes
                                                start_ts = date_str_to_timestamp(start_s)
                                              File "/home/wark/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/xmltv.py", line 257, in date_str_to_timestamp
                                                d = datetime.datetime.strptime(s, date_format_notz)
                                            TypeError: attribute of type 'NoneType' is not callable
2019-11-23 10:18:39.172 T:139899188033280 WARNING: ###### debug ######
2019-11-23 10:18:39.172 T:139899188033280 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/main/tv_guide_menu/'
2019-11-23 10:18:39.172 T:139899188033280 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{u'item_id': u'fr_live', u'item_dict': {u'info': {'title': u'France'}, u'art': {u'thumb': u'https://github.com/Catch-up-TV-and-More/images/raw/master/channels/fr.png'}, u'stream': {}, u'label': u'France', u'params': <class 'codequick.listing.Params'>({u'item_id': u'fr_live', '_title_': u'France', u'is_folder': True, u'is_playable': False, u'item_dict': {...}}), u'context': {}, u'properties': {}, u'subtitles': []}, u'is_playable': False, u'is_folder': True}'
2019-11-23 10:18:39.172 T:139899188033280 WARNING: [Catch-up-TV-&-More] xmltv url of fr_live: https://github.com/Catch-up-TV-and-More/xmltv/raw/master/tv_guide_fr_20191123.xml
2019-11-23 10:18:39.172 T:139899188033280 WARNING: [Catch-up-TV-&-More] xmltv filename of fr_live: tv_guide_fr_20191123.xml

**Comment by SylvainCecchetto** [comment]
J'avoue que je sèche :-/ Dans le fichier XMLTV que tu as en pièce jointe, tous les champs `start` sont les mêmes et je n'arrive pas à avoir cette erreur.
Ce que je fais :
* J'ouvre Kodi avec la branche dev du plugin
* Je vais dans Live TV et dans France
* Je démarre France 2
* Je stop la lecture
* RAS

**Comment by wwark** [comment]
ça doit venir surement d'une lib de mon côté lié à mon environnement.

**Comment by SylvainCecchetto** [comment]
ça me parait étrange ..
Et si tu fais un des print entre chaque instructions de la fonction `date_str_to_timestamp` tu as plus d'infos ?

**Comment by wwark** [comment]
Ok je prépare ça d'ici demain.

**Comment by SylvainCecchetto** [comment]
Après je suis en train de faire le switch pour passer tous les XMLTV en UTC (afin d'éviter les problèmes de timezone comme expliqué ici https://trello.com/c/4QgWc6hy ).
Donc peut être que le problème va disparaitre en même temps xD (enfin ça serait bien :-P)

**Comment by SylvainCecchetto** [comment]
Oh yeah je crois que j'arrive à reproduire ton bug sur l'Apple TV, je vais la mettre en mode debug pour essayer de voir ça ;-)

**Comment by SylvainCecchetto** [comment]
Bonne nouvelle (enfin je crois xD), c'est un problème connu : https://forum.kodi.tv/showthread.php?tid=112916

**Comment by SylvainCecchetto** [comment]
As-tu moyen de tester ce commit stp https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/028904001dae33ad90bfda89c4402c3be082223a
Il est push sur dev.

Sur l'Apple TV ça semble régler le problème

**Comment by wwark** [comment]
Test ok aussi de mon côté !

**Comment by SylvainCecchetto** [comment]
Cool merci pour ton test !!
C'est vraiment un bug à la con ça...
