### ISSUE TITLE
urllib3 not found on librelec 9.0.2 - Kodi 18.2

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#250]
### Describe the bug
A clear and concise description of what the bug is:
Issue during import request - > urllib3 not found

### To Reproduce
1.
2.
3.
4.

### Expected behavior
A clear and concise description of what you expected to happen:
Issue below

### Actuel behavior
Tell us what happens instead:
no issue

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:Librelec 9.0.2
 - Kodi version: 18.2
 - Catch-up TV & More version: v0.2.11
 - Installation method: Kodi Repo

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

```
2019-11-22 19:57:39.923 T:1464857456 WARNING: Previous line repeats 1 times.
2019-11-22 19:57:39.923 T:1464857456  NOTICE: LoadJpeg: unable to load https://github.com/Catch-up-TV-and-More/images/raw/master/channels/fr/6ter_fanart.jpg
2019-11-22 19:57:58.774 T:1552089968   FATAL: [Catch-up-TV-&-More.support] No module named urllib3
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 292, in run_callback
                                                results = route.function(parent_ins, **self.callback_params)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 367, in live_bridge
                                                item_module = importlib.import_module(kwargs.get('item_module'))
                                              File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/mycanal.py", line 43, in <module>
                                                import requests
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 43, in <module>
                                                import urllib3
                                            ImportError: No module named urllib3
2019-11-22 19:57:58.774 T:1552089968 WARNING: ###### debug ######
2019-11-22 19:57:58.774 T:1552089968 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/main/live_bridge/'
2019-11-22 19:57:58.775 T:1552089968 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{u'item_id': u'canalplus', u'item_dict': {u'info': {u'genre': u'Football', u'plot': u'19h45 - 21h40', 'title': u'Canal + \u2014 Football (Paris-SG / Lille)'}, u'art': {u'fanart': u'https://television.telerama.fr/sites/tr_master/files/sheet_media/media/f11e47b9-cbb1-42ef-84a3-ef884996af09.jpg', u'thumb': u'https://television.telerama.fr/sites/tr_master/files/sheet_media/media/f11e47b9-cbb1-42ef-84a3-ef884996af09.jpg'}, u'stream': {}, u'label': u'Canal + \u2014 Football (Paris-SG / Lille)', u'params': <class 'codequick.listing.Params'>({u'item_module': u'resources.lib.channels.fr.mycanal', '_title_': u'Canal + \u2014 Football (Paris-SG / Lille)', u'is_playable': True, u'is_folder': False, u'item_id': u'canalplus', u'item_dict': {...}}), u'context': {}, u'properties': <class 'codequick.listing.Property'>({}), u'subtitles': []}, u'item_module': u'resources.lib.channels.fr.mycanal', u'is_playable': True, u'is_folder': False}'
2019-11-22 19:57:58.775 T:1552089968 WARNING: ###### debug ######
2019-11-22 19:58:06.142 T:1552089968 WARNING: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py): the python script "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui8ListItemE
2019-11-22 19:58:06.159 T:1936969248   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/main/live_bridge/?_pickle_=80027d710028580b0000006974656d5f6d6f64756c65710158210000007265736f75726365732e6c69622e6368616e6e656c732e66722e6d7963616e616c710255075f7469746c655f7103582700000043616e616c202b20e2809420466f6f7462616c6c202850617269732d5347202f204c696c6c65297104580b00000069735f706c617961626c65710588580900000069735f666f6c64657271068958070000006974656d5f69647107580900000063616e616c706c7573710858090000006974656d5f6469637471097d710a285804000000696e666f710b7d710c28580500000067656e7265710d5808000000466f6f7462616c6c710e5804000000706c6f74710f580d0000003139683435202d203231683430711055057469746c657111582700000043616e616c202b20e2809420466f6f7462616c6c202850617269732d5347202f204c696c6c6529711275580300000061727471137d711428580600000066616e6172747115586f00000068747470733a2f2f74656c65766973696f6e2e74656c6572616d612e66722f73697465732f74725f6d61737465722f66696c65732f73686565745f6d656469612f6d656469612f66313165343762392d636262312d343265662d383461332d6566383834393936616630392e6a7067711658050000007468756d627117586f00000068747470733a2f2f74656c65766973696f6e2e74656c6572616d612e66722f73697465732f74725f6d61737465722f66696c65732f73686565745f6d656469612f6d656469612f66313165343762392d636262312d343265662d383461332d6566383834393936616630392e6a7067711875580600000073747265616d71197d711a58050000006c6162656c711b582700000043616e616c202b20e2809420466f6f7462616c6c202850617269732d5347202f204c696c6c6529711c5806000000706172616d73711d63636f6465717569636b2e6c697374696e670a506172616d730a711e2981711f7d712055087261775f646963747121680073625807000000636f6e7465787471227d7123580a00000070726f70657274696573712463636f6465717569636b2e6c697374696e670a50726f70657274790a7125298171267d71272868217d712855095f6c6973746974656d71296378626d636775690a4c6973744974656d0a712a2981712b756258090000007375627469746c6573712c5d712d75752e]
2019-11-22 19:58:10.964 T:1593815920   FATAL: [Catch-up-TV-&-More.support] No module named urllib3
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 292, in run_callback
                                                results = route.function(parent_ins, **self.callback_params)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 367, in live_bridge
                                                item_module = importlib.import_module(kwargs.get('item_module'))
                                              File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/mycanal.py", line 43, in <module>
                                                import requests
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 43, in <module>
                                                import urllib3
                                            ImportError: No module named urllib3
2019-11-22 19:58:10.965 T:1593815920 WARNING: ###### debug ######
2019-11-22 19:58:10.965 T:1593815920 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/main/live_bridge/'
2019-11-22 19:58:10.965 T:1593815920 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{u'item_id': u'canalplus', u'item_dict': {u'info': {u'genre': u'Football', u'plot': u'19h45 - 21h40', 'title': u'Canal + \u2014 Football (Paris-SG / Lille)'}, u'art': {u'fanart': u'https://television.telerama.fr/sites/tr_master/files/sheet_media/media/f11e47b9-cbb1-42ef-84a3-ef884996af09.jpg', u'thumb': u'https://television.telerama.fr/sites/tr_master/files/sheet_media/media/f11e47b9-cbb1-42ef-84a3-ef884996af09.jpg'}, u'stream': {}, u'label': u'Canal + \u2014 Football (Paris-SG / Lille)', u'params': <class 'codequick.listing.Params'>({u'item_module': u'resources.lib.channels.fr.mycanal', '_title_': u'Canal + \u2014 Football (Paris-SG / Lille)', u'is_playable': True, u'is_folder': False, u'item_id': u'canalplus', u'item_dict': {...}}), u'context': {}, u'properties': <class 'codequick.listing.Property'>({}), u'subtitles': []}, u'item_module': u'resources.lib.channels.fr.mycanal', u'is_playable': True, u'is_folder': False}'
2019-11-22 19:58:10.965 T:1593815920 WARNING: ###### debug ######
```

**Comment by SylvainCecchetto** [comment]
Je n'arrive pas à reproduire sur ma VM LibreElec 9.0.2.
Ils en parlent ici : https://forum.kodi.tv/showthread.php?tid=324742

Peux-tu check dans `Settings --> System --> Addons (Expert view) --> Manage dependencies` que `urllib3` est bien activé ?

**Comment by wwark** [comment]
Merci pour le test. C'est un cas remonté par mail. J'ai demandé d'avoir les logs en debug.

**Comment by wwark** [comment]
Si c'est une mise à jour de request on pourrait augmenter la version de request compatible.

**Comment by SylvainCecchetto** [comment]
Pas sûr que ça change quelque chose, à l'heure actuelle la seule version de request sur les repos de Kodi est la 2.22.0 (https://mirrors.kodi.tv/addons/krypton/script.module.requests/) donc logiquement on doit tous utiliser cette version à l'heure actuelle.

**Comment by wwark** [comment]
Ok mais sur le plugin on a ça
<import addon="script.module.requests" version="2.12.4"/>
Si on le passe en 2.22.0 est-ce que ça aurait un impact sur Kodi 17 ?

**Comment by SylvainCecchetto** [comment]
Si j'avais bien compris ce qu'on m'avait expliqué sur le Slack de la Team Kodi ; augmenter la version dans notre `addon.xml` ne servirait à rien car sur le repo de Krypton il n'y a que la version 2.22.0 de requests (https://mirrors.kodi.tv/addons/krypton/script.module.requests/) ce qui signifie que les users de Kodi Krypton utilisent actuellement cette version là de requests obligatoirement. (Sauf si l'user a installé une ancienne version de Krypton et qu'il n'a jamais connecté son Kodi à Internet ... mais c'est peu probable, surtout pour utiliser notre plugin).

Je vais essayer de retrouver la discussion que j'avais eu sur le slack, mais en gros la conclusion qu'on m'avait donné c'était "Kodi utilise toujours la dernière version des scripts présents sur le repo de la version de Kodi correspondante".

**Comment by wwark** [comment]
Merci @SylvainCecchetto pour cette information.
Je vais fermer ce ticket. Il est possible que cette personne est installé un addon utilisant un requests modifié et non compatible avec les addons officiel de Kodi.
Si cette personne revient vers moi je lui demanderais d'installer Kodi à zéro et de tester.

Merci !
