### ISSUE TITLE
[Errno 111] Connection refused with France TV (France 2, France 3)

### ISSUE THREAD

**Issue by awiouy** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#254]
### Describe the bug
[Errno 111] Connection refused with France TV (France 2, France 3)

### To Reproduce
Playing France 2, France 3 with NordVPN via VPN Manager for OpenVPN produces the error
Arte and TMC play fine

### Expected behavior
France 2, France 3 should play

### Actual behavior
Errno 111

### Screenshots
N/A

### Your environment
 - Operating system version/name: LibreELEC 9.2.0 for RPi 4
 - Kodi version: 18.5
 - Catch-up TV & More version: v0.2.16~beta04
 - Installation method: beta repository

### Additional context
Using NordVPN, France, via VPN Manager for OpenVPN

### Debug log
```
2019-11-29 18:21:17.287 T:2088194928   FATAL: [Catch-up-TV-&-More.support] [Errno 111] Connection refused
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 292, in run_callback
                                                results = route.function(parent_ins, **self.callback_params)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 374, in live_bridge
                                                kwargs.get('item_dict', {}))
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/francetv.py", line 438, in live_entry
                                                return get_live_url(plugin, item_id, item_id.upper(), item_dict)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/francetv.py", line 446, in get_live_url
                                                plugin, broadcast_id % item_id.split('-')[1])
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py", line 316, in get_francetv_live_stream
                                                geoip_value = web_utils.geoip()
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/web_utils.py", line 54, in geoip
                                                resp = urlquick.get('http://ip-api.com/json', max_age=-1)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 1449, in get
                                                return session.request(u"GET", url, params=params, **kwargs)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 1043, in request
                                                raw_resp = self.make_request(req, timeout, verify, max_age)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 542, in make_request
                                                return self.connect(req, timeout, verify)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 569, in connect
                                                response = self.send_request(conn, req)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 597, in send_request
                                                raise ConnError(e)
                                            ConnError: [Errno 111] Connection refused
2019-11-29 18:21:17.287 T:2088194928 WARNING: ###### debug ######
2019-11-29 18:21:17.287 T:2088194928 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/main/live_bridge/'
2019-11-29 18:21:17.287 T:2088194928 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{u'item_id': u'france-3', u'item_dict': u'{}', u'item_module': u'resources.lib.channels.fr.francetv'}'
2019-11-29 18:21:17.287 T:2088194928 WARNING: [urlquick] Requesting resource: https://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=SIM_France3
2019-11-29 18:21:17.287 T:2088194928 WARNING: [urlquick] Request headers: {u'Host': u'sivideo.webservices.francetelevisions.fr', u'Accept-language': u'en-gb,en-us,en', u'Connection': u'keep-alive', u'Accept': u'*/*', u'Accept-Encoding': u'gzip, deflate'}
2019-11-29 18:21:17.287 T:2088194928 WARNING: [urlquick] Attempting to decode with default encoding: 'utf8'
2019-11-29 18:21:17.287 T:2088194928 WARNING: [urlquick] Requesting resource: http://ip-api.com/json
2019-11-29 18:21:17.287 T:2088194928 WARNING: [urlquick] Request headers: {u'Host': u'ip-api.com', u'Accept-language': u'en-gb,en-us,en', u'Connection': u'keep-alive', u'Accept': u'*/*', u'Accept-Encoding': u'gzip, deflate'}
2019-11-29 18:21:17.287 T:2088194928 WARNING: ###### debug ######
```

**Comment by vladc** [comment]
Hello,

ip-api.com was not refusing connections at the date and time indicated in the log. It's possible NordVPN is returning a different IP address for the domain, or perhaps you're using piHole with a list that includes the domain.
Can you run a ping to ip-api.com from a machine using the same VPN, and reply with the output?

disclaimer: working at ip-api.com

**Comment by awiouy** [comment]
Yes, I use pi-hole.
Ping seems weird indeed.
```
PING ip-api.com (0.0.0.0): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=64 time=1.154 ms
```

**Comment by vladc** [comment]
In that case you can [whitelist] the domain ip-api.com.

[whitelist]: https://discourse.pi-hole.net/t/how-do-i-whitelist-or-blacklist-a-domain/244

**Comment by awiouy** [comment]
That fixes it.
Merci.

**Comment by wwark** [comment]
Hi,
Thanks for this information.
Do you know why ip-api.com is blocked by pi-hole ?

Thanks

**Comment by vladc** [comment]
Hi wwark,

I don't know the reason. It's listed in this one (default pi-hole list):

> list.2.sysctl.org.domains (http://sysctl.org/cameleon/hosts)

We've emailed the list maintainer asking for an explanation, but we haven't received any response.
That list hasn't been updated since 2018-03-17.

**Comment by wwark** [comment]
Hi @vladc,
Thank you for the explanation.
We will add a message in the addon to explain how to add ip-api.com in the whitelist.
Wwark
