### ISSUE TITLE
Erreur RTBF Auvio (certaines émissions)

### ISSUE THREAD

**Issue by dhtek** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#267]
Bonjour,

Utilisant la dernière version de Kodi (18.5) sur OSMC (Rasperry) ou sur Windows, j'ai l'erreur suivante lorsque je souhaite revoir l'émission "La tribune" dans Football sur RTBF Auvio. 
J'ai remarqué que certaines émissions fonctionnent sans problème.

```
2019-12-27 21:10:43.049 T:13552 WARNING: ###### debug ######
2019-12-27 21:10:43.049 T:13552 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/be/rtbf/list_videos_sub_category_dl/'
2019-12-27 21:10:43.049 T:13552 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{'item_id': u'auvio', 'sub_category_data_uuid': u'widget-12378-3772', 'sub_category_id': u'widget-ml-latribune-', u'is_playable': False, u'is_folder': True}'
2019-12-27 21:10:43.049 T:13552 WARNING: [urlquick] Requesting resource: https://www.rtbf.be/news/api/block?data%5B0%5D%5Buuid%5D=widget-12378-3772&data%5B0%5D%5Btype%5D=widget&data%5B0%5D%5Bsettings%5D%5Bid%5D=12378
2019-12-27 21:10:43.049 T:13552 WARNING: [urlquick] Request headers: {u'Host': u'www.rtbf.be', u'Accept-language': u'en-gb,en-us,en', u'Connection': u'keep-alive', u'Accept': u'*/*', u'Accept-Encoding': u'gzip, deflate'}
2019-12-27 21:10:43.050 T:13552 WARNING: [urlquick] Cache is fresh, returning cached response
2019-12-27 21:10:43.050 T:13552 WARNING: ###### debug ######
2019-12-27 21:11:03.263 T:13440   ERROR: CPythonInvoker(3, C:\Users\xxx\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py): script didn't stop in 5 seconds - let's kill it
2019-12-27 21:11:03.263 T:13440   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf/list_videos_sub_category_dl/?_pickle_=80027d71002855167375625f63617465676f72795f646174615f75756964710158110000007769646765742d31323337382d33373732710255075f7469746c655f7103580a0000004c612054726962756e657104580b00000069735f706c617961626c65710589580900000069735f666f6c64657271068855076974656d5f696471075805000000617576696f7108550f7375625f63617465676f72795f6964710958140000007769646765742d6d6c2d6c6174726962756e652d710a752e
2019-12-27 21:11:03.267 T:11432   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf/list_videos_sub_category_dl/?_pickle_=80027d71002855167375625f63617465676f72795f646174615f75756964710158110000007769646765742d31323337382d33373732710255075f7469746c655f7103580a0000004c612054726962756e657104580b00000069735f706c617961626c65710589580900000069735f666f6c64657271068855076974656d5f696471075805000000617576696f7108550f7375625f63617465676f72795f6964710958140000007769646765742d6d6c2d6c6174726962756e652d710a752e) failed
2019-12-27 21:11:06.657 T:11432   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-12-27 21:11:07.902 T:12536  NOTICE: [Catch-up-TV-&-More] [cq_utils.import_needed_module] Import module resources.lib.channels.be.rtbf on the fly
2019-12-27 21:11:08.264 T:12536   FATAL: [Catch-up-TV-&-More.support] expected string or buffer
                                            Traceback (most recent call last):
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 295, in run_callback
                                                redirect = parent_ins._process_results(results)
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\route.py", line 95, in _process_results
                                                raw_listitems = validate_listitems(raw_listitems)
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\route.py", line 34, in validate_listitems
                                                raw_listitems = list(raw_listitems)
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\be\rtbf.py", line 320, in list_videos_sub_category_dl
                                                json_parser = json.loads(video_datas.get('data-card'))
                                              File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                            TypeError: expected string or buffer
2019-12-27 21:11:08.264 T:12536 WARNING: ###### debug ######
```

Merci pour votre aide et votre super extension ;)

**Comment by SylvainCecchetto** [comment]
Bonjour dhtek,

Merci beaucoup pour votre retour de bug, je viens de résoudre le problème dans le commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/5971902c2e134e7e5ee8a42d6029dabaff7d67d8, si vous utilisez notre dépôt BETA, vous pourrez profiter directement dès demain de la correction de ce bug avec la version 0.2.17~beta05 du plugin.

Je ferme ce ticket mais n'hésitez pas à l'ouvrir de nouveau si besoin ;-)
