### ISSUE TITLE
Cnews le replay ne marche plus.

### ISSUE THREAD

**Issue by gilles0606** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#269]
Bonjour,

le replay de cnews ne marche plus chez moi ?
Est ce général ?

Merci

**Comment by SylvainCecchetto** [comment]
Bonjour Gilles,

Quelle est le problème exactement ?
Sous quelle version de Kodi et de Catch-Up TV & More es-tu ?
Est-ce que tu auras un log aussi stp ?

Je n'ai pas de problème de mon coté avec Kodi Leia et la dernière version du plugin en bêta.

Merci beaucoup !

**Comment by gilles0606** [comment]
hello,

je suis sous kodi sous raspbery. Librelec  Kodi 19.0
je vais effectivement récupéré un log

**Comment by gilles0606** [comment]
Voilà :

2020-02-09 14:11:39.480 T:1531954048  NOTICE: [Catch-up-TV-&-More] [cq_utils.import_needed_module] Import module resources.lib.main on the fly
2020-02-09 14:12:34.135 T:1531954048  NOTICE: Previous line repeats 3 times.
2020-02-09 14:12:34.136 T:1531954048  NOTICE: [Catch-up-TV-&-More] [cq_utils.import_needed_module] Import module resources.lib.channels.fr.cnews on the fly
2020-02-09 14:12:43.302 T:1531954048  NOTICE: Previous line repeats 1 times.
2020-02-09 14:12:43.302 T:1531954048   FATAL: [Catch-up-TV-&-More.support] list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 292, in run_callback
                                                results = route.function(parent_ins, **self.callback_params)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/cnews.py", line 140, in get_video_url
                                                resp.text)[0]
                                            IndexError: list index out of range
2020-02-09 14:12:43.302 T:1531954048 WARNING: ###### debug ######
2020-02-09 14:12:43.302 T:1531954048 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/fr/cnews/get_video_url/'
2020-02-09 14:12:43.302 T:1531954048 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{'item_id': u'cnews', u'is_playable': True, 'video_url': u'https://www.cnews.fr/emission/2020-02-09/la-chronique-cinema-du-09022020-925565', u'is_folder': False, 'video_label': u'CNews - La chronique Cin\xe9ma du 09/02/2020'}'
2020-02-09 14:12:43.302 T:1531954048 WARNING: [urlquick] Requesting resource: https://www.cnews.fr/emission/2020-02-09/la-chronique-cinema-du-09022020-925565
2020-02-09 14:12:43.302 T:1531954048 WARNING: [urlquick] Request headers: {u'Accept-language': u'en-gb,en-us,en', u'Accept-Encoding': u'gzip, deflate', u'Host': u'www.cnews.fr', u'Accept': u'*/*', u'User-Agent': u'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36', u'Connection': u'keep-alive'}
2020-02-09 14:12:43.302 T:1531954048 WARNING: ###### debug ######

**Comment by SylvainCecchetto** [comment]
Merci pour les informations supplémentaires.

Je pense que tu utilises la version 0.2.16 du plugin non ? Dans cette version CNews ne fonctionne plus.
WWark a corrigé le problème dans ce commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/a1390b44da45c98920942cae82d0933eaa55280b.
Tu peux attendre que la version 0.2.17 soit disponible afin de bénéficier du correctif ou bien tu peux installer la version beta du plugin en suivant ce tutoriel : https://catch-up-tv-and-more.github.io/fr/installation/

Nous restons disponible si besoin.

J'en profite pour te préciser que le script YouTube-DL (que nous utilisons dans notre plugin pour certaines chaines) n'est pas entièrement fonctionnel avec Python3 (et donc avec Kodi 19), il est alors fort probable que beaucoup de vidéos ne fonctionne pas à cause de ça...
De ce coté nous ne pouvons pas faire grand chose si ce n'est d'attendre que le développer de Youtube-DL mette à jour son plugin pour Kodi 19.

**Comment by gilles0606** [comment]
Trop bête le suis, j'ai mis à jour mais pas avec la dev. JE SUIS NUL ...   !!!!!
Toutes mes excuses....2020-02-09 14:44:08.614 T:1546642304  NOTICE: [Catch-up-TV-&-More] [import_needed_module] Import module resources.lib.main on the fly
2020-02-09 14:44:11.511 T:1536160640  NOTICE: [Catch-up-TV-&-More] [import_needed_module] Import module resources.lib.channels.fr.cnews on the fly
2020-02-09 14:44:27.341 T:1536160640  NOTICE: Previous line repeats 1 times.
2020-02-09 14:44:27.341 T:1536160640  NOTICE: script.module.youtube.dl: youtube_dl core version: 2019.09.12.1
2020-02-09 14:44:27.634 T:1536160640 WARNING: addons must not activate DialogBusy
2020-02-09 14:44:28.625 T:1936779712  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/cnews/get_video_url/?_pickle_=80027d71002855076974656d5f696471015805000000636e657773710255075f7469746c655f710358220000004c61206368726f6e69717565204dc3a9646961732064752030392f30322f3230323071045509766964656f5f75726c7105584f00000068747470733a2f2f7777772e636e6577732e66722f656d697373696f6e2f323032302d30322d30392f6c612d6368726f6e697175652d6d65646961732d64752d30393032323032302d3932353537377106752e
2020-02-09 14:44:28.626 T:1495077760  NOTICE: Creating InputStream
2020-02-09 14:44:28.627 T:1495077760  NOTICE: Creating Demuxer
2020-02-09 14:44:29.515 T:1495077760  NOTICE: Opening stream: 1 source: 256
2020-02-09 14:44:29.515 T:1495077760  NOTICE: Creating video codec with codec id: 27
2020-02-09 14:44:29.531 T:1495077760  NOTICE: Creating video thread
2020-02-09 14:44:29.532 T:1546642304  NOTICE: running thread: video_thread
2020-02-09 14:44:29.816 T:1495077760  NOTICE: Opening stream: 0 source: 256
2020-02-09 14:44:29.816 T:1495077760  NOTICE: Finding audio codec for: 86018
2020-02-09 14:44:29.818 T:1495077760  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2020-02-09 14:44:29.818 T:1495077760  NOTICE: Creating audio thread
2020-02-09 14:44:29.820 T:1470612352  NOTICE: running thread: CVideoPlayerAudio::Process()
2020-02-09 14:44:30.387 T:1470612352  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)

**Comment by gilles0606** [comment]
Trop bête le suis, j'ai mis à jour mais pas avec la dev. JE SUIS NUL ... !!!!!
Toutes mes excuses....

Du coup, j'ais mis à jour ma config.
LibreELEC release: RPi2.arm-9.2.0
Starting Kodi (18.5 Git:newclock5_18.5-Leia). Platform: Linux ARM 32-bit

Tout marche NIKEL, une fois de plus Grand merci.

**Comment by SylvainCecchetto** [comment]
Aucun problème, le principal c'est que ça fonctionne 😃
