### ISSUE TITLE
Problème du navigation dans les répertoires de la chaine Arte

### ISSUE THREAD

**Issue by alexismorillo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#270]
Cette erreur survient lorsque l'on pagine dans les répertoires :
2020-02-10 21:56:22.614 T:1782989552  NOTICE: [Catch-up-TV-&-More] [cq_utils.import_needed_module] Import module resources.lib.channels.wo.arte on the fly
2020-02-10 21:56:23.550 T:1782989552   FATAL: [Catch-up-TV-&-More.support] HTTP Client Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 295, in run_callback
                                                redirect = parent_ins._process_results(results)
                                              File "/home/pi/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 95, in _process_results
                                                raw_listitems = validate_listitems(raw_listitems)
                                              File "/home/pi/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 34, in validate_listitems
                                                raw_listitems = list(raw_listitems)
                                              File "/home/pi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/wo/arte.py", line 307, in list_videos_sub_category
                                                resp = urlquick.get(sub_category_url.replace('https://api-cdn.arte.tv', 'https://www.arte.tv/guide'))
                                              File "/home/pi/.kodi/addons/script.module.codequick/lib/urlquick.py", line 1449, in get
                                                return session.request(u"GET", url, params=params, **kwargs)
                                              File "/home/pi/.kodi/addons/script.module.codequick/lib/urlquick.py", line 1071, in request
                                                resp.raise_for_status()
                                              File "/home/pi/.kodi/addons/script.module.codequick/lib/urlquick.py", line 1380, in raise_for_status
                                                raise HTTPError(self.url, self.status_code, self.reason, self.headers)
                                            HTTPError: HTTP Client Error 403: Forbidden
2020-02-10 21:56:23.550 T:1782989552 WARNING: ###### debug ######
2020-02-10 21:56:23.550 T:1782989552 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/wo/arte/list_videos_sub_category/'
2020-02-10 21:56:23.551 T:1782989552 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{'item_id': u'arte', 'sub_category_url': u'https://api-internal.arte.tv/api/emac/v3/fr/web/data/MOST_RECENT_SUBCATEGORY/?imageFormats=landscape&mainZonePage=1&authorizedAreas=DE_FR%2CEUR_DE_FR%2CSAT%2CALL&subCategoryCode=ENN&page=2&limit=10'}'
2020-02-10 21:56:23.551 T:1782989552 WARNING: [urlquick] Requesting resource: https://api-internal.arte.tv/api/emac/v3/fr/web/data/MOST_RECENT_SUBCATEGORY/?imageFormats=landscape&mainZonePage=1&authorizedAreas=DE_FR%2CEUR_DE_FR%2CSAT%2CALL&subCategoryCode=ENN&page=2&limit=10
2020-02-10 21:56:23.551 T:1782989552 WARNING: [urlquick] Request headers: {u'Host': u'api-internal.arte.tv', u'Accept-language': u'en-gb,en-us,en', u'Connection': u'keep-alive', u'Accept': u'*/*', u'Accept-Encoding': u'gzip, deflate'}
2020-02-10 21:56:23.551 T:1782989552 WARNING: ###### debug ######
2020-02-10 21:56:23.704 T:1621955312   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/channels/wo/arte/list_videos_sub_category/?_pickle_=80027d71002855076974656d5f69647101580400000061727465710255075f7469746c655f71035817000000456e7669726f6e6e656d656e74206574206e61747572657104550f5f6e65787470616765636f756e745f71054b02550f5f7570646174656c697374696e675f71068955107375625f63617465676f72795f75726c710758c500000068747470733a2f2f6170692d696e7465726e616c2e617274652e74762f6170692f656d61632f76332f66722f7765622f646174612f4d4f53545f524543454e545f53554243415445474f52592f3f696d616765466f726d6174733d6c616e647363617065266d61696e5a6f6e65506167653d3126617574686f72697a656441726561733d44455f46522532434555525f44455f4652253243534154253243414c4c2673756243617465676f7279436f64653d454e4e26706167653d32266c696d69743d31307108752e

**Comment by wwark** [comment]
Bonjour,

Vous avez eu un HTTP 403. (refusé - géolocalisation ?)
Est-ce que vous pouvez tester d'acceder au replay sur le site officiel pour vérifier si vous pouvez lire les contenus?

Merci,
Wwark

**Comment by jamb0ree** [comment]
Idem pour moi, impossible de naviguer au-delà de la première page des répertoires du replay d'Arte (je n'ai pas tout vérifié, mais au moins pour les répertoires "Séries et Fiction/Séries" et "Info et socéité/Enquêtes et reportages").
En fait, c'est lorsqu'on clique sur "Page suivante" que le message "HTTP 403. (refusé - géolocalisation ?)" apparaît (sans utilisation de VPN, donc une adresse IP en France).

La lecture des vidéos de la première page fonctionne correctement.
Les vidéos sont lisibles sans aucun problème sur le site d'Arte.

![catchuptv](https://user-images.githubusercontent.com/60649416/75094248-b859e100-5589-11ea-8437-a68286b4548d.png)

**Comment by wwark** [comment]
Bonjour @jamb0ree,
Merci pour l'information.
Nous avons pu trouver une correction.
Disponible dans la 0.2.17-beta18

**Comment by wwark** [comment]
Je ferme ce ticket à rouvrir si besoin.
Merci,
