### ISSUE TITLE
Replay issue with RTBF observed with 2.17 (but this version was working fine until last week)

### ISSUE THREAD

**Issue by eenbroleke** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#280]
### Describe the bug
The replay is not working since last update (or change on rtbf side).
There is an error when trying to access any replay.

### To Reproduce
1. select the last available news for instance
2. an error pops out

### Expected behavior
Well, the stream should begin to play "as usual" :)

### Actuel behavior
2020-03-23 20:20:13.091 T:3226428288 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-03-23 20:21:09.410 T:4059529232   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-03-23 20:21:11.663 T:3298800512  NOTICE: [Catch-up-TV-&-More] [import_needed_module] Import module resources.lib.main on the fly
2020-03-23 20:21:18.974 T:3234820992  NOTICE: Previous line repeats 4 times.
2020-03-23 20:21:18.974 T:3234820992  NOTICE: [Catch-up-TV-&-More] [import_needed_module] Import module resources.lib.channels.be.rtbf on the fly
2020-03-23 20:21:20.678 T:3318944640  NOTICE: Previous line repeats 1 times.
2020-03-23 20:21:20.679 T:3318944640   FATAL: [Catch-up-TV-&-More.support] expected string or buffer
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 295, in run_callback
                                                redirect = parent_ins._process_results(results)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 95, in _process_results
                                                raw_listitems = validate_listitems(raw_listitems)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 34, in validate_listitems
                                                raw_listitems = list(raw_listitems)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py", line 279, in list_videos_sub_category
                                                json_parser = json.loads(video_datas.get('data-card'))
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                            TypeError: expected string or buffer

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ x] Linux 

 - Operating system version/name: CoreELEC-9.2.1
 - Kodi version: 18.5
 - Catch-up TV & More version: 2.17
 - Installation method: through repo

### Additional context
Add any other context about the problem here:

### Debug log
check https://paste.kodi.tv/uyafogiqol

**Comment by eenbroleke** [comment]
does not seem linked to https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/246 as it the same kind of replay was possible in 2.16 and/or until last week.

**Comment by eenbroleke** [comment]
full size log (167k gz)
[kodi.log.gz](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/4371600/kodi.log.gz)

**Comment by wwark** [comment]
hi,
Thank you for the report of this issue.
There is some characters not well parsed ....
We will see if we can find a fixed.

Regards,

**Comment by wwark** [comment]
I found a fix.
It is available in the beta 0.2.18~beta12
Regards,

**Comment by eenbroleke** [comment]
WAF says wait for the actual release, I guess it will happen soon. Thanks for your fix and the work you 're doing, I appreciate.
