### ISSUE TITLE
Dailymotion videos broken with Youtube-DL >= 2019.11.28

### ISSUE THREAD

**Issue by pedipaco** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#289]
Bonjour,

Depuis ce matin, j'ai l'erreur "Runtime error - Impossible de résoudre l'URL" quand je sélectionne une chaîne de groupe Canal, par exemple C8.

Voici mes versions :
Kodi : 18.6
Plugin Catch UP TV & More : 0.2.18
Raspberry pi 3 B

**Comment by jlb312** [comment]
Bonjour, Hello

Le problème vient de script.module.youtube-dl ne pas mettre à jour et garder la version 19.912.1 la dernière qui fonctionne.

The problem comes from script.module.youtube-dl don't update to 2020 version keep the last working version 19.912.1

Kodi : 18.6
Catch Up Tv & More : 0.2.18
KODI Windows 10 and librelec 9.2.1
YOUTUBE-DL : 19.912.1 (last working version)

**Comment by SylvainCecchetto** [comment]
Hello !

Merci jlb312 pour l'info ! On va voir ce qu'on peut faire pour que Youtube-DL fonctionne à nouveau avec le plugin!

**Comment by wwark** [comment]
Hello,

je pense que c'est lié à ce ticket (https://github.com/willforde/script.module.codequick/issues/36)
Il faut qu'on ne passe pas pour youtube-dl pour la partie dailymotion le temps que ce soit regarder par codequick si c'est le cas.

Merci,
Wwark.

**Comment by SylvainCecchetto** [comment]
Hello wwark,
Bien vu, c'est exactement ce problème que je rencontre dans les logs en testant.
C'est donc un problème de Youtube-DL core et pas de script de ruuk si je comprends bien.
Tu sais s'il y a un ticket d'ouvert chez ytdl concernant le problème ?

**Comment by wwark** [comment]
difficile à dire ... on trappe dans codequick et pas dans ytdl.
surement que codequick ne gère plus corectement le retour de ytdl.

**Comment by SylvainCecchetto** [comment]
C'est bien un problème de Youtube-DL core (en fait on le voit bien dans le traceback, l'erreur intervient dans les fichiers `script.module.youtube.dl/lib/youtube_dl/extractor/...`.
Les gens en parlent ici aussi : https://github.com/ytdl-org/youtube-dl/issues/20673#issuecomment-584027727

**Comment by wwark** [comment]
oui je viens de reproduire ....
Il indique que ça peut impacter plusieurs extractor ...
On n'a pas le choix que de ne plus utiliser youtube-dl pour dailymotion le temps que ça soit corrigé.

Je vais fermer le ticket coté codequick

**Comment by wwark** [comment]
ça marche sur python3 mais pas python2 donc il est possible qu'il ne corrige pas ...

wark@wark-home:~/Downloads$ python3 youtube-dl https://www.dailymotion.com/video/x7ohvao
[dailymotion] Downloading Access Token
[dailymotion] x7ohvao: Downloading media JSON metadata
[dailymotion] x7ohvao: Downloading metadata JSON
[dailymotion] x7ohvao: Downloading m3u8 information
[download] Destination: Chanson douce  - l'interview de mam' et de nounou de Karin Viard-x7ohvao.mp4
[download]   1.0% of 195.08MiB at  2.02MiB/s ETA 01:35^C
ERROR: Interrupted by user
wark@wark-home:~/Downloads$ python2 youtube-dl https://www.dailymotion.com/video/x7ohvao
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "youtube-dl/__main__.py", line 19, in <module>
  File "youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "youtube-dl/youtube_dl/YoutubeDL.py", line 2019, in download
  File "youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
  File "youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "youtube-dl/youtube_dl/extractor/dailymotion.py", line 235, in _real_extract
  File "youtube-dl/youtube_dl/extractor/dailymotion.py", line 50, in _call_api
  File "youtube-dl/youtube_dl/extractor/dailymotion.py", line 31, in _get_dailymotion_cookies
  File "youtube-dl/youtube_dl/extractor/common.py", line 2831, in _get_cookies
  File "/usr/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/usr/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'

**Comment by SylvainCecchetto** [comment]
Ça semble juste être un problème de string Python2/Python3.
Je vais essayer de corriger le problème dans Youtube-DL et proposer un PR.

**Comment by wwark** [comment]
ok

**Comment by SylvainCecchetto** [comment]
Yes bonne idée ;-)
Si tu as besoin d'inspiration pour extraire l'URL de la vidéo, tu as peut être des infos ici https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/dailymotion.py ;-)

**Comment by wwark** [comment]
j'ai repris un ancien code (l'api fonctionne toujours)

https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/0d4c7b5d346e8a468406690ec473df82f652f96d

C'est fixé en beta. Testé sur live TV et replay.

Je pense qu'on peut continuer à tester et faire la release demain soir par exemple.

**Comment by SylvainCecchetto** [comment]
Voilà : https://github.com/ytdl-org/youtube-dl/pull/24776
On verra bien l'avenir que ce petit PR aura :-P

**Comment by wwark** [comment]
Ok pour faire la release ?

**Comment by SylvainCecchetto** [comment]
🚀

**Comment by wwark** [comment]
on va tester si ça prend feu je te dis !

**Comment by jlb312** [comment]
Bonsoir Marc et Sylvain,

Je viens de faire la mise à jour vers 0.2.19 sur mon RPi 4 Librelec 9.2.1 , Youtube-DL est repassé en version 2020.03.24 et je ne peux lire aucuns flux provenant de mycanal ni en direct ni en replay.

Je ne touche rien à mon install sous windows 10 pour l'instant
 
J'ai une "error creating demuxer" voir ci-dessous mon log ? Une idée merci

Voici mon une partie de mon log 

2020-04-14 22:06:37.023 T:2382349168  NOTICE: [Catch-up-TV-&-More] [import_needed_module] Import module resources.lib.main on the fly
2020-04-14 22:06:37.806 T:3011027552  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/Toutes les chaînes/pvr.iptvsimple_1683613277.pvr
2020-04-14 22:06:37.807 T:2271486832  NOTICE: Creating InputStream
2020-04-14 22:06:37.882 T:2271486832  NOTICE: Creating Demuxer
2020-04-14 22:06:37.971 T:2271486832   ERROR: OpenDemuxStream - Error creating demuxer
2020-04-14 22:06:37.971 T:2271486832  NOTICE: CVideoPlayer::OnExit()
2020-04-14 22:06:38.040 T:3011027552  NOTICE: CVideoPlayer::CloseFile()
2020-04-14 22:06:38.040 T:3011027552  NOTICE: VideoPlayer: waiting for threads to exit
2020-04-14 22:06:38.040 T:3011027552  NOTICE: VideoPlayer: finished waiting

**Comment by SylvainCecchetto** [comment]
Bonjour jlb312,
La version de Catch-Up TV & More qui règle le problème de des vidéos Dailymotion avec Youtube-DL est la version 0.2.20 que nous avons déployée hier soir sur notre dépôt (elle est en cours d'acceptation sur le dépôt officiel de Kodi).
Avec la version 0.2.20, wwark a fait en sorte de ne pas utiliser Youtube-DL pour les vidéos Dailymotion, donc aucun problème si Youtube-DL est en version 2020.03.24.

La version 0.2.20 peut être installée via notre dépôt (voir https://catch-up-tv-and-more.github.io/fr/installation/).
Sinon il faut attendre que la Team Kodi accepte la nouvelle version car pour le moment seule la version 0.2.19 est disponible sur leur dépôt ;-)

**Comment by jlb312** [comment]
Bonjour Sylvain

J'avais bien fait l'installation depuis votre repo ce matin j'ai installé le repo des beta j'ai la version 0.2.19 beta 04 donc pas de 0.2.20 je me doutais de la confusion.

Par contre évidemment en version 0.2.19 toujours error creating demux error sur toute les chaines du groupe canal de la TNT (C8, CNEWS, etc.). Le player commence et s'arrête tout de suite pas de message d'erreur. Par contre dans les log j'ai l'erreur ci-dessus.
Même comportement sur le plugin et la TV (PVR-simple-client)

J'espère que c'est pas DailyMotion qui a mis une API perso comme youtube maintenant ?

JL

**Comment by SylvainCecchetto** [comment]
Arf c'est bizarre, je viens encore de tester à l'instant et je n'ai aucun problème pour lancer C8 avec la 0.2.19.

Pouvez vous nous fournir le log mettant en évidence l'erreur en utilisant le plugin pour lancer C8 svp ?

**Comment by jlb312** [comment]
Oui le voici, C8 sur le plugin en direct

2020-04-15 11:10:11.762 T:2716689264  NOTICE: [Catch-up-TV-&-More] [import_needed_module] Import module resources.lib.main on the fly
2020-04-15 11:10:12.319 T:3011125856  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.catchuptvandmore/resources/lib/main/live_bridge/?_pickle_=80027d71002858070000006974656d5f6964710158020000006338710255075f7469746c655f7103581a000000433820e28094204c657320616e696d617578206465206c6120387104580b0000006974656d5f6d6f64756c65710558210000007265736f75726365732e6c69622e6368616e6e656c732e66722e6d7963616e616c71065808000000786d6c74765f696471075814000000433434352e6170692e74656c6572616d612e66727108752e
2020-04-15 11:10:12.390 T:2384446320  NOTICE: Creating InputStream
2020-04-15 11:10:12.458 T:2384446320  NOTICE: Creating Demuxer
2020-04-15 11:10:12.549 T:2384446320   ERROR: OpenDemuxStream - Error creating demuxer
2020-04-15 11:10:12.549 T:2384446320  NOTICE: CVideoPlayer::OnExit()
2020-04-15 11:10:12.612 T:3011125856  NOTICE: CVideoPlayer::CloseFile()
2020-04-15 11:10:12.612 T:3011125856  NOTICE: VideoPlayer: waiting for threads to exit
2020-04-15 11:10:12.613 T:3011125856  NOTICE: VideoPlayer: finished waiting
2020-04-15 11:15:05.265 T:2716689264  NOTICE: [Catch-up-TV-&-More] [import_needed_module] Import module resources.lib.main on the fly
2020-04-15 11:15:14.221 T:3011125856  NOTICE: Previous line repeats 1 times.
2020-04-15 11:15:14.221 T:3011125856  NOTICE: Quitting due to POSIX signal
2020-04-15 11:15:14.241 T:3011125856  NOTICE: Stopping player

**Comment by SylvainCecchetto** [comment]
Oups désolé, j'ai oublié de préciser, mais pouvez activer les DEBUG log dans les réglages de Kodi avant svp.

**Comment by jlb312** [comment]
Est-ce que ça vous va le fichier est beaucoup plus gros évidemment ? 

2020-04-15 11:29:12.982 T:3011560032  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.catchuptvandmore/resources/lib/main/live_bridge/?_pickle_=80027d71002858070000006974656d5f6964710158020000006338710255075f7469746c655f7103581a000000433820e28094204c657320616e696d617578206465206c6120387104580b0000006974656d5f6d6f64756c65710558210000007265736f75726365732e6c69622e6368616e6e656c732e66722e6d7963616e616c71065808000000786d6c74765f696471075814000000433434352e6170692e74656c6572616d612e66727108752e
2020-04-15 11:29:12.982 T:3011560032    INFO: easy_acquire - Created session to https://stream-01.dc3.dailymotion.com
2020-04-15 11:29:13.072 T:3011560032   DEBUG: CCurlFile::GetMimeType - https://stream-01.dc3.dailymotion.com/sec(3uHXKsK7_-J9YIYIiNPgONCuVGWpJWpb2jFmo3IHLX23TUsTlMBF5EsXCg_bVIwo)/p/dm/3/x5idx4k/d/live-4.m3u8#cell=lcore&qos_vpart=1&qos_stail=1 -> application/vnd.apple.mpegurl
2020-04-15 11:29:13.073 T:3011560032   DEBUG: CMMALRenderer::CMMALRenderer
2020-04-15 11:29:13.073 T:2286895984   DEBUG: Thread MMALProcess start, auto delete: false
2020-04-15 11:29:13.073 T:3011560032   DEBUG: OnPlayBackStarted: CApplication::OnPlayBackStarted
2020-04-15 11:29:13.073 T:2272260976   DEBUG: Thread VideoPlayer start, auto delete: false
2020-04-15 11:29:13.073 T:2286895984   DEBUG: CMMALRenderer::Run - starting
2020-04-15 11:29:13.073 T:2379215728   DEBUG: Thread BackgroundLoader start, auto delete: false
2020-04-15 11:29:13.073 T:2272260976  NOTICE: Creating InputStream
2020-04-15 11:29:13.074 T:2272260976   DEBUG: CurlFile::Open(0x876fe7b0) https://stream-01.dc3.dailymotion.com/sec(3uHXKsK7_-J9YIYIiNPgONCuVGWpJWpb2jFmo3IHLX23TUsTlMBF5EsXCg_bVIwo)/p/dm/3/x5idx4k/d/live-4.m3u8#cell=lcore&qos_vpart=1&qos_stail=1
2020-04-15 11:29:13.115 T:3011560032   DEBUG: CVideoGUIInfo::InitCurrentItem(plugin://plugin.video.catchuptvandmore/resources/lib/main/live_bridge/?_pickle_=80027d71002858070000006974656d5f6964710158020000006338710255075f7469746c655f7103581a000000433820e28094204c657320616e696d617578206465206c6120387104580b0000006974656d5f6d6f64756c65710558210000007265736f75726365732e6c69622e6368616e6e656c732e66722e6d7963616e616c71065808000000786d6c74765f696471075814000000433434352e6170692e74656c6572616d612e66727108752e)
2020-04-15 11:29:13.115 T:3011560032   DEBUG: CPlayerGUIInfo::InitCurrentItem(plugin://plugin.video.catchuptvandmore/resources/lib/main/live_bridge/?_pickle_=80027d71002858070000006974656d5f6964710158020000006338710255075f7469746c655f7103581a000000433820e28094204c657320616e696d617578206465206c6120387104580b0000006974656d5f6d6f64756c65710558210000007265736f75726365732e6c69622e6368616e6e656c732e66722e6d7963616e616c71065808000000786d6c74765f696471075814000000433434352e6170692e74656c6572616d612e66727108752e)
2020-04-15 11:29:13.123 T:2328859504   DEBUG: Loading settings for plugin://plugin.video.catchuptvandmore/resources/lib/main/live_bridge/?_pickle_=80027d71002858070000006974656d5f6964710158020000006338710255075f7469746c655f7103581a000000433820e28094204c657320616e696d617578206465206c6120387104580b0000006974656d5f6d6f64756c65710558210000007265736f75726365732e6c69622e6368616e6e656c732e66722e6d7963616e616c71065808000000786d6c74765f696471075814000000433434352e6170692e74656c6572616d612e66727108752e
2020-04-15 11:29:13.125 T:2379215728   DEBUG: Thread BackgroundLoader 2379215728 terminating
2020-04-15 11:29:13.143 T:2272260976  NOTICE: Creating Demuxer
2020-04-15 11:29:13.186 T:3011556208   DEBUG: UPnP: Building didl for object 'plugin://plugin.video.catchuptvandmore/resources/lib/main/live_bridge/?_pickle_=80027d71002858070000006974656d5f6964710158020000006338710255075f7469746c655f7103581a000000433820e28094204c657320616e696d617578206465206c6120387104580b0000006974656d5f6d6f64756c65710558210000007265736f75726365732e6c69622e6368616e6e656c732e66722e6d7963616e616c71065808000000786d6c74765f696471075814000000433434352e6170692e74656c6572616d612e66727108752e'
2020-04-15 11:29:13.190 T:2746168176   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: Info.OnChanged  - data: null
2020-04-15 11:29:13.190 T:2746168176   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: Player.OnPlay  - data: {"item":{"title":"C8 — Les animaux de la 8","type":"video"},"player":{"playerid":1,"speed":1}}
2020-04-15 11:29:13.202 T:2729382768   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender xbmc - method: Info.OnChanged  - data: null
2020-04-15 11:29:13.202 T:2729382768   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender xbmc - method: Player.OnPlay  - data: {"item":{"title":"C8 — Les animaux de la 8","type":"video"},"player":{"playerid":1,"speed":1}}
2020-04-15 11:29:13.216 T:3011560032   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-04-15 11:29:13.235 T:2272260976   DEBUG: ffmpeg[876FF370]: [https] HTTP error 403 Forbidden
2020-04-15 11:29:13.235 T:2272260976   DEBUG: Error, could not open file https://stream-01.dc3.dailymotion.com/sec(3uHXKsK7_-J9YIYIiNPgONCuVGWpJWpb2jFmo3IHLX23TUsTlMBF5EsXCg_bVIwo)/p/dm/3/x5idx4k/d/live-4.m3u8#cell=lcore&qos_vpart=1&qos_stail=1
2020-04-15 11:29:13.236 T:2272260976   ERROR: OpenDemuxStream - Error creating demuxer
2020-04-15 11:29:13.236 T:2272260976  NOTICE: CVideoPlayer::OnExit()
2020-04-15 11:29:13.236 T:2272260976   DEBUG: Thread VideoPlayer 2272260976 terminating
2020-04-15 11:29:13.278 T:2320466800   DEBUG: OnPlayBackStopped: CApplication::OnPlayBackStopped
2020-04-15 11:29:13.296 T:3011560032  NOTICE: CVideoPlayer::CloseFile()
2020-04-15 11:29:13.296 T:3011560032   DEBUG: DeleteRenderer - deleting renderer
2020-04-15 11:29:13.296 T:3011560032   DEBUG: CMMALRenderer::~CMMALRenderer
2020-04-15 11:29:13.296 T:3011560032   DEBUG: CMMALRenderer::UnInitMMAL
2020-04-15 11:29:13.296 T:2286895984   DEBUG: CMMALRenderer::Run - stopping
2020-04-15 11:29:13.297 T:2286895984   DEBUG: Thread MMALProcess 2286895984 terminating
2020-04-15 11:29:13.297 T:3011560032  NOTICE: VideoPlayer: waiting for threads to exit
2020-04-15 11:29:13.297 T:3011560032  NOTICE: VideoPlayer: finished waiting

**Comment by SylvainCecchetto** [comment]
Merci beaucoup!

La ligne `2020-04-15 11:29:13.235 T:2272260976   DEBUG: ffmpeg[876FF370]: [https] HTTP error 403 Forbidden` est intéressante et explique certainement pourquoi vous n'avez pas la vidéo.

Pourtant avec VLC j'arrive à accéder au live `https://stream-01.dc3.dailymotion.com/sec(3uHXKsK7_-J9YIYIiNPgONCuVGWpJWpb2jFmo3IHLX23TUsTlMBF5EsXCg_bVIwo)/p/dm/3/x5idx4k/d/live-4.m3u8#cell=lcore&qos_vpart=1&qos_stail=1` que je sois avec une IP française ou non.

@wwark ça te parle cette erreur 403 avec Dailymotion?

**Comment by jlb312** [comment]
Oui c'est étrange car cela marchait avant les mises à jour je suis sur libreelec 9.2.1 avec un RPi4. 

J'ai également une version kodi 18.6 qui tourne sous windows 10 avec 0.2.18 pour catch up TV & more et Youtube-DL 19.912.1 avec aucun problème.

Merci de vous occuper de mon cas qui devient singulier du coup, pas de nouvelles de pedipaco sur sur Raspberry  Pi 3B ?

**Comment by jlb312** [comment]
Je suis repassé en version 0.2.18 et Youtube-DL 19.912.1 sur mon RPi 4 et ça remarche très bien.

Pour info. Peut être la voie du PR sur ytdl de Sylvain donnera qq chose. Wait and see ?

**Comment by SylvainCecchetto** [comment]
Bon ... C'est étrange car de mon coté je suis avec Youtube-DL 20.324.0 et CUTV en 0.2.19 et ça fonctionne bien.
Si j'ai le temps cette semaine je ferrai le test sur mon Raspberry avec LibreElec pour voir si j'ai le même problème 😉

**Comment by jlb312** [comment]
OK merci

**Comment by SylvainCecchetto** [comment]
Bon, la "bonne" nouvelle c'est que j'ai réussi à reproduire votre erreur sur mon Raspberry 3 avec une installation fraiche de LE.
Je ne pense pas avoir le temps ce soir de chercher d'où vient le problème, mais au moins je le rencontre enfin 😉 
Entonnant d'ailleurs que sur mon mac ça ne se produise pas...

Je regarde tout ça dès que possible !

**Comment by SylvainCecchetto** [comment]
Bon j'ai ouvert un thread chez LibreElec... https://forum.libreelec.tv/thread/21818-m3u8-file-http-error-403-on-libreelec-but-not-with-kodi-desktop/

**Comment by jlb312** [comment]
Bonjour,
OK je suis inscrit au forum également mais je ne trouve pas votre thread, si je clique sur le lien ci-dessus j'ai le message access denied qui s'affiche, je ne suis pas autorisé à visualiser le thread.

C'est pas grave

Merci

**Comment by SylvainCecchetto** [comment]
Il n'a pas encore été "autorisé" ;-)

> This thread will remain inaccessible for others until approved by a moderator.

**Comment by jlb312** [comment]
OK

**Comment by wwark** [comment]
Bonjour,

@jlb312 tu habites dans quel pays ?

Merci,
Wwark

**Comment by SylvainCecchetto** [comment]
Hello wwark,
Pas sûr que ce soit un problème de localisation IP, de mon coté je suis en France je n'arrive pas à lancer C8 sur mon RB avec LibreElec (alors qu'avec la même version du plugin ça fonctionne sur mon Mac et c'est la même IP Orange :-/).

**Comment by jlb312** [comment]
France également

**Comment by jlb312** [comment]
FAI Free mais ça marchait avant les updates divers

**Comment by wwark** [comment]
ok il doit donc se baser sur d'autres informations pour bloquer le flux. (User agents, etc ...) ou non information ....
Je dois regarder comment fait youtube-dl pour ce cas.

**Comment by SylvainCecchetto** [comment]
J'ai aussi pensé à un blocage User-Agent (je me suis dit que peut être le FFMPEG de Libteelec n'utilise pas le même user-agent que celui de Kodi) donc j'ai ajouté l'User-Agent directement à l'URL du M3U8 juste avant que le plugin donne l'URL à Kodi.

Ça donne ça dans le fichier `resolver_proxy.py`:

````python3
[...]
    manifest = urlquick.get(url_stream, max_age=-1)
    lines = manifest.text.splitlines()
    inside_m3u8 = ''
    for k in range(0, len(lines) - 1):
        if 'RESOLUTION=' in lines[k]:
            inside_m3u8 = lines[k + 1]
    return inside_m3u8 + '|User-Agent=' + web_utils.get_random_ua()
```

Malheureusement je me prends toujours un 403 ... :-/

**Comment by wwark** [comment]
il faudrait récupérer tous les flux du fichier manifest et tester tous les flux et voir si un passe sur ton environnement.

**Comment by SylvainCecchetto** [comment]
👍  J'essaie ça dès que possible !

**Comment by wwark** [comment]
l'autre test serait de remplacer le header par celui ci "Referer: https://www.dailymotion.com/video/x5gv5rr"

x5gv5rr est le video_id qu'on doit remplacer dans le header referer.

**Comment by SylvainCecchetto** [comment]
Je viens de tester à plusieurs reprises avec youtube-dl depuis mon terminal et voici ce qu'il me retourne:

```bash
$ python -m youtube_dl https://www.dailymotion.com/video/x5gv5rr -g
https://stream-10.ix7.dailymotion.com/sec(3uHXKsK7_-J9YIYIiNPgONCuVGWpJWpb2jFmo3IHLX23TUsTlMBF5EsXCg_bVIwo)/p/dm/3/x5idx4k/d/live-4.m3u8
$ python -m youtube_dl https://www.dailymotion.com/video/x5gv5rr -g
https://stream-03.ix7.dailymotion.com/sec(3uHXKsK7_-J9YIYIiNPgONCuVGWpJWpb2jFmo3IHLX23TUsTlMBF5EsXCg_bVIwo)/p/dm/3/x5idx4k/d/live-4.m3u8
$ python -m youtube_dl https://www.dailymotion.com/video/x5gv5rr -g
https://stream-06.ix7.dailymotion.com/sec(3uHXKsK7_-J9YIYIiNPgONCuVGWpJWpb2jFmo3IHLX23TUsTlMBF5EsXCg_bVIwo)/p/dm/3/x5idx4k/d/live-4.m3u8
$ python -m youtube_dl https://www.dailymotion.com/video/x5gv5rr -g
https://stream-15.dc3.dailymotion.com/sec(3uHXKsK7_-J9YIYIiNPgONCuVGWpJWpb2jFmo3IHLX23TUsTlMBF5EsXCg_bVIwo)/p/dm/3/x5idx4k/d/live-4.m3u8
```

Alors que dans le log de job on a :

```
https://stream-01.dc3.dailymotion.com/sec(3uHXKsK7_-J9YIYIiNPgONCuVGWpJWpb2jFmo3IHLX23TUsTlMBF5EsXCg_bVIwo)/p/dm/3/x5idx4k/d/live-4.m3u8#cell=lcore&qos_vpart=1&qos_stail=1
```

Tu crois que la partie à la fin (`#cell=lcore&qos_vpart=1&qos_stail=1`) change quelque chose pour le player ?

**Comment by wwark** [comment]
on pourrait tester de spliter sur #cell et voir ce que ça donne.

**Comment by SylvainCecchetto** [comment]
Yes, j'essaie de rebrancher le RB ce soir pour tester ;-)

**Comment by wwark** [comment]
le fait de se baser sur youtube-dl permet de cacher la complexité.
Les flux videos youtube, dailymotion, vimeo il y a vraiment trop de cas différents ..

**Comment by SylvainCecchetto** [comment]
Oh yeah ça fonctionne on dirait bien. Je commit ça ;-)

**Comment by wwark** [comment]
Il vaut mieux faire une 0.2.20 pour ne pas être perdu et annuler/remplacer le PR.

**Comment by wwark** [comment]
le split '#' est à faire sur '#cell' je pense

**Comment by SylvainCecchetto** [comment]
Dac, donc demain matin:

* J'annule le PR de repo Kodi
* Je fais le split sur `#cell`
* Je release la 0.2.20 chez nous
* J'ouvre le PR sur le repo Kodi pour la 0.2.20

Tu en penses quoi ?

**Comment by wwark** [comment]
Top !

**Comment by SylvainCecchetto** [comment]
C'est tout bon ! (en fait j'ai pas attendu demain 😉)

**Comment by jlb312** [comment]
OK merci je teste la beta ou j'attends la release ?

**Comment by jlb312** [comment]
Pour l'instant la beta n'est pas sur le serveur beta donc j'attends

**Comment by SylvainCecchetto** [comment]
Soit la 0.2.20 de notre repo release. 
Soit la 0.2.20~beta02 de notre repo beta. 
C’est les mêmes 😉
Merci d’avance pour le test !

**Comment by jlb312** [comment]
OK j'attends quelles soient dispos et je teste sur mon RPi 4

**Comment by jlb312** [comment]
C'est bon pour moi avec la release 0.2.20 en tout cas pour CNEWS direct et replay (TV et plugin)

Tout n'est pas lisible en replay sur C8 mais c'était déjà le cas avant, problème de drm je crois erreur "u' unvalailable" ou un truc comme ça .

Plus de problèmes sur les directs des chaines mycanal de la TNT.

Merci @SylvainCecchetto  et @wwark ;) good job guys.

**Comment by wwark** [comment]
Merci !
Ticket fermé :+1:

**Comment by SylvainCecchetto** [comment]
Juste pour info, Youtube-DL (core) devrait maintenant fonctionner pour DailyMotion (fixé par ce commit https://github.com/ytdl-org/youtube-dl/commit/6c22cee673f59407a63b2916d8f0623a95a8ea20).
D'ici à ce que Youtube-DL (kodi) intègre la nouvelle version du core, on garde ton patch @wwark ;-)
