### ISSUE TITLE
RTL TVI replay error

### ISSUE THREAD

**Issue by eenbroleke** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#303]
### Describe the bug
An issue arises when trying to watch any replay from RTL TVI.
It was working fine a few days ago.
I'm using 2.20 verision of the plugin.

### To Reproduce
Select any replay show available.
Clearing cache as no impact.

### Expected behavior
Being able to watch a replay from RTL TVI ((Belgian channel).

### Actuel behavior
Cannot play any replay from RTL TVI.
### Your environment
- CoreELEC

 - Operating system version/name:
 - Kodi version:
 - Catch-up TV & More version:
 - Installation method:

### Additional context
2020-05-22 17:17:08.026 T:3356484480   FATAL: [Catch-up-TV-&-More.support] list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 292, in run_callback
                                                results = route.function(parent_ins, **self.callback_params)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtlplaybe.py", line 389, in get_video_url
                                                resp.text)[0]
                                            IndexError: list index out of range

### Debug log
https://paste.kodi.tv/juzefosaqi

**Comment by eenbroleke** [comment]
working fine with https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/releases/tag/v0.2.21.
