### ISSUE TITLE
[FR - L'équipe] Erreur programme 'Événements'

### ISSUE THREAD

**Issue by Napator** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#342]
Bonjour,

En voulant charger le programme "évenement" de la chaine l'équipe, je tombe toujours sur cette erreur : 

```
ERROR: [Catch-up-TV-&-More.support] Extra data: line 30 column 2 - line 31 column 2 (char 1421 - 1430)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 328, in run_callback
                                                redirect = parent_ins._process_results(results)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 95, in _process_results
                                                raw_listitems = validate_listitems(raw_listitems)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 34, in validate_listitems
                                                raw_listitems = list(raw_listitems)
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/lequipe.py", line 76, in list_videos
                                                resp = urlquick.get(program_url % page)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 1427, in get
                                                return session.request(u"GET", url, params=params, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 1021, in request
                                                raw_resp = self.make_request(req, timeout, verify, max_age)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 504, in make_request
                                                cached_resp = self.cache_check(req.method, req.url, req.data, req.headers, max_age=max_age)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 442, in cache_check
                                                self.__cache = cache = CacheHandler.from_url(url, data, max_age)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 422, in from_url
                                                return cls(uid, max_age)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 272, in __init__
                                                self.response = self._load()
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 349, in _load
                                                json_data = _json.load(stream)
                                              File "/usr/lib/python2.7/json/__init__.py", line 291, in load
                                                **kw)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
                                                raise ValueError(errmsg("Extra data", s, end, len(s)))
                                            ValueError: Extra data: line 30 column 2 - line 31 column 2 (char 1421 - 1430)
ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/lequipe/list_videos/?_pickle_=80027d71002855075f7469746c655f7101580d000000c3a976c3a96e656d656e7473207102580b00000069735f706c617961626c65710389550b70726f6772616d5f75726c7104584b000000687474703a2f2f7777772e6c6571756970652e66722f65717569706568642f6170706c69732f66696c747265732f656d697373696f6e732f6576656e656d656e74732d5f25732e6a736f6e7105580900000069735f666f6c64657271068855076974656d5f6964710758070000006c65717569706571085504706167657109580100000031710a752e
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/lequipe/list_videos/?_pickle_=80027d71002855075f7469746c655f7101580d000000c3a976c3a96e656d656e7473207102580b00000069735f706c617961626c65710389550b70726f6772616d5f75726c7104584b000000687474703a2f2f7777772e6c6571756970652e66722f65717569706568642f6170706c69732f66696c747265732f656d697373696f6e732f6576656e656d656e74732d5f25732e6a736f6e7105580900000069735f666f6c64657271068855076974656d5f6964710758070000006c65717569706571085504706167657109580100000031710a752e) failed
```

Pour les autres programmes cela semble OK.
Je n'arrive pas à comprendre de quel fichier vient l'erreur.

Merci à vous.

**Comment by wwark** [comment]
Bonjour @Napator,
C'est un problème de décodage du json contenant les informations des vidéos.
Je viens de tester je ne reproduis pas le soucis.
Est-ce que le problème est toujours présent de votre côté ?
Merci,

**Comment by Napator** [comment]
Bonjour, oui le problème existe chez moi depuis plusieurs jours, et même avec la version bêta en cours.

Pour info j'utilise osmc sur un raspberry pi.

**Comment by sy6sy2** [comment]
Hello tout le monde,

Après un bref test je ne rencontre pas non plus de problème pour accéder au dossier "événements". Peut être que tu peux essayer un "Clear cache" dans les réglages du plugin --> Advanced settings --> Clear Cache 😉

**Comment by wwark** [comment]
Merci @sy6sy2 pour ton test.
Si le problème persiste il faudrait le log complet en mode débug.
Est-ce qu'il est aussi possible de tester sur un autre Kodi pour voir si ça ne vient pas la connexion internet?

**Comment by Napator** [comment]
Bonjour,

Vider le cache a résolu le problème, merci beaucoup !
