### ISSUE TITLE
Arte episodes cannot be accessed  -> RuntimeError - No Item found

### ISSUE THREAD

**Issue by cmoulliard** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#366]
### Describe the bug

Arte episodes cannot be accessed as we got a `RuntimeError - No Item found` when we click
on a folder available under `Policier et Thriller` 

### To Reproduce
1. Click on Catch-up & More add on
2. Select Catch-Up TV
3. Select International
4. Select Arte (FR)
5. Move to `Series et Fiction` and `Policier et Thriller`
6. Click on one of the series
<img width="1792" alt="Screenshot 2020-10-08 at 18 31 54" src="https://user-images.githubusercontent.com/463790/95487426-9be1ac00-0994-11eb-87bf-f1bbe465c48f.png">

### Expected behavior
The list of the episodes of the series selected should be displayed/listed.

The episodes are available on arte.tv

![Screenshot 2020-10-08 at 18 37 03](https://user-images.githubusercontent.com/463790/95488115-71dcb980-0995-11eb-9f32-1d5290b46aeb.png)
 and they can be watched

![Screenshot 2020-10-08 at 18 37 18](https://user-images.githubusercontent.com/463790/95488102-6e493280-0995-11eb-8e30-e7ad8d87f6fc.png)

### Actuel behavior
We got the error `RuntimeError - No Item found`

Here is the stacktrace
```
2020-10-08 18:23:16.696 T:123145372835840   DEBUG: [Catch-up-TV-&-More.support] Attempting to import route: resources.lib.channels.wo.arte
2020-10-08 18:23:16.712 T:123145372835840   DEBUG: [urlquick] Cache location: /Users/cmoullia/Library/Application Support/Kodi/userdata/addon_data/plugin.video.catchuptvandmore/
2020-10-08 18:23:16.716 T:4720500160   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-10-08 18:23:16.753 T:123145372835840   DEBUG: CAddonSettings[plugin.video.catchuptvandmore]: loading setting definitions
2020-10-08 18:23:16.753 T:123145372835840   DEBUG: CAddonSettings[plugin.video.catchuptvandmore]: trying to load setting definitions from old format...
2020-10-08 18:23:16.759 T:123145372835840   DEBUG: [urlquick] Requesting resource: https://www.arte.tv/fr/videos/series-et-fictions/
2020-10-08 18:23:16.759 T:123145372835840   DEBUG: [urlquick] Request headers: {u'Host': u'www.arte.tv', u'Accept-language': u'en-gb,en-us,en', u'Connection': u'keep-alive', u'Accept': u'*/*', u'Accept-Encoding': u'gzip, deflate'}
2020-10-08 18:23:16.761 T:123145372835840   DEBUG: [urlquick] Cache is fresh, returning cached response
2020-10-08 18:23:16.836 T:123145372835840   DEBUG: [Catch-up-TV-&-More.route] Content-type: files
2020-10-08 18:23:16.837 T:123145372835840   DEBUG: [Catch-up-TV-&-More.support] Route Execution Time: 81ms
2020-10-08 18:23:16.837 T:123145372835840    INFO: CPythonInvoker(16, /Users/cmoullia/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2020-10-08 18:23:16.837 T:123145372835840   DEBUG: onExecutionDone(16, /Users/cmoullia/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore/addon.py)
2020-10-08 18:23:16.837 T:123145371226112   DEBUG: Thread waiting 123145371226112 terminating
2020-10-08 18:23:16.848 T:4720500160   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-10-08 18:23:16.852 T:123145371226112   DEBUG: Thread BackgroundLoader start, auto delete: false
2020-10-08 18:23:16.853 T:123145372835840    INFO: Python interpreter stopped
2020-10-08 18:23:16.853 T:123145372835840   DEBUG: Thread LanguageInvoker 123145372835840 terminating
2020-10-08 18:23:16.857 T:123145371226112   DEBUG: Thread BackgroundLoader 123145371226112 terminating
2020-10-08 18:23:22.993 T:4720500160   DEBUG: ProcessMouse: trying mouse action leftclick
2020-10-08 18:23:22.994 T:4720500160   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.catchuptvandmore/resources/lib/channels/wo/arte/list_videos_program/?_pickle_=80027d71012855076974656d5f69647102580400000061727465710355075f7469746c655f71045824000000224b69646e617070696e6722206176656320436861726c6f7474652052616d706c696e6755167375625f63617465676f72795f636f64655f6e616d657105582400000036346137663932352d313566622d346632622d396134322d6530393131643961353964387106550a70726f6772616d5f69647107580900000052432d303139383930752e)
2020-10-08 18:23:22.994 T:4720500160   DEBUG:   ParentPath = [plugin://plugin.video.catchuptvandmore/resources/lib/channels/wo/arte/list_programs/?_pickle_=80027d71012855076974656d5f69647102580400000061727465710355075f7469746c655f71045814000000506f6c696369657220657420746872696c6c657255167375625f63617465676f72795f636f64655f6e616d657105582400000036346137663932352d313566622d346632622d396134322d65303931316439613539643855107375625f63617465676f72795f75726c7106583100000068747470733a2f2f7777772e617274652e74762f66722f766964656f732f7365726965732d65742d66696374696f6e732f7107752e]
2020-10-08 18:23:22.995 T:123145371226112   DEBUG: Thread waiting start, auto delete: false
2020-10-08 18:23:22.996 T:123145371762688   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.catchuptvandmore] took 1 ms
2020-10-08 18:23:22.997 T:123145371226112   DEBUG: StartScript - calling plugin Catch-up TV & More('plugin://plugin.video.catchuptvandmore/resources/lib/channels/wo/arte/list_videos_program/','16','?_pickle_=80027d71012855076974656d5f69647102580400000061727465710355075f7469746c655f71045824000000224b69646e617070696e6722206176656320436861726c6f7474652052616d706c696e6755167375625f63617465676f72795f636f64655f6e616d657105582400000036346137663932352d313566622d346632622d396134322d6530393131643961353964387106550a70726f6772616d5f69647107580900000052432d303139383930752e','resume:false')
2020-10-08 18:23:22.997 T:123145372835840   DEBUG: Thread LanguageInvoker start, auto delete: false
2020-10-08 18:23:22.997 T:123145372835840    INFO: initializing python engine.
2020-10-08 18:23:22.997 T:123145372835840   DEBUG: CPythonInvoker(17, /Users/cmoullia/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore/addon.py): start processing
2020-10-08 18:23:23.013 T:123145372835840   DEBUG: -->Python Interpreter Initialized<--
2020-10-08 18:23:23.013 T:123145372835840   DEBUG: CPythonInvoker(17, /Users/cmoullia/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore/addon.py): the source file to load is "/Users/cmoullia/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore/addon.py"
2020-10-08 18:23:23.015 T:123145372835840   DEBUG: CPythonInvoker(17, /Users/cmoullia/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore/addon.py): setting the Python path to /Users/cmoullia/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.addon.signals/lib:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.certifi/lib:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.chardet/lib:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.codequick/lib:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.future/libs:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.htmlement/lib:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.idna/lib:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.inputstreamhelper/lib:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.kodi-six/libs:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.pyqrcode/lib:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.pytz/lib:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.requests/lib:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.six/lib:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.tzlocal/lib:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.urllib3/lib:/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.youtube.dl/lib:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/site-packages/Pillow-3.0.0-py2.7-macosx-10.14-x86_64.egg:/Applications/Kodi.app/Contents/Libraries:/Applications/Kodi.app/Contents/Libraries/lib/python27.zip:/Applications/Kodi.app/Contents/Libraries/lib/python2.7:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/site-packages:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/plat-darwin:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/plat-mac:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/plat-mac/lib-scriptpackages:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/lib-tk:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/lib-old:/Applications/Kodi.app/Contents/Libraries/lib/python2.7/lib-dynload
2020-10-08 18:23:23.015 T:123145372835840   DEBUG: CPythonInvoker(17, /Users/cmoullia/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore/addon.py): entering source directory /Users/cmoullia/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore
2020-10-08 18:23:23.015 T:123145372835840   DEBUG: CPythonInvoker(17, /Users/cmoullia/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore/addon.py): instantiating addon using automatically obtained id of "plugin.video.catchuptvandmore" dependent on version 2.25.0 of the xbmc.python api
2020-10-08 18:23:23.078 T:123145372835840   DEBUG: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/wo/arte/list_videos_program/'
2020-10-08 18:23:23.078 T:123145372835840   DEBUG: [Catch-up-TV-&-More.support] Callback parameters: '{'item_id': u'arte', 'sub_category_code_name': u'64a7f925-15fb-4f2b-9a42-e0911d9a59d8', 'program_id': u'RC-019890'}'
2020-10-08 18:23:23.078 T:123145372835840   DEBUG: [Catch-up-TV-&-More.support] Attempting to import route: resources.lib.channels.wo.arte
2020-10-08 18:23:23.095 T:123145372835840   DEBUG: [urlquick] Cache location: /Users/cmoullia/Library/Application Support/Kodi/userdata/addon_data/plugin.video.catchuptvandmore/
2020-10-08 18:23:23.096 T:4720500160   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-10-08 18:23:23.139 T:123145372835840   DEBUG: CAddonSettings[plugin.video.catchuptvandmore]: loading setting definitions
2020-10-08 18:23:23.139 T:123145372835840   DEBUG: CAddonSettings[plugin.video.catchuptvandmore]: trying to load setting definitions from old format...
2020-10-08 18:23:23.145 T:123145372835840   DEBUG: [urlquick] Requesting resource: http://www.arte.tv/hbbtvv2/services/web/index.php/OPA/v3/videos/collection/64A7F925-15FB-4F2B-9A42-E0911D9A59D8/RC-019890/fr
2020-10-08 18:23:23.145 T:123145372835840   DEBUG: [urlquick] Request headers: {u'Host': u'www.arte.tv', u'Accept-language': u'en-gb,en-us,en', u'Connection': u'keep-alive', u'Accept': u'*/*', u'Accept-Encoding': u'gzip, deflate'}
2020-10-08 18:23:23.145 T:123145372835840   DEBUG: [urlquick] Cache is fresh, returning cached response
2020-10-08 18:23:23.146 T:123145372835840   DEBUG: [urlquick] Attempting to decode with default encoding: 'utf8'
2020-10-08 18:23:23.146 T:123145372835840   ERROR: [Catch-up-TV-&-More.support] No items found
                                            Traceback (most recent call last):
                                              File "/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/support.py", line 328, in run_callback
                                                redirect = parent_ins._process_results(results)
                                              File "/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/route.py", line 95, in _process_results
                                                raw_listitems = validate_listitems(raw_listitems)
                                              File "/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/route.py", line 48, in validate_listitems
                                                raise RuntimeError("No items found")
                                            RuntimeError: No items found
2020-10-08 18:23:23.147 T:123145372835840    INFO: CPythonInvoker(17, /Users/cmoullia/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2020-10-08 18:23:23.147 T:123145372835840   DEBUG: onExecutionDone(17, /Users/cmoullia/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmore/addon.py)
2020-10-08 18:23:23.151 T:4720500160   DEBUG: ------ Window Init (DialogNotification.xml) ------
2020-10-08 18:23:23.163 T:123145372835840    INFO: Python interpreter stopped
2020-10-08 18:23:23.163 T:123145372835840   DEBUG: Thread LanguageInvoker 123145372835840 terminating
2020-10-08 18:23:23.183 T:123145371226112   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/channels/wo/arte/list_videos_program/?_pickle_=80027d71012855076974656d5f69647102580400000061727465710355075f7469746c655f71045824000000224b69646e617070696e6722206176656320436861726c6f7474652052616d706c696e6755167375625f63617465676f72795f636f64655f6e616d657105582400000036346137663932352d313566622d346632622d396134322d6530393131643961353964387106550a70726f6772616d5f69647107580900000052432d303139383930752e
2020-10-08 18:23:23.183 T:123145371226112   DEBUG: Thread waiting 123145371226112 terminating
```

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: MacOS
 - Kodi version: 18.8
 - Catch-up TV & More version: 0.2.7-Beta05

### Additional information

Here is the response that we got using the HTTP request executed within the python script which confirms that we dont receive a list as the array of the videos is empty `    "videos": []`
```
http http://www.arte.tv/hbbtvv2/services/web/index.php/OPA/v3/videos/collection/64A7F925-15FB-4F2B-9A42-E0911D9A59D8/RC-019890/fr
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Cache-Control: public, max-age=289, s-maxage=300
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 206
Content-Type: application/json
Date: Thu, 08 Oct 2020 16:55:08 GMT
Server: nginx
Vary: Accept-Encoding

{
    "meta": {
        "category": {
            "code": "SER",
            "name": "Séries et fictions",
            "order": 3,
            "slug": "series-et-fictions",
            "url": "https://www.arte.tv/fr/videos/series-et-fictions/"
        },
        "page": 1,
        "pages": 1,
        "programId": "RC-019890",
        "title": "Kidnapping",
        "totalCount": 0
    },
    "videos": []
}
```

**Comment by wwark** [comment]
Hello @cmoulliard,

Thank you for all those informations.
I reproduce the issue.

**Comment by wwark** [comment]
It is fixed on this version "0.2.27~beta06" of the plugin.

**Comment by cmoulliard** [comment]
> It is fixed on this version "0.2.27~beta06" of the plugin.

How can I download `0.2.27~beta06` to test it ?

**Comment by cmoulliard** [comment]
I applied the patch manually and the problem is fixed as I can access the list of the episodes :-) 

Nevertheless, there is still an issue as all the episodes of all the seasons are listed when we select one of the season 

Example :

- When we click on the link of the series `The Killing` 

<img width="1792" alt="Screenshot 2020-10-08 at 21 26 41" src="https://user-images.githubusercontent.com/463790/95504908-b96f3f80-09ad-11eb-9dd8-5b9e616dcc04.png">

- The screen is refreshed and will display the 3 seasons `The killing - Saison 1|2|3`

<img width="1792" alt="Screenshot 2020-10-08 at 21 26 37" src="https://user-images.githubusercontent.com/463790/95504993-dd328580-09ad-11eb-8180-0b0a0652cb41.png">

- And If I click on the season `1` then **all** the episodes of the `3` seasons are displayed

<img width="1792" alt="Screenshot 2020-10-08 at 21 26 56" src="https://user-images.githubusercontent.com/463790/95505097-1539c880-09ae-11eb-8dc6-1f526fc6466f.png">
<img width="1792" alt="Screenshot 2020-10-08 at 21 38 33" src="https://user-images.githubusercontent.com/463790/95505484-ae68df00-09ae-11eb-989a-78695c7810da.png">

**Comment by cmoulliard** [comment]
I think maybe that the problem is because the following field `code/name` is not searched
```
          {
            "id": "kidnapping_f71c6",
            "code": {
              "name": "collection_subcollection",
              "id": "RC-019890_RC-019891"
            },
            "title": "Kidnapping",
            "description":
```
but instead within the code `if 'subcategory' in sub_category_datas['code']['name']:` at line 119

Here is an example of output
```
          {
            "id": "kidnapping_f71c6",
            "code": {
              "name": "collection_subcollection",
              "id": "RC-019890_RC-019891"
            },
            "title": "Kidnapping",
            "description": "Un policier danois et une enquêtrice française s’unissent pour démanteler un trafic d’enfants.",
            "displayOptions": {
              "zoneLayout": "horizontal",
              "itemTemplate": "landscape",
              "theme": null,
              "showZoneTitle": true,
              "showItemTitle": true
            },
            "link": null,
            "pageNumber": 1,
            "nextPage": null,
            "data": [
              {
                "title": "Kidnapping (1\u002F8)",
                "id": "083867-001-A_fr",
                "type": "teaser",
                "kind": {
                  "code": "SHOW",
                  "label": "Programme",
                  "isCollection": false
                },
                "programId": "083867-001-A",
                "url": "https:\u002F\u002Fwww.arte.tv\u002Ffr\u002Fvideos\u002F083867-001-A\u002Fkidnapping-1-8\u002F",
                "deeplink": "arte:\u002F\u002Fprogram\u002F083867-001-A",
                "subtitle": null,
                "teaserText": "Le combat d’un policier danois pour démanteler un réseau de trafiquants d’enfants et retrouver sa fille.",
                "shortDescription": "Le combat d’un policier danois pour démanteler un réseau de trafiquants d’enfants et retrouver sa fille. Avec Anders W. Berthelsen et l'impériale Charlotte Rampling, une série tourmentée et addictive qui porte sur l’Europe un regard lucide.",
                "images": {
                  "landscape": {
                    "caption": " ",
                    "resolutions": [
                      {
                        "url": "https:\u002F\u002Fapi-cdn.arte.tv\u002Fapi\u002Fmami\u002Fv1\u002Fprogram\u002Ffr\u002F083867-001-A\u002F200x113",
                        "w": 200,
                        "h": 113
                      },
                      {
                        "url": "https:\u002F\u002Fapi-cdn.arte.tv\u002Fapi\u002Fmami\u002Fv1\u002Fprogram\u002Ffr\u002F083867-001-A\u002F400x225",
                        "w": 400,
                        "h": 225
                      },
                      {
                        "url": "https:\u002F\u002Fapi-cdn.arte.tv\u002Fapi\u002Fmami\u002Fv1\u002Fprogram\u002Ffr\u002F083867-001-A\u002F720x406",
                        "w": 720,
                        "h": 406
                      },
                      {
                        "url": "https:\u002F\u002Fapi-cdn.arte.tv\u002Fapi\u002Fmami\u002Fv1\u002Fprogram\u002Ffr\u002F083867-001-A\u002F940x530",
                        "w": 940,
                        "h": 530
                      },
                      {
                        "url": "https:\u002F\u002Fapi-cdn.arte.tv\u002Fapi\u002Fmami\u002Fv1\u002Fprogram\u002Ffr\u002F083867-001-A\u002F1920x1080",
                        "w": 1920,
                        "h": 1080
                      }
                    ],
                    "blurUrl": "https:\u002F\u002Fapi-cdn.arte.tv\u002Fapi\u002Fmami\u002Fv1\u002Fprogram\u002Ffr\u002F083867-001-A\u002F80x45?blur=true"
                  },
                  "banner": null,
                  "square": null,
                  "portrait": null
                },
                "stickers": [
                  {
                    "code": "PLAYABLE",
                    "label": "PLAYABLE"
                  },
                  {
                    "code": "FULL_VIDEO",
                    "label": "Voir le programme"
                  }
                ],
                "duration": 2332,
                "childrenCount": null,
                "geoblocking": {
                  "code": "EUR_DE_FR",
                  "label": ""
                },
                "availability": {
                  "type": "VOD",
                  "start": "2020-09-24T03:00:00Z",
                  "end": "2020-11-07T04:00:00Z",
                  "upcomingDate": "2020-09-24T03:00:00Z",
                  "label": "Disponible du 24\u002F09\u002F2020 au 06\u002F11\u002F2020"
                },
                "ageRating": 0,
                "trackingPixel": "https:\u002F\u002Fwww.arte.tv\u002Fct\u002F?language=fr&pageid=RC-019890&support=web&zonename=Kidnapping&zoneid=collection_subcollection&position=1&teaserid=083867-001-A_fr&teasertitle=Kidnapping%20(1%2F8)&em=083867-001-A"
              },
```

**Comment by wwark** [comment]
It is the line 115 used "'collection_subcollection' in sub_category_datas['code']['name']:" in this case.
I will check this tomorrow or this week-end.
Thanks for your tests !

**Comment by cmoulliard** [comment]
I have discovered another problem with the category `Emissions`. Do you prefer that we continue to use this ticket to fix the problems or another one ?

**Comment by wwark** [comment]
We can used the same ticket.
Thanks !

**Comment by cmoulliard** [comment]
We got also the error `No items found` when we select : 

1. Click on Catch-up & More add on
2. Select Catch-Up TV
3. Select International
4. Select Arte (FR)
5. Select Series et Fiction 
6. Select Emissions


```
2020-10-10 15:47:05.874 T:123145571700736   DEBUG: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/wo/arte/list_programs/'
2020-10-10 15:47:05.875 T:123145571700736   DEBUG: [Catch-up-TV-&-More.support] Callback parameters: '{'item_id': u'arte', 'sub_category_code_name': u'magazines', 'sub_category_url': u'https://www.arte.tv/fr/videos/series-et-fictions/'}'
2020-10-10 15:47:05.875 T:123145571700736   DEBUG: [urlquick] Requesting resource: https://www.arte.tv/fr/videos/series-et-fictions/
2020-10-10 15:47:05.875 T:123145571700736   DEBUG: [urlquick] Request headers: {u'Host': u'www.arte.tv', u'Accept-language': u'en-gb,en-us,en', u'Connection': u'keep-alive', u'Accept': u'*/*', u'Accept-Encoding': u'gzip, deflate'}
2020-10-10 15:47:05.877 T:123145571700736   DEBUG: [urlquick] Cache is fresh, returning cached response
2020-10-10 15:47:05.907 T:123145571700736   ERROR: [Catch-up-TV-&-More.support] No items found
                                            Traceback (most recent call last):
                                              File "/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/support.py", line 328, in run_callback
                                                redirect = parent_ins._process_results(results)
                                              File "/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/route.py", line 95, in _process_results
                                                raw_listitems = validate_listitems(raw_listitems)
                                              File "/Users/cmoullia/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/route.py", line 48, in validate_listitems
                                                raise RuntimeError("No items found")
                                            RuntimeError: No items found
```

**Comment by wwark** [comment]
I think this one is normal.
On the website https://www.arte.tv/fr/videos/series-et-fictions/, i didn't find emissions.

**Comment by cmoulliard** [comment]
> I think this one is normal.
> On the website https://www.arte.tv/fr/videos/series-et-fictions/, i didn't find emissions.

I agree with you but then why is `Emissions` displayed as part of the list under catchup ?

**Comment by wwark** [comment]
It is proposed by the Arte API like other sections and we don't know if the Emissions have contents or not in the API.

**Comment by cmoulliard** [comment]
> It is proposed by the Arte API

Do you have the link where I could have a look to the Arte TV API ?

**Comment by cmoulliard** [comment]
> we don't know if the Emissions have contents or not in this call.

We could perhaps check the HTTP Reponse received and remove from the list an item if it is empty. WDYT @wwark  ?

**Comment by wwark** [comment]
To add more calls will slow down the plugin and be noticeable for low end device. It means also more codes and calls so increase issues to happen.

The link is "https://www.arte.tv/fr/videos/series-et-fictions/".
You need to search the pattern "_INITIAL_STATE__" and get the json after that pattern until "};". You could find the emissions in this json.

**Comment by wwark** [comment]
For the other case some rewrite needs to be done.

**Comment by wwark** [comment]
I found also we don't have all videos for TV Shows and Emissions ....

**Comment by cmoulliard** [comment]
> To add more calls will slow down the plugin and be noticeable for low end device. It means also more codes and calls so increase issues to happen.

I agree with you here :-)

**Comment by cmoulliard** [comment]
> You need to search the pattern "_INITIAL_STATE__" and get the json after that pattern until "};". You could find the emissions in this json.

There is an emission but the data array is empty
```
     {
        "id": "emissions_275eb",
        "code": {
          "name": "magazines",
          "id": "SER"
        },
        "title": "Émissions",
        "description": null,
        "displayOptions": {
          "zoneLayout": "horizontal",
          "itemTemplate": "landscape",
          "theme": "cyan",
          "showZoneTitle": true,
          "showItemTitle": true
        },
        "link": {
          "page": null,
          "title": null,
          "url": null,
          "deeplink": null
        },
        "pageNumber": 1,
        "nextPage": null,
        "data": []
      }
```
full json is available here: https://gist.github.com/cmoulliard/0bae1320dc0da3daddf79a9f39722bdd#file-gistfile1-txt-L6867-L6890

**Comment by wwark** [comment]
Grâce au travail de @jmzambon (Merci :+1: ) : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/a18e849c68a7c3dd6b038f91b16d606ed78b4394

On va pouvoir fermer ce ticket je pense.

**Comment by wwark** [comment]
Ticket fermé à rouvrir si besoin.
