### ISSUE TITLE
DPlay : JSON Decode Error

### ISSUE THREAD

**Issue by berkhornet** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#384]
### Describe the bug
I've now tried every option within the DPlay section of CUTV, and get a JSON Decode error on each one.

### To Reproduce
1. Open CUTV
2. Select Dplay
3. Select any option
4.

### Expected behavior
The next level menu should appear

### Actuel behavior
Error message "This selection triggered an unexpected error ......" is displayed.

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: Kodi 19 Alpha 3
 - Catch-up TV & More version: 0.2.28 beta 4
 - Installation method: Manual

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

An example from the debug log is here:

2020-11-16 14:31:43.699 T:16020 ERROR : [Catch-up-TV-&-More.support] Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
File "C:\Users\mickr\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 328, in run_callback
redirect = parent_ins._process_results(results)
File "C:\Users\mickr\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\route.py", line 95, in process_results
raw_listitems = validate_listitems(raw_listitems)
File "C:\Users\mickr\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\route.py", line 34, in validate_listitems
raw_listitems = list(raw_listitems)
File "C:\Users\mickr\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\uk\dplay.py", line 132, in list_programs_mode
json_parser = json.loads(resp.text)
File "C:\Program Files\Kodi\system\python\Lib\json_init.py", line 357, in loads
return _default_decoder.decode(s)
File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Many thanks in advance for your help.

**Comment by wwark** [comment]
Hi,

Thanks for report the issue.
DPLay becomes Decovery+.
We need to update the Catchup TV and maybe Live TV.

Thanks,

**Comment by berkhornet** [comment]
Many thanks for your reply.

Regards Mick

________________________________

**Comment by naszdom** [comment]
I have now got the same problem, although it was working a month ago.

"This selection triggered an unexpected error..."  on anything you try to play on UKTVnow or even TV (France)

Kodi19.1  /Shield TV

[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/6924691/kodi.log)
