### ISSUE TITLE
TFX erreur 404, version 0.2.28

### ISSUE THREAD

**Issue by theoden11** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#412]
Bonjour.
Déjà sous la version 0.2.27 j'avais remarqué que la chaîne TFX (en Live TV) renvoyait immédiatement une étrange boîte de dialogue HTTP 404, tant sous Windows 10 avec Kodi que sous OSMC sur Raspberry Pi. Cette erreur continue avec la version 0.2.28 et ne concerne que TFX. Aucune autre erreur pour l'instant avec aucune autre chaîne TV TNT. Ci-après les traces sous Windows. 

kodi.log
2021-01-28 08:29:05.284 T:14212   ERROR: [Catch-up-TV-&-More.support] HTTP Client Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "C:\Users\*****\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 325, in run_callback
                                                results = route.function(parent_ins, *arg_params, **self.callback_params)
                                              File "C:\Users\*****\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\fr\mytf1.py", line 339, in get_live_url
                                                max_age=-1)
                                              File "C:\Users\*****\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 1427, in get
                                                return session.request(u"GET", url, params=params, **kwargs)
                                              File "C:\Users\*****\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 1049, in request
                                                resp.raise_for_status()
                                              File "C:\Users\*****\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 1358, in raise_for_status
                                                raise HTTPError(self.url, self.status_code, self.reason, self.headers)
                                            HTTPError: HTTP Client Error 404: Not Found

**Comment by wwark** [comment]
Bonjour @theoden11,

Ce problème est déjà suivi dans ce ticket avec un fix.
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/407

Merci,
Wwark

**Comment by theoden11** [comment]
Bonjour Marc.
Désolé, bien que j'avais pourtant regardé les issues auparavant, j'ai zappé
le rapprochement avec mon bug remarqué qui n'affectait qu'une seule chaine.
Merci pour le fix.

Cordialement, SVL

**Comment by wwark** [comment]
Je viens de changer le titre de l'autre issue pour que ce soit plus parlant !
La release devrait avoir lieu ce week end.
On vérifie que le code est stable.
Marc.

**Comment by theoden11** [comment]
Pas de souci, je voulais juste remonter un incident constaté, bien que moi
je regarde peu la TV ! Merci pour tout.

Cordialement, SVL
