### ISSUE TITLE
Plugin seems not working with a second profile

### ISSUE THREAD

**Issue by ptit-nico** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#43]
Bonjour et bonne année ! :)

Je me permets de poster en français car j'ai vu que certains l'avaient déjà fait (si besoin je peux écrire en anglais).

Tout d'abord merci pour ce plugin et le tout le travail autour.
Cependant il me semble que j'ai découvert un petit bug, car j'ai réussi à le reproduire deux fois.

Environnement : 
Rapberry 3
LibreELEC à jour 8.2.2
Kodi version 17.6
Plugin installé depuis le dépôt officiel donc version : 0.1.4

Lorsque j'installe le plugin tout fonctionne bien.
Puis lorsque je créé un profil supplémentaire pour les enfants (je choisi mode "séparé" pour les plugins et les sources)
Une fois logué avec le profil enfant j'active le plugin Catch-up (c'est le fonctionnement normal pour les plugin en multi-compte) et lorsque je le lance rien ne se passe et il y a un message d'erreur.

Dans les logs j'ai cru comprendre qu'il ne trouvait pas le chemin (ce qui peut paraitre logique car un profil secondaire se range dans un emplacement différent (demandé à la création du profil).

Les logs :
À 11h54,52 je me suis délogué du compte Master pour me loguer sur le compte enfant

```
11:41:34.075 T:1945473024  NOTICE: starting zeroconf publishing
11:41:34.076 T:1945473024  NOTICE: CWebServer[8080]: Started
11:41:34.076 T:1945473024  NOTICE: starting upnp client
11:41:35.626 T:1945473024  NOTICE: ADDONS: Using repository repository.kodi.game
11:41:35.626 T:1945473024  NOTICE: ADDONS: Using repository repository.libreelec.tv
11:41:35.626 T:1945473024  NOTICE: ADDONS: Using repository repository.xbmc.org
11:41:35.946 T:1945473024 WARNING: Cleanup: Having to cleanup texture button_middle_focus.png
11:41:35.946 T:1945473024 WARNING: Cleanup: Having to cleanup texture button_middle3.png
11:41:36.107 T:1604318112  NOTICE: script.grab.fanart: Grab Fanart Service Started
11:41:42.995 T:1945473024   ERROR: Window Translator: Can't find window games
11:53:26.366 T:1537205152   ERROR: GetDirectory - Error getting
11:53:30.415 T:1694176160   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/
11:53:37.916 T:1945473024   ERROR: Control 57 in window 10025 has been asked to focus, but it can't
11:53:45.572 T:1518334880  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.12.31
11:53:45.648 T:1518334880   ERROR: /storage/.kodi/addons/script.module.youtube.dl/lib/YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
11:53:45.654 T:1518334880 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
11:53:55.051 T:1518334880  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.12.31
11:53:55.089 T:1518334880   ERROR: /storage/.kodi/addons/script.module.youtube.dl/lib/YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
11:53:55.128 T:1518334880 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
11:54:02.891 T:1484780448  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.12.31
11:54:02.936 T:1484780448   ERROR: /storage/.kodi/addons/script.module.youtube.dl/lib/YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
11:54:02.942 T:1484780448 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
11:54:19.089 T:1945473024   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/?action=list_channels&category_id=main_menu.fr&window_title=Cha%c3%aenes%20fran%c3%a7aises
11:54:25.362 T:1945473024   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/?action=list_channels&category_id=main_menu.fr&window_title=Cha%c3%aenes%20fran%c3%a7aises) failed
11:54:27.026 T:1945473024   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/
11:54:27.027 T:1945473024   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/) failed
11:54:38.574 T:1484780448  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.12.31
11:54:38.731 T:1484780448   ERROR: /storage/.kodi/addons/script.module.youtube.dl/lib/YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
11:54:39.870 T:1465906080  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.12.31
11:54:41.368 T:1465906080  NOTICE: Previous line repeats 1 times.
11:54:41.368 T:1465906080   ERROR: /storage/.kodi/addons/script.module.youtube.dl/lib/YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
11:54:41.408 T:1484780448 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
11:54:41.506 T:1474294688   ERROR: /storage/.kodi/addons/script.module.youtube.dl/lib/YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
11:54:41.700 T:1474294688 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
11:54:41.721 T:1465906080   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory', u'/storage/.kodi/userdata/addon_data/plugin.video.catchuptvandmore/__gettext__.pcl.tmp')
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 49, in <module>
                                                _ = common.ADDON.initialize_gettext()
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 765, in initialize_gettext
                                                self._ui_strings_map = deepcopy(ui_strings_map)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 184, in __exit__
                                                self.flush()
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 224, in flush
                                                move(tmp, self._filename)  # Atomic save
                                              File "/usr/lib/python2.7/shutil.py", line 302, in move
                                              File "/usr/lib/python2.7/shutil.py", line 130, in copy2
                                              File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
                                            IOError: (2, 'No such file or directory', u'/storage/.kodi/userdata/addon_data/plugin.video.catchuptvandmore/__gettext__.pcl.tmp')
                                            -->End of Python script error report<--
11:54:41.973 T:1945473024   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/
11:54:41.974 T:1945473024   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/) failed
11:54:43.711 T:1694176160   ERROR: Unable to find plugin
11:54:43.711 T:1945473024   ERROR: GetDirectory - Error getting plugin://
11:54:43.712 T:1945473024   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
11:54:52.104 T:1945473024  NOTICE: ES: Stopping event server
11:54:52.451 T:1727730592  NOTICE: ES: UDP Event server stopped
11:54:52.836 T:1945473024  NOTICE: stopping upnp
11:54:52.987 T:1945473024  NOTICE: stopping zeroconf publishing
11:54:52.996 T:1945473024  NOTICE: CWebServer[8080]: Stopped
11:54:53.100 T:1710953376  NOTICE: ES: Starting UDP Event server on port 9777
11:54:53.100 T:1710953376  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
11:54:54.622 T:1945473024  NOTICE: ES: Stopping event server
11:54:55.102 T:1710953376  NOTICE: ES: UDP Event server stopped
11:54:55.105 T:1945473024  NOTICE: special://profile/ is mapped to: special://masterprofile/profiles/Noé/
11:54:55.127 T:1945473024  NOTICE: Loaded settings file from special://xbmc/system/advancedsettings.xml
11:54:55.127 T:1945473024  NOTICE: Contents of special://xbmc/system/advancedsettings.xml are...
                                            <?xml version="1.0" encoding="UTF-8" ?>
                                            <advancedsettings>
                                              <showexitbutton>false</showexitbutton>
                                              <remotedelay>1</remotedelay>
                                              <fanartres>720</fanartres>
                                              <imageres>540</imageres>
                                              <samba>
                                                <clienttimeout>30</clienttimeout>
                                              </samba>
                                            </advancedsettings>
11:54:55.130 T:1945473024  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
11:54:55.130 T:1945473024  NOTICE: Default Video Player: VideoPlayer
11:54:55.130 T:1945473024  NOTICE: Default Audio Player: paplayer
11:54:55.130 T:1945473024  NOTICE: Disabled debug logging due to GUI setting. Level 0.
11:54:55.130 T:1945473024  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
11:54:55.131 T:1945473024  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/profiles/Noé/sources.xml
11:54:55.132 T:1945473024  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
11:54:55.134 T:1945473024  NOTICE: Loaded playercorefactory configuration
11:54:55.134 T:1945473024  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
11:54:55.135 T:1945473024  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
11:54:55.183 T:1945473024  NOTICE: Running database version Addons27
11:54:55.186 T:1945473024  NOTICE: Running database version ViewModes6
11:54:55.189 T:1945473024  NOTICE: Running database version Textures13
11:54:55.197 T:1945473024  NOTICE: Running database version MyMusic60
11:54:55.206 T:1945473024  NOTICE: Running database version MyVideos107
11:54:55.209 T:1945473024  NOTICE: Running database version TV29
11:54:55.211 T:1945473024  NOTICE: Running database version Epg11
11:54:55.298 T:1945473024   ERROR: GetCdInfo: Error in automatically selecting driver with input
11:54:55.298 T:1945473024   ERROR: Detection of DVD-ROM media failed.
11:54:55.303 T:1945473024  NOTICE: starting zeroconf publishing
11:54:55.304 T:1945473024  NOTICE: CWebServer[8080]: Started
11:54:55.304 T:1945473024  NOTICE: starting upnp client
11:54:55.306 T:1787474848  NOTICE: ES: Starting UDP Event server on port 9777
11:54:55.307 T:1787474848  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
11:54:58.805 T:1945473024  NOTICE: ADDONS: Using repository repository.kodi.game
11:54:58.806 T:1945473024  NOTICE: ADDONS: Using repository repository.libreelec.tv
11:54:58.806 T:1945473024  NOTICE: ADDONS: Using repository repository.xbmc.org
11:54:59.278 T:1726337952  NOTICE: script.grab.fanart: Grab Fanart Service Started
11:55:02.659 T:1945473024   ERROR: Window Translator: Can't find window games
11:55:05.376 T:1694176160   ERROR: GetDirectory - Error getting
11:55:05.425 T:1537205152 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
11:55:05.426 T:1537205152  NOTICE: LoadJpeg: unable to load special://skin/extras/moviegenres/Default.jpg
11:55:05.472 T:1594880928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 35: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 24, in <module>
                                                import YDStreamUtils
                                              File "/storage/.kodi/addons/script.module.youtube.dl/lib/YDStreamUtils.py", line 5, in <module>
                                                from yd_private_libs import util
                                              File "/storage/.kodi/addons/script.module.youtube.dl/lib/yd_private_libs/util.py", line 15, in <module>
                                                if not os.path.exists(TMP_PATH): os.makedirs(TMP_PATH)
                                              File "/usr/lib/python2.7/genericpath.py", line 26, in exists
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 35: ordinal not in range(128)
                                            -->End of Python script error report<--
11:55:05.477 T:1945473024   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/
11:55:05.478 T:1945473024   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/) failed
```

Puis j'ai attendu et je réessayé pour avoir des logs plus clairs
```
11:58:06.322 T:1945473024   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
11:58:06.326 T:1518334880 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
11:58:06.326 T:1518334880  NOTICE: LoadJpeg: unable to load special://skin/extras/moviegenres/Default.jpg
11:58:06.471 T:1493169056   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 35: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 24, in <module>
                                                import YDStreamUtils
                                              File "/storage/.kodi/addons/script.module.youtube.dl/lib/YDStreamUtils.py", line 5, in <module>
                                                from yd_private_libs import util
                                              File "/storage/.kodi/addons/script.module.youtube.dl/lib/yd_private_libs/util.py", line 15, in <module>
                                                if not os.path.exists(TMP_PATH): os.makedirs(TMP_PATH)
                                              File "/usr/lib/python2.7/genericpath.py", line 26, in exists
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 35: ordinal not in range(128)
                                            -->End of Python script error report<--
11:58:06.482 T:1945473024   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/
11:58:06.483 T:1945473024   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/) failed
```

Merci de votre aide :)

**Comment by wwark** [comment]
Bonjour,

Bonne Année ! Merci pour votre intérêt pour ce plugin.
Le plugin a évolué et maintenant à la version 0.1.8.
Il est disponible en téléchargement sur un répository détaillé dans cette page wiki https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/wiki/Add-the-official-repository
Nous poussons de temps en temps des mises à jour sur le répository de Kodi mais les acceptations peuvent prendre du temps.

Est-ce qu'il possible de tester si ce comportement est toujours présent dans la version 0.1.8 du plugin ? Si le problème persiste pouvez-vous nous fournir les logs ?

Merci d'avance,
Wwark.

**Comment by ptit-nico** [comment]
J'ai pu mettre à jour le plugin en 0.1.8 avec le dépot mais le problème persiste.
Les logs (ici avec le master user le plugin marche bien)
```
14:48:08.917 T:1611486112  NOTICE: script.grab.fanart: Grab Fanart Service Started
14:48:14.117 T:1945576000   ERROR: Window Translator: Can't find window games
14:48:15.692 T:1526723488  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.12.31
14:48:21.212 T:1526723488  NOTICE: Previous line repeats 2 times.
14:48:21.212 T:1526723488 WARNING: CPythonInvoker(9, /storage/.kodi/addons/script.extendedinfo/plugin.py): the python script "/storage/.kodi/addons/script.extendedinfo/plugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui10DialogBusyE
14:48:22.839 T:1594708896  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.12.31
14:48:23.249 T:1535112096 WARNING: CPythonInvoker(8, /storage/.kodi/addons/script.extendedinfo/plugin.py): the python script "/storage/.kodi/addons/script.extendedinfo/plugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui10DialogBusyE
14:48:23.613 T:1569543072   ERROR: GetDirectory - Error getting
14:48:23.846 T:1516237728 WARNING: CPythonInvoker(10, /storage/.kodi/addons/script.extendedinfo/plugin.py): the python script "/storage/.kodi/addons/script.extendedinfo/plugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui10DialogBusyE
14:48:24.099 T:1594708896 WARNING: CPythonInvoker(11, /storage/.kodi/addons/script.extendedinfo/plugin.py): the python script "/storage/.kodi/addons/script.extendedinfo/plugin.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui10DialogBusyE
14:51:31.921 T:1677140896  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.12.31
14:51:44.820 T:1584395168  NOTICE: Previous line repeats 1 times.
14:51:44.820 T:1584395168 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
14:51:44.821 T:1584395168 WARNING: Previous line repeats 1 times.
14:51:44.821 T:1584395168  NOTICE: LoadJpeg: unable to load /storage/.kodi/addons/plugin.video.catchuptvandmore/resources/media/channels/fr/tf1_fanart.jpg
14:51:53.298 T:1945576000   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/
14:51:53.299 T:1945576000   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/) failed
14:51:54.195 T:1677140896  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.12.31

```

Puis je me délogue et me logue avec le compte enfant : 
``14:51:56.573 T:1945576000  NOTICE: ES: Stopping event server
14:51:57.137 T:1693918112  NOTICE: ES: UDP Event server stopped
14:51:57.363 T:1945576000  NOTICE: stopping upnp
14:51:57.514 T:1945576000  NOTICE: stopping zeroconf publishing
14:51:57.520 T:1945576000  NOTICE: CWebServer[8080]: Stopped
14:51:57.556 T:1744249760  NOTICE: ES: Starting UDP Event server on port 9777
14:51:57.556 T:1744249760  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
14:52:04.189 T:1945576000  NOTICE: ES: Stopping event server
14:52:04.564 T:1744249760  NOTICE: ES: UDP Event server stopped
14:52:04.583 T:1945576000  NOTICE: special://profile/ is mapped to: special://masterprofile/profiles/Noé/
14:52:04.608 T:1945576000  NOTICE: Loaded settings file from special://xbmc/system/advancedsettings.xml
14:52:04.609 T:1945576000  NOTICE: Contents of special://xbmc/system/advancedsettings.xml are...
                                            <?xml version="1.0" encoding="UTF-8" ?>
                                            <advancedsettings>
                                              <showexitbutton>false</showexitbutton>
                                              <remotedelay>1</remotedelay>
                                              <fanartres>720</fanartres>
                                              <imageres>540</imageres>
                                              <samba>
                                                <clienttimeout>30</clienttimeout>
                                              </samba>
                                            </advancedsettings>
14:52:04.612 T:1945576000  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
14:52:04.612 T:1945576000  NOTICE: Default Video Player: VideoPlayer
14:52:04.612 T:1945576000  NOTICE: Default Audio Player: paplayer
14:52:04.612 T:1945576000  NOTICE: Disabled debug logging due to GUI setting. Level 0.
14:52:04.612 T:1945576000  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
14:52:04.612 T:1945576000  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/profiles/Noé/sources.xml
14:52:04.615 T:1945576000  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
14:52:04.617 T:1945576000  NOTICE: Loaded playercorefactory configuration
14:52:04.618 T:1945576000  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
14:52:04.618 T:1945576000  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
14:52:04.751 T:1945576000  NOTICE: Running database version Addons27
14:52:04.757 T:1945576000  NOTICE: Running database version ViewModes6
14:52:04.827 T:1945576000  NOTICE: Running database version Textures13
14:52:04.847 T:1945576000  NOTICE: Running database version MyMusic60
14:52:05.134 T:1945576000  NOTICE: Running database version MyVideos107
14:52:05.141 T:1945576000  NOTICE: Running database version TV29
14:52:05.147 T:1945576000  NOTICE: Running database version Epg11
14:52:05.238 T:1945576000   ERROR: GetCdInfo: Error in automatically selecting driver with input
14:52:05.238 T:1945576000   ERROR: Detection of DVD-ROM media failed.
14:52:05.244 T:1945576000  NOTICE: starting zeroconf publishing
14:52:05.244 T:1945576000  NOTICE: CWebServer[8080]: Started
14:52:05.245 T:1945576000  NOTICE: starting upnp client
14:52:05.246 T:1693918112  NOTICE: ES: Starting UDP Event server on port 9777
14:52:05.246 T:1693918112  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
14:52:07.624 T:1945576000  NOTICE: ADDONS: Using repository repository.kodi.game
14:52:07.624 T:1945576000  NOTICE: ADDONS: Using repository repository.libreelec.tv
14:52:07.624 T:1945576000  NOTICE: ADDONS: Using repository repository.xbmc.org
14:52:08.012 T:1660363680  NOTICE: script.grab.fanart: Grab Fanart Service Started
14:52:15.206 T:1945576000   ERROR: Window Translator: Can't find window `games`

Et enfin je lance le plugin (qui ne marche pas)
``
14:56:07.153 T:1569543072   ERROR: GetDirectory - Error getting
14:56:07.179 T:1858073504 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
14:56:07.180 T:1858073504  NOTICE: LoadJpeg: unable to load special://skin/extras/moviegenres/Default.jpg
14:56:08.777 T:1584395168   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 35: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 24, in <module>
                                                import YDStreamUtils
                                              File "/storage/.kodi/addons/script.module.youtube.dl/lib/YDStreamUtils.py", line 5, in <module>
                                                from yd_private_libs import util
                                              File "/storage/.kodi/addons/script.module.youtube.dl/lib/yd_private_libs/util.py", line 15, in <module>
                                                if not os.path.exists(TMP_PATH): os.makedirs(TMP_PATH)
                                              File "/usr/lib/python2.7/genericpath.py", line 26, in exists
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 35: ordinal not in range(128)
                                            -->End of Python script error report<--
14:56:08.781 T:1945576000   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/
14:56:08.782 T:1945576000   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/) failed

``

**Comment by wwark** [comment]
Bonjour,

Merci pour ce nouveau test.
L'erreur semble au niveau du plugin youtube-dl utilisé par le plugin Catchup TV & More pour le mode téléchargement ou le visionnage des vidéos hébergés par Youtube.
C'est un problème d'encodage sur le nom du profil. Est-ce qu'il est possible de tester avec le prénom non accentué.
Nous allons regarder pour la reproduire de notre côté et voir comment la corriger (Issue sur le git plugin YTDL, etc ...).

Merci d'avance,
Wwark

**Comment by wwark** [comment]
Bonsoir,
Je viens de tester avec des profils "Noël" et "Céline". Je n'ai pas obtenu l'erreur.

Lors de la création du profil, est-ce que vous utiliser l'option "start fersh" ou la copie du profil précent ?

Merci pour votre retour,
Wwark

**Comment by ptit-nico** [comment]
Merci pour votre retour. J'aurais du me douter que l'accent dans le nom du profil poserait problème...
Je vais essayer dès que j'ai un peu de temps (le media center est en prod' maintenant) de me loguer en ssh, de copier le profil avec un nom sans accent et de le faire pointer dessus, ça devrait marcher.

Je vous tiens au courant :)

**Comment by wwark** [comment]
Sous debian (buster) avec Kodi 17.6 => L'erreur n'est pas présente
Sous libreelec avec kodi 17.6 => J'obtiens l'erreur.
Est-ce qu'il est possible de tester sur un autre environnement par exemple Windows ?

Il est possible que le problème est que sous libreelec.
Wwark.

**Comment by ptit-nico** [comment]
Bonjour,

J'ai pu enfin avoir du temps pour finaliser mes tests. En fait je suis reparti sur une fresh install de mon pi sous LibreELEC (j'avais testé trop d'extensions) et cette fois j'ai créé le profil enfants sans accent et tout fonctionne bien.

Je m'aperçois que je n'avais pas répondu à la précédente question "Lors de la création du profil, est-ce que vous utiliser l'option "start fresh" ou la copie du profil précent ?" --> Je faisais une copie parce que j'avais déjà configuré pas mal de petits trucs.

Donc au final le problème est résolu avec un nom de profil ne comprenant pas de caractère spécial.

Merci en tout cas pour vos réponses et votre réactivité, maintenant mon fils va pouvoir regarder le replay de Gulli tranquillement. ;-)

@+ :)
