### ISSUE TITLE
[RTBF] Live broken - "TypeError: list indices must be integers or slices, not str"

### ISSUE THREAD

**Issue by gleonet** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#444]
### Describe the bug
"Live" -> "Belgium" -> "RTBF Auvio" doesn't work and display the following error message :
" TypeError: list indices must be integers or slices, not str "

### To Reproduce
1. Start the extension
2. Go to Live
3. Go to Belgium
4. Select RTBF Auvio

### Screenshots

![IMG_20210224_192918](https://user-images.githubusercontent.com/1931859/109050244-76520680-76d9-11eb-8f2e-51d84cd0a646.jpg)

### Your environment
 - [ ] Android
 - [ ] iOS
 - [X] **Linux**
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: Ubuntu 20.04
 - Kodi version: 19
 - Catch-up TV & More version: 0.2.29

### Debug log
```
2021-02-24 19:28:41.689 T:1808     INFO <general>: initializing python engine.
2021-02-24 19:28:43.414 T:1808    ERROR <general>: [Catch-up-TV-&-More.support] list indices must be integers or slices, not str
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 328, in run_callback
                                                       redirect = parent_ins._process_results(results)
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 95, in _process_results
                                                       raw_listitems = validate_listitems(raw_listitems)
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 34, in validate_listitems
                                                       raw_listitems = list(raw_listitems)
                                                     File "/home/kodi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py", line 664, in list_lives
                                                       if 'url_hls' in json_parser["url_streaming"]:
                                                   TypeError: list indices must be integers or slices, not str
```

**Comment by wwark** [comment]
Hi @gleonet,

Sorry, the plugin is not officially compatible with Kodi 19 and not well tested by us.
It seems some part needs to be adapt for this "if".

I will let opened this ticket to fix it when the plugin will be available on Kodi 19.

Thanks for the report.

**Comment by wwark** [comment]
Hi @gleonet,
Do you still have the issue with the version 0.2.32+ of CUTV&More ?
If it is the case could you please try this version : 
[plugin.video.catchuptvandmore-dev.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/6057508/plugin.video.catchuptvandmore-dev.zip)

Thank you !

**Comment by gleonet** [comment]
Hi @wwark,
I will test tonight and update the issue accordingly.

**Comment by gleonet** [comment]
Hi @wwark,
I have one good news and one bad news :)

With the version 0.2.32+ I saw in the list of lives several entries related to RTBF:
- RTBF Auvio
- La Une - XXX
- La Deux - YYY
- ...

The general entry "RTBF Auvio" (with a "folder icon") doesn't work but the other entries like "La Une - XXX" work perfectly.
I didn't test yet the dev version attached in your previous comment but I will do today.

**Comment by wwark** [comment]
The new version is available.
It fixed normally your issue.
I closed this ticket. You can reopen it if needed.
Thanks,
