### ISSUE TITLE
[M6] Catchup TV KO

### ISSUE THREAD

**Issue by bamboozila** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#458]
Salut, tout d'abord, merci pour l' addon. Jusqu'à présent rien à redire !

Je suis en 0.2.32, j'imagine que le problème avec M6 correspond à ce [message](https://forum.kodi.tv/showthread.php?tid=307107&pid=3017931#pid3017931)

### Describe the bug
les catchup tv autour de m6 sont ko

### To Reproduce
Kodi 19 + catchup tv 0.2.32

### Your environment
 - [X] Android
 - [X] Linux
 
  - Operating system version/name: Nvidia shield Android et sur mon pc linux
  - Kodi version: 19
 - Catch-up TV & More version: 0.2.32
 - Installation method: zip and repo install

### Debug log
```
2021-03-04 21:54:19.952 T:10976   ERROR <general>: [Catch-up-TV-&-More.support] sequence item 1: expected a bytes-like object, str found
                                                   Traceback (most recent call last):
                                                     File "/home/mistertea/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/mistertea/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/home/mistertea/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/home/mistertea/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/6play.py", line 398, in get_video_url
                                                       resp2 = urlquick.post(URL_COMPTE_LOGIN,
                                                     File "/home/mistertea/.kodi/addons/script.module.codequick/lib/urlquick.py", line 505, in post
                                                       return request('post', url, data=data, json=json, **kwargs)
                                                     File "/home/mistertea/.kodi/addons/script.module.codequick/lib/urlquick.py", line 482, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                     File "/home/mistertea/.kodi/addons/script.module.codequick/lib/urlquick.py", line 436, in request
                                                       response = super(Session, self).request(*args, **kwargs)
                                                     File "/home/mistertea/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 533, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "/home/mistertea/.kodi/addons/script.module.codequick/lib/urlquick.py", line 445, in send
                                                       return super(Session, self).send(request, **kwargs)
                                                     File "/home/mistertea/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "/home/mistertea/.kodi/addons/script.module.codequick/lib/urlquick.py", line 349, in send
                                                       urlhash = hash_url(request)
                                                     File "/home/mistertea/.kodi/addons/script.module.codequick/lib/urlquick.py", line 203, in hash_url
                                                       return hashlib.sha1(b''.join((data, req.body or b''))).hexdigest()
                                                   TypeError: sequence item 1: expected a bytes-like object, str found

```

**Comment by wwark** [comment]
Hello @bamboozila,
Ce problème est suivi ici : #447

Merci,
Wwark !
