### ISSUE TITLE
Euronews Fr and France 24 FR KO

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#464]
### Describe the bug
Tested on Windows  + kodi 19 just now, i will test under linux after
![euronews](https://user-images.githubusercontent.com/31815445/110360631-43940080-803f-11eb-8c3c-811531f27ee5.png)

Edit: same for Linux Kodi 19 also, have no Kodi 18 anymore to test more..

**Comment by Grouickman** [comment]
Same here for France 24 FR, with an error error 403.

here's the debug log :
`2021-03-08 22:54:09.634 T:1156571360   DEBUG: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/wo/france24/get_live_url/'
2021-03-08 22:54:09.635 T:1156571360   DEBUG: [Catch-up-TV-&-More.support] Callback parameters: '{u'item_id': u'france24', u'language': u'FR'}'
2021-03-08 22:54:09.635 T:1156571360   DEBUG: [Catch-up-TV-&-More.support] Attempting to import route: resources.lib.channels.wo.france24
2021-03-08 22:54:10.623 T:1156571360   DEBUG: CAddonSettings[plugin.video.catchuptvandmore]: loading setting definitions
2021-03-08 22:54:10.623 T:1156571360   DEBUG: CAddonSettings[plugin.video.catchuptvandmore]: trying to load setting definitions from old format...
2021-03-08 22:54:10.625 T:1156571360   DEBUG: CAddonSettings[plugin.video.catchuptvandmore]: loading setting values
2021-03-08 22:54:10.885 T:1156571360   DEBUG: [urllib3.connectionpool] Starting new HTTP connection (1): apis.france24.com:80
2021-03-08 22:54:10.914 T:1156571360   DEBUG: [urllib3.connectionpool] http://apis.france24.com:80 "GET /products/get_product/78dcf358-9333-4fb2-a035-7b91e9705b13?token_application=66b85dad-3ad5-40f3-ab32-2305fc2357ea HTTP/1.1" 403 355
2021-03-08 22:54:10.923 T:1156571360   ERROR: [Catch-up-TV-&-More.support] 403 Client Error: Forbidden for url: http://apis.france24.com/products/get_product/78dcf358-9333-4fb2-a035-7b91e9705b13?token_application=66b85dad-3ad5-40f3-ab32-2305fc2357ea
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                redirect = parent_ins(route, arg_params, self.callback_params)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                results = super(Resolver, self).__call__(route, args, kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                return route.function(self, *args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/wo/france24.py", line 338, in get_live_url
                                                params={'token_application': TOKEN_APP})
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 493, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 487, in request
                                                return s.request(method=method, url=url, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 442, in request
                                                self._raise_for_status(response, raise_for_status)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 415, in _raise_for_status
                                                response.raise_for_status()
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 940, in raise_for_status
                                                raise HTTPError(http_error_msg, response=self)
                                            HTTPError: 403 Client Error: Forbidden for url: http://apis.france24.com/products/get_product/78dcf358-9333-4fb2-a035-7b91e9705b13?token_application=66b85dad-3ad5-40f3-ab32-2305fc2357ea
2021-03-08 22:54:10.926 T:1156571360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'HTTPError' object has no attribute 'code'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 45, in <module>
                                                main()
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 41, in main
                                                main.error_handler(exception)
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 313, in error_handler
                                                code = exception.code
                                            AttributeError: 'HTTPError' object has no attribute 'code'
                                            -->End of Python script error report<--
2021-03-08 22:54:10.926 T:1156571360   DEBUG: onExecutionDone(16, /home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py)
2021-03-08 22:54:11.078 T:1156571360    INFO: Python interpreter stopped`


And for Euronews FR (API changed ?):
`2021-03-08 22:56:53.902 T:1916133392   DEBUG: ------ Window Init () ------
2021-03-08 22:56:53.953 T:1765798112   DEBUG: Thread Timer 1765798112 terminating
2021-03-08 22:56:53.957 T:1916133392   DEBUG: Keyboard: scancode: 0x20, sym: 0x0064, unicode: 0x0004, modifier: 0xc3
2021-03-08 22:56:54.142 T:1916133392   DEBUG: Keyboard: scancode: 0x2a, sym: 0x0130, unicode: 0x0000, modifier: 0xc0
2021-03-08 22:56:54.188 T:1916133392   DEBUG: Keyboard: scancode: 0x1d, sym: 0x0132, unicode: 0x0000, modifier: 0x0
2021-03-08 22:56:55.889 T:1895821536   DEBUG: CLibInputKeyboard::ProcessKey - using delay: 500ms repeat: 50ms
2021-03-08 22:56:55.889 T:1765798112   DEBUG: Thread Timer start, auto delete: false
2021-03-08 22:56:55.936 T:1916133392   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x000d, modifier: 0x0
2021-03-08 22:56:55.969 T:1765798112   DEBUG: Thread Timer 1765798112 terminating
2021-03-08 22:56:55.982 T:1916133392   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x000d, modifier: 0x0
2021-03-08 22:56:55.982 T:1916133392   DEBUG: HandleKey: return (0xf00d) pressed, action is Select
2021-03-08 22:56:56.007 T:1916133392   DEBUG: StartScript - calling plugin Catch-up TV & More('plugin://plugin.video.catchuptvandmore/resources/lib/channels/wo/euronews/get_live_url/','4','?item_id=euronews&language=FR','resume:false')
2021-03-08 22:56:56.008 T:1765798112   DEBUG: Thread LanguageInvoker start, auto delete: false
2021-03-08 22:56:56.008 T:1765798112    INFO: initializing python engine.
2021-03-08 22:56:56.008 T:1765798112   DEBUG: CPythonInvoker(17, /home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py): start processing
2021-03-08 22:56:56.029 T:1793061088   DEBUG: Thread scriptobs start, auto delete: false
2021-03-08 22:56:56.229 T:1916133392   DEBUG: ------ Window Init (DialogBusy.xml) ------
2021-03-08 22:56:56.307 T:1765798112   DEBUG: -->Python Interpreter Initialized<--
2021-03-08 22:56:56.307 T:1765798112   DEBUG: CPythonInvoker(17, /home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py): the source file to load is "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py"
2021-03-08 22:56:56.310 T:1765798112   DEBUG: CPythonInvoker(17, /home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py): setting the Python path to /home/osmc/.kodi/addons/plugin.video.catchuptvandmore:/home/osmc/.kodi/addons/script.module.addon.signals/lib:/home/osmc/.kodi/addons/script.module.certifi/lib:/home/osmc/.kodi/addons/script.module.chardet/lib:/home/osmc/.kodi/addons/script.module.codequick/lib:/home/osmc/.kodi/addons/script.module.future/libs:/home/osmc/.kodi/addons/script.module.htmlement/lib:/home/osmc/.kodi/addons/script.module.idna/lib:/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib:/home/osmc/.kodi/addons/script.module.kodi-six/libs:/home/osmc/.kodi/addons/script.module.pyqrcode/lib:/home/osmc/.kodi/addons/script.module.pytz/lib:/home/osmc/.kodi/addons/script.module.requests/lib:/home/osmc/.kodi/addons/script.module.six/lib:/home/osmc/.kodi/addons/script.module.tzlocal/lib:/home/osmc/.kodi/addons/script.module.urllib3/lib:/home/osmc/.kodi/addons/script.module.youtube.dl/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-arm-linux-gnueabihf:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/gtk-2.0
2021-03-08 22:56:56.310 T:1765798112   DEBUG: CPythonInvoker(17, /home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py): entering source directory /home/osmc/.kodi/addons/plugin.video.catchuptvandmore
2021-03-08 22:56:56.310 T:1765798112   DEBUG: CPythonInvoker(17, /home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py): instantiating addon using automatically obtained id of "plugin.video.catchuptvandmore" dependent on version 2.25.0 of the xbmc.python api
2021-03-08 22:56:56.926 T:1765798112   DEBUG: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/wo/euronews/get_live_url/'
2021-03-08 22:56:56.926 T:1765798112   DEBUG: [Catch-up-TV-&-More.support] Callback parameters: '{u'item_id': u'euronews', u'language': u'FR'}'
2021-03-08 22:56:56.926 T:1765798112   DEBUG: [Catch-up-TV-&-More.support] Attempting to import route: resources.lib.channels.wo.euronews
2021-03-08 22:56:57.909 T:1765798112   DEBUG: CAddonSettings[plugin.video.catchuptvandmore]: loading setting definitions
2021-03-08 22:56:57.909 T:1765798112   DEBUG: CAddonSettings[plugin.video.catchuptvandmore]: trying to load setting definitions from old format...
2021-03-08 22:56:57.911 T:1765798112   DEBUG: CAddonSettings[plugin.video.catchuptvandmore]: loading setting values
2021-03-08 22:56:57.951 T:1765798112   DEBUG: [urllib3.connectionpool] Starting new HTTP connection (1): fr.euronews.com:80
2021-03-08 22:56:58.122 T:1765798112   DEBUG: [urllib3.connectionpool] http://fr.euronews.com:80 "GET /api/watchlive.json HTTP/1.1" 301 0
2021-03-08 22:56:58.129 T:1765798112   DEBUG: [urlquick] Cache is fresh
2021-03-08 22:56:58.134 T:1765798112   ERROR: [Catch-up-TV-&-More.support] argument of type 'NoneType' is not iterable
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                redirect = parent_ins(route, arg_params, self.callback_params)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                results = super(Resolver, self).__call__(route, args, kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                return route.function(self, *args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/wo/euronews.py", line 60, in get_live_url
                                                if 'http' in json_parser["url"]:
                                            TypeError: argument of type 'NoneType' is not iterable
2021-03-08 22:56:58.203 T:1916133392   DEBUG: ------ Window Init (DialogNotification.xml) ------
2021-03-08 22:56:58.466 T:1916133392   DEBUG: ------ Window Init (DialogConfirm.xml) ------
2021-03-08 22:56:59.657 T:1916133392   DEBUG: Keyboard: scancode: 0x1d, sym: 0x0132, unicode: 0x0000, modifier: 0xc0
2021-03-08 22:56:59.657 T:1916133392   DEBUG: HandleKey: ctrl-leftctrl (0x1f0d0) pressed, action is
2021-03-08 22:56:59.857 T:1916133392   DEBUG: Keyboard: scancode: 0x2a, sym: 0x0130, unicode: 0x0000, modifier: 0xc3
2021-03-08 22:56:59.857 T:1916133392   DEBUG: HandleKey: ctrl-shift-leftshift (0x3f0d2) pressed, action is
2021-03-08 22:57:00.537 T:1895821536   DEBUG: CLibInputKeyboard::ProcessKey - using delay: 500ms repeat: 50ms
2021-03-08 22:57:00.537 T:1185935584   DEBUG: Thread Timer start, auto delete: false
2021-03-08 22:57:00.541 T:1916133392   DEBUG: Keyboard: scancode: 0x20, sym: 0x0064, unicode: 0x0004, modifier: 0xc3
2021-03-08 22:57:00.541 T:1916133392   DEBUG: HandleKey: ctrl-shift-d (0x3f044) pressed, action is ToggleDebug
2021-03-08 22:57:00.541 T:1916133392  NOTICE: Disabled debug logging due to GUI setting. Level 0.
2021-03-08 22:57:00.541 T:1916133392  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
2021-03-08 22:57:00.541 T:1916133392  NOTICE: Disabled debug logging due to GUI setting. Level 0.
2021-03-08 22:57:00.541 T:1916133392  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"`

**Comment by enigma131** [comment]
Oops yes havent give debug logs yesterday

For France 24 Fr: same 403 error as above:
ERROR <general>: [Catch-up-TV-&-More.support] 403 Client Error: Forbidden for url: http://apis.france24.com/products/get_product/78dcf358-9333-4fb2-a035-7b91e9705b13?token_application=66b85dad-3ad5-40f3-ab32-2305fc2357ea

For Euronews Fr: same python error as above:
2021-03-09 09:32:07.172 T:9982    DEBUG <general>: [urllib3.connectionpool] https://fr.euronews.com:443 "GET /api/watchlive.json HTTP/1.1" 200 51
2021-03-09 09:32:07.173 T:9982    DEBUG <general>: [urlquick] Caching 200 OK response
2021-03-09 09:32:07.187 T:9982    ERROR <general>: [Catch-up-TV-&-More.support] argument of type 'NoneType' is not iterable
                                                   Traceback (most recent call last):
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/wo/euronews.py", line 40, in get_live_url
                                                       if 'http' in json_parser["url"]:
                                                   TypeError: argument of type 'NoneType' is not iterable

**Comment by enigma131** [comment]
commit is working for F24 :https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/1351e24aafc1608f13fbbb7f205806140ddbdd2e

**Comment by chamchenko** [comment]
this is just a suggested fix for the old code, using the new euronews api (api used within euronews app for iPhone)
# -*- coding: utf-8 -*-
# Copyright: (c) 2017, SylvainCecchetto
# GNU General Public License v2.0+ (see LICENSE.txt or https://www.gnu.org/licenses/gpl-2.0.txt)

# This file is part of Catch-up TV & More

from __future__ import unicode_literals
import json

from codequick import Resolver, Script
import urlquick

from resources.lib import resolver_proxy
from resources.lib import web_utils


# TODO
# Replay add emissions
URL_LIVE_API = 'https://api.euronews.com/v2/apps/iphoneEuronews-3.10/languages/%s/livestream'
# Language

DESIRED_LANGUAGE = Script.setting['euronews.language']


@Resolver.register
def get_live_url(plugin, item_id, **kwargs):
    final_language = kwargs.get('language', Script.setting['euronews.language'])

    url_live_json = URL_LIVE_API % final_language.lower()

    resp = urlquick.get(url_live_json,
                        headers={'User-Agent': web_utils.get_random_ua()},
                        max_age=-1)
    json_parser = json.loads(resp.text)
    return json_parser["primary"]

**Comment by wwark** [comment]
thank you @chamchenko (I will keep it)
It is already fixed here https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/793e3f9b478be52d658c0afc72292669cdcb15dc but I'm waiting release of new version of YT-DL fixed playing YT contents.
Euronews use YT for their contents.

Thanks again.

**Comment by enigma131** [comment]
Commit test and works too, thanks Wwark to give Euronews back!
I have notice a little bug, 1080p content choosing gives 720p... perhaps a limitation from my adsl at evening, I will test at middle of the day next days

**Comment by wwark** [comment]
New version fixed those issues available.
