### ISSUE TITLE
Live Nrj Hits TV :  list index out of range

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#472]
Extrait du log : 

2021-03-14 09:14:33.894 T:12054   ERROR <general>: [Catch-up-TV-&-More.support] list index out of range
                                                   Traceback (most recent call last):
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/be/nrjhitstvbe.py", line 76, in get_live_url
                                                       data_player = re.compile(r'data-video-player-id\=\"(.*?)\"').findall(
                                                   IndexError: list index out of range

**Comment by wwark** [comment]
Hi @enigma131,
It is working on my side.
Could you please provide the whole log with this issue ?

Thanks,

**Comment by enigma131** [comment]
Here it is : https://paste.kodi.tv/ezotujezib.kodi

**Comment by wwark** [comment]
Désolé je pensais que tu parlais de NRJ 12 ...
Ils ont arrêté de diffuser la chaine sur le site web : https://www.nrj.be/tv

Je vais enlever la chaine du site web.
Merci,

**Comment by enigma131** [comment]
Arf, elle me plaisait bien ... 
Donc Nrj Play prends le relais ?
Si oui add new content ?
