### ISSUE TITLE
Channel unduly exported in EPG generating errors in IPTV manager

### ISSUE THREAD

**Issue by billy34** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#500]
### Describe the bug
Using IPTV manager integration I made selection of 28 channels to use (mostly french + arte FR in world)
I'm getting a lot of errors in log and no epg displayed. I already cleared epg cache rebuilt it with IPTV manager, manually removed epg.xml file from filesystem using ssh, regenerate it and nothing.
Errors are generated by IPTV simple trying to read a date from stop attribute of program. Looking at it there is a bunch of `stop `attributes having a value of `None`, all belonging to Euronews channel. That surprises me because I haven't selected this channel ! So I analyzed the `epg.xml` file and found my 28 channels at the beginning and after extracting all channel attributes from program entries I got 66 channels !
Shouldn't they been filtered by the `send_epg `function of CUTVM' `iptvmanager.py` ?
It wouldn't solve the error when reading `None `dates but maybe solve mine if this channel is no more exported.

By the way thank you for this marvelous plugin 😄 

Using : OSMC Kodi Leia, CUTVM 0.2.35~beta02

The error from log file (one of ...)
```
2021-04-16 18:36:14.262 T:1402986720  NOTICE: [service.iptv.manager] [resources.lib.modules.addon] Executing RunPlugin(plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/epg/?port=38369)...
2021-04-16 18:38:50.287 T:1402986720   ERROR: [service.iptv.manager] [resources.lib.modules.iptvsimple] Could not parse item: {u'subtitle': None, u'description': None, u'title': u'Good Morning Europe', u'image': None, u'stop': None, u'start': u'2021-04-12T04:00:00', u'genre': None, u'episode': None}
2021-04-16 18:38:50.294 T:1402986720   ERROR: [service.iptv.manager] [resources.lib.modules.iptvsimple] Parser must be a string or character stream, not NoneType
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/service.iptv.manager/resources/lib/modules/iptvsimple.py", line 201, in _construct_epg_program_xml
                                                stop = dateutil.parser.parse(item.get('stop')).strftime('%Y%m%d%H%M%S %z').rstrip()
                                              File "/home/osmc/.kodi/addons/script.module.dateutil/lib/dateutil/parser/_parser.py", line 1374, in parse
                                                return DEFAULTPARSER.parse(timestr, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.dateutil/lib/dateutil/parser/_parser.py", line 646, in parse
                                                res, skipped_tokens = self._parse(timestr, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.dateutil/lib/dateutil/parser/_parser.py", line 725, in _parse
                                                l = _timelex.split(timestr)         # Splits the timestr into tokens
                                              File "/home/osmc/.kodi/addons/script.module.dateutil/lib/dateutil/parser/_parser.py", line 207, in split
                                                return list(cls(s))
                                              File "/home/osmc/.kodi/addons/script.module.dateutil/lib/dateutil/parser/_parser.py", line 76, in __init__
                                                '{itype}'.format(itype=instream.__class__.__name__))
                                            TypeError: Parser must be a string or character stream, not NoneType

```

**Comment by sy6sy2** [comment]
Hi!
Thank you for pointing this two issues!

Can you try 0.2.35~beta03 version to see if it's solve your issue?

**Comment by billy34** [comment]
Cool it's working back now !
Thanks a lot
