### ISSUE TITLE
Erreur "indexerror" "List of index out of range" sur RMC Story et RMC Découverte

### ISSUE THREAD

**Issue by theoden11** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#548]
Bonjour. Le problème n'est pas nouveau et a été déjà signalé auparavant, mais il a la vie dure. Je ne peux toujours pas regarder RMC Découverte et Story, sur aucune plateforme supportant Kodi et Catchup TV (Raspberry PI 3 + OSMC, linux fedora + Kodi 18.9 et Windows 10 + Kodi 18.9 Leia). Ayant appliqué la version 0.2.36 beta qui résout les problèmes sur Arte et la 5, je ne suis rendu compte que je ne pouvais toujours regarder les 2 chaînes citées en Live TV. Et ce, depuis la version 0.2.33 du plugin, donc ce n'est pas nouveau. C'est bête, je suis accro à Wheeler Dealers !

Ce topic en parle de manière précise en page 78
https://forum.mpdb.tv/index.php/topic,35713.1540.html

**Comment by alexismorillo** [comment]
J'ai le même problème sur Arte.

**Comment by theoden11** [comment]
Bjr. Etonnant, je ne l'ai jamais eu sur Arte. Le dernier patch beta résout le problème rencontré sur Arte et la 5 décrit dans un autre post.

**Comment by alexismorillo** [comment]
J'ai mis la dernière version et pourtant j'ai le même problème

**Comment by theoden11** [comment]
Même après reboot ?

**Comment by alexismorillo** [comment]
Je suis sur le repo beta, (Krypton Beta Repository) version 0.2.36-beta09. Ma version de kodi est 2:18.7-1~buster. Quand je vais sur Arte, j'ai les logs suivantes:
```
2021-08-13 18:04:04.896 T:1751675104 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
2021-08-13 18:04:04.896 T:1751675104  NOTICE: LoadJpeg: unable to load resource://resource.images.catchuptvandmore/channels/wo/arte_fanart.jpg
2021-08-13 18:04:06.880 T:1587306720   ERROR: [Catch-up-TV-&-More.support] list index out of range
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                redirect = parent_ins(route, arg_params, self.callback_params)
                                              File "/home/pi/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                session_data = self._process_results(results)
                                              File "/home/pi/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                listitems = validate_listitems(results)
                                              File "/home/pi/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                raw_listitems = list(raw_listitems)
                                              File "/home/pi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/wo/arte.py", line 64, in list_categories
                                                json_value = re.compile(r'_INITIAL_STATE__ \= (.*?)\}\;').findall(resp.text)[0]
                                            IndexError: list index out of range

```
France 5 fonctionne.

**Comment by alexismorillo** [comment]
Avec la dernière mise à jour, Arte refonctionne !

**Comment by theoden11** [comment]
Certes (quoique Arte est en basse résolution désormais) mais le problème des "Index out of range" n'est toujours pas résolu, et ce depuis longtemps !

**Comment by Trangsene** [comment]
Bonjour,
J'ai ce problème sur Arte (et d'autres chaines) depuis plusieurs semaines (Raspberry Pi4 + LibreElec).
Je viens d'installer la version beta de l'extension depuis le repo, Fausse joie.
C'est un peu mieux, j'ai accès à la liste des programmes d'Arte alors qu'avant j'étais dégagé tout de suite par l'erreur Index out of range.
Par contre dès que je lance une lecture, ça me lit 2 secondes de vidéo, puis ça freeze et ça revient à la liste des programmes :-(
Amère déception

**Comment by enigma131** [comment]
RMC Découverte et Story toujours pas OK avec la dernière MAJ (0.2.37 beta8)

**Comment by joaopa00** [comment]
Devrait être résolu dans la branche dev. Je ferme ce rapport.

**Comment by Falcou85** [comment]
Pourquoi fermer le problème s’il n’est pas résolu ?
