### ISSUE TITLE
Perte de RMC story et RMC découverte

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#555]
No more live

 - Operating system version/name: Linux Mint 20.2
 - Kodi version: 19.1
 - Catch-up TV & More version: latest beta 12
 - Installation method: standard
error : 

2021-09-05 09:18:37.804 T:13666   ERROR <general>: [Catch-up-TV-&-More.support] 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/rmc.py", line 125, in get_live_url
                                                       data_account = live_datas.get('data-account')
                                                   AttributeError: 'NoneType' object has no attribute 'get'

**Comment by ayoub-benali** [comment]
I have the same problem since months ...

**Comment by ayoub-benali** [comment]
FYI some info about the env: LibreElec 9.2.8 on RPI4 and Catch-up TV & More version: 0.2.36~beta15

**Comment by osmoze06** [comment]
Bonjour, Y a-t'il du nouveau concernant les replays de ces deux chaines non fonctionnelles ?

**Comment by enigma131** [comment]
Bonjour, rien de neuf pour le live inopérant ?

**Comment by enigma131** [comment]
à l'image  : 
![Capture d’écran du 2021-12-08 20-13-53](https://user-images.githubusercontent.com/31815445/145269913-a1fccd3e-ad6c-4baa-b0a5-b06f16a15f97.png)

**Comment by PsYk0zE** [comment]
Salut @enigma131, l’issue est fermée car un correctif a été implémenté?
Car j’ai toujours le même problème. 
a moins que le problème ait été fusionné avec l’issue #565 ?
Je te remercie

**Comment by enigma131** [comment]
Oui c'était un doublon, mais cela fait un bail que l'on a perdu ces 2 chaines, du coup faudrait peut être reposter une nouvelle issue ? En plus elles fonctionnent avec Captvty c'est rageant.

**Comment by enigma131** [comment]
fonctionne ici, voir #565

**Comment by joaopa00** [comment]
N'oubliez pas de remercier Arias !!
