### ISSUE TITLE
FranceTV : sivideo.webservices.francetelevisions.fr "This api is deprecated, contact France.tv video-factory"

### ISSUE THREAD

**Issue by Grouickman** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#558]
### Describe the bug
A clear and concise description of what the bug is:

Unable to play any FranceTV chanels (2,3,5,...)

### To Reproduce
1. Start France2
2.
3.
4.

### Expected behavior
A clear and concise description of what you expected to happen:

### Actuel behavior
Tell us what happens instead:
showing a popup with "404 Client Error: Not Found for url: https://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=006194ea-117d-4bcf-94a9-153d999c59ae"

when copy-pasting the URL in a web browser, I get the response :
{"status":"NOK","code":404,"message":"This api is deprecated, contact France.tv video-factory"}

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19.1.0
 - Catch-up TV & More version: 0.2.35+matrix.1
 - Installation method: dépot.

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

2021-09-13 20:52:50.642 T:426      INFO <general>: Log level changed to "INFO"
2021-09-13 20:52:58.144 T:540      INFO <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/francetv/get_live_url/?item_id=france-2
2021-09-13 20:52:58.148 T:1555     INFO <general>: initializing python engine.
2021-09-13 20:53:03.457 T:1555    ERROR <general>: [Catch-up-TV-&-More.support] 404 Client Error: Not Found for url: https://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=006194ea-117d-4bcf-94a9-153d999c59ae
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/francetv.py", line 414, in get_live_url
                                                       return resolver_proxy.get_francetv_live_stream(plugin, broadcast_id)
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py", line 350, in get_francetv_live_stream
                                                       max_age=-1).text)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 493, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 487, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 442, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 415, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 943, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=006194ea-117d-4bcf-94a9-153d999c59ae
2021-09-13 20:53:03.476 T:1555    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 290, in error_handler
                                                       code = exception.code
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--

2021-09-13 20:53:03.934 T:1555     INFO <general>: Python interpreter stopped

**Comment by SuperToma** [comment]
+1 :slightly_frowning_face:

**Comment by Ykwily** [comment]
Same problem than @Grouickman

**Comment by philippe44** [comment]
Seems that we might have to move to this api https://player.webservices.francetelevisions.fr/v1/videos/$id but I have no documentation. All I know it's MPD...

**Comment by Grouickman** [comment]
Looks like someone worked on it alreday : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/560/commits/1d35153e14d56bdb2aa4b81f97c06edc05b9fc05

I'll give a try by manually editing the resolver_proxy.py script and see.

**Comment by Grouickman** [comment]
ok... well, did not work :

2021-09-16 09:17:34.078 T:1112    DEBUG <general>: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/fr/francetv/get_live_url/'
2021-09-16 09:17:34.079 T:1112    DEBUG <general>: [Catch-up-TV-&-More.support] Callback parameters: '{'item_id': 'france-2'}'
2021-09-16 09:17:34.080 T:1112    DEBUG <general>: [Catch-up-TV-&-More.support] Attempting to import route: resources.lib.channels.fr.francetv
2021-09-16 09:17:36.138 T:1112    DEBUG <CAddonSettings[plugin.video.catchuptvandmore]>: trying to load setting definitions from old format...
2021-09-16 09:17:36.275 T:1112    DEBUG <general>: [urllib3.connectionpool] Starting new HTTPS connection (1): www.france.tv:443
2021-09-16 09:17:36.457 T:1112    DEBUG <general>: [urllib3.connectionpool] https://www.france.tv:443 "GET /france-2/direct.html HTTP/1.1" 200 11245
2021-09-16 09:17:36.566 T:1112    DEBUG <general>: [urllib3.connectionpool] Starting new HTTPS connection (1): geoftv-a.akamaihd.net:443
2021-09-16 09:17:36.794 T:1112    DEBUG <general>: [urllib3.connectionpool] https://geoftv-a.akamaihd.net:443 "GET /ws/edgescape.json HTTP/1.1" 200 166
2021-09-16 09:17:36.893 T:1112    DEBUG <general>: [urllib3.connectionpool] Starting new HTTPS connection (1): player.webservices.francetelevisions.fr:443
2021-09-16 09:17:37.152 T:1112    DEBUG <general>: [urllib3.connectionpool] https://player.webservices.francetelevisions.fr:443 "GET /v1/videos/006194ea-117d-4bcf-94a9-153d999c59ae&player_version=5.52.0&&device_type=desktop&browser=chrome?country_code=FR HTTP/1.1" 400 39
2021-09-16 09:17:37.172 T:1112    ERROR <general>: [Catch-up-TV-&-More.support] 400 Client Error: Bad Request for url: https://player.webservices.francetelevisions.fr/v1/videos/006194ea-117d-4bcf-94a9-153d999c59ae&player_version=5.52.0&&device_type=desktop&browser=chrome?country_code=FR
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/francetv.py", line 414, in get_live_url
                                                       return resolver_proxy.get_francetv_live_stream(plugin, broadcast_id)
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py", line 361, in get_francetv_live_stream
                                                       max_age=-1).text)['video']
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 493, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 487, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 442, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 415, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 943, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://player.webservices.francetelevisions.fr/v1/videos/006194ea-117d-4bcf-94a9-153d999c59ae&player_version=5.52.0&&device_type=desktop&browser=chrome?country_code=FR
2021-09-16 09:17:37.175 T:435     DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2021-09-16 09:17:37.178 T:1112    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 290, in error_handler
                                                       code = exception.code
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--

2021-09-16 09:17:37.179 T:1112    DEBUG <general>: onExecutionDone(11, /home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py)
2021-09-16 09:17:37.313 T:1112    DEBUG <general>: .
2021-09-16 09:17:37.622 T:1112     INFO <general>: Python interpreter stopped
2021-09-16 09:17:37.622 T:1112    DEBUG <general>: Thread LanguageInvoker 1282138304 terminating
2021-09-16 09:17:37.633 T:1113    DEBUG <general>: Thread scriptobs 1428140224 terminating

**Comment by Grouickman** [comment]
Nevermind, I'm dumb ! I chossed the wrong comit.

This one works : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/560/commits/6751a2ddba7431c52356214c11c8843143f389b8

**Comment by Phigen** [comment]
Merci, ça refonctionne correctement.
Dommage que la version "stable" intégrée au dépot de Kodi 19.1 soit totalement inutilisable chez moi.

**Comment by enigma131** [comment]
Commit 6751a2d didn't work here, kodi 19.1 Linux

**Comment by Phigen** [comment]
> Commit [6751a2d](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/6751a2ddba7431c52356214c11c8843143f389b8) didn't work here, kodi 19.1 Linux

I put this file :
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/6751a2ddba7431c52356214c11c8843143f389b8/resources/lib/resolver_proxy.py
into the plugin to replace the old file and this solve the problem on french channels (FranceTV).

**Comment by enigma131** [comment]
Thanks mate, it's working again !

**Comment by siick** [comment]
Thanks @Phigen it works now!

**Comment by Phigen** [comment]
It's not my work, thanks to Grouickman.

**Comment by Grouickman** [comment]
> It's not my work, thanks to Grouickman.

It's not my work either, I just found a pull request with the corrections...
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/560
credits goes to Arias800 for the actual corrections !

**Comment by mafatv** [comment]
Bonjour,

J'ai un souci : le patch fonctionne sans souci sous kodi depuis mon PC (pop OS 21.04).

Cependant, j'essaie de paramétrer un OSMC installé sur une raspberry pi 3+.
La version de kodi est la 19.1, la version d'OSMC est la 2021-07-15

Quand je met le fichier .zip modifié avec le patch sur la carte sd /home/osmc/catch_up et que je tente de l'installer depuis OSMC, j'ai une erreur : "L'installation de l'extension en fichier Zip depuis l'emplacement /home/osmc/catch_up/plugin.video.catchuptvandmore-dev.zip a échoué pour cause de structure invalide."

C'est le même zip qui marche sans souci sur pc desktop et qui plante sous OSMC. 

Quelqu'un sait quoi faire ?
