### ISSUE TITLE
Rmc decouverte and rmc story error

### ISSUE THREAD

**Issue by ricky074** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#594]
Hello,

I have some errors while playing rmc channels (drmc ecouverte and rmc story).
I can't display those channel....
I saw a closed issue #555 but the problem is still there...
I'm on the 0.2.37 beta 08 version (android)

Here is the log file :

2021-12-28 11:00:25.068 T:16166    INFO <general>: initializing python engine.
2021-12-28 11:00:25.317 T:16137   ERROR <general>: DoWork - Direct texture file loading failed for resource://resource.images.catchuptvandmore/channels/fr/rmcstory_fanart.jpg
2021-12-28 11:00:27.647 T:16166   ERROR <general>: [Catch-up-TV-&-More.support] 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/rmc.py", line 125, in get_live_url
                                                       data_account = live_datas.get('data-account')
                                                   AttributeError: 'NoneType' object has no attribute 'get'
2021-12-28 11:00:27.671 T:16166 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-12-28 11:00:32.215 T:16166    INFO <general>: CPythonInvoker(5, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2021-12-28 11:00:37.075 T:16166    INFO <general>: Python interpreter interrupted by user
2021-12-28 11:00:37.080 T:15979   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/rmc/get_live_url/?_pickle_=8004956b000000000000007d94288c075f7469746c655f948c21524d432053746f727920e28094204c6573206772616e64657320677565756c6573948c08786d6c74765f6964948c1543313430322e6170692e74656c6572616d612e6672948c076974656d5f6964948c08726d6373746f727994752e]
2021-12-28 11:00:37.091 T:15979    INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2021-12-28 11:00:41.062 T:16179    INFO <general>: initializing python engine.
2021-12-28 11:00:42.849 T:16179    INFO <general>: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run

**Comment by enigma131** [comment]
Same here under Linux, Kodi 19.3, plug-in latest beta

**Comment by nmaster2042** [comment]
Same on my Coreelec box 19.3 Matrix, plugin 0.2.37 beta 08.

**Comment by enigma131** [comment]
Installed beta 09. Still no solution ?

**Comment by enigma131** [comment]
Beta 11 .. Still nothing

**Comment by vinceducat** [comment]
Beta 15 stiil no solution ?  :-(

**Comment by enigma131** [comment]
Same here, list index out of range ... :-(

**Comment by joaopa00** [comment]
Le replay fonctionne normalement. Si vous savez comment récupérer le direct, merci de partager.

**Comment by nmaster2042** [comment]
Toujours la même erreur de mon côté sur RMC Découverte & RMC Story avec la dernière version.

**Comment by joaopa00** [comment]
Fonctionne très bien chez moi. On est en phase de tests: Tu dois remplir tes identifiants pour le site de RMC. Ensuite, il faut que WIdevine soit installé sur ton appareil. Enfin, il faut chercher la vidéo dans l'item RMCBFMPlay

**Comment by enigma131** [comment]
Pour le live j'ai pas les liens, mais Captvty est ok pour les RMC

**Comment by joaopa00** [comment]
La télévision par rattrage et le direct des chaines RMC sont fonctionnels dans la branche dev. Si vous constatez des bugs en utilisant cette dernière version, merci d'ouvrir un nouveau rapport de bug en y attachant un log. Merci d'avance.

**Comment by enigma131** [comment]
Fonctionne ici, voir #565

**Comment by nmaster2042** [comment]
Fonctionne avec la dernière version pour moi désormais, merci

**Comment by vinceducat** [comment]
apres beta44 erreur authentification pour RMC story et decouverte error 403 :-(  bien  que le compte soit bien renseigné dans les parametres de CU TV :-(

**Comment by Arias800** [comment]
Essaye de te connecter via l'application Android officiel de rmcbfmplay.
Ça permettra de savoir c'est lié a l'addon ou si le facteur est externe.
Quelqu'un a déjà eu un problème similaire, c'était le fournisseur de la connexion qui posait un problème.
Donc impossible à corriger pour nous.

**Comment by vinceducat** [comment]
Merci a vous, lors de la mise a jour quelque chose n a pas du bien ce passé, le compte avait été verouillé pour defaut de mot de passe :-( donc reinitialisation sur le site RMCBFM et re saisie du mdp tout est ok ..

merci encore pour cet Add-On
