### ISSUE TITLE
can't search channels in France folder

### ISSUE THREAD

**Issue by daufinsyd** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#685]
### Describe the bug
can't search channels in folder (at least for France)

### To Reproduce
Steps to reproduce the behaviour:
0. Go-to Direct TV
1. Try to open some folder (ex France from direct tv)
2. Failed because of "ASCII Codec can't encode character u'\xe9' "

### Expected behaviour
Folder open and displays list of channels from the country

### Actual behaviour
Folder with list of channels won't open

### Screenshots
:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:
 - Catch-up TV & More version:
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by darodi** [comment]
No problem here.

Linux osmc 5.10.32-2-osmc armv7l
raspberry pi 3b
Kodi matrix 19.3

shouldn't happen normally 
`# -*- coding: utf-8 -*-`
is present as a header for each file.

Do you have more information?

- A log file?
- Operating system version/name:
- Kodi version:
- Catch-up TV & More version:
- Installation method:

**Comment by joaopa00** [comment]
This bug looks similar to issue #678

**Comment by daufinsyd** [comment]
Hello

Yes I'm Using Leia 18.9.0 Git:leia_pi4_18.9-Leia (with LibreElec)
Yes here it is (sorry I forgot to include it):

```
2022-03-09 19:11:21.080 T:2510811904   ERROR: [Catch-up-TV-&-More.support] 'ascii' codec can't encode character u'\xe9' in position 5: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                redirect = parent_ins(route, arg_params, self.callback_params)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                session_data = self._process_results(results)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                listitems = validate_listitems(results)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                raw_listitems = list(raw_listitems)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 136, in tv_guide_menu
                                                for item in generic_menu(plugin, live_country_id):
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 61, in generic_menu
                                                menu = get_sorted_menu(plugin, menu_id)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/menu_utils.py", line 167, in get_sorted_menu
                                                desired_language = utils.ensure_unicode(Script.setting[item_id + '.language'])
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 40, in __getitem__
                                                return addon_data.getSetting(key)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 5: ordinal not in range(128)
2022-03-09 19:11:43.959 T:2529780480   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/main/tv_guide_menu/?_pickle_=80027d71012858070000006974656d5f69647102580700000066725f6c697665710355075f7469746c655f710458060000004672616e63655808000000786d6c74765f696471054e752e
2022-03-09 19:11:43.987 T:3010811264   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/resources/lib/main/tv_guide_menu/?_pickle_=80027d71012858070000006974656d5f69647102580700000066725f6c697665710355075f7469746c655f710458060000004672616e63655808000000786d6c74765f696471054e752e) failed
2022-03-09 19:11:44.503 T:2510811904   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/main/generic_menu/?_pickle_=80027d71012858070000006974656d5f6964710258070000006c6976655f7476710355075f7469746c655f7104580c000000545620656e206469726563745808000000786d6c74765f696471054e752e
2022-03-09 19:11:44.518 T:3010811264   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/resources/lib/main/generic_menu/?_pickle_=80027d71012858070000006974656d5f6964710258070000006c6976655f7476710355075f7469746c655f7104580c000000545620656e206469726563745808000000786d6c74765f696471054e752e) failed
2022-03-09 19:11:48.870 T:3010811264   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
```

I'm running Raspberry pi 4
LE Version: 9.2.7
CatchUp Version: 0.2.37
I Installed Catch-Up TV using the official documentation (with repo so that it can auto upate).

**Comment by joaopa00** [comment]
Can you test the latest beta:
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/archive/refs/heads/dev.zip

**Comment by darodi** [comment]
seems to be a librelec problem.
You should try that:

https://forum.libreelec.tv/thread/24898-error-with-plexkodiconnect/


> Well after some research i installed the Locale addon in the libreelec repository and the errors disapear..
> I hope everything goes fine from now on ;)

**Comment by PrPierre** [comment]
Having the same issue using Raspberry Pi OS.

- Kodi version : 18.7 (latest available for my OS)
- Catch Up addon version : v0.2.37
- Hardware : Raspberry Pi 3 B
-  kernel version : 5.10
-  Debian version : 10 (Buster)

**Comment by joaopa00** [comment]
Did you try what darodi said in the message above yours?

**Comment by PrPierre** [comment]
> Did you try what darodi said in the message above yours?

Since I am not using librelec (Raspberry Pi OS instead), I thought there was no addon to install on my side, is there any equivalent ?

**Comment by joaopa00** [comment]
In a terminal, what gives the command
locale

mine is
LANG=fr_FR.UTF-8
LANGUAGE=fr
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=

**Comment by chrysal** [comment]
> seems to be a librelec problem. You should try that:
> 
> https://forum.libreelec.tv/thread/24898-error-with-plexkodiconnect/
> 
> > Well after some research i installed the Locale addon in the libreelec repository and the errors disapear..
> > I hope everything goes fine from now on ;)

Thanks darodi it did the trick for me (Rasberry PI3 with Libreelec 9.2.8)

**Comment by daufinsyd** [comment]
> seems to be a librelec problem. You should try that:
> 
> https://forum.libreelec.tv/thread/24898-error-with-plexkodiconnect/
> 
> > Well after some research i installed the Locale addon in the libreelec repository and the errors disapear..
> > I hope everything goes fine from now on ;)

Thank you ! It solved the issue.
However I still don't understand why it worked until a few days ago. I didn't updated libreelec in weeks.

**Comment by joaopa00** [comment]
>Since I am not using libreelec (Raspberry Pi OS instead), I thought there was no addon to install on my side, is there any equivalent ?

Another user had success in upgrading Widevine. You could give a try. (see issue #695)

**Comment by joaopa00** [comment]
Problème de rasperry, pas de Catchtvandmore.
