### ISSUE TITLE
'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)

### ISSUE THREAD

**Issue by nax870** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#695]
### Describe the bug
Bonjour, depuis hier j'obtiens une erreur en essayant de lire les fichiers du replay de TF1, TMC, ...
Est-ce un problème connu? Merci d'avance de votre aide.

### Your environment
Raspberry-Pi

 - Operating system version/name: Libreelec 9.2.8
 - Kodi version: 18.9
 - Catch-up TV & More version: 0.2.38-beta03

### Debug log
`2022-03-13 20:09:46.613 T:1639867264   ERROR: [Catch-up-TV-&-More.support] 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                redirect = parent_ins(route, arg_params, self.callback_params)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                results = super(Resolver, self).__call__(route, args, kwargs)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                return route.function(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/mytf1.py", line 275, in get_video_url
                                                if not is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 359, in _check_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 329, in _check_widevine
                                                self._update_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 288, in _update_widevine
                                                latest_version = latest_widevine_version()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 164, in latest_widevine_version
                                                devices = chromeos_config()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
                                                return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 73, in http_get
                                                return content.decode()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)`

**Comment by b46-2022** [comment]
J'ai le même problème avec les mêmes versions de kodi et Catch-up TV, sur raspberry.

Ça fonctionne par contre sur kodi 19 sur mon laptop.

J'ai réussi à contourner le problème en commentant les lignes 275 et 276 dans le fichier .kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/mytf1.py.

**Comment by joaopa00** [comment]
Avez-vous installé l'addon locale?

voir l'issue #685

**Comment by nax870** [comment]
Merci @joaopa00 L'installation de l'addon Locale échouait sur mon raspberry sans que je ne trouve pourquoi.
La source du problème c'etait Widevine, mais forcer la réinstallation via InputStream helper ne marchait pas.

@b46-2022 J'ai résolu le problème en mettant à jour ma version de LibreELEC sur mon raspberry (9.2.8 >> 10.0)
Ensuite la réinstallation de Widevine CDM s'est bien passée, et tout fonctionne à nouveau.
