### ISSUE TITLE
Schedules Direct support

### ISSUE THREAD

**Issue by sy6sy2** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#699]
Hello @JungleJim42

J'ouvre une nouvelle issue ici afin qu'on continue la discussion concernant https://github.com/Catch-up-TV-and-More/xmltv/issues/15.
En effet, comme le support de Schedules Direct va se faire directement dans le plugin et non dans le backend chargé de générer les fichiers XMLTV je préfère qu'on passe sur ce repo.

Déjà un grand merci pour ton aide concernant le service Schedules Direct !

Je viens de push le commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/2dda805a09393de209c352a64cfa1dbba88a9b9b qui est (logiquement) la toute première version du plugin qui permet de récupérer les guides TV de Schedules Direct.

Ce n'est que la version alpha, il y a encore une bonne liste de choses à faire que je vais détailler ici sous forme de TODO.

Si tu peux, aurais tu s'il te plait la possibilité de tester la version 0.2.38~beta05 du plugin afin de nous faire tes premiers retours ?
Tu auras besoin d'aller dans les préférences du plugin pour renseigner ton user et mot de passe de Schedules Direct (dans la section Account).

Merci d'avance pour tes retours!

TODO:

- [x] Fix flake8
- [x] Ignorer les chaines qui ne sont pas dans le plugin pour générer plus rapidement le fichier XMLTV
- [x] Pouvoir télécharger les programmes TV de J+1, J+2, ....
- [x] Vérifier que cela fonctionne avec IPTV Manager
- [ ] Vérifier s'il n'y a pas de décalage horaire
- [x] Si une exception est levée, supprimer les fichiers XML
- [x] Ajouter une notification pour indiquer à l'user que Kodi est en train de DL le guide TV

**Comment by JungleJim42** [comment]
Bonjour! Voici les premiers résultats:
- j'ai bien installé la version 0.2.38 beta09.
- dans les paramètres, je peux entrer mes coordonnées schedules direct (username, password, lineup)
- quand je vais dans iptv manager et que je demande un refresh de "channels and guide", il s'active et me fait un message de "downloading tv guide". Tout s'exécute sans erreurs.
- dans /userdata/addon_data/plugin.video.catchuptvandmore/, il y a les tv_guide_fr_20220318.xml (et autres) pour FR et pour WO mais pas pour CA.
- le fichier /userdata/addon_data/service.iptv.manager est bien mis à jour, il contient les "channel id" de toutes les chaines (CA et autres), mais pour les informations "programme", il n'y a pas les programmes des chaînes CA.
- dans le guide à l'intérieur de Kodi, le guide est correct pour les châines autres que CA, mais vide pour celle CA.

Voici le log de Kodi, il semble y avoir une erreur ascii:
2022-03-18 09:54:53.227 T:9714     INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Updating IPTV data for plugin.video.catchuptvandmore...
2022-03-18 09:54:53.227 T:9714     INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Requesting channels from plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/channels/...
2022-03-18 09:54:53.232 T:9714     INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Executing RunPlugin(plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/channels/?port=40093)...
2022-03-18 09:54:53.245 T:9715     INFO <general>: initializing python engine.
2022-03-18 09:54:53.591 T:9715     INFO <general>: CPythonInvoker(8, /home/alexandre/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2022-03-18 09:54:53.606 T:9714     INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Requesting epg from plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/epg/...
2022-03-18 09:54:53.615 T:9715     INFO <general>: Python interpreter stopped
2022-03-18 09:54:53.616 T:9714     INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Executing RunPlugin(plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/epg/?port=56647)...
2022-03-18 09:54:53.628 T:9716     INFO <general>: initializing python engine.
2022-03-18 09:54:53.979 T:7342     INFO <general>: CActiveAESink::OpenSink - initialize sink
2022-03-18 09:54:54.230 T:7342     INFO <general>: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms Periodsize 50 ms
2022-03-18 09:54:58.137 T:9716    ERROR <general>: [Catch-up-TV-&-More] xmltv module failed with error: 'ascii' codec can't encode character '\xe9' in position 3242: ordinal not in range(128)
2022-03-18 09:55:08.726 T:9716     INFO <general>: Skipped 3 duplicate messages..
2022-03-18 09:55:08.726 T:9716     INFO <general>: CPythonInvoker(9, /home/alexandre/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2022-03-18 09:55:08.751 T:9716     INFO <general>: Python interpreter stopped
2022-03-18 09:55:08.874 T:9712     INFO <general>: PVR Manager: Stopping
2022-03-18 09:55:08.874 T:7423     INFO <general>: EPG Container: Persisting unsaved events...
2022-03-18 09:55:08.874 T:7423     INFO <general>: EPG Container: Persisting events done
2022-03-18 09:55:09.429 T:9712     INFO <general>: PVR Manager: Stopped
2022-03-18 09:55:09.950 T:7336  WARNING <general>: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2022-03-18 09:55:09.953 T:9714     INFO <general>: Skipped 7 duplicate messages..
2022-03-18 09:55:09.953 T:9714     INFO <general>: CPythonInvoker(7, /home/alexandre/.kodi/addons/service.iptv.manager/default.py): script successfully run
2022-03-18 09:55:09.964 T:9714     INFO <general>: Python interpreter stopped
2022-03-18 09:55:09.972 T:7336  WARNING <general>: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2022-03-18 09:55:11.280 T:9712     INFO <general>: Skipped 8 duplicate messages..
2022-03-18 09:55:11.280 T:9712     INFO <general>: ADDON: Dll Destroyed - PVR IPTV Simple Client
2022-03-18 09:55:11.284 T:9713     INFO <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - Create - Creating the PVR IPTV Simple add-on
2022-03-18 09:55:11.292 T:9713     INFO <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadPlayList Playlist Loaded - 1 (ms)
2022-03-18 09:55:11.292 T:9713     INFO <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadPlayList - Loaded 6 channels.
2022-03-18 09:55:11.292 T:9713     INFO <general>: AddOnLog: pvr.iptvsimple: Create Starting separate client update thread...
2022-03-18 09:55:11.292 T:9713     INFO <general>: PVR Manager: Starting
2022-03-18 09:55:11.403 T:9725     INFO <general>: PVR Manager: Started

**Comment by joaopa00** [comment]
Si tu es sur Libreelec, as-tu installer l'extension locale?

**Comment by JungleJim42** [comment]
Je suis sous Ubuntu. Je ne sais pas ce que tu veux dire par extension locale. J'ai téléchargé le code de la version  0.2.38 beta09 en tant que .zip, puis dans Kodi j'ai fait "installer un addon à partir d'un zip".

**Comment by joaopa00** [comment]
L'extension locale est seulement pour Libreelec. Oublie ça. Tu es sous quelle version de Ubuntu et de Kodi?

**Comment by JungleJim42** [comment]
Ubuntu 20.04 et Kodi 19.4

**Comment by darodi** [comment]
@JungleJim42 
quel est le résultat de ces commandes?

```
locale -a | grep "UTF-8"
env|grep -E '(LC|LANG)'
cat /etc/default/locale
python -c "print (u'voil\u00e0')"
```

**Comment by JungleJim42** [comment]
locale -a | grep "UTF-8"
C.UTF-8

env|grep -E '(LC|LANG)'
LANGUAGE=fr_CA:fr
LANG=fr_CA.UTF-8

cat /etc/default/locale
#  File generated by update-locale
LANG="fr_CA.UTF-8"
LANGUAGE="fr_CA:fr"

python3 -c "print (u'voil\u00e0')"
voilà

**Comment by darodi** [comment]
@JungleJim42 

ce qui m'étonne, c'est que fr_CA.UTF-8 n'est pas renvoyé par 
`locale -a`


il faudrait peut être essayer:

```
sudo locale-gen fr_CA.UTF-8
sudo locale-gen fr_CA
```

ou encore 

`sudo apt-get install language-pack-fr`

**Comment by JungleJim42** [comment]
locale -a (sans | grep "UTF-8") me donne:
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IL
en_IL.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
fr_BE.utf8
fr_CA.utf8
fr_CH.utf8
fr_FR.utf8
fr_LU.utf8
POSIX

Donc si je comprends bien, fr_CA.utf8 est bien présent

**Comment by JungleJim42** [comment]
J'ai testé sur un autre appareil (aussi Ubuntu 20.04 et Kodi 19.4) et j'ai exactement la même erreur dans le log de Kodi:
ERROR : [Catch-up-TV-&-More] xmltv module failed with error: 'ascii' codec can't encode character '\xe9' in position 3242: ordinal not in range(128)

**Comment by JungleJim42** [comment]
Cette erreur semble commune: https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

**Comment by joaopa00** [comment]
Ce genre de problème n'est pas sensé se produire avec Matrix puisqu'il utilise normaleemntPython3 qui n'utilise que l'UTF et pas l'ascii.. Peux-tu essayer sur une nouvelle version d'Ubuntu? Impish serait l'idéal.

**Comment by sy6sy2** [comment]
Je viens de tester, et je n'ai pas cette erreur d'encoding. Quand j'active IPTVManager j'ai bien les trois fichiers 

```
tv_guide_ca_20220319.xml
tv_guide_ca_20220320.xml
tv_guide_ca_20220321.xml
tv_guide_ca_20220322.xml
```

qui sont téléchargés dans mon dossier user data.

Après je suis sur macOS, donc Kodi utilise le binaire Python intégré à Kodi. Et comme le dit joapa00, il me semble que sous Linux Kodi utilise le. Python exposé par le système, ce qui explique peut être la différence.

Je vais essayé de reproduire dans un VM Ubuntu pour voir si j'arrive à reproduire.

**Comment by sy6sy2** [comment]
Re, peux tu essayer la version 0.2.38~beta11 du plugin stp ? Je pense avoir résolu le problème, en tout cas dans mon cas ça fonctionnement maintenant sur ma VM Ubuntu.
Merci !

**Comment by JungleJim42** [comment]
Un gros merci pour les efforts pour cette fonctionnalité! J'ai installé 0.2.38-beta11 et malheureusement ça ne fonctionne toujours pas. Il s'installe bien mais j'ai une nouvelle erreur quand je "refresh" les chaînes et les programmes dans IPTV manager:
ERROR <general>: [Catch-up-TV-&-More.support] invalid syntax (sd_json.py, line 283)

Voici le log de kodi:

2022-03-19 09:46:03.190 T:6552     INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Updating IPTV data for plugin.video.catchuptvandmore...
2022-03-19 09:46:03.190 T:6552     INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Requesting channels from plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/channels/...
2022-03-19 09:46:03.195 T:6552     INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Executing RunPlugin(plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/channels/?port=54505)...
2022-03-19 09:46:03.199 T:6553     INFO <general>: initializing python engine.
2022-03-19 09:46:03.730 T:6553    ERROR <general>: [Catch-up-TV-&-More.support] invalid syntax (sd_json.py, line 283)
                                                   Traceback (most recent call last):
                                                     File "/home/alexandre/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 300, in run_callback
                                                       route = self.get_route(self.selector)
                                                     File "/home/alexandre/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 248, in get_route
                                                       importlib.import_module(module_path)
                                                     File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
                                                       return _bootstrap._gcd_import(name[level:], package, level)
                                                     File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 848, in exec_module
                                                     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
                                                     File "/home/alexandre/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/iptvmanager.py", line 17, in <module>
                                                       from resources.lib.xmltv import grab_programmes
                                                     File "/home/alexandre/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/xmltv.py", line 32, in <module>
                                                       from resources.lib.xmltv_utils.sd_json import SD_JSON
                                                     File "/home/alexandre/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/xmltv_utils/sd_json.py", line 283
                                                       et.SubElement(programme, "episode-num", attrib={"system": "dd_progid"}).text =  '{}.{}'.format(pgm["programID"], pgmid_counts[pgm["programID"]]:0 + '{}'.format(pgm_prec)d)
                                                                                                                                                                                                      ^
                                                   SyntaxError: invalid syntax

**Comment by JungleJim42** [comment]
Si je retire les lignes 280 à 284 de sd_json.py (celles ayant trait à  episode-num), le plugin s'exécute mais ne produit toujours pas de fichiers tv_guide_ca_date.xml. Dans ce cas voici le log:

2022-03-19 10:00:56.157 T:4408     INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Updating IPTV data for plugin.video.catchuptvandmore...
2022-03-19 10:00:56.157 T:4408     INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Requesting channels from plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/channels/...
2022-03-19 10:00:56.162 T:4408     INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Executing RunPlugin(plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/channels/?port=52565)...
2022-03-19 10:00:56.166 T:4409     INFO <general>: initializing python engine.
2022-03-19 10:00:57.041 T:4409     INFO <general>: CPythonInvoker(5, /home/alexandre/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2022-03-19 10:00:57.068 T:4408     INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Requesting epg from plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/epg/...
2022-03-19 10:00:57.073 T:4409     INFO <general>: Python interpreter stopped
2022-03-19 10:00:57.073 T:4408     INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Executing RunPlugin(plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/epg/?port=33513)...
2022-03-19 10:00:57.091 T:4410     INFO <general>: initializing python engine.
2022-03-19 10:01:04.360 T:4410    ERROR <general>: [Catch-up-TV-&-More] xmltv module failed with error: write() argument must be str, not bytes
2022-03-19 10:01:17.085 T:4410    ERROR <general>: Skipped 2 duplicate messages..
2022-03-19 10:01:17.085 T:4410    ERROR <general>: [Catch-up-TV-&-More] xmltv module failed with error: write() argument must be str, not bytes
2022-03-19 10:01:22.979 T:4410     INFO <general>: CPythonInvoker(6, /home/alexandre/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2022-03-19 10:01:23.004 T:4410     INFO <general>: Python interpreter stopped
20

**Comment by JungleJim42** [comment]
Je ne sais pas si ça peut aider, mais voici les versions de python installées sur mon poste:

~$ python3 --version
Python 3.8.10
~$ python2 --version
Python 2.7.18
~$ python --version

La commande « python » n'a pas été trouvée, voulez-vous dire :

  commande « python3 » du deb python3
  commande « python » du deb python-is-python3

**Comment by joaopa00** [comment]
J'ai poussé une rustine dans git. Peux-tu refaire un essai?
Merci d'avance.

**Comment by JungleJim42** [comment]
On avance! Avec le beta12, je n'ai plus l'erreur invalid syntax, le script s'exécute, mais j'ai une nouvelle erreur:
ERROR <general>: [Catch-up-TV-&-More] xmltv module failed with error: write() argument must be str, not bytes

Voici le log:
2022-03-19 14:42:46.365 T:15004    INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Updating IPTV data for plugin.video.catchuptvandmore...
2022-03-19 14:42:46.365 T:15004    INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Requesting channels from plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/channels/...
2022-03-19 14:42:46.370 T:15004    INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Executing RunPlugin(plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/channels/?port=56965)...
2022-03-19 14:42:46.375 T:15005    INFO <general>: initializing python engine.
2022-03-19 14:42:46.743 T:15005    INFO <general>: CPythonInvoker(6, /home/alexandre/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2022-03-19 14:42:46.766 T:15005    INFO <general>: Python interpreter stopped
2022-03-19 14:42:46.767 T:15004    INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Requesting epg from plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/epg/...
2022-03-19 14:42:46.767 T:15004    INFO <general>: [service.iptv.manager] [resources.lib.modules.addon] Executing RunPlugin(plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/epg/?port=38075)...
2022-03-19 14:42:46.775 T:15006    INFO <general>: initializing python engine.
2022-03-19 14:42:52.944 T:15006   ERROR <general>: [Catch-up-TV-&-More] xmltv module failed with error: write() argument must be str, not bytes
2022-03-19 14:43:03.227 T:15006   ERROR <general>: Skipped 1 duplicate messages..
2022-03-19 14:43:03.227 T:15006   ERROR <general>: [Catch-up-TV-&-More] xmltv module failed with error: write() argument must be str, not bytes
2022-03-19 14:43:10.715 T:15006    INFO <general>: Skipped 1 duplicate messages..
2022-03-19 14:43:10.715 T:15006    INFO <general>: CPythonInvoker(7, /home/alexandre/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2022-03-19 14:43:10.742 T:15006    INFO <general>: Python interpreter stopped

**Comment by joaopa00** [comment]
Peux-tu activer le mode debug de Kodi et attacher (pas copier...) le fichier log.txt?
Merci d'avance

**Comment by JungleJim42** [comment]
Dis-moi si c'est ce dont tu as besoin:
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8309912/kodi.log)

**Comment by joaopa00** [comment]
C'est ce qui était demandé. Au passage, comme prévu tu as les deux vesions de Python installés et kodi utilise la version 2.

**Comment by joaopa00** [comment]
La version attachée est une version de débiggage. Elle ne résout pas le problème. Peut-tu l'essayer et attacher de nouveau le fichier log.txt?
Merci d'avance

[plugin.video.catchuptvandmore-dev.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8309967/plugin.video.catchuptvandmore-dev.zip)

**Comment by JungleJim42** [comment]
Le dernier .zip était 2.37.beta11. Voici le log:
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8309994/kodi.log)

**Comment by joaopa00** [comment]
Désolé. Je me suis trompé de fichier. C'est celui-ci. Peux-tu réattacher le fichier log.txt en testant le fichier joint?
Merci d'avance

https://docs.google.com/uc?export=download&id=1tqUmhXfyE7ghsEoqZnnmIwU0cpDkpYid

**Comment by JungleJim42** [comment]
Pas de problème, ça me fait plaisir d'aider comme je peux. Par contre le lien au dernier téléchargement fait une erreur 404

**Comment by joaopa00** [comment]
Tu es sûr pour le lien. Chez moi, il fonctionne parfaitement

**Comment by JungleJim42** [comment]
Ça ne fonctionne pas du tout. Google dit erreur 404. Désolé.

**Comment by joaopa00** [comment]
Ca devrait fonctionner maintenant.

**Comment by JungleJim42** [comment]
Le fichier a bien fonctionné (55 megs v0238-beta12 mais le résultat est le même. Il ne génère pas les fichiers tv_guide_ca_date.xml.
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8310172/kodi.log)

**Comment by joaopa00** [comment]
Une nouvelle version:


[plugin.video.catchuptvandmore-dev.zip](https://docs.google.com/uc?export=download&id=1PjYt6YmqWALyLKr1ZVAP8Bzbk3-fs3F9)

**Comment by JungleJim42** [comment]
Désolé. Toujours le même résultat même avec cette dernière version. Je vois qu'il télécharge les programmes mais il ne réussit pas à écrire les fichiers tv_guide_ca_date.xml:
ERROR <general>: [Catch-up-TV-&-More] xmltv module failed with error: write() argument must be str, not bytes

[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8310322/kodi.log)

**Comment by JungleJim42** [comment]
J'ai trouvé!
dans sd_json.py
à la ligne 362, il faut ajouter "b" à "wb", et enlever ", encoding="utf-8""
ce qui donne:
        with open(self.xmltv_filepath, 'wb') as f:
Avec ce changement, il écrit les fichiers tv_guide_ca et les intègre dans le epg. Tout fonctionne!
Je ne sais pas par contre si ce changement va nuire à d'autres configurations que la mienne...

**Comment by JungleJim42** [comment]
Aussi, maintenant que ça fonctionne, je confirme que le décalage horaire est correct :+1:

**Comment by joaopa00** [comment]
Super!! Veux-tu envoyer une Pull Request pour corriger le problème?

**Comment by JungleJim42** [comment]
Je ne sais pas comment faire cela. Peux-tu le faire pour moi ou m'expliquer?
Je vous dois un énorme merci pour tout le temps que vous avez mis là-dessus!

**Comment by joaopa00** [comment]
Pas de problème. Je vais la faire. Je te mets en auteur du patch.

**Comment by JungleJim42** [comment]
Wow merci, c'est un honneur :1st_place_medal:

**Comment by joaopa00** [comment]
Quel est ton email. C'est obligatoire pour te mettre en auteur: JungleJin42@...?

**Comment by JungleJim42** [comment]
wazowazo@gmail.com. Merci!
PS: avez-vous testé que ma modification ne nuise pas à d'autres configurations?

**Comment by joaopa00** [comment]
La modification est correcte. C'était la prochaine modification sur celle possible que je souhaitais faire. Tu m'as superbement devancé  :dancers:

**Comment by joaopa00** [comment]
As-tu des problèmes de décalages horaires?

**Comment by JungleJim42** [comment]
Non, l'heure est bonne, il n'y a pas de décalage :-1:

**Comment by JungleJim42** [comment]
Je voudrais déplacer la chaîne "ici-rdi" du sous-groupe "wo" vers le sous-groupe "ca". Il s'agit d'une chaîne canadienne qui intéresse surtout les québecois. Ce changement dans le groupe "ca" permettrait aussi d'utiliser le GÉP qui sera fourni avec la nouvelle fonction Schedules direct. Je sais quels changements il faudrait faire pour implanter cela, mais je ne sais pas comment les intégrer (c'est ma première expérience avec Github). Je vous fais une liste de modifications? Je fais une nouvelle branche de dev? 
Voici toutes les modifications à faire: 
- déplacer le fichier icirdi.py de ressources/lib/channels/wo vers /ressources/lib/channels/ca
- déplacer la section "icirdi" du fichier ressources/lib/skeletons/wo_live.py vers le fichier /ressources/lib/skeletons/ca_live.py (modifier les 3 liens "wo" pour "ca") (le xml_id est déjà bon pour schedules direct)
- déplacer addons/ressources.images.catchuptvandmore/channels/wo/icirdi.png vers ../ca
Dans un test local avec ces changements, tout fonctionne!

**Comment by JungleJim42** [comment]
Autre commentaire: la chaîne Télé-mag n'est pas une chaine très populaire. Il existe un guide de programmes sur Schedules direct, mais il est dans un autre "lineup" que toutes les autres chaines. J'ai cherché mais aucun lineup ne comprend toutes les autres chaînes ET télé-mag.
Je ne sais pas si c'est complexe à implanter (ne pas faire quelque chose de compliqué pour cette chaîne peu écoutée), mais je peux vous donner les coordonnées: 
Lineup: 0004980-X
Identificateur de la chaîne: I72595.json.schedulesdirect.org
Le xml_id est déjà inclus dans ca_live.py, mais ne donne pas de résultat puisque le lineup est différent.

**Comment by joaopa00** [comment]
Si tu ne veux pas t'embêter à faire une pull request, tu peux faire un patch et l'attacher ainsi. Je le pousserai alors dans Git. Voici un wiki qui explique très bien comment faire un patch: [gérer Github](https://wiki.winehq.org/Git_Wine_Tutorial)

**Comment by JungleJim42** [comment]
J'ai essayé de faire un pull request pour les changements pour transférer icirdi du groupe WO vers le groupe CA. Il y a un pull request dans plugin.video.catchuptvandmore et un autre dans ressources.images.catchuptvandmore (pour seulement l'image).
C'est la première fois que je fais un pull request, en espérant que c'est bon et que je n'ai rien démantibulé :-P

**Comment by joaopa00** [comment]
JungleJim42 a confirmer qu'il n'y pas de problème de décalage horaire. On peut considérer cette issue comme résolue. S'il y a encore des problèmes, merci d'ouvrir un nouveau rapport.
