### ISSUE TITLE
Encoding error when trying to open TF1 (and others)

### ISSUE THREAD

**Issue by Biniou180** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#700]
Hi / Bonjour, 

I recently encounter an issue (since ~ 13/03/2022) when trying to watch TF1, TFX or TF1 Séries Films (other channels like Arte, France Televisions etc are working). When opening the channel, the following error occurs in the kodi logs. 

```
2022-03-17 21:06:11.568 T:1740579712   ERROR: [Catch-up-TV-&-More.support] 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
  Traceback (most recent call last):
    File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
      redirect = parent_ins(route, arg_params, self.callback_params)
    File "/storage/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
      results = super(Resolver, self).__call__(route, args, kwargs)
    File "/storage/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
      return route.function(self, *args, **kwargs)
    File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/mytf1.py", line 306, in get_live_url
      if not is_helper.check_inputstream():
    File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
      return self._check_drm()
    File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 359, in _check_drm
      return self._check_widevine()
    File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 329, in _check_widevine
      self._update_widevine()
    File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 288, in _update_widevine
      latest_version = latest_widevine_version()
    File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 164, in latest_widevine_version
      devices = chromeos_config()
    File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
      return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
    File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 73, in http_get
      return content.decode()
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)

```

My current config is  : 

  * Kodi Leia 18.9 (LibreElec 9.2.8, on a raspberry Pi 2)
  * Catch-up extension v0.2.37
  * inputstreamhelper v0.5.8

I'm not sure where it comes from as only particular channels are not working (DRM related?)
Could you please help me on this subject?

Thanks a lot (and thanks for all the work done on this extension! :-))

**Comment by joaopa00** [comment]
As-tu installé l'addon locale?

**Comment by Biniou180** [comment]
(for english readers, please see below)

Bonjour Jaopao00,
Je ne sais pas si j'ai installé l'addon locale, mais j'ai fini par trouver le problème après une soirée de recherche! C'était InputStreamHelper qui avait des soucis pour lancer / mettre à jour Widevine. J'ai installé un paquet correctif trouvé dans leur github et ca a marché (je mets en anglais en dessous dans la continuité de mon message initial). Du coup désolé pour le bruit.

**After several hours searching information on this, I have found a solution!** 
The problem was not Catch-up TV add-on but InputStreamHelper that was not able to launch / re-install widevine.
I've seen the problem when going to the options of InputStreamHelper and trying to reinstall widevine : the uninstall was working the installation was failing with same error as my first post.
Searching in their github i was able to find a recent issue concerning last CDM version problems and a fix to try to address them : https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/497#issuecomment-1068239609
After installing their zip, everything was working fine again :-)

I'm sorry to have opened a ticket here as it was not a Catch-up TV extension issue, but i hope this will help other people.
Regards!

**Comment by raphaelbrugier** [comment]
Bonjour / Hello,

I have the same error on my Kodi 18.9 install on a fire tv stick.
If I understood correctly, the issue is with an upstream library.

@Biniou180 How did you install the zip with the fix for the InputStreamHelper? 
Did you do it by connecting to the server running Kodi, or is it something you can do from the Kodi interface?

**Comment by 0rganite** [comment]
Thanks Biniou180. https://github.com/emilsvennesson/script.module.inputstreamhelper/files/8255662/script.module.inputstreamhelper-0.5.8-install_from-101f947.zip Works for me. @raphaelbrugier just install zip through the Kodi interface (install add-on from zip)

**Comment by Biniou180** [comment]
@raphaelbrugier i have installed the zip through the kodi interface as @0rganite has said (i've used SSH to copy the file, but you can do the copy as you want :))

**Comment by mpommarel** [comment]
Merci bcp j'avais le même problème depuis plusieurs jour. Installation du zip, maj widevine et c'est reparti. Thanks a lot!

**Comment by raphaelbrugier** [comment]
@Biniou180 Merci pour la réponse. Une version 0.59 a été créée depuis, mais j'avais également un problème pour la télécharger car sa publication avait échouée.

Mon problème c'est surtout que je ne peux pas SSH directement sur une clé Kindle fire, donc pas aussi facile.

Je n'ai pas compris le point sur Widevine. 
C'est un service à redémarrer dans Kodi?

**Comment by darodi** [comment]
@raphaelbrugier 
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/740
