### ISSUE TITLE
Python error on beta 11

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#701]
### Describe the bug
A clear and concise description of what the bug is: Python error

### To Reproduce on Linux ( Mint / Ubuntu 2004)
Steps to reproduce the behaviour:
1. Launch interface and go to french list

log extract : 
2022-03-19 15:42:48.329 T:15210   ERROR <general>: [Catch-up-TV-&-More.support] invalid syntax (sd_json.py, line 283)
                                                   Traceback (most recent call last):
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                       session_data = self._process_results(results)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                       listitems = validate_listitems(results)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                       raw_listitems = list(raw_listitems)
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 132, in tv_guide_menu
                                                       xmltv = importlib.import_module('resources.lib.xmltv')
                                                     File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
                                                       return _bootstrap._gcd_import(name[level:], package, level)
                                                     File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 848, in exec_module
                                                     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/xmltv.py", line 32, in <module>
                                                       from resources.lib.xmltv_utils.sd_json import SD_JSON
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/xmltv_utils/sd_json.py", line 283
                                                       et.SubElement(programme, "episode-num", attrib={"system": "dd_progid"}).text =  '{}.{}'.format(pgm["programID"], pgmid_counts[pgm["programID"]]:0 + '{}'.format(pgm_prec)d)
                                                                                                                                                                                                      ^
                                                   SyntaxError: invalid syntax

**Comment by f28gin** [comment]
#678

**Comment by joaopa00** [comment]
J'ai poussé un patch pour remédier au problème. En espérant qu'il fonctionne...
Le but des précédentes modifications étaient de garder la compatibilité avec Kodi Leia. Désolé pour le dérangement.

**Comment by joaopa00** [comment]
Devrait être fixé dans git. Tu peux réouvrir si le problème persiste.

**Comment by enigma131** [comment]
Fonctionne à nouveau avec beta 13. merci
