### ISSUE TITLE
RTL Italy broken

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#754]
2022-04-03 16:46:40.093 T:1779    ERROR <general>: [Catch-up-TV-&-More.support] cannot pickle 'xbmc.PlayList' object
                                                   Traceback (most recent call last):
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/it/rtl.py", line 82, in get_live_url
                                                       return resolver_proxy.get_stream_with_quality(plugin, video_url=url, manifest_type="hls")
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py", line 155, in get_stream_with_quality
                                                       return __get_non_ia_stream_with_quality(plugin, video_url,
                                                     File "/home/toto/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py", line 96, in __get_non_ia_stream_with_quality
                                                       item.context.related(add_context_qualities, plugin, m3u8)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/listing.py", line 474, in related
                                                       self.container(callback, related_videos_text, *args, **kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/listing.py", line 487, in container
                                                       command = "Container.Update(%s)" % build_path(callback, args, kwargs)
                                                     File "/home/toto/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 395, in build_path
                                                       pickled = binascii.hexlify(pickle.dumps(query, protocol=PICKLE_PROTOCOL))
                                                   TypeError: cannot pickle 'xbmc.PlayList' object
2022-04-03 16:46:40.100 T:1779  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2022-04-03 16:46:40.116 T:1735     INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2022-04-03 16:46:45.980 T:1779     INFO <general>: CPythonInvoker(4, /home/toto/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run

My VLC link is still OK

**Comment by darodi** [comment]
@enigma131 

fixed in PR #755 
In the meantime, while waiting for the fix to be merged, you can go in the add on settings and activate 
`use intputstream HLS?`

**Comment by enigma131** [comment]
Yes, it's working, super.

**Comment by joaopa00** [comment]
Merged!!
I close...
