### ISSUE TITLE
UKTV Live Channels - Error when attempting playback

### ISSUE THREAD

**Issue by kevwag** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#762]
### Describe the bug
None of the UKTV Live channels work, either via the Live TV menu or the IPTV EPG

### To Reproduce
Steps to reproduce the behaviour:
1. Navigate to Live TV >> United Kingdom
2. Select one of the UKTV Channels (Yesterday / Dave / Drama)

### Expected behaviour
Playback of the selected channel should begin

### Actual behaviour
Error notification popup: Indexerror / list index out of range

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ x] Linux

 - Operating system version/name: CoreELEC  19.5 Matrix
 - Kodi version: 19.5
 - Catch-up TV & More version: 0.2.37 Beta11
 - Installation method: Zip file from Dev branch

### Additional context
Same problem occurs on Windows platform so I've copied the log data from my Windows PC as it's easier. The error is identical on CoreELEC, just with different file paths.

### Debug log
2022-04-11 23:56:42.723 T:9396    ERROR <general>: [Catch-up-TV-&-More.support] list index out of range
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\uk\uktvplay.py", line 311, in get_live_url
                                                       token_id = re.compile(r'tokenId: \'(.*?)\'').findall(resptokenid.text)[2]
                                                   IndexError: list index out of range

**Comment by jamieburchell** [comment]
I have an idea. Can you try something on your system?

Change [this line](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/dev/resources/lib/channels/uk/uktvplay.py#L307)

To:

`token_id = '11372E1C67F3435CB12646D2051DE628'`

Make sure you have a UKTV Play account and have entered your email and password in the settings page for the plugin.

**Comment by joaopa00** [comment]
Thanks for the analysis. Should be fixed in git.

**Comment by jamieburchell** [comment]
@kevwag Does this resolve the issue for you? I'm not able to test it myself at the moment.

**Comment by kevwag** [comment]
@jamieburchell  Yes sir, once again you've nailed it with a single line of code! Many thanks! Now it's just a case of getting the guide data fixed and I'm quietly confident I can probably find new urls to replace the ones that are failing.

It's also nice to know that I wasn't too far away from the source of the problem, I just need to learn how to capture those browser requests you talked about and then I'll be better equipped to fix these kinds of bug.

@joaopa00  when you say "should be fixed in git", do you mean that the latest dev release is fixed version?

**Comment by kevwag** [comment]
> The catch-up code used to have code which scraped/downloaded all JS files found, but this is slow and inefficient.

I have 500Mbit fibre broadband, are the JS files big enough to make a difference?

Thank you for taking the time to explain how you did this by the way. I appreciate that a lot and hopefully it'll mean that I'll have a good chance of fixing it myself if it breaks again!

**Comment by jamieburchell** [comment]
> I have 500Mbit fibre broadband, are the JS files big enough to make a difference?

Download time of the files is negligible, but at least for me running Kodi on a Raspberry Pi 2, the processing time required to run regex matching over several lengthy JS files was significant.

Glad I could help and that it's working :)

**Comment by kevwag** [comment]
@jamieburchell  One last question if I may?

Would I be correct in assuming that Brightcove and the amazonaws URLs are part of a high-bandwidth hosting platform owned by Amazon that enables companies like UKTV to out-source their content hosting to a larger platform that's capable of handling the heavy loads a streaming service would expect?

**Comment by jamieburchell** [comment]
> @jamieburchell One last question if I may?

AWS (Amazon Web Services) is a cloud based platform offering many, many services. Content delivery (CDN) is one of them.

Brightcove looks to be a video platform.

So yes basically they're making use of third party cloud based services to provide their solution.
