### ISSUE TITLE
UK:STV Catch up fails with "Type Error"

### ISSUE THREAD

**Issue by berkhornet** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#812]
### Describe the bug
When trying to play any program from UK:STV Catchup a "Type Error" message is displayed. This is using addon version 0.2.38 beta 25. This functionality works on release 0.2.37 and also on earlier beta versions of 0.2.38 - I am not sure which beta version broke this functionality.

### To Reproduce
Steps to reproduce the behaviour:
1. Start addon
2. Select Catch up TV
3. Select United Kingdom
4. Select STV
5. Navigate to any episode in any program
6. Select the episode
7. Then a "Type Error" is displayed

### Expected behaviour
A clear and concise description of what you expected to happen:

The episode should stream/play successfully

### Actual behaviour
Tell us what happens instead:
"Type Error" message is displayed

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ X] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19.4

Extract from Kodi log:

2022-05-06 07:46:47.761 T:23724 WARNING <CSettingsManager>: unable to read value of setting "quality"
2022-05-06 07:46:47.762 T:23724 WARNING <CAddonSettings[plugin.video.catchuptvandmore]>: failed to load value "BEST" for setting quality
2022-05-06 07:46:48.142 T:23724    INFO <general>: [Catch-up-TV-&-More] Ignoring QS: fastly_token=NjI5NzMwZjBfNjhjYzcxZmQzNjlkODYwMmU3ZjczOWU3NzZmMDlkYTJjN2QzZDQ0MDI1MDRkNzFjZjI3ZTAzNDQ5NjYxZGU0Nw%3D%3D
2022-05-06 07:46:48.159 T:23724   ERROR <general>: EXCEPTION: argument "path" for method "setPath" must be unicode or str
2022-05-06 07:46:48.166 T:23724   ERROR <general>: [Catch-up-TV-&-More.support] argument "path" for method "setPath" must be unicode or str
                                                   Traceback (most recent call last):
                                                     File "C:\Users\xxxxx\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "C:\Users\xxxxx\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 68, in __call__
                                                       return self._process_results(results)
                                                     File "C:\Users\xxxxx\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 279, in _process_results
                                                       listitem = resolved.build()[1]
                                                     File "C:\Users\xxxxx\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\listing.py", line 706, in build
                                                       listitem.setPath(path)
                                                   TypeError: argument "path" for method "setPath" must be unicode or str
2022-05-06 07:46:48.192 T:23724 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2022-05-06 07:46:48.202 T:129652    INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2022-05-06 07:46:57.484 T:23724    INFO <general>: CPythonInvoker(25, C:\Users\xxxxx\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py): script successfully run
2022-05-06 07:46:57.756 T:23724    INFO <general>: Python interpreter stopped
2022-05-06 07:46:57.767 T:129652   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/uk/stv/get_video_url/?_pickle_=800495bb000000000000007d94288c075f7469746c655f948c2154686520497063726573732046696c65202d20457069736f64652031206f662036948c076974656d5f6964948c03737476948c08766964656f5f6964948a06d1420cb7ba058c087375627469746c65948c5768747470733a2f2f66696c65732e7374762e74762f706c617965722f7375627469746c65732f7468652d697063726573732d66696c652d7365726965732d312d657069736f64652d312d6f662d362e737562732e76747494752e]

 - Catch-up TV & More version: 0.2.38 beta 25
 - Installation method: zip file

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by darodi** [comment]
I know this is not you mail problem, but for this:

`2022-05-06 07:46:47.762 T:23724 WARNING <CAddonSettings[plugin.video.catchuptvandmore]>: failed to load value "BEST" for setting quality`

- go in add-on settings
- quality and content
- change video quality to DEFAULT and save
- again, change video quality to BEST and save

video qualities have been changed to an enum. "BEST" is not the value anymore.

in userdata\addon_data\plugin.video.catchuptvandmore\settings.xml

you should have quality with a value from [0,1,2,3]

```
<settings version="2">
    <setting id="auto_run" default="true">false</setting>
    <setting id="quality">0</setting>
...
```
not 
```
<settings version="2">
    <setting id="auto_run" default="true">false</setting>
    <setting id="quality">BEST</setting>
...
```

**Comment by kevwag** [comment]
UK Blaze catchup content is giving a very similar error.
UKTV Play was also doing the same thing but that's been fixed now.
Problem is with the code that scrapes for the token URL as the site has changed.
Solution with the UKTV play was to open the webpage, view source and search for the token string and then replace the re.compile line in /channels/uktvplay.py with a hard-coded token from the token string in the source html.
eg:
TOKEN = "HSJHWJUWSA663YJE6YR4J"
instead of the re.compile line that scrapes the token

Even when fixed, as was mentioned with UKTV Play, it probably will break again next time the site changes but it's easier to fix with a hard-coded the token rather than trying to modify the regex every time.

**Comment by darodi** [comment]
There was a problem in the code, I fixed it. see #842 
The "Type Error" is gone.

I can't test the stream though. I'm not in UK and get a 403 error.

If there is a second problem with the token, I let you check and continue the issue.

**Comment by joaopa00** [comment]
With Darodi's patch, no problem for the replay. I could watch some videos

**Comment by berkhornet** [comment]
> I know this is not you main problem, but for this:
> 
> `2022-05-06 07:46:47.762 T:23724 WARNING <CAddonSettings[plugin.video.catchuptvandmore]>: failed to load value "BEST" for setting quality`
> 
> * go in add-on settings
> * quality and content
> * change video quality to DEFAULT and save
> * again, change video quality to BEST and save
> 
> video qualities have been changed to an enum. "BEST" is not the value anymore.
> 
> in userdata\addon_data\plugin.video.catchuptvandmore\settings.xml
> 
> you should have quality with a value from [0,1,2,3]
> 
> ```
> <settings version="2">
>     <setting id="auto_run" default="true">false</setting>
>     <setting id="quality">0</setting>
> ...
> ```
> 
> not
> 
> ```
> <settings version="2">
>     <setting id="auto_run" default="true">false</setting>
>     <setting id="quality">BEST</setting>
> ...
> ```

@darodi - thanks for this suggestion. I have applied to my system.

**Comment by berkhornet** [comment]
> There was a problem in the code, I fixed it. see #842 The "Type Error" is gone.
> 
> I can't test the stream though. I'm not in UK and get a 403 error.
> 
> If there is a second problem with the token, I let you check and continue the issue.

@darodi - many thanks for this fix. Like @joaopa00 , I have tested and STV catch up is working again on version 0.2.38 beta 28.

**Comment by berkhornet** [comment]
Closing issue, many thanks for your help.
