### ISSUE TITLE
UK Blaze Catchup fails with "InvalidHeader" Error

### ISSUE THREAD

**Issue by kevwag** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#843]
### Describe the bug
Trying to play content from Catchup>>United Kingdom>>Blaze fails, producing an "Invalid Header" error.

### To Reproduce
Steps to reproduce the behaviour:
1.Launch Addon
2.Navigate to Catchup>>United Kingdom>>Blaze>>All Videos
3.Select a show from the list

### Expected behaviour
The show should start playing

### Actual behaviour
InvalidHeader Error notification shows

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [x] Linux
 - [x] Windows

 - Operating system version/name: Windows 10 & CoreELEC 20
 - Kodi version: 20.0 Nexus Nightly
 - Catch-up TV & More version: 0.2.38-beta28
 - Installation method: Zip file

### Additional context
There is also a problem with the list of shows available. The addon is not showing all the available shows compared to the website.
Unfortunately, everything is in a single "All Videos" folder and there are multiple duplicates of each show so there are hundreds of shows in the folder but the addon is only showing 406 shows (no option for "page 2" etc) and there are many more than that on the website.

### Debug log
    ERROR <general>: [Catch-up-TV-&-More.support] Value for header {token-expiry: 1652429329} must be of type str or bytes, not <class 'int'>
        Traceback (most recent call last):
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\utils.py", line 956, in check_header_validity
              if not pat.match(value):
               TypeError: expected string or bytes-like object
                                                   
               During handling of the above exception, another exception occurred:
                                                   
               Traceback (most recent call last):
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
               redirect = parent_ins(route, arg_params, self.callback_params)
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 67, in __call__
              results = super(Resolver, self).__call__(route, args, kwargs)
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\script.py", line 169, in __call__
               return route.function(self, *args, **kwargs)
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\uk\blaze.py", line 98, in get_video_url
               resp3 = urlquick.get(video_url,
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 493, in get
               return request('get', url, params=params, **kwargs)
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 487, in request
               return s.request(method=method, url=url, **kwargs)
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 441, in request
               response = super(Session, self).request(*args, **kwargs)
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 528, in request
               prep = self.prepare_request(req)
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 456, in prepare_request
               p.prepare(
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 317, in prepare
              self.prepare_headers(headers)
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 451, in prepare_headers
               check_header_validity(header)
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\utils.py", line 959, in check_header_validity
              raise InvalidHeader("Value for header {%s: %s} must be of type str or "
              requests.exceptions.InvalidHeader: Value for header {token-expiry: 1652429329} must be of type str or bytes, not <class 'int'>
    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/uk/blaze/get_video_url/?_pickle_=80049564000000000000007d94288c075f7469746c655f948c2a4375727365204f6620546865204c6f737420416d617a6f6e20476f6c64202d20533120e280a220457033948c076974656d5f6964948c05626c617a65948c08766964656f5f6964948c08343439343434393394752e]

**Comment by joaopa00** [comment]
Fixed in git. I close this issue. If the still occurs, don't hesitate to reopen.
