### ISSUE TITLE
Cnews replay error 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by gilles0606** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#864]
Bonjour,

lorsque j'essais d'avoir la liste des replay j'ai une erreur 'NoneType' object has no attribute 'text'

Voici le log...

Merci....

2022-05-24 07:52:00.361 T:1118     INFO <general>: initializing python engine.
2022-05-24 07:52:01.747 T:1118     INFO <general>: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2022-05-24 07:52:01.997 T:1118     INFO <general>: Python interpreter stopped
2022-05-24 07:52:02.659 T:1124     INFO <general>: initializing python engine.
2022-05-24 07:52:03.531 T:1124    ERROR <general>: [Catch-up-TV-&-More.support] 'NoneType' object has no attribute 'text'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                       session_data = self._process_results(results)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                       listitems = validate_listitems(results)
                                                     File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                       raw_listitems = list(raw_listitems)
                                                     File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/cnews.py", line 93, in list_emissions
                                                       item.label = video_datas.find(".//h2[@class='emission-title']").text
                                                   AttributeError: 'NoneType' object has no attribute 'text'
2022-05-24 07:52:03.558 T:1124  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2022-05-24 07:52:03.613 T:1007     INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2022-05-24 07:52:13.730 T:1007     INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2022-05-24 07:52:18.162 T:1124     INFO <general>: CPythonInvoker(8, /storage/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2022-05-24 07:52:18.416 T:1124     INFO <general>: Python interpreter stopped
2022-05-24 07:52:18.426 T:1123    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/cnews/list_emissions/?_pickle_=80049598000000000000007d94288c075f7469746c655f948c0e4e6f7320c3a96d697373696f6e73948c076974656d5f6964948c05636e657773948c0c63617465676f72795f75726c948c4968747470733a2f2f7777772e636e6577732e66722f736572766963652f646d5f6c6f61646d6f72652f646d5f656d697373696f6e5f696e6465785f656d697373696f6e732f25732f30948c0470616765948c013094752e
2022-05-24 07:52:18.430 T:1007    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/cnews/list_emissions/?_pickle_=80049598000000000000007d94288c075f7469746c655f948c0e4e6f7320c3a96d697373696f6e73948c076974656d5f6964948c05636e657773948c0c63617465676f72795f75726c948c4968747470733a2f2f7777772e636e6577732e66722f736572766963652f646d5f6c6f61646d6f72652f646d5f656d697373696f6e5f696e6465785f656d697373696f6e732f25732f30948c0470616765948c013094752e) failed

**Comment by joaopa00** [comment]
Devrait être fixé dans git.
Tu peux attendre la libération d'une version béta pour tester ou alors télécharger le zip du git.

**Comment by gilles0606** [comment]
Bonjour,

je confirme que la version GIT fonctionne...
Grand merci à toi...

**Comment by joaopa00** [comment]
Super. Je ferme donc.
