### ISSUE TITLE
LCI replay Error

### ISSUE THREAD

**Issue by nmaster2042** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#874]
### Describe the bug
No access to LCI french chanel replays:

### To Reproduce
Steps to reproduce the behaviour:
1. go to extensions / Catch-Up-TV / télévision de rattrapage / France / LCI
2. chose any item

### Expected behaviour
When chose an item, should get a list of subfolders or replays to watch

### Actual behaviour
Error "Unable to find requested section with tag of 'ul' and attributes of {'class': 'topic-chronology-milestone-component"

### Your environment
Linux Kubuntu 21.10 / kodi 19.4, Catch-Up-YV-And-More 

 - Operating system version/name: Linux Kubuntu 21.10 
 - Kodi version: 19.4
 - Catch-up TV & More version: 0.2.38-beta29
 - Installation method: official beta repositary

### Debug log

```
2022-05-30 16:25:33.818 T:210180 WARNING <general>: CGLContextEGL::SwapBuffers: last msc time greater than interval
2022-05-30 16:25:33.834 T:210180 WARNING <general>: CGLContextEGL::SwapBuffers: last msc time greater than interval (1)
2022-05-30 16:25:37.405 T:213823    INFO <general>: Skipped 2 duplicate messages..
2022-05-30 16:25:37.405 T:213823    INFO <general>: initializing python engine.
2022-05-30 16:25:37.432 T:213823   ERROR <general>: [Catch-up-TV-&-More.support] Unable to find requested section with tag of 'ul' and attributes of {'class': 'topic-chronology-milestone-component'}
                                                   Traceback (most recent call last):
                                                     File "/home/nicolas/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/nicolas/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                       session_data = self._process_results(results)
                                                     File "/home/nicolas/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                       listitems = validate_listitems(results)
                                                     File "/home/nicolas/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                       raw_listitems = list(raw_listitems)
                                                     File "/home/nicolas/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/lci.py", line 59, in list_programs
                                                       root = resp.parse("ul", attrs={"class": "topic-chronology-milestone-component"})
                                                     File "/home/nicolas/.kodi/addons/script.module.codequick/lib/urlquick.py", line 183, in parse
                                                       return parser.close()
                                                     File "/home/nicolas/.kodi/addons/script.module.htmlement/lib/htmlement.py", line 244, in close
                                                       return self._parser.close()
                                                     File "/home/nicolas/.kodi/addons/script.module.htmlement/lib/htmlement.py", line 404, in close
                                                       raise RuntimeError(msg.format(self.tag, self.attrs))
                                                   RuntimeError: Unable to find requested section with tag of 'ul' and attributes of {'class': 'topic-chronology-milestone-component'}
2022-05-30 16:25:37.435 T:213823 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2022-05-30 16:25:43.535 T:213823    INFO <general>: CPythonInvoker(9, /home/nicolas/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2022-05-30 16:25:46.422 T:213823    INFO <general>: Python interpreter interrupted by user
2022-05-30 16:25:46.423 T:213893   ERROR <general>: Skipped 1 duplicate messages..
2022-05-30 16:25:46.423 T:213893   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/lci/list_programs/?_pickle_=80049539000000000000007d94288c075f7469746c655f948c0ac3896d697373696f6e73948c065f617267735f948c036c6369948c09656d697373696f6e73948694752e
2022-05-30 16:25:46.425 T:210180   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/lci/list_programs/?_pickle_=80049539000000000000007d94288c075f7469746c655f948c0ac3896d697373696f6e73948c065f617267735f948c036c6369948c09656d697373696f6e73948694752e) failed
2022-05-30 16:25:46.453 T:213984    INFO <general>: initializing python engine.
2022-05-30 16:25:46.651 T:210180 WARNING <general>: CGLContextEGL::SwapBuffers: last msc time greater than interval
2022-05-30 16:25:46.668 T:210180 WARNING <general>: CGLContextEGL::SwapBuffers: last msc time greater than interval (1)
2022-05-30 16:25:46.888 T:213984    INFO <general>: Skipped 11 duplicate messages..
2022-05-30 16:25:46.888 T:213984    INFO <general>: CPythonInvoker(10, /home/nicolas/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run

```

**Comment by joaopa00** [comment]
Devrait être fixé dans la dernière béta

**Comment by nmaster2042** [comment]
Je confirme, cela fonctionne à nouveau Merci
