### ISSUE TITLE
Francetv sport est cassé

### ISSUE THREAD

**Issue by joaopa00** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#877]
Aussi bien le direct que la télévision de rattrapage est hors service.

-05-31 02:25:07.812 T:3790    DEBUG <general>: [Catch-up-TV-&-More.support] Callback parameters: '{'xmltv_id': None, 'item_id': 'francetvsport'}'
2022-05-31 02:25:07.812 T:3790    DEBUG <general>: [Catch-up-TV-&-More.support] Attempting to import route: resources.lib.channels.fr.francetvsport
2022-05-31 02:25:08.194 T:3790    DEBUG <general>: [Catch-up-TV-&-More.route] Listitem Cache: Miss
2022-05-31 02:25:08.203 T:3790    DEBUG <general>: [urllib3.connectionpool] Starting new HTTPS connection (1): api-mobile.yatta.francetv.fr:443
2022-05-31 02:25:10.230 T:3790    DEBUG <general>: [urllib3.connectionpool] https://api-mobile.yatta.francetv.fr:443 "GET /generic/directs?platform=apps HTTP/1.1" 200 14693
2022-05-31 02:25:10.475 T:3790    DEBUG <general>: [urllib3.connectionpool] Starting new HTTPS connection (1): api-sport-events.webservices.francetelevisions.fr:443
2022-05-31 02:25:13.012 T:3790    DEBUG <general>: [urllib3.connectionpool] https://api-sport-events.webservices.francetelevisions.fr:443 "GET /directs HTTP/1.1" 503 272
2022-05-31 02:25:13.017 T:3790    ERROR <general>: [Catch-up-TV-&-More.support] 503 Server Error: Service Unavailable for url: https://api-sport-events.webservices.francetelevisions.fr/directs
                                                   Traceback (most recent call last):
                                                     File "/home/david/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/david/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                       session_data = self._process_results(results)
                                                     File "/home/david/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                       listitems = validate_listitems(results)
                                                     File "/home/david/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                       raw_listitems = list(raw_listitems)
                                                     File "/home/david/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/francetvsport.py", line 144, in list_lives
                                                       resp = urlquick.get(URL_FRANCETV_SPORT % 'directs', max_age=-1)
                                                     File "/home/david/.kodi/addons/script.module.codequick/lib/urlquick.py", line 493, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "/home/david/.kodi/addons/script.module.codequick/lib/urlquick.py", line 487, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                     File "/home/david/.kodi/addons/script.module.codequick/lib/urlquick.py", line 442, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/home/david/.kodi/addons/script.module.codequick/lib/urlquick.py", line 415, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/home/david/.kodi/addons/script.module.requests/lib/requests/models.py", line 943, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api-sport-events.webservices.francetelevisions.fr/directs
2022-05-31 02:25:13.019 T:3790    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/home/david/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/home/david/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/home/david/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 290, in error_handler
                                                       code = exception.code
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--

**Comment by darodi** [comment]
https://sport.francetvinfo.fr

renvoie vers 
https://www.francetvinfo.fr/sports/
et les liens ce ce site renvoient aussi vers
https://www.france.tv/sport/

n'est-ce pas déjà géré par 
resources/lib/channels/fr/franceinfo.py
resources/lib/channels/fr/francetv.py

?

**Comment by joaopa00** [comment]
Tu as raison. Il  y a un même un item pour le direct. Peut-être supprimer l'item dans direct et garder dans la télévision de rattrapage est la bonne solution.
Mais le problème existe quand même. Il est impossible de jouer le direct.

**Comment by joaopa00** [comment]
C'est cela.

**Comment by darodi** [comment]
Il faudra revenir demain...

![image](https://user-images.githubusercontent.com/4682830/171279070-b346fbce-7cb6-4577-a4cc-246d84b20ce6.png)
