### ISSUE TITLE
Impossible de regarder BFMTV sur kodi android TV

### ISSUE THREAD

**Issue by Ptiji** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#891]
### Describe the bug
A clear and concise description of what the bug is:

J'ai ajouté les ID de 2 comptes différents et le bug est toujours la. 

Je me rends sur mes chaines Françaises sur BFMTV. La chaine ne se lance pas. Un message impossible de resoudre l'url apparait. Une information propose de vous partager le journal d'erreur. Cependant en mettant oui, un autre message annonce desolé, le partage de votre journal d'erreurs à échoué : Unable to retrieve the paste url.

### To Reproduce
Steps to reproduce the behaviour:
1. J'allume Kodi 19.4
2. Dans extension je lance catch Tv
3. Chaine francaise en direct je lance bfm

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [x] Android TV
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:  MIBOX4 / Version noyau 4.9.113
 - Kodi version: matrix 19.4
 - Catch-up TV & More version: 0.2.37+matrix.1
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy): j'essaie de voir si je peux récupérer le log
https://paste.kodi.tv/owilivuhew

**Comment by Ptiji** [comment]
Je pense que l'erreur est décrite ligne 1514 :
`2022-06-09 07:50:44.271 T:10574   DEBUG <general>: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/fr/rmcbfmplay/get_live_url/'
2022-06-09 07:50:44.272 T:10574   DEBUG <general>: [Catch-up-TV-&-More.support] Callback parameters: '{'xmltv_id': 'C481.api.telerama.fr', 'item_id': 'BFM TV'}'
2022-06-09 07:50:44.272 T:10574   DEBUG <general>: [Catch-up-TV-&-More.support] Attempting to import route: resources.lib.channels.fr.rmcbfmplay
2022-06-09 07:50:44.287 T:10598   DEBUG <general>: Thread scriptobs start, auto delete: false
2022-06-09 07:50:44.333 T:10574   DEBUG <CAddonSettings[plugin.video.catchuptvandmore]>: trying to load setting definitions from old format...
2022-06-09 07:50:44.360 T:10574   DEBUG <general>: [urlquick] Cache is fresh
2022-06-09 07:50:44.487 T:10534   DEBUG <general>: Skipped 2 duplicate messages..
2022-06-09 07:50:44.487 T:10534   DEBUG <general>: ------ Window Init (DialogBusy.xml) ------
2022-06-09 07:50:44.501 T:10574   ERROR <general>: [Catch-up-TV-&-More.support] Impossible de résoudre l'URL
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 68, in __call__
                                                       return self._process_results(results)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 307, in _process_results
                                                       raise RuntimeError(self.localize(localized.NO_VIDEO))
                                                   RuntimeError: Impossible de résoudre l'URL
2022-06-09 07:50:44.524 T:10534   DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2022-06-09 07:50:44.534 T:10574 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2022-06-09 07:50:44.580 T:10534   DEBUG <general>: ------ Window Init (DialogConfirm.xml) ------
2022-06-09 07:50:44.580 T:10534    INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY`

**Comment by joaopa00** [comment]
As-tu bien renseigné tes identifiants RMCBFM dans la partie <<paramètre de l'extension>> de Catchuptvandmore?

**Comment by Ptiji** [comment]
J'ai essayé 2 identifiants différents. Sans succès.

**Comment by joaopa00** [comment]
Je confirme le problème. Il est aussi présent sous Linux. Cela concerne toutes les chaines de BFMRMC play. Il y a eu une mise à jou de l'appli le 7 Juin qui a du certainement changé les API. Dommage...

**Comment by joaopa00** [comment]
Devrait être fixé dans la béta 32. N'hésite pas à réouvrir si le problème persiste après avoir mis à jour l'application.

Merci pour le rapport de bug.

**Comment by Ptiji** [comment]
Merci, je ferai la maj et vous tiendrai au courant

**Comment by Ptiji** [comment]
Je confirme le fix fonctionne. 

Merci @joaopa00
