### ISSUE TITLE
Arte replay does not work anymore

### ISSUE THREAD

**Issue by alexismorillo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#91]
The following error appears in the logs :
`
21:52:18.142 T:1682699008   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('type',)
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 459, in <module>
                                                common.PLUGIN.run()
                                              File "/home/pi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 1057, in run
                                                result = self._resolve_function()
                                              File "/home/pi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 1088, in _resolve_function
                                                return action_callable(self._params)
                                              File "/home/pi/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 215, in replay_entry
                                                return channel.channel_entry(params)
                                              File "/home/pi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/root/channels/wo/arte.py", line 46, in channel_entry
                                                return list_shows(params)
                                              File "/home/pi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 701, in inner_wrapper
                                                return self._get_cached_data(cache, func, duration, *args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 653, in _get_cached_data
                                                data = func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/root/channels/wo/arte.py", line 75, in list_shows
                                                if category['type'] == 'category':
                                            KeyError: ('type',)
                                            -->End of Python script error report<--
21:52:18.362 T:1488974592   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/?item_skeleton=%7B%7D&item_id=arte&item_path=%5B%27root%27%2C+%27channels%27%2C+%27wo%27%2C+%27arte%27%5D&module_name=None&action=replay_entry&module_path=None&window_title=Arte
`

**Comment by wwark** [comment]
Hi Alexis,
I push a fix in dev branche https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/2da3809618c1c40279869b6340adbe7706f30415

Don't hesitate if you still have issue.
BR,
Wwark

**Comment by alexismorillo** [comment]
Hi,
When will it be available ? I only can update to version 0.1.10 (which is my current version) from the Kodi add-ons repository.
Regards,

**Comment by SylvainCecchetto** [comment]
Hi alexismorillo,

In order to get the betas version you need to use the beta repo.
Do you speak French? If yes, you can follow the "Installation depuis le dépôt officiel Catch-Up TV & More" chapter of this page https://forum.mpdb.tv/index.php/topic,35713.0.html 

Then you can install the beta version of the repo.

If need help do not hesitate ;-)

**Comment by alexismorillo** [comment]
Super. Ça marche très bien. Encore merci Sylvain pour ce plugin très utile.

**Comment by SylvainCecchetto** [comment]
Parfait alors ;-)
De rien mais le plugin ne serait rien sans tout le travail que wwark y apporte ;-)
