### ISSUE TITLE
the French channels "francetv" no longer work

### ISSUE THREAD

**Issue by monfiston** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#910]
### Describe the bug
hello
since I switched to the v37 beta version of "catchup", the French channels "francetv" no longer work
previously with the beta v1, it worked very well
I have 2 systems, 1 under windows 11 and 1 on a CoreELEC box: Amlogic.arm-9.2.8

### To Reproduce
Steps to reproduce the behaviour:
1.launch of live television france 2/france 3/france 4/....
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
ERROR: [Catch-up-TV-&-More.support] 'unable to import route module: resources.lib.channels.fr.francetv'
### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [x ] Other

 - Operating system version/name:
 - Kodi version:Kodi 18.9 
 - Catch-up TV & More version:02.38 béta37
 

### Debug log
`#####################################
# ... output of cat /storage/.kodi/temp/kodi.log
# CoreELEC release: Amlogic.arm-9.2.8
#
################################################################################
﻿2022-07-09 17:36:51.935 T:4087918656  NOTICE: -----------------------------------------------------------------------
2022-07-09 17:36:51.935 T:4087918656  NOTICE: Starting Kodi (18.9 (18.9.0) Git:00ff7594e42e9539912c9bd12c5a6a9d1b9d8d78). Platform: Linux ARM 32-bit
2022-07-09 17:36:51.935 T:4087918656  NOTICE: Using Release Kodi x32 build
2022-07-09 17:36:51.936 T:4087918656  NOTICE: Kodi compiled 2021-09-07 by GCC 8.3.0 for Linux ARM 32-bit version 3.14.29 (200221)
2022-07-09 17:36:51.936 T:4087918656  NOTICE: Running on CoreELEC (official): 9.2.8, kernel: Linux ARM 64-bit version 3.14.29 aarch64
2022-07-09 17:36:51.936 T:4087918656  NOTICE: FFmpeg version/source: 4.2.4-Kodi
2022-07-09 17:36:51.936 T:4087918656  NOTICE: Host CPU: Amlogic S912 rev a, 8 cores available
2022-07-09 17:36:51.936 T:4087918656  NOTICE: ARM Features: Neon enabled
2022-07-09 17:36:51.936 T:4087918656  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi/
2022-07-09 17:36:51.936 T:4087918656  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/kodi
2022-07-09 17:36:51.936 T:4087918656  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib/kodi/addons
2022-07-09 17:36:51.936 T:4087918656  NOTICE: special://masterprofile/ is mapped to: /storage/.kodi/userdata
2022-07-09 17:36:51.936 T:4087918656  NOTICE: special://envhome/ is mapped to: /storage
2022-07-09 17:36:51.936 T:4087918656  NOTICE: special://home/ is mapped to: /storage/.kodi
2022-07-09 17:36:51.936 T:4087918656  NOTICE: special://temp/ is mapped to: /storage/.kodi/temp
2022-07-09 17:36:51.936 T:4087918656  NOTICE: special://logpath/ is mapped to: /storage/.kodi/temp
2022-07-09 17:36:51.936 T:4087918656  NOTICE: The executable running is: /usr/lib/kodi/kodi.bin
2022-07-09 17:36:51.936 T:4087918656  NOTICE: Local hostname: CoreELEC
2022-07-09 17:36:51.936 T:4087918656  NOTICE: Log File is located: /storage/.kodi/temp/kodi.log
2022-07-09 17:36:51.936 T:4087918656  NOTICE: -----------------------------------------------------------------------
2022-07-09 17:36:51.952 T:4087918656    INFO: loading settings
2022-07-09 17:36:51.958 T:4087918656  NOTICE: special://profile/ is mapped to: special://masterprofile/
2022-07-09 17:36:51.995 T:4087918656   DEBUG: CSkinSettings: no <skinsettings> tag found
2022-07-09 17:36:52.018 T:4087918656  NOTICE: Loaded settings file from special://xbmc/system/advancedsettings.xml

2022-07-09 17:34:33.550 T:3603428160 WARNING: Repository add-on repository.StreamArmy uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/nemesis668/repository.streamarmy18-19/main/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-07-09 17:34:33.550 T:3603428160 WARNING: Repository add-on repository.StreamArmy uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/nemesis668/repository.streamarmy/master/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-07-09 17:34:34.458 T:3665376064  NOTICE: AddOnLog: PVR IPTV Simple Client: LoadPlayList PlayList Loaded - 3 (ms)
2022-07-09 17:34:34.458 T:3665376064  NOTICE: AddOnLog: PVR IPTV Simple Client: Loaded 31 channels.
2022-07-09 17:34:34.458 T:3665376064  NOTICE: PVR Manager: Starting
2022-07-09 17:34:34.462 T:3893748544 WARNING: Repository add-on repository.StreamArmy uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/nemesis668/repository.streamarmy18-19/main/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-07-09 17:34:34.462 T:3893748544 WARNING: Repository add-on repository.StreamArmy uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/nemesis668/repository.streamarmy/master/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-07-09 17:34:34.588 T:3893748544 WARNING: Repository add-on repository.StreamArmy uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/nemesis668/repository.streamarmy18-19/main/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-07-09 17:34:34.588 T:3893748544 WARNING: Repository add-on repository.StreamArmy uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/nemesis668/repository.streamarmy/master/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-07-09 17:34:34.628 T:3893748544 WARNING: Repository add-on repository.StreamArmy uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/nemesis668/repository.streamarmy18-19/main/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-07-09 17:34:34.628 T:3893748544 WARNING: Repository add-on repository.StreamArmy uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/nemesis668/repository.streamarmy/master/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-07-09 17:34:34.843 T:3486249792  NOTICE: PVR Manager: Started
2022-07-09 17:34:34.843 T:3907044160  NOTICE: EPG thread started
2022-07-09 17:34:36.001 T:3446678336  NOTICE: AddOnLog: PVR IPTV Simple Client: LoadEPG EPG Loaded - 157 (ms)
2022-07-09 17:34:50.825 T:3455071040   ERROR: [Catch-up-TV-&-More.support] 'unable to import route module: resources.lib.channels.fr.francetv'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 300, in run_callback
                                                route = self.get_route(self.selector)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 250, in get_route
                                                raise RouteMissing("unable to import route module: %s" % module_path)
                                            RouteMissing: 'unable to import route module: resources.lib.channels.fr.francetv'
2022-07-09 17:35:07.714 T:4091048000  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/Toutes les chaînes/pvr.iptvsimple_1986557532.pvr
2022-07-09 17:35:07.717 T:3470783296  NOTICE: Creating InputStream
2022-07-09 17:35:07.743 T:3470783296   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2022-07-09 17:35:12.836 T:3470783296  NOTICE: Creating Demuxer
2022-07-09 17:35:12.837 T:3470783296  NOTICE: Opening stream: 1001 source: 256
2022-07-09 17:35:12.896 T:3470783296  NOTICE: CVideoPlayerVideo::OpenStream - Creating codec: 27
2022-07-09 17:35:12.899 T:3470783296  NOTICE: Creating video thread
2022-07-09 17:35:12.900 T:3395322688  NOTICE: running thread: video_thread
2022-07-09 17:35:12.981 T:3470783296  NOTICE: Opening stream: 1003 source: 256
2022-07-09 17:35:13.036 T:3470783296  NOTICE: Finding audio codec for: 86018
2022-07-09 17:35:13.038 T:3470783296  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2022-07-09 17:35:13.038 T:3470783296  NOTICE: Creating audio thread
2022-07-09 17:35:13.038 T:3378537280  NOTICE: running thread: CVideoPlayerAudio::Process()
2022-07-09 17:35:13.038 T:3470783296  NOTICE: Opening stream: 1006 source: 256
2022-07-09 17:35:13.946 T:3395322688  NOTICE: CAMLCodec::OpenDecoder - using V4L2 pts format: 64Bit
2022-07-09 17:35:14.019 T:3378537280  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2022-07-09 17:35:14.019 T:3378537280  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
2022-07-09 17:35:14.126 T:4091048000  NOTICE: Whitelist search for: width: 1920, height: 1080, fps: 50.000, 3D: false
2022-07-09 17:35:14.127 T:4091048000  NOTICE: Display resolution ADJUST : 1920x1080 @ 50.00 - Full Screen (29) (weight: 0.000)
2022-07-09 17:35:14.128 T:4091048000  NOTICE: VideoPlayer: OnLostDisplay received
2022-07-09 17:35:14.128 T:4091048000   ERROR: GetString: error reading /sys/class/amhdmitx/amhdmitx0/custom_mode
2022-07-09 17:35:14.374 T:4091048000  NOTICE: VideoPlayer: OnResetDisplay received
2022-07-09 17:35:14.408 T:4091048000  NOTICE: Whitelist search for: width: 1920, height: 1080, fps: 50.000, 3D: false
2022-07-09 17:35:14.409 T:4091048000  NOTICE: Display resolution ADJUST : 1920x1080 @ 50.00 - Full Screen (29) (weight: 0.000)
2022-07-09 17:35:16.554 T:4091048000  NOTICE: CVideoPlayer::CloseFile()
2022-07-09 17:35:16.554 T:4091048000  NOTICE: VideoPlayer: waiting for threads to exit
2022-07-09 17:35:16.614 T:3470783296  NOTICE: CVideoPlayer::OnExit()
2022-07-09 17:35:16.614 T:3470783296  NOTICE: Closing stream player 1
2022-07-09 17:35:16.615 T:3470783296  NOTICE: Waiting for audio thread to exit
2022-07-09 17:35:16.676 T:3378537280  NOTICE: thread end: CVideoPlayerAudio::OnExit()
2022-07-09 17:35:16.676 T:3470783296  NOTICE: Closing audio device
2022-07-09 17:35:16.762 T:3470783296  NOTICE: Deleting audio codec
2022-07-09 17:35:16.762 T:3470783296  NOTICE: Closing stream player 2
2022-07-09 17:35:16.763 T:3470783296  NOTICE: waiting for video thread to exit
2022-07-09 17:35:16.763 T:3395322688   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2022-07-09 17:35:16.763 T:3395322688  NOTICE: thread end: video_thread
2022-07-09 17:35:16.764 T:3470783296  NOTICE: deleting video codec
2022-07-09 17:35:16.801 T:3470783296  NOTICE: Closing stream player 3
2022-07-09 17:35:16.960 T:4091048000  NOTICE: VideoPlayer: finished waiting
2022-07-09 17:35:16.960 T:4091048000  NOTICE: CVideoPlayer::CloseFile()
2022-07-09 17:35:16.960 T:4091048000  NOTICE: VideoPlayer: waiting for threads to exit
2022-07-09 17:35:16.960 T:4091048000  NOTICE: VideoPlayer: finished waiting
2022-07-09 17:35:17.113 T:4091048000   ERROR: GetString: error reading /sys/class/amhdmitx/amhdmitx0/custom_mode
2022-07-09 17:35:20.954 T:3893748544 WARNING: Repository add-on repository.StreamArmy uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/nemesis668/repository.streamarmy18-19/main/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-07-09 17:35:20.954 T:3893748544 WARNING: Repository add-on repository.StreamArmy uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/nemesis668/repository.streamarmy/master/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-07-09 17:35:21.043 T:3893748544 WARNING: Repository add-on repository.StreamArmy uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/nemesis668/repository.streamarmy18-19/main/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-07-09 17:35:21.043 T:3893748544 WARNING: Repository add-on repository.StreamArmy uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/nemesis668/repository.streamarmy/master/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-07-09 17:35:21.079 T:3893748544 WARNING: Repository add-on repository.StreamArmy uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/nemesis668/repository.streamarmy18-19/main/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-07-09 17:35:21.079 T:3893748544 WARNING: Repository add-on repository.StreamArmy uses plain HTTP for add-on downloads in path http://raw.githubusercontent.com/nemesis668/repository.streamarmy/master/zips/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2022-07-09 17:35:52.108 T:4091048000   ERROR: Control 1000 in window 13001 has been asked to focus, but it can't
2022-07-09 17:36:17.633 T:4091048000  NOTICE: Quitting due to POSIX signal
2022-07-09 17:36:17.666 T:4091048000  NOTICE: Stopping player
2022-07-09 17:36:17.666 T:4091048000  NOTICE: Storing total System Uptime
2022-07-09 17:36:17.666 T:4091048000  NOTICE: Saving settings
2022-07-09 17:36:17.679 T:4091048000  NOTICE: Saving skin settings
2022-07-09 17:36:17.684 T:4091048000  NOTICE: Stopping all
2022-07-09 17:36:17.684 T:4091048000  NOTICE: ES: Stopping event server
2022-07-09 17:36:17.995 T:3749667648  NOTICE: ES: UDP Event server stopped
2022-07-09 17:36:18.419 T:4091048000  NOTICE: stopping zeroconf publishing
2022-07-09 17:36:18.424 T:4091048000  NOTICE: CWebServer[8080]: Stopped
2022-07-09 17:36:18.424 T:4091048000  NOTICE: stop dvd detect media
2022-07-09 17:36:23.426 T:4091048000   ERROR: CPythonInvoker(3, /storage/.kodi/addons/plugin.video.catchuptvandmore/service.py): script didn't stop in 5 seconds - let's kill it
2022-07-09 17:36:23.610 T:4091048000  NOTICE: Application stopped
2022-07-09 17:36:23.811 T:4091048000  NOTICE: XBApplicationEx: destroying...
2022-07-09 17:36:23.811 T:4091048000  NOTICE: PVR Manager: Stopping
2022-07-09 17:36:24.467 T:4091048000  NOTICE: PVR Manager: Stopped
2022-07-09 17:36:26.656 T:4091048000  NOTICE: unload skin
2022-07-09 17:36:26.707 T:4091048000 WARNING: Cleanup: Having to cleanup texture lists/focus.png
2022-07-09 17:36:26.822 T:4091048000  NOTICE: unload sections
2022-07-09 17:36:27.443 T:4091048000  NOTICE: XBApplicationEx: application stopped!`

**Comment by meeuuh92** [comment]
Hi, i confirm the bug on coreelec 9.2.8 and last beta. It's ok with the stable version of plugin.

**Comment by joaopa00** [comment]
Est-ce que ça marche sans utiliser l'interface de catchuptvandmore? (pas le pvr)

**Comment by joaopa00** [comment]
Désolé, je voulais écrire **en utilsant** l'interface de Catchuptvandmore. Pas de pvr.
J'ai l'impression que le problème chez vous vient d'un pvr.

**Comment by monfiston** [comment]
pour mon cas, je n'utilise pas le PVR, je passe systématiquement par  Catchuptvandmore

**Comment by meeuuh92** [comment]
J'ai l'addon PVR tvheadaddon mais comme ce n'est pas le cas pour monfiston, cela ne doit pas être la cause. ;-) après dans le log de monfiston, on voit de l'iptvsimple qui traine.

**Comment by joaopa00** [comment]
> GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/

Tu as toujours le m^me problème avec Inputstreamadaptive. Tant que tu ne l'as pas résolu, Catchuptvandmore ne fonctionnera pas avec les chaines qui en ont besoin (Francetv, RMC,....)

**Comment by meeuuh92** [comment]
RMC BFM play fonctionne de mon côté (cela faisait plus d'un an que je ne l'avais plus). J'ai testé en enlevant l'intégration PVR mais cela ne semble avoir aucun rapport... Tu as des pistes pour Inpustreamadaptative?  En tant qu'utilisateur de cet excellent addon, on a tendance à penser que c'est un bug dans son installation car la version stable est fonctionnelle pour francetv.

**Comment by monfiston** [comment]
> > GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
> 
> Tu as toujours le même problème avec Inputstreamadaptive. Tant que tu ne l'as pas résolu, Catchuptvandmore ne fonctionnera pas avec les chaines qui en ont besoin (Francetv, RMC,....) Il n'y a rien queCatchuptvandmore puisse faire. Tu as un problème de configuration.

Rmc fonctionne chez moi aussi 
Concernant Francetv, comme dit meeuuh92, avec la bêta v1 ça fonctionne,  on passe sur la v37 ca ne fonctionne plus
Quand je fais une nouvelle installation avec un environnement Windows,  j ai exactement le même pb

**Comment by joaopa00** [comment]
Je viens de tester sous linux, androidtv et windows. Aucun problème avec la version beta 0.2.37.
Sur windows, j'ai même essayé avec une version fraîchement installée.
Pour windows, il faut désinstaller kodi complètement ainsi que le fichier de configuration lorsque cela est demandé.
Refaites une installation suivant la page wiki. Tester tout de suite france 2 et Kodi installera automatiquement et **PROPREMENT** inputstream adaptive.

**Comment by monfiston** [comment]
quelle version de kodi tu as installé?

**Comment by monfiston** [comment]
je viens de désinstaller kodi en supprimant ces fichiers de configuration
j'ai réinstallé, kodi v18.9 64 bits, **et pas kodi v19**, sur un windows 11
refait l'installation de catch up
et j'ai toujours les même problème

```
2022-07-12 18:57:57.024 T:9852  NOTICE: -----------------------------------------------------------------------
2022-07-12 18:57:57.024 T:9852  NOTICE: Starting Kodi (18.9 (18.9.0) Git:20201023-0655c2c718). Platform: Windows NT x86 64-bit
2022-07-12 18:57:57.024 T:9852  NOTICE: Using Release Kodi x64 build
2022-07-12 18:57:57.024 T:9852  NOTICE: Kodi compiled 2020-10-23 by MSVC 191627035 for Windows NT x86 64-bit version 10.0 (0x0A000007)
2022-07-12 18:57:57.024 T:9852  NOTICE: Running on Windows 10, kernel: Windows NT x86 64-bit version 10.0.22000
2022-07-12 18:57:57.024 T:9852  NOTICE: FFmpeg version/source: 4.0.4-Kodi
2022-07-12 18:57:57.024 T:9852  NOTICE: Host CPU: AMD FX(tm)-8350 Eight-Core Processor, 8 cores available
2022-07-12 18:57:57.024 T:9852  NOTICE: Desktop Resolution: 1920x1080 32Bit at 60Hz
2022-07-12 18:57:57.024 T:9852  NOTICE: Running with restricted rights
2022-07-12 18:57:57.024 T:9852  NOTICE: Aero is enabled
2022-07-12 18:57:57.024 T:9852  NOTICE: special://xbmc/ is mapped to: C:\Program Files\Kodi
2022-07-12 18:57:57.024 T:9852  NOTICE: special://xbmcbin/ is mapped to: C:\Program Files\Kodi
2022-07-12 18:57:57.024 T:9852  NOTICE: special://xbmcbinaddons/ is mapped to: C:\Program Files\Kodi/addons
2022-07-12 18:57:57.024 T:9852  NOTICE: special://masterprofile/ is mapped to: C:\Users\antho\AppData\Roaming\Kodi\userdata
2022-07-12 18:57:57.024 T:9852  NOTICE: special://home/ is mapped to: C:\Users\antho\AppData\Roaming\Kodi\
2022-07-12 18:57:57.024 T:9852  NOTICE: special://temp/ is mapped to: C:\Users\antho\AppData\Roaming\Kodi\cache
2022-07-12 18:57:57.024 T:9852  NOTICE: special://logpath/ is mapped to: C:\Users\antho\AppData\Roaming\Kodi\
2022-07-12 18:57:57.024 T:9852  NOTICE: The executable running is: C:\Program Files\Kodi\kodi.exe
2022-07-12 18:57:57.027 T:9852  NOTICE: Local hostname: SALON
2022-07-12 18:57:57.027 T:9852  NOTICE: Log File is located: C:\Users\antho\AppData\Roaming\Kodi\kodi.log
2022-07-12 18:57:57.027 T:9852  NOTICE: -----------------------------------------------------------------------
2022-07-12 18:57:57.028 T:9852    INFO: loading settings
2022-07-12 18:57:57.029 T:9852  NOTICE: special://profile/ is mapped to: special://masterprofile/
2022-07-12 18:57:57.035 T:9852   DEBUG: CSkinSettings: no <skinsettings> tag found
2022-07-12 18:57:57.035 T:9852  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
2022-07-12 18:57:57.040 T:9852  NOTICE: Loaded settings file from special://profile/advancedsettings.xml
2022-07-12 18:57:57.040 T:9852  NOTICE: Contents of special://profile/advancedsettings.xml are...

`2022-07-12 18:57:58.594 T:9852  NOTICE: initialize done
2022-07-12 18:57:58.594 T:9852  NOTICE: Running the application...
2022-07-12 18:57:58.595 T:5080  NOTICE: ES: Starting UDP Event server on port 9777
2022-07-12 18:57:58.595 T:5080  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
2022-07-12 18:57:58.979 T:540  NOTICE: AddOnLog: PVR IPTV Simple Client: PVRIptvData::LoadPlayList PlayList Loaded - 1 (ms)
2022-07-12 18:57:58.979 T:540  NOTICE: AddOnLog: PVR IPTV Simple Client: Loaded 28 channels.
2022-07-12 18:57:58.979 T:540  NOTICE: PVR Manager: Starting
2022-07-12 18:57:59.001 T:2232  NOTICE: PVR Manager: Started
2022-07-12 18:57:59.033 T:540  NOTICE: VideoInfoScanner: Starting scan ..
2022-07-12 18:57:59.132 T:4040  NOTICE: EPG thread started
2022-07-12 18:58:00.183 T:7804  NOTICE: AddOnLog: PVR IPTV Simple Client: PVRIptvData::LoadEPG EPG Loaded - 49 (ms)
2022-07-12 18:58:00.298 T:540  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:01
2022-07-12 18:58:10.582 T:9544   ERROR: [Catch-up-TV-&-More.support] 'unable to import route module: resources.lib.channels.fr.francetv'
                                            Traceback (most recent call last):
                                              File "C:\Users\antho\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 300, in run_callback
                                                route = self.get_route(self.selector)
                                              File "C:\Users\antho\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 250, in get_route
                                                raise RouteMissing("unable to import route module: %s" % module_path)
                                            RouteMissing: 'unable to import route module: resources.lib.channels.fr.francetv'
2022-07-12 18:58:19.491 T:9852   ERROR: Previous line repeats 1 times.
2022-07-12 18:58:19.492 T:9852 WARNING: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2022-07-12 18:58:21.719 T:5052 WARNING: Previous line repeats 2 times.
2022-07-12 18:58:21.719 T:5052   ERROR: [Catch-up-TV-&-More.support] 'unable to import route module: resources.lib.channels.fr.mycanal'
                                            Traceback (most recent call last):
                                              File "C:\Users\antho\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 300, in run_callback
                                                route = self.get_route(self.selector)
                                              File "C:\Users\antho\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 250, in get_route
                                                raise RouteMissing("unable to import route module: %s" % module_path)
                                            RouteMissing: 'unable to import route module: resources.lib.channels.fr.mycanal'
2022-07-12 18:58:26.424 T:7180   ERROR: [Catch-up-TV-&-More.support] 'unable to import route module: resources.lib.channels.fr.francetv'
                                            Traceback (most recent call last):
                                              File "C:\Users\antho\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 300, in run_callback
                                                route = self.get_route(self.selector)
                                              File "C:\Users\antho\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 250, in get_route
                                                raise RouteMissing("unable to import route module: %s" % module_path)
                                            RouteMissing: 'unable to import route module: resources.lib.channels.fr.francetv'
2022-07-12 18:58:31.513 T:11504  NOTICE: [script.module.inputstreamhelper] Widevine update check was made on 2022-07-12 18:57
2022-07-12 18:58:33.410 T:9852  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/Toutes les chaînes/pvr.iptvsimple_942456342.pvr
2022-07-12 18:58:33.410 T:280  NOTICE: Creating InputStream
2022-07-12 18:58:33.421 T:280   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Program Files\Kodi\addons\inputstream.adaptive\
2022-07-12 18:58:35.113 T:280  NOTICE: Creating Demuxer
2022-07-12 18:58:35.113 T:280  NOTICE: Opening stream: 1001 source: 256
2022-07-12 18:58:35.193 T:280  NOTICE: Creating video codec with codec id: 27
2022-07-12 18:58:35.193 T:280  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2022-07-12 18:58:35.194 T:280  NOTICE: Creating video thread`

**Comment by meeuuh92** [comment]
Coreelec 9.2.8 tourne avec kodi 18 également...

**Comment by monfiston** [comment]
Mes box qui sont sous correlec ne peuvent pas tourner avec la version 19 de kodi

**Comment by meeuuh92** [comment]
Si tu veux t'amuser il faut essayer la distribution armbian et installer kodi 19 par dessus etc .. Mais je crains fortement qu'il n'y ai pas toutes les optimisations amlogic et de fonctionner bcp moins bien... Après sans home cinéma, ni de télé 4k, ce n'est pas grave.

**Comment by joaopa00** [comment]
J'ai installé une version 18 de Kodi pour tester. J'arrive à reproduire le problème.
Mais en fait, j'ai beaucoup plus de chaînes qui ne fonctionnent pas. Par exemple antennereunion, rtl2 etc.

Pouvez-vous confirmer?

Le problème a débuter à la version beta 5. La beta 4 ne rencontre pas ce problème de route.
A partir de la beta 5, il y a des modifications qui cassé la compatibilité avec Kodi 18.
C'est l'ajout de l'import
from resources/lib/ import resolver_proxy qui fait crasher Kodi.

Tous les fichiers qui ont cet import échouent lamentablement.

**Comment by meeuuh92** [comment]
Pour ma part je n'utilise les betas dans l'optique de récupérer le replay de RMC.Comme je rencontrais plusieurs problèmes lors de mes tests, je réinstalle systématiquement la stable...  Je me disais que la beta n'était pas fiable mais en même j'étais étonné que personne ne remonte de bug(en fait c'etait une question de compatibilité avec kodi 18).. je vais faire quelques essais du coup.

**Comment by joaopa00** [comment]
Je suis en train de faire un test de regression pour voir quel commit merdouille. Bonne nouvelle, ça marche pour le commit 8a9cf1df7cf737d6d2d363ec77f0cd8965d9cfdd

**Comment by joaopa00** [comment]
Devrait être fixé dans la beta 38.
N'oubliez pas de tester les chaines qui vous intéressent, mais aussi des chaines qui ne vous intéressent pas ;) :dancers: 
Je ferme.
Si le problème persiste, n'hésitez pas à réouvrir.

**Comment by monfiston** [comment]
bonjour
savez vous quand devrait sortir la béta 38 environ? (1 semaine, 1 mois, 3 mois,...)

**Comment by monfiston** [comment]
récupérer ou exactement le zip, je ne voie pas de beta38 ici

**Comment by meeuuh92** [comment]
Voici le lien de téléchargement : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/archive/refs/heads/dev.zip

**Comment by monfiston** [comment]
merci, effectivement les chaines francetv fonctionnent maintenant
un grand merci à vous!

je viens de tester toutes les autres chaines, voici celles qui ne fonctionnent pas:
canal+
c8
cstar
culturebox
francetv sport

**Comment by joaopa00** [comment]
Francetvsport a déjà son issue.
Les chaines du groupe canal avec les liens MyCanal ne fonctionnent pas non plus sur Kodi 19, donc le problème est ailleurs.
Les liens dailymotion fonctionnent quant à eux.
Je pense que le problème de CultureBox est le même que celui de Francetvsport.
