### ISSUE TITLE
quelque stream suisse a ajouter

### ISSUE THREAD

**Issue by Sphinxroot** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#936]
https://canal9.ch/direct/
http://livevideo.infomaniak.com/streaming/livecast/livehd/playlist.m3u8

https://canal9.ch/de/direct/
http://livevideo..infomaniak.com/livecast/livesd2/playlist.m3u8

https://www.canalalpha.ch/tv/ne
http://canalalpha.vedge.infomaniak.com/livecast/canalalpha/playlist.m3u8

https://www.canalalpha.ch/tv/ju
http://canalalphaju.vedge.infomaniak.com/livecast/canalalphaju/playlist.m3u8

https://latele.ch/live
http://livevideo.infomaniak.com/streaming/livecast/naxoo/playlist.m3u8

https://www.onetv.ch/
http://livevideo.infomaniak.com/streaming/livecast/onefmmd/playlist.m3u8

https://www.alpen-welle.ch/live/ jai essayer avec http://livevideo.infomaniak.com/..../playlist.m3u8 semble pas vouloir le prendre
https://edge20.vedge.infomaniak.com/livecast/ik:alpen-wellelivestream/manifest.m3u8

https://www.blick.ch/video/  possible token (07ed7acc64fb437683bbe1dc2237f587)
https://bcovlive-a.akamaihd.net/07ed7acc64fb437683bbe1dc2237f587/eu-central-1/4772533039001/3aee249144a84c0c865010baa0fd02f1/playlist_dvr_ssaiM.m3u8

http://elittv.ch/index.php
http://source2.primetime.ch:2981/play/elittv/index.m3u8

https://www.die-neue-zeit.tv/web-tv-radio/
https://www.onairport.live/die-neue-zeit-tv-live/livestream_high/playlist.m3u8

https://dieutv.com/
https://katapy.hs.llnwd.net/dieutvwza1/DIEUTVLIVE/smil:dieutv.smil/playlist.m3u8

https://drita.tv/live-tv/
https://monamour.agency/dritaweb008/index.m3u8

https://www.handelsregister.tv/
https://www.youtube.com/channel/UC-LkziTVeh7uoG_PqjS015g/live

JLM TV  sur leur site le stream n`est pas en mode /live
https://www.youtube.com/channel/UC7pVPkfQFqLa3asf8OGUcvA/live

https://qs24.tv/live/  site geo mais stream non
https://h030.video-stream-hosting.de/quantisana-live/_definst_/smil:livestream.smil/playlist.m3u8

https://www.argovia.ch/shows/blick-ins-argovia-studio-131499687  jai une erreur sur leur lecteur

https://radio3i.ch/diretta
https://livestream03.gruppocdt.ch/hls/radio3i.m3u8

Radio Pilatus TV
https://livevideo.infomaniak.com/streaming/livecast/rp_tv_1/playlist.m3u8

https://www.tele1.ch/live
https://cdnapisec.kaltura.com/p/1719221/sp/171922100/playManifest/entryId/1_xias5bqq/protocol/https/format/applehttp/flavorIds/1_tj9pcgrp,1_ym0klyy9,1_epgizhdj/a.m3u8
https://klive.kaltura.com/env/cluster-1-a.live.nvp1/live/hls/p/1719221/e/1_xias5bqq/tl/main/st/0/t/EjtPy5XqRLICzo6ldkTW9w/index-s32.m3u8

https://tv.telebaern.tv/live
https://cdnapisec.kaltura.com/p/1719221/sp/171922100/playManifest/entryId/1_obr1n222/protocol/https/format/applehttp/flavorIds/1_ilmyd94i,1_ndclh5za,1_y4atcpo4/a.m3u8
https://klive.kaltura.com/env/cluster-1-a.live.nvp1/live/hls/p/1719221/e/1_obr1n222/tl/main/st/0/t/_O-oCNON5VqA2aG8WYVDeg/index-s32.m3u8

https://telebasel.ch/live/
https://cldf-wzw-live.r53.cdn.tv1.eu/10096xtelebase/_definst_/1000199copo/live/app510394368/w162136077/live_de_1500/playlist.m3u8

https://tv.telezueri.ch/live
https://cdnapisec.kaltura.com/p/1719221/sp/171922100/playManifest/entryId/1_se36k3uk/protocol/https/format/applehttp/flavorIds/1_i4zc9zv3,1_2vzxm8zl,1_yjohpwzj/a.m3u8
https://klive.kaltura.com/env/cluster-1-a.live.nvp1/live/hls/p/1719221/e/1_se36k3uk/tl/main/st/0/t/WBrfPA9txtU5iuPYBt6pjA/index-s32.m3u8

https://www.tvo-online.ch/live
https://cdnapisec.kaltura.com/p/1719221/sp/171922100/playManifest/entryId/1_t5h46v64/protocol/https/format/applehttp/flavorIds/1_m7gtmg3i,1_520uxci9,1_r3vyu64o/a.m3u8
https://klive.kaltura.com/env/cluster-1-a.live.nvp1/live/hls/p/1719221/e/1_t5h46v64/tl/main/st/0/t/pABgewKPiCnchxEl-FUtqQ/index-s32.m3u8

https://wetter.tv/de-CH/vl
https://streaming.meteonews.net/hls/stream.m3u8

si possible

https://gvfm.ch/radiovision/
https://www.twitch.tv/rgvfm

https://tv.help.ch/
https://www.twitch.tv/telecasino/

https://www.rfj.ch/
https://www.dailymotion.com/video/x7wf94u

https://www.rjb.ch/
https://www.dailymotion.com/video/x7xygyv

https://www.rtn.ch/
https://www.dailymotion.com/video/x7wamzq

https://www.musig24.tv
https://api.new.livestream.com/accounts/16598383/events/8687407/

5 stream non 24/7
https://www.parlament.ch/fr/services/open-data-services-web/integration-live-stream

tous token

https://www.auftanken.tv/livestream/

https://www.tikilive.com/channel/ch-music-tv

https://www.tikilive.com/channel/label-tv-1

https://www.tikilive.com/channel/label-tv-2

https://www.tikilive.com/channel/rocklabel-tv

https://www.tikilive.com/channel/swissrock-tv

Star Schmuck  (pas toujours 24/7)
https://www.youtube.com/channel/UCrzWFws5zrY7f-naFmAXgBg

Geo 
https://www.suedostschweiz.ch/tv/wilmaa

**Comment by darodi** [comment]
CARAC =nouveau nom de https://www.onetv.ch/

**Comment by darodi** [comment]
> https://canal9.ch/direct/ http://livevideo.infomaniak.com/streaming/livecast/livehd/playlist.m3u8
> 
> https://canal9.ch/de/direct/ http://livevideo..infomaniak.com/livecast/livesd2/playlist.m3u8

- **DONE**  https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1319

> 
> https://www.canalalpha.ch/tv/ne http://canalalpha.vedge.infomaniak.com/livecast/canalalpha/playlist.m3u8
> 
> https://www.canalalpha.ch/tv/ju http://canalalphaju.vedge.infomaniak.com/livecast/canalalphaju/playlist.m3u8

- **DONE** https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1320
> 
> https://latele.ch/live http://livevideo.infomaniak.com/streaming/livecast/naxoo/playlist.m3u8

- **DONE** https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/720
> 
> https://www.onetv.ch/ http://livevideo.infomaniak.com/streaming/livecast/onefmmd/playlist.m3u8

- **DONE** https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1321
> 
> https://www.alpen-welle.ch/live/ jai essayer avec http://livevideo.infomaniak.com/..../playlist.m3u8 semble pas vouloir le prendre https://edge20.vedge.infomaniak.com/livecast/ik:alpen-wellelivestream/manifest.m3u8
> 

- **DONE** https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1322

> https://www.blick.ch/video/ possible token (07ed7acc64fb437683bbe1dc2237f587) https://bcovlive-a.akamaihd.net/07ed7acc64fb437683bbe1dc2237f587/eu-central-1/4772533039001/3aee249144a84c0c865010baa0fd02f1/playlist_dvr_ssaiM.m3u8


- **DONE**  #1323


> 
> http://elittv.ch/index.php http://source2.primetime.ch:2981/play/elittv/index.m3u8

- **BROKEN** ?
> 
> https://www.die-neue-zeit.tv/web-tv-radio/ https://www.onairport.live/die-neue-zeit-tv-live/livestream_high/playlist.m3u8
> 
- **DONE**  #1323

> https://dieutv.com/ https://katapy.hs.llnwd.net/dieutvwza1/DIEUTVLIVE/smil:dieutv.smil/playlist.m3u8
- **DONE**  #1323
> 
> https://drita.tv/live-tv/ https://monamour.agency/dritaweb008/index.m3u8
- **DONE**  #1323
- En Albanais? pas sûr que ça doit être dans la section CH/Suisse
> 
> https://www.handelsregister.tv/ https://www.youtube.com/channel/UC-LkziTVeh7uoG_PqjS015g/live
> 
> JLM TV sur leur site le stream n`est pas en mode /live https://www.youtube.com/channel/UC7pVPkfQFqLa3asf8OGUcvA/live
> 
> https://qs24.tv/live/ site geo mais stream non https://h030.video-stream-hosting.de/quantisana-live/_definst_/smil:livestream.smil/playlist.m3u8
> 
> https://www.argovia.ch/shows/blick-ins-argovia-studio-131499687 jai une erreur sur leur lecteur
> 
> https://radio3i.ch/diretta https://livestream03.gruppocdt.ch/hls/radio3i.m3u8
> 
> Radio Pilatus TV https://livevideo.infomaniak.com/streaming/livecast/rp_tv_1/playlist.m3u8
> 
> https://www.tele1.ch/live https://cdnapisec.kaltura.com/p/1719221/sp/171922100/playManifest/entryId/1_xias5bqq/protocol/https/format/applehttp/flavorIds/1_tj9pcgrp,1_ym0klyy9,1_epgizhdj/a.m3u8 https://klive.kaltura.com/env/cluster-1-a.live.nvp1/live/hls/p/1719221/e/1_xias5bqq/tl/main/st/0/t/EjtPy5XqRLICzo6ldkTW9w/index-s32.m3u8
> 
> https://tv.telebaern.tv/live https://cdnapisec.kaltura.com/p/1719221/sp/171922100/playManifest/entryId/1_obr1n222/protocol/https/format/applehttp/flavorIds/1_ilmyd94i,1_ndclh5za,1_y4atcpo4/a.m3u8 https://klive.kaltura.com/env/cluster-1-a.live.nvp1/live/hls/p/1719221/e/1_obr1n222/tl/main/st/0/t/_O-oCNON5VqA2aG8WYVDeg/index-s32.m3u8
> 
> https://telebasel.ch/live/ https://cldf-wzw-live.r53.cdn.tv1.eu/10096xtelebase/_definst_/1000199copo/live/app510394368/w162136077/live_de_1500/playlist.m3u8
> 
> https://tv.telezueri.ch/live https://cdnapisec.kaltura.com/p/1719221/sp/171922100/playManifest/entryId/1_se36k3uk/protocol/https/format/applehttp/flavorIds/1_i4zc9zv3,1_2vzxm8zl,1_yjohpwzj/a.m3u8 https://klive.kaltura.com/env/cluster-1-a.live.nvp1/live/hls/p/1719221/e/1_se36k3uk/tl/main/st/0/t/WBrfPA9txtU5iuPYBt6pjA/index-s32.m3u8
> 
> https://www.tvo-online.ch/live https://cdnapisec.kaltura.com/p/1719221/sp/171922100/playManifest/entryId/1_t5h46v64/protocol/https/format/applehttp/flavorIds/1_m7gtmg3i,1_520uxci9,1_r3vyu64o/a.m3u8 https://klive.kaltura.com/env/cluster-1-a.live.nvp1/live/hls/p/1719221/e/1_t5h46v64/tl/main/st/0/t/pABgewKPiCnchxEl-FUtqQ/index-s32.m3u8
> 
> https://wetter.tv/de-CH/vl https://streaming.meteonews.net/hls/stream.m3u8
> 
> si possible
> 
> https://gvfm.ch/radiovision/ https://www.twitch.tv/rgvfm
> 
> https://tv.help.ch/ https://www.twitch.tv/telecasino/
> 
> https://www.rfj.ch/ https://www.dailymotion.com/video/x7wf94u
> 
> https://www.rjb.ch/ https://www.dailymotion.com/video/x7xygyv
> 
> https://www.rtn.ch/ https://www.dailymotion.com/video/x7wamzq
> 
> https://www.musig24.tv https://api.new.livestream.com/accounts/16598383/events/8687407/
> 
> 5 stream non 24/7 https://www.parlament.ch/fr/services/open-data-services-web/integration-live-stream
> 
> tous token
> 
> https://www.auftanken.tv/livestream/
> 
> https://www.tikilive.com/channel/ch-music-tv
> 
> https://www.tikilive.com/channel/label-tv-1
> 
> https://www.tikilive.com/channel/label-tv-2
> 
> https://www.tikilive.com/channel/rocklabel-tv
> 
> https://www.tikilive.com/channel/swissrock-tv
> 
> Star Schmuck (pas toujours 24/7) https://www.youtube.com/channel/UCrzWFws5zrY7f-naFmAXgBg
> 
> Geo https://www.suedostschweiz.ch/tv/wilmaa

**Comment by CorentinWicht** [comment]
Bonjour,

Je me permets de relancer ce thread car deux des chaînes mentionnées ci-dessus ne fonctionnent plus.

LATELE log d'erreur:
```
2026-04-20 07:16:49.445 T:4408     info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: plugin://plugin.video.catchuptvandmore/resources/lib/channels/ch/latele/get_live_url/?item_id=latele
2026-04-20 07:16:50.102 T:6756  warning <general>: [script.module.inputstreamhelper] Widevine update check was made on 2026-04-09 20:37
2026-04-20 07:16:50.130 T:6756  warning <general>: ListItem.addStreamInfo() is deprecated and might be removed in future Kodi versions. Please use InfoTagVideo.addVideoStream(), InfoTagVideo.addAudioStream() and InfoTagVideo.addSubtitleStream().
2026-04-20 07:16:50.143 T:6756  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2026-04-20 07:16:50.171 T:6772     info <general>: GetVideoSync: Using presentation protocol for video sync
2026-04-20 07:16:50.172 T:4408     info <general>: VideoPlayer::OpenFile: pvr://channels/tv/All%20channels@-1/1@pvr.iptvsimple_945600496.pvr
2026-04-20 07:16:50.172 T:6773     info <general>: Creating InputStream
2026-04-20 07:16:50.173 T:6773     info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 800x600, max allowed: 800x600, Adjust refresh rate: 1
2026-04-20 07:16:58.815 T:6773    error <general>: AddOnLog: inputstream.adaptive: Download failed, HTTP error 404: https://latele2.vedge.infomaniak.com/livecast/latele2/manifest.m3u8
2026-04-20 07:16:58.815 T:6773    error <general>: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/All%20channels@-1/1@pvr.iptvsimple_945600496.pvr]
2026-04-20 07:16:58.815 T:6773     info <general>: CVideoPlayer::OnExit()
2026-04-20 07:16:58.815 T:6773     info <general>: ADDON: Dll Destroyed - InputStream Adaptive
2026-04-20 07:16:58.829 T:4408     info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2026-04-20 07:16:58.836 T:4408     info <general>: CVideoPlayer::CloseFile()
2026-04-20 07:16:58.836 T:4408     info <general>: VideoPlayer: waiting for threads to exit
2026-04-20 07:16:58.836 T:4408     info <general>: VideoPlayer: finished waiting
```

LemanBleu log d'erreur:
```
2026-04-20 07:17:06.514 T:4408     info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - GetChannelStreamProperties - Live Stream URL: plugin://plugin.video.catchuptvandmore/resources/lib/channels/ch/lemanbleu/get_live_url/?item_id=lemanbleu
2026-04-20 07:17:07.351 T:6756    error <general>: [Catch-up-TV-&-More.support] 404 Client Error: Not Found for url: https://www.lemanbleu.ch/fr/Live.html
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/ch/lemanbleu.py", line 148, in get_live_url
                                                       resp = urlquick.get(URL_LIVE)
                                                              ^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/urlquick.py", line 492, in get
                                                       return request('get', url, params=params, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/urlquick.py", line 486, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/urlquick.py", line 440, in request
                                                       response = super(Session, self).request(*args, **kwargs)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 589, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/urlquick.py", line 449, in send
                                                       return super(Session, self).send(request, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 725, in send
                                                       history = [resp for resp in gen]
                                                                 ^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 266, in resolve_redirects
                                                       resp = self.send(
                                                              ^^^^^^^^^^
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/urlquick.py", line 458, in send
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/home/kodi/.kodi/addons/script.module.codequick/lib/urlquick.py", line 414, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.lemanbleu.ch/fr/Live.html
2026-04-20 07:17:07.353 T:6756    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'HTTPError' object has no attribute 'code'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 25, in <module>
                                                       main()
                                                     File "/home/kodi/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 19, in main
                                                       main.error_handler(exception)
                                                     File "/home/kodi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 283, in error_handler
                                                       code = exception.code
                                                              ^^^^^^^^^^^^^^
                                                   AttributeError: 'HTTPError' object has no attribute 'code'
                                                   -->End of Python script error report<--
```
