### ISSUE TITLE
UK Channel 4 : Error when selecting Catch up or Live

### ISSUE THREAD

**Issue by berkhornet** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#963]
### Describe the bug
A clear and concise description of what the bug is:

Route Error when selecting Channel 4

### To Reproduce
Steps to reproduce the behaviour:
1. Start CUTV
2. Navigate to Catch up / UK / Channel 4 or Live / UK / Channel 4

### Expected behaviour
Subsequent menus should appear

### Actual behaviour
Error message - see debug log below

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X ] Windows
 - [ ] Other

 - Operating system version/name: Windows 10
 - Kodi version: 19.4
 - Catch-up TV & More version: 0.2.39~beta 6
 - Installation method:

### Debug log
ERROR <general>: [Catch-up-TV-&-More.support] 'unable to import route module: resources.lib.channels.uk.channel4'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\mickr\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 248, in get_route
                                                       importlib.import_module(module_path)
                                                     File "C:\Program Files\Kodi\system\python\Lib\importlib\__init__.py", line 127, in import_module
                                                       return _bootstrap._gcd_import(name[level:], package, level)
                                                     File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 719, in exec_module
                                                     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
                                                     File "C:\Users\mickr\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\uk\channel4.py", line 22, in <module>
                                                       from Crypto.Cipher import AES
                                                   ModuleNotFoundError: No module named 'Crypto'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\mickr\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 300, in run_callback
                                                       route = self.get_route(self.selector)
                                                     File "C:\Users\mickr\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 250, in get_route
                                                       raise RouteMissing("unable to import route module: %s" % module_path)
                                                   codequick.support.RouteMissing: 'unable to import route module: resources.lib.channels.uk.channel4'
2022-10-01 22:34:37.452 T:18276 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2022-10-01 22:34:49.194 T:18276    INFO <general>: CPythonInvoker(191, C:\Users\mickr\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py): script successfully run
2022-10-01 22:34:49.640 T:18276    INFO <general>: Python interpreter stopped
2022-10-01 22:34:49.654 T:32304   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/channels/uk/channel4/list_categories/?_pickle_=8004953c000000000000007d94288c075f7469746c655f948c094368616e6e656c2034948c08786d6c74765f6964944e8c076974656d5f6964948c086368616e6e656c3494752e
2022-10-01 22:34:49.664 T:15584   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/resources/lib/channels/uk/channel4/list_categories/?_pickle_=8004953c000000000000007d94288c075f7469746c655f948c094368616e6e656c2034948c08786d6c74765f6964944e8c076974656d5f6964948c086368616e6e656c3494752e) failed
2022-10-01 22:34:49.688 T:16268    INFO <general>: initializing python engine.

**Comment by berkhornet** [comment]
PR opened with fix

**Comment by joaopa00** [comment]
Thanks for the report and the fix!
