### ISSUE TITLE
Client Error: Forbidden for url: https://sso-client.sfr.fr rmcbfm play

### ISSUE THREAD

**Issue by Schonke26** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#990]
### Describe the bug
A clear and concise description of what the bug is:
403 Client Error: Forbidden for url: https://sso-client.sfr.fr/cas/services/rest/3.2/createToken.json?duration=86400
Not possible to view "RMC Decouverte" and "RCM Story" with last Kodi version on OSMC.

### To Reproduce
Steps to reproduce the behaviour:
1. Start Raspberry PI with OSMC
2. Clic on TV
3. Clic on RCM Decouverte or RMC Story

### Expected behaviour
A clear and concise description of what you expected to happen:
Display these channels.

### Actual behaviour
Tell us what happens instead:
Error display on top right.

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: OSMC 2022.03-1
 - Kodi version: 19.4.0
 - Catch-up TV & More version: 0.2.37
 - Installation method: Thru Kodi

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):
2022-11-12 23:13:39.190 T:2294    ERROR <general>: [Catch-up-TV-&-More.support] 403 Client Error: Forbidden for url: https://sso-client.sfr.fr/cas/services/rest/3.2/createToken.json?duration=86400
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 300, in run_callback
                                                       route = self.get_route(self.selector)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 248, in get_route
                                                       importlib.import_module(module_path)
                                                     File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
                                                       return _bootstrap._gcd_import(name[level:], package, level)
                                                     File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 983, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 728, in exec_module
                                                     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay.py", line 76, in <module>
                                                       token = get_token()
                                                     File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay.py", line 52, in get_token
                                                       resp = urlquick.get(url, params=params, headers=headers).json()
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 493, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 487, in request
                                                       return s.request(method=method, url=url, **kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 442, in request
                                                       self._raise_for_status(response, raise_for_status)
                                                     File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 415, in _raise_for_status
                                                       response.raise_for_status()
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/models.py", line 960, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://sso-client.sfr.fr/cas/services/rest/3.2/createToke
n.json?duration=86400

**Comment by Schonke26** [comment]
Additionnal information :
My user and password is OK on RMCBFM Play. I've set them by editing .kodi/userdata/addon_data/plugin.video.catchuptvandmore/settings.xml :
    <setting id="rmcbfmplay.login">_**MyEmail**_</setting>
    <setting id="rmcbfmplay.password">_**MyPassword**_</setting>

**Comment by Schonke26** [comment]
Error on my last comment :
```
<setting id="rmcbfmplay.login">MyEmail</setting>
<setting id="rmcbfmplay.password">MyPassword</setting>
```

**Comment by joaopa00** [comment]
It iis fixed in the beta already since a long time. Please install it. Have a look at the wiki to do it [wiki](https://catch-up-tv-and-more.github.io/installation/)

**Comment by Schonke26** [comment]
Sorry. I didn't find that fix. Thank's.
